### ISSUE TITLE
Operational process documentation index/ToC

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#1001]
**Describe the issue**
We have define various tickets for creation of operational process documentation.  We would like to have this documentation well-organized an navigable.  To that end, we want to provide an index/ToC page/view to summarize the documentation set as well as provide simplified navigation into specific documentation.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- as new docs are added, this index page would need to be updated

**Definition of done**
- a markdown file stored in `bcgov-c/cloudops` that provides a linked listing of existing process docs and some preamble text about the documentation set (who it's for, etc.)

**Comment by mitovskaol** [comment]
will be tracked in different tickets
