### ISSUE TITLE
Connect to Platform Services Project Registry

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1003]
**Describe the issue**
Once our vending machine automation is in an MVP format, we need to connect it to the Project Registry.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- When a new project-set is enabled for a new team, an entry appears in the Project Registry
- Well formed tickets for the RUD tasks created
- A well formed ticket for a task to backfill the existing projects we have into the Project Registry is created

**Comment by mitovskaol** [comment]
Closing as a duplicate.
