### ISSUE TITLE
Interview with Developer for user journey

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1004]
**Describe the issue**
As a prerequisite for the user journey work, we need to inform ourselves via an outreach to that user role.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Will has graciously agreed to help us

**Definition of done**
- Interview and notes done

**Comment by bharmouche** [comment]
Had the interview with Will and will share the board with our PO
