### ISSUE TITLE
Connect with GCPE to access licensed image service

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1005]
**Describe the issue**
GCPE Government Communications and Public Engagement has a licensed image service

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- replace slide deck material

**Comment by ActionAnalytics** [comment]
Reached out to GCPE awaiting answer

**Comment by wrnu** [comment]
No longer relevant
