### ISSUE TITLE
Admin role users in AWS unable to create budgets

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1009]
**Describe the bug**
Clecio on the NRM Observability Metrics team is reporting unable to budgets in AWS

**Additional context**
- See channel aws-tenant-requests for details (post on Aug 10)

**Definition of done**
- Admin and Dev (per tech team review and discussion) to be able to create budgets in AWS

**Comment by MaxWardle** [comment]
This was only reproducible through the AWS Cosole's UI, Budgets could be created through the CLI and through GitHub Actions/ Terraform. I let Clecio know, and will follow up with Ryan J on the UI bug.
