### ISSUE TITLE
End of Sprint User Feedback Template 

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#1014]
**Describe the issue**
We would like to to have our users feedback every Sprint to collect and document as much data as possible on our service. we can crate an automized template that we can have in our system and can be run anytime. This template can be run by anyone in the absence of service designer.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
This in the future can be hooked to a dashboard where our PO and the rest of the team can check on the ongoing effect of our service.  

**Definition of done**
- Draft the questions and share with PO
- Populate the question on designated platform
- Run a test, amend, and save
- Two KPI/Metrics gatherers/collectors:  Do one for users, one for demo attendees

**Comment by wrnu** [comment]
No longer relevant
