### ISSUE TITLE
AWS SEA state machine not setting up accounts correctly

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1015]
**Describe the bug**
There is SEA state machine automation that is supposed to run everytime an account is created. It consists of 7 phases,
phase -1, 0, 1-5. The phases correspond to cloud formation stacksets in every workload account. Accounts are missing the stacksets for 2,3,4. -1,0,5 are present. 

**Additional context**
The below accounts are missing stacksets and all the resources created by these stacksets: 
 - sqr9b6-dev
 - sqr9b6-test
-  sqr9b6-prod
 - lqc63d-dev
 - lqc63d-test
 - lqc63d-prod

**Definition of done**
- Co-ordinate with AWS to have them the SEA state machine needs to be fixed so that if it fails at the same place it informs the operator. 
- Co-ordinate with AWS to have them fix the state machine so that it runs as intended. 
- The 6 accounts identified need to have missing stacksets and resources.

**Comment by wrnu** [comment]
Ryan J confirmed that there are bugs related to the number of accounts that is preventing the SM form running correctly. This is blocked until AWS released fixes to the ASEA
