### ISSUE TITLE
[Parks ResourceSpace] Automation to detect and block access when default credentials

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1022]
**Describe the issue**
ResourceSpace from Bitnami or source built has default credentials.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- This is a ResourceSpace application default accounts. 

**Definition of done**
- Use one of our security tools to scan for VM's using default credentials to make sure that teams aren't leaving those unchanged from default
- Connect the scan results to one of our security log streams (whichever makes most sense) and mark findings as critical

**Comment by wrnu** [comment]
No longer relevant
