### ISSUE TITLE
SPIKE - [BC Parks ResourceSpace] Define Private Marketplace Tickets

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1023]
**Describe the issue**
We wish to make available ResourceSpace via the AWS Private Market

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Core Accounts should be unaffected because CPF uses the Public Marketplace for the firewall appliances
- there are likely steps required involving GoC cloud Brokerage related to enabling marketplace - revisit brokerage onboarding documentation / process.  @scayzer has managed this doc in the past.

**Definition of done**
- Coordinate and meet with Ryan J from AWS to determine what needs to be done for the Private Marketplace to be turned on across the Workload Accounts
- Public Marketplace must be turned off across the Workload Accounts.

**Comment by wrnu** [comment]
No longer relevant
