### ISSUE TITLE
[Parks ResourceSpace]Research Hardening VM Image reusing patterns from on-prem

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#1024]
**Describe the issue**
- BC Parks ResourceSpace team is potentially using AMI from Bitnami and we wish their VMs to have additional security measures in place. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Get VM Access to on prem to look at their hardened images 
- This is in the Team part of the shared responsibility but we are helping due to timelines

**Definition of done**
- Implement CI security benchmarks recommendations that make sense for AWS AMIs
- Install EnCase agent
- Connect EnCase agent to SecOps central control
- Cap to 3 possibly skip the connection bit if this is hard and define further tickets instead.

**Comment by wrnu** [comment]
No longer relevant
