### ISSUE TITLE
Virtual Machines covered by PIA

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1028]
**Describe the issue**
We have a new team pathfinding with us using Virtual Machines (VMs) and we need to modify the PIA to include this service.

**Which Sprint Goal is this issue related to?**
Sprint: Aug 23 - Sept 10

**Additional context**
- Technology explainer meeting with PO and Holly to get started (Security & Privacy to collab)
- We are aiming to use a Private Marketplace and create a funnel around VM images that are available to teams from that private marketplace
- The first offering in that Private Marketplace is intended to be ResourceSpace by Bitnami
- VMs are currently scoped out of the corporate PIA. 

**Definition of done**
- Meetings with security and/or PO to go over technical questions privacy might have
- Appropriate format to capture the change confirmed with PCT Director (Initiative Update, capturing change in an Excel sheet)
- Draft, Review and Submit the updated PIA (if that's the decision from the Director)

**Comment by ActionAnalytics** [comment]
This ticket is not fully refined, we're guessing a lot of the details.  We need to review further with Holly

**Comment by hromanow** [comment]
PCT Director reviewing proposed format for capturing change - to be confirmed.

**Comment by hromanow** [comment]
Changes to existing PIA with PCT Director for review.

**Comment by hromanow** [comment]
PIA is sign off stage. Holly to close the file when it comes back fully signed.
