### ISSUE TITLE
Update SOAR for Virtual Machines

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1029]
**Describe the issue**
We have a new team pathfinding with us using Virtual Machines (VMs) and we need to modify the SOAR to include this service.

**Which Sprint Goal is this issue related to?**

Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'.
The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**

-We are aiming to use a Private Marketplace and create a funnel around VM images that are available to teams from that private marketplace
-The first offering in that Private Marketplace is intended to be ResourceSpace by Bitnami

**Definition of done**
- Decide whether to create an appendix in the SOAR and PIA (scope to VMs only, in Private Marketplace) or edit the existing.
- Draft, Review and Submit the updated SOAR (with whichever mechanism chosen above)
- Does not include signoff

**Comment by bluemel-gov** [comment]
@wrnu would you know about '-The first offering in that Private Marketplace is intended to be ResourceSpace by Bitnami' or who added that line in? just looking to learn  more. thx

**Comment by wrnu** [comment]
@bluemel-gov I can speak to that. That line means that the project intents to use a pre-packaged AMI from Bitnami for running the ResourceSpace application.

**Comment by bluemel-gov** [comment]
- meeting booked with csp vendor on 8/24 and privacy
