### ISSUE TITLE
Automated report of SCP in use

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder#1035]
**Describe the issue**
SCP = Service Control Policy
For every release of SEA, there could be changes to the AWS Config SCP included or changed.
These changes could impact teams and what teams can and can't do.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Review and capture SEA SCPs in use (1.x.x)
- Capture patterns to review and make automation (guardrail, cloud custodian or other) that checks as further tickets.

**Comment by wrnu** [comment]
No longer relevant
