### ISSUE TITLE
User understanding for VM users

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1039]
**Describe the issue**
We need to understand what are the needs for the VM users and what is their strategy to use VMs. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- BC Parks ResourceSpace team (Robbert F)

**Definition of done**
- Meet PO to discuss pre-meeting questions to ask the team
- Book meeting with BC Parks team
- Report back to PO, Stu with the insights.

**Comment by bharmouche** [comment]
met with the PO and had a good chat will share the insights today.
