### ISSUE TITLE
Search within DevHub Cloud Services Page

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1041]
**Describe the issue**
We would like to have a search function within the DevHub Cloud Services Page since the set of cards that is displayed is long/overwhelming.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- it is unlikely that native DevHub functionality can meet the need; however, there are optional settings available in the AirTable embed/share code that is used in the DevHub that will enable filtering, sorting and searching.  This may be sufficient to resolved the issue described in this ticket. Example (a version of the card view with these feature enabled): https://airtable.com/embed/shrB5dKrUTGPAz1ZX/tblbsT84TZr9UXdtJ?backgroundColor=yellow&viewControls=on

**Definition of done**
- Review UX of card list with additional functions.  If acceptable, update embed code in markdown file used in Devhub.
- If more/different functionality desired, convene meeting with Patrick from the DevHub team, Bahaa, and Warren
 to explain the need from the UX perspective. As an output, define tickets or make a request in the DevHub team's ticketing system.

**Comment by sheaphillips** [comment]
@bharmouche pls take a look at the link [here](https://airtable.com/embed/shrB5dKrUTGPAz1ZX/tblbsT84TZr9UXdtJ?backgroundColor=yellow&viewControls=on) If you're happy with it, then you can coordinate with tech team to make the (minor) change required.

**Comment by bharmouche** [comment]
@sheaphillips this is perfect i thinks we can definitely pass it to the tech team. Thank you so much
