### ISSUE TITLE
CITZ IMB Community information tool issue

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1051]
**Describe the bug**
CITZ IMB team does not have backend support for their tool that has been transitioned to the Azure workspace. They are not able to update certain files and are seeking support from NTT to help resolve this. NTT will be digging into logs and will be giving us an indicator for the cause/account to look for to resolve the update issue

**Additional context**
This is the CITZ IMB Community information tool (CIT). 

**Definition of done**
- Working with IMB, NTT to resolve this
- Once cause is provided from NTT, Investigate and define new tickets accordingly

**Comment by ActionAnalytics** [comment]
Might unblock soon as the team is appearing to have their resources almost prepared

**Comment by ActionAnalytics** [comment]
Pending confirm from team that they're done

**Comment by ActionAnalytics** [comment]
jon-mc-git
commented 3 days ago

Issue was fixed. Client should get shortly with summary of lessons learned on the issue experienced.

Client was also advised that they need to bring this into the Azure SEA when it is up and that they should plan for it if it is viewed that the CIT application is something that will be kept longer term. Closing ticket.
