### ISSUE TITLE
Various team access / contact updates

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#1056]
**Describe the issue**
Appropriate team members need to have access to specific services, and be established as contact point for certain business processes.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**

- DNS for cloud.gov.bc.ca domains is controlled by a systems called "NNR"at https://remedyapps.gov.bc.ca.  NNR access is controlled via IDIR/AD groups.  The group that has access to the cloud domain is called "BCDevOps".  Julian and Max should be added to this group in order to allow them to administer the domain.  Justin/Olena have joint "ownership" of this group/domain and Luke knows how to get membership updated.
- Wildcard Certificate. We have a set of wildcard certificates. The technical contact associated with these of these needs to be updated to a government team member so expiry notices, etc. will be sent to the right person.  I believe this can be done by contacting "ims  at gov.bc.ca"

**Definition of done**
- above access and contacts updated.

**Comment by wrnu** [comment]
not relevant
