### ISSUE TITLE
Document all the Pathfinder-isms along with a rationale for each

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1057]
**Describe the issue**
Since we are a Pathfinder project, we are cutting corners in several places, perhaps skipping certain processes in favour of velocity, or using manual instead of automated controls.

It would be valuable to our org to document how exactly we are Pathfinding so that the org can understand what impediments might be affecting teams without the Pathfinder license.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- A shared spreadsheet in Teams listing Pathfinding areas, with a column describing the impediment being avoided, and a rationale for why and how this Pathfinding is accomplished, with a column for which group could theoretically in the future tackle the removal of this impediment for the greater org.
- Review with PO, then check with Exec to see if this is suitable to present at OKR sessions or keep for internal lessons learned for Executive

**Comment by scayzer** [comment]
Started this as a Word document, in Teams CP General>001 - Team Documents>Benefits of Pathfinding

**Comment by wrnu** [comment]
No longer relevant
