### ISSUE TITLE
Terraform Cloud Runs Hang (Waiting for Input) Sometimes When Running From Github Actions

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1058]
**Describe the bug**
We have had multiple instances of users saying that their terraform cloud apply action can't run because there is another run occupying the runner. We have found that the runs occasionally get stuck waiting for input on the terraform apply. Additionally the users have no way of interacting with the console, or canceling the stuck run without a TFC account because the apply is running within a GitHub action.

**Additional context**
Because TFC only has one runner this affects the entire platform. When a run is stuck like this it occupies the only runner for the platform, so no teams can run any terraform commands in the cloud until someone with a TFC account goes in and cancels the run.

One way that this can happen from ci/cd is if terraform is run without -auto-approve or terragrunt without --no-interactive

One team that experienced this is Team Falcon.

**Definition of done**
- investigate the "problem" runs and determine the issue
- fix the issue if possible or determine an automated/manual/notification work around
- There is an API for Terraform Cloud and getting a notification in Rocket Chat would be a good detective mechanism.
- Investigate putting a link up in the login app that shows the status and allows someone to kick it (waiting in the needs attention state), say enable the Kick option after 10 minutes of wait.

**Comment by wrnu** [comment]
Covered by other tickerts
