### ISSUE TITLE
Subset of Reserved Instances - Trade Compliance

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1060]
**Describe the issue**
Compliance of the GCFA with Trade agreements

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Endorsement of the approach to use the federal supply arrangement by JERI

**Comment by fastaudra** [comment]
Note to contract file - emails with JERI.
