### ISSUE TITLE
Documentation for the contract file

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1061]
**Describe the issue**
The Service Orders for BC Gov public cloud under the GCFA (GoC Cloud Framework Agreement) supply arrangement will likely be audited by OCG (Office of the Comptroller General) under BC Gov Ministry of Finance. Before we can enable larger $ value purchases for teams we need to have assurance that the procurement is fully compliant. The one missing piece is the legal review. 

**Additional context**

**Definition of done**
- Comprehensive contract files saved on the LAN

**Comment by sid-gov** [comment]
Blocked by LSB

**Comment by ActionAnalytics** [comment]
Waiting for legal resources

**Comment by sid-gov** [comment]
Waiting for legal review.

**Comment by fastaudra** [comment]
waiting for RFP to continue legal review.

**Comment by ActionAnalytics** [comment]
Hillary and Audra have been filing files onto the LAN.

**Comment by ActionAnalytics** [comment]
Will have to restart and train up Dana

**Comment by ActionAnalytics** [comment]
Audra found the legal advice we were looking for and put it in the LAN folder
