### ISSUE TITLE
Optimize Azure Tenancy costs & ease of management

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1063]
**Describe the issue**
We want to know the cost optimization for the current Azure space to get an understanding of how the tenancy is being used vs how it should ideally be used. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- This is done to profile the client usage of their Azure projects and to be able to make decisions to optimize their usage or retire them as necessary. 

**Definition of done**
- Cost optimization report with recommendations for the azure tenancy space

**Comment by wrnu** [comment]
No longer relevant
