### ISSUE TITLE
Optimize Azure tenancy VM usage

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1064]
**Describe the issue**
We want to understand current VM usage with the view of being able to make cost optimizations for VM usage in Azure tenancy. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
The activities done here support baseline profiling of VM usage within the tenancy and to be able to make cost optimization decisions as part of tenancy governance. 

**Definition of done**
- Macro review of what VM usage is within the tenancy
- VM cost optimization report with trends/possible recommendations
- Working with clients as necessary to optimize that usage

**Comment by wrnu** [comment]
No longer relevant
