### ISSUE TITLE
Azure Tenancy Clean-Up

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1065]
**Describe the issue**
There are 70+ subscriptions involved, these are all sitting in the root of the tenancy.  People across gov seem to be able to create new subscriptions (directly or by way of SaaS automation) and they land by default in the root folder of the tenancy which makes managing it very hard.  We cannot easily identify new entrants/project within the 70+ already present.  We want to throw the existing subscription into folders using categories/classification so that way the platform is easier to administer.

Based on the spreadsheet (and CRM info) from the results from #1062 we want to start the process of cleaning the current Azure tenancy space. 

**Additional context**
- These are SaaS made subscriptions and resources outside the SEA - they still need to be organized
- Pending a meeting with ADMS and its challenging to get time with them right now (Meeting in Jan 2022). 
- ADMS needs to give Jon admin permissions for help.
- ADMS is supportive of this work. 

**Definition of done**
- Clarify what is not being used and can be deleted or advisements made to clients that dormant projects will be deleted. 
- Come up with a lightweight classification structure that lead to sanity
- Show Julian for his curiosity before implementing

**Comment by ActionAnalytics** [comment]
As a matter of scrum practice, just make sure that I am the one pulling tickets into the sprint

**Comment by jon-mc-git** [comment]
There was a meeting scheduled for this by ADMS however it has is wrongly titled (titled under Ministry issue. Will get them to correct

**Comment by jon-mc-git** [comment]
Clean up has been completed, except for two legacy subscriptions that must be deleted by MS themselves.  Have left instructions with the ADMS group on how to pursue this (ticket system in Azure is currently turned off), so they should work through their MS contacts to get that completed

**Comment by jon-mc-git** [comment]
Established a new process using Privileged Identity Management (PIM) function in Azure that allows us to examine new subscriptions that appear, create internal tickets (DevOps & CRM tickets) in accordance to what is found, a draft classification and the communication summary of this within a PIM request ticket completed, and if approved allows for the temp update of permissions and the completion of the new Azure subscription classification process.  Initial automation around this has been tested with great success, and additional testing will take place in early Sept.  

Once testing is completed and adjustments made, this new semi-automated Azure Tenancy Maintenance process will be ratified by both Cloud Pathfinder and the ADMS group, and the final process established.

**Comment by jon-mc-git** [comment]
Note that initial difficulties in investigating some remaining subscriptions and tracking down owners has been resolved.  There are only the two remaining subscriptions left as mentioned above (called 'Access to Azure Active Directory') that should be handled by the ADMS group.  Information\instructions sent around these legacy subscriptions to ADMS - will confirm action around this with them in early September

**Comment by jon-mc-git** [comment]
New process with ADMS group has been worked out and currently troubleshooting.  Not currently receiving email when tickets being submitted via Azure PIM to their team.  Will likely use Teams as the main communication method during this process post-PIM req/ticket submission.
