### ISSUE TITLE
Create explicit IAM role and policy for running Billing Utility

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#1067]
**Describe the issue**
Currently the billing utility requires a "kitchen sink" role to run successfully.  This is not ideal as it prevents less-privileged users/services from running it.  A role with *only* the required permissions should be created and a mechanism provided for the appropriate users to assume this role should be established.  The role/policy definition and application can/should be done with Terraform.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
The specific permission required by the billing utility include:
- reading from the `organizations` API
- reading/writing to `s3` buckets
- executing `athena` queries.

The above and any others would need to be translated into IAM policy.

For interactive use, the role would need to be populated into KeyCloak and associated with a group or users likely to need it.  It would then be possible to generate temporary credentials with *just this role* vie the usual `was-login` mechanism.

**Definition of done**
- terraform created, committed to Github, tested that does the following:
- defines policy with correct permissions
- creates role 
-  associates role to policy
- publishes role to KeyCloak

**Comment by sheaphillips** [comment]
policy should also include accessing `ses` APIs to send email.

**Comment by sheaphillips** [comment]
The terraform code in the billing utility repo *prior* to deprecation of the lambda-based version (SHA e6dcd70676d46173425e87a3cefc262c93718b11) may be useful as reference in completing the tasks described in this issue.

**Comment by unoah** [comment]
Permissions scaled back for Athena queries, S3 bucket access, reading org accounts and SES components. This was addressed in ticket [1068](https://app.zenhub.com/workspaces/cloud-pathfinder-5e4dbb426c3c6af8dcbf06a7/issues/bcgov/cloud-pathfinder/1068). Closing on that note.
