### ISSUE TITLE
Containerize and schedule Billing Utility so it is automated and "hands off"

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#1068]
**Describe the issue**
Currently the Billing Utility is manually run on an admin's workstation based on a periodic schedule.  This is a well-defined, but currently "toilful", potentially error-prone, and time-sensitive activity that would be better handled as a "hands-off" process running autonomously.  The current utility could relatively easily be adapted to run in a scheduled container (e.g. in lambda, ECS, or other chosen environment).

**Additional context**
- this task should also include an automated CI/CD process to publish updated version of the utility.
- The free API that we use for grabbing the conversion rate from USD to CAD is called [Fixer](https://fixer.io/) and the free tier comes with the caveat that there is no uptime or availability commitment. The workaround we use currently is to manually input the conversion rate via another environment variable when the API is down. This will have to be rethought when we automate this.
  - There are other currency conversion services (oanda.com for example), so one option for solving this problem is that we can have a few "fallback APIs" for grabbing the conversion rate.

**Definition of done**
- Dockerfile and other build/packaging/deployment artifacts created, tested, and committed to Github
- utility deployed and configured to run on a schedule determined by CPF PO, with appropriate parameters - likely weekly, monthly, quarterly, and perhaps annually.
- automated CI/CD process configured, tested, and operational

**Comment by sheaphillips** [comment]
The terraform code in the billing utility repo *prior* to deprecation of the lambda-based version (SHA e6dcd70676d46173425e87a3cefc262c93718b11) may be useful as reference in completing the tasks described in this issue.

**Comment by unoah** [comment]
### Partial summary of work done so far
- [x] Identified resources that were created via the AWS console prior to this ticket
  - [x] These were mostly on LZ2
  - [x] Began porting those resources to Terraform. These can be found in: [billing-report-glue-resources](https://github.com/BCDevOps/terraform-octk-aws-sea-billing-reports/tree/cpf-1068/billing-report-glue-resources)
  - [x] Tested deployment LZ0s master account
  - [ ] Terraform config for Athena and SES resources are pending. These are going to be deployed to the master account with existing Glue resources
- [x] Created deployment mechanism to enable deploying existing container and functions to operations account on the LZs
  - [x] Tested deployment with placeholder functions. Terraform config can be found at: [billing-report-utility-infra](https://github.com/BCDevOps/terraform-octk-aws-sea-billing-reports/tree/cpf-1068/billing-report-utility-infra)
  - [x] CLI arguments managed by argparse have been removed, arguments needed for the different periods are now set as environment variables in EventBridge targets
  - [x] Moved S3 query output bucket from being hard coded to environment variable in EventBridge.
  - [x] Removed unnecessary Python function that created query output S3 bucket if the hard coded bucket was not found. Query output S3 bucket is no longer handled within the Python code, but rather by Terraform. This will allow passing bucket name as an environment variable.
  - [x] The query output bucket name is no longer `bcgov-aws-sea-billing-reports`. Now uses the format: `bcgov-ecf-billing-reports-output-<AWS-AccountID>-<AWS-Region>`. This will eliminate name collisions as we deploy across LZ0, LZ1 and LZ2 using a deployment pipeline.
- [ ] Currently refactoring existing Python code to something better suited for scheduled tasks on Fargate.
  - [ ] Mostly working from Git branch [cpf-1068](https://github.com/BCDevOps/terraform-octk-aws-sea-billing-reports/tree/cpf-1068)

**Comment by unoah** [comment]
Changes done so far on this ticket addressed scaling back permissions around:
- reading from the organizations API
- reading/writing to S3 buckets
- executing Athena queries
There's some overlap with ticket [1067](https://app.zenhub.com/workspaces/cloud-pathfinder-5e4dbb426c3c6af8dcbf06a7/issues/bcgov/cloud-pathfinder/1067).

**Comment by ActionAnalytics** [comment]
CI/CD component and cleanup left.  Create new tickets?

**Comment by unoah** [comment]
- [ ] Revise SES entities, specifying them as variables instead of hard coded in main.tf.
- [ ] Add product owners email address and `cloud.gov.bc.ca` to SES entities variables also. Product owners email address is easier will take less time to validate compared to domain identities. Especially post deployment to LZ0 and LZ1

**Comment by unoah** [comment]
Deployed to LZ0 and LZ1. Need to verify info@cloud email identity for SES. Few rough edges fro the CI/CI component being worked on.

**Comment by unoah** [comment]
PR for deployment to LZ0 submitted: https://github.com/BCDevOps/terraform-octk-aws-sea-billing-reports/pull/7

**Comment by unoah** [comment]
Service was deployed to both LZ0 and LZ1 late last month.

**Comment by unoah** [comment]
Pending CI/CD strategy for deploying tools to Core accounts
Need to validate the identities: info@cloud.gov.bc.ca and cloud.gov.bc.ca SES

**Comment by unoah** [comment]
cloud.gov.bc.ca domain verified in SES. Deployed to LZ2

**Comment by wrnu** [comment]
Created new tickets to finish the FX feature and verify the info@cloud... email address for sending
