### ISSUE TITLE
More information on Lambda tile 

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder#1071]
**Describe the issue**
If a team wants to use lambda services, guidance should be provided to teams and create patterns for monitoring at the platform level. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- the work on #976 included updating the compliance tile to 'compliant'
- There is more information to share with teams

**Definition of done**
- Review, parse and layout the lambda information for airtable
- publish supporting information in the tiles in airtable

**Comment by wrnu** [comment]
No longer relevant
