### ISSUE TITLE
Turn off Public Marketplace and turn on Private Marketplace

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1075]
**Describe the issue**
Work with AWS to enable SEA config to enable Private Marketplace as setting in our SEA config repo

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- The intention is for CPF to conduct very lightweight rubberstamp ingress of marketplace images into the private marketplace

**Definition of done**
- In AWS SEA Prod workspace accounts only (not core), Teams cannot deploy custom VMs from the marketplace without it being in an allow-list in the private marketplace

**Comment by wrnu** [comment]
No longer relevant
