### ISSUE TITLE
Prototype new login app with login portal

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1084]
**Describe the issue**
Current issue is that the app is not really scalable (cannot support Azure or GCP), just redirects to AWS
Doesn't have proper auth in that it's all behind the public SAML
Cannot have public pages
Cannot refresh the login page
Cannot have POs log in and get their billing reports from here
Cannot have security reports contextualized per Team
Future self-serve (add remove team members, permissions, service accounts, new layers, TFC workspaces)

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Keycloak clients for GCP, AWS, Azure
- This app should have true authentication and consider using keycloak as SAML IDP (passthrough from BC GOV IDPs) and cognito as SP (Service Provider). 

**Definition of done**
- Build basic framework 
- Consider stacks like React/Express
- Evaluate if we want 3 separate apps or try to take advantage of one app for all?
- Tickets defined for MVP and 
- Consider modular approach for 3 clouds via appsync graphql for managing http resolvers (apollo)

**Comment by wrnu** [comment]
No longer relevant
