### ISSUE TITLE
Billing for reserved instances in AWS

### ISSUE THREAD

**Issue by fastaudra** [bcgov/cloud-pathfinder#1087]
**Describe the issue**
Conversations with PO and SM about how billing works.  

**Additional context**
- We will never let teams self-serve this utility because it's irreversible
- Infrequent, not that hard for CPF team to manage
- Doesn't prevent teams from doing work, they can start with pay-as-you-go, then work with us to get cheaper

**Definition of done**
- Decide between 2 options: Pay up front and managed by CPF (say 2yrs up front), or Pay as we go commit for 2 years managed by CPF.  [PO says: let's do option 1, pay in advance]
- Investigate minimum commitments in fee schedule in the contract in the framework agreement likely accessed through the GoC Brokerage Portal

**Comment by fastaudra** [comment]
Framework agreement is on the LAN

**Comment by wrnu** [comment]
No longer relevant
