### ISSUE TITLE
SOAR Approval

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1094]
**Describe the issue**
Ryan B has crafted CPF a SOAR for the limited Team usage of Virtual Machines in AWS

**Additional context**
- Nick and Avneet to coordinate as learning

**Definition of done**
- The SOAR needs to be QA'd, understood, and handed over to the next Security analyst
- SOAR is reviewed and signed by approver Gary M
- A slide announcing that the security review is done in the next Demo slide deck

**Comment by wrnu** [comment]
No longer relevant
