### ISSUE TITLE
Make spot for Azure SEA Dev

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1096]
**Describe the issue**
Microsoft tells us we can create a "directory" off to the side that won't affect the Phase II workloads and Foundational pieces.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- See the Mural diagram (roadmap details) to see that the directory is intended to be to the side of (outside) AAD

**Definition of done**
- Create a separate directory (a management group was made instead by Jon and Julian "BCGov-AppDev-Accelerator-Dev")
- Provide access to CPF team  (see comments below for latest status)

**Comment by ActionAnalytics** [comment]
Max and Julian have access to management group. Barry, Stewart and Warren still need to get access to Management Group "BCGov-AppDev-Accelerator-Dev"

**Comment by jon-mc-git** [comment]
Done.  Waiting for response from Barry (Microsoft) on SEA script particulars, will connect him in then if he's the one to work with us
