### ISSUE TITLE
Review survey work to gauge interest in Azure Services

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1100]
**Describe the issue**
We wish to engage with Ministries wanting Azure to find out where Ministry priorities are.
We could pre-seed the survey with info we already know eg "we've seen interest in Azure Files, Azure Functions, etc"  What are we missing that you are interested in?

**Additional context**
- See the round of UX workshops and survey with Brian F, service design work 2019
- Not in scope, application modernization
- In scope, greenfield apps in line with DIB Trends & IT Operating model review Maggie C.  Smaller $ amounts, duration.

**Definition of done**
- Acquire the latest list from Bahaa
- Review and discuss with PO
- Provide Julian the list to use to store in the front counter list.

**Comment by sid-gov** [comment]
Closed as complete
