### ISSUE TITLE
Learn hardening steps of Linux VM

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1102]
**Describe the issue**
Study on-prem Linux VM to learn the configuration used for security hardening.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Documented requirements for a security hardened Linux VM

**Comment by ActionAnalytics** [comment]
Dup
