### ISSUE TITLE
Learn hardening steps of Linux VM

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1103]
**Describe the issue**
Study on-prem Linux VM to learn the configuration used for security hardening.

**Additional context**
- This will feed into how we handle VMs in all our clouds and the VM accelerator app, very important
- Expecting that there will be manifest files lying about on the desktop or in some config folders, mostly likely at C:\ level
- Requires VPN Access

**Definition of done**
- Documented what BC Gov did to security hardened their Linux VM
- - see if we can detect user limitations
- - additional security tracking software that was installed
- - services turned off
- Might need to buddy up with Prabhu to get him to quickly grab the info off the machine and then you process it
- Hardening steps get documented in a bcgov-c repo (cloud-ops...)
- Reach out to Prabhu to see if he can VPN access and collab on this ticket

**Comment by ActionAnalytics** [comment]
The team's focus was on SEA upgrade issues, so ok that this fell between the cracks.

**Comment by ActionAnalytics** [comment]
I'll escalate and take a swing at it

**Comment by ActionAnalytics** [comment]
Sean from DXE shared the security config settings and verbally updated me, so no need for this VM.  I will share with the team
