### ISSUE TITLE
Learn hardening steps of Windows VM

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1104]
**Describe the issue**
Study on-prem Windows VM to learn the configuration used for security hardening.

**Additional context**
- This will feed into how we handle VMs in all our clouds and the VM accelerator app, very important
- Expecting that there will be manifest files lying about on the desktop or in some config folders, mostly likely at C:\ level
- Requires BC Gov VPN access

**Definition of done**
- Documented what BC Gov did to security hardened their Windows VM
- - see if we can detect user limitations
- - additional security tracking software that was installed
- - services turned off
- Hardening steps get documented in a bcgov-c repo (cloud-ops...)
- Reach out to Prabhu and Jon to do a ride along and collab on this ticket because Jon has the 2022 and 2019 config
- Jon to share the above configs

**Comment by ActionAnalytics** [comment]
"you asked for SSH not RDP"

**Comment by ActionAnalytics** [comment]
Our team's VPN IP Ranges not in the allowlist

**Comment by ActionAnalytics** [comment]
Julian to escalate

**Comment by ActionAnalytics** [comment]
Sean from DXE shared the security config settings and verbally updated me, so no need for this VM.  I will share with the team
