### ISSUE TITLE
Privacy Compliance for Terraform Cloud

### ISSUE THREAD

**Issue by hromanow** [bcgov/cloud-pathfinder#1107]
**Describe the issue**
Terraform Cloud is a requirement moving forward.

**Additional context**

**Definition of done**
- Determine what compliance work is needed for Terraform Cloud.
- Document any compliance work in the appropriate format (e.g. PIA template).
- Gather signatures for the compliance work where necessary.

**Comment by ActionAnalytics** [comment]
Currently we are intending to continue using TFC the same way as before, just with a bit of parallelism (having several runners rather than one shared one for all)
We will revisit this ticket when we start to look at the TFC Business governance capability.

**Comment by hromanow** [comment]
Assigning to Andrea as part of the transition of this role.

**Comment by ActionAnalytics** [comment]
We'll revisit when we figure out path forward for TFC
