### ISSUE TITLE
Setup the use of local serverless instance of Lambda for development

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#1110]
**Describe the issue**
Our apps are complex due to having two parallel environments to support: local and live. It will be valuable to have a simpler app to maintain and would provide teams a much cleaner example that would help their understanding faster. 

Update the Developer scripts for the startup-sample-app to support the new lambda version

**Additional context**
- The only current option we know of is localstack which is AWS mock local dev instance which supports terraform deployments. 
- Warren has a trick with terragrunt to generate the providers to switch between localstack and AWS. 
- localstack has license tiers but we think we're not using anything that depends on the paid version

**Definition of done**
- New version of the startup-sample-app was created by using the currently existing Container version repo 
- The Dev scripts needs to be updated to support this

**Comment by wrnu** [comment]
No longer relevant
