### ISSUE TITLE
Get latest Naming Convention list

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1114]
**Describe the issue**
Jon to grab the latest naming conventions for us

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Jon to provide document to team

**Comment by jon-mc-git** [comment]
Azure Foundation naming convention doc found and sent.  Will be reviewed together by technical team soon
