### ISSUE TITLE
Enable the use of AD Groups to manage Azure (PIM etc)

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1115]
**Describe the issue**
We want people's names to disappear from IAM and we want to see AD groups used to manage (via default packages).  Low level default packages, upgrade access package so we default to low level access.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- This will be very similar to the RBAC pattern existing in 

**Definition of done**
- Meet with Julian for management support for this.
- Set up AD groups move away from managing CPF access via people and create an platform admin type of access for our team that uses this pattern.
- Coordinate with ADMS for this for PIM
- Related to the login page work

**Comment by wrnu** [comment]
Covered by other tickets
