### ISSUE TITLE
Review latest version of cloud naming convention doc with team

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1117]
**Describe the issue**
A review of the unified, cloud agnostic resource naming convention developed along side the Gov Azure Foundation work - to be held with SEA implementation team
 
**Which Sprint Goal is this issue related to?**
This work item is dependent on completion of ticket #946 (Retrieval and sending of latest Naming Convention version).  Completion of Ticket# 955 (rollout of Azure SEA for Dev) is dependent on this. 

Goal is to incorporate this into the Azure SEA Dev rollout and refine how maintaining\supporting the use of this unified naming convention can be achieved

**Additional context**
With a cloud asset naming convention being important for on-going resource management & long-term governance objectives, a review of the multi-cloud (non-Azure specific) naming protocol developed in cooperation with Microsoft during the Gov Azure Foundation work will be completed and incorporated into SEA wherever possible\practical.  

**Definition of done**
- Azure SEA build team to go over the naming convention documentation together to review and familiarize ourselves with the common patterns that should be used wherever possible to build consensus across all Azure infra resources, with an ability to draw this convention over to other cloud providers when\where possible

**Comment by ActionAnalytics** [comment]
Jon wants to look at AWS billing metadata which is easy to provide but we make a separate ticket bc we're in planning atm

**Comment by jon-mc-git** [comment]
Warren is away on vacation, will touch base with him on whether we can approach this on the more multi-cloud perspective first and when Azure SEA work starts up again turn it into a review and follows that could be tracked by separate tickets. Will touch base with Warren when he is back

**Comment by wrnu** [comment]
No longer relevant
