### ISSUE TITLE
Baseline our KPIs for future reporting to governance bodies

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#1119]
**Describe the issue**
Our business case for building out the Public Cloud Accelerator Service goes to Digital Investment Board on October 21. It includes several KPIs that will measure our progress towards realizing the desired benefits, and we'll report on these to several governance bodies (ED cloud group (tri-weekly), ADMs (tri-weekly), ES client centric governance model, DIB (quarterly)).

Ideally we should baseline these KPIs in time for the DIB presentation on October 21.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Here are the KPIs proposed in our business case:
- Number of compliant public cloud services available to ministry teams​
- Number of teams onboarded to compliant public cloud platforms​
- Net Promoter Score (1-10, How likely they are to recommend this service)
- Average time to bring a ministry team onboard and enable them to begin deploying an application
- Number of digital government services available
- Number, duration and cost of outages affecting public cloud digital services

**Definition of done**
Determine feasibility of measuring each of these KPIs
If any are not feasible, suggest variations or alternatives
Establish repository for recording our KPIs and their measurements (Airtable?)
Record baseline measurements of all KPIs

**Comment by lukegonis** [comment]
No longer relevant
