### ISSUE TITLE
SPIKE: Creation of Azure DevOps CI/CD pipeline automation workspace w/ GitHub connection

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1124]
**Describe the issue**
To create an Azure DevOps workspace for the Azure AppDev SEA CI\CD pipeline creation & automation work 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Would still pull code from GitHub but would manage its deployment\pipeline automations from the Azure DevOps platform.  Can unify and improved the Azure deploy experience & act as a point of collaboration for technical team members, including for planning and the micro-task management that can be involved with IaC deploys, pipeline management and automation setups (macro-task management still covered through ZenHub)

**Definition of done**
- Create a pipeline automation and collaboration workspace for both the Province technical cloud IoC team members and Microsoft technical resources
- Create the DevOps workspace and invite all technical team members, including currently assigned Microsoft technical resources
- GitHub repos don't exist and out of scope for this ticket
- Create well-formed tickets as the result of this ticket

**Comment by ActionAnalytics** [comment]
Blocked because Warren thinks he lacks proper permissions.
