### ISSUE TITLE
Coordination of the SecOps Azure Foundation Hub fw resiliency update

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1128]
**Describe the issue**
Coordinate with Security Operations for their Azure Hub firewall resiliency update

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Updates it to latest version and improves its resiliency which improves cloud networking for the Foundation workloads

**Definition of done**
- Prepare\coordinate a test plan with SecOps
- Coordinate and confirm test of new update from the test environment
- Coordinate with SecOps for this update on the current Foundation networking Hub instance

**Comment by wrnu** [comment]
Covered by other tickets
