### ISSUE TITLE
DevExchange Azure RedHat Openshift (ARO) - Post-project clean up

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1136]
**Describe the issue**
Shutdown\delete all remaining resources within the DevExchange's Azure ARO environment

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
The Platform Services team lacks permission to do a full cleanup of their former test ARO environment so they need a hand tearing it down. The benefit is cost savings and less to maintain (Azure was notifying us about a pending needed ARO upgrade otherwise).

**Definition of done**

- Take a screencap of the activity in the ARO subscription(s) before any changes.
- Shutdown all remaining ARO resources
- Delete remaining infrastructure and communicate with project lead (Olena) upon completion for any 
- Remove the ARO platform instance
- Take a screencap of the activity in the ARO subscription(s) after the changes.
- Send a screencap of the activity monitor before and after the changes to Olena so her team can have confidence that the cluster, and any expenses is generates, is gone.

**Comment by aghori1** [comment]
1. Jon provided an overview of the Azure environment, explained naming convention, etc.
2. Jon send a note to Olena Mitovska to provide any help that she could to help me remove the ARO cluster.
3. Olena provided steps written by Shea Stewart to remove the ARO from the subscription.
4. Jon will provide me access to the Azure environment.
5. I'll proceed with the unused cluster deletion early next week.

**Comment by aghori1** [comment]
![Email 3.PNG](https://images.zenhubusercontent.com/6165e35ca875bbca65fde762/b42143b3-5c28-428f-ad11-5e00d6a7436f)
![Email 2.PNG](https://images.zenhubusercontent.com/6165e35ca875bbca65fde762/e950aef0-6bfd-4ed1-b3a4-850b05072385)
![Email 1.PNG](https://images.zenhubusercontent.com/6165e35ca875bbca65fde762/9fa4ebc2-e03a-44be-820e-31d7d1671a85)

![Deletion Activities 1.PNG](https://images.zenhubusercontent.com/6165e35ca875bbca65fde762/c0158504-6f73-49a7-ba37-dc88fd0ba12b)
![Deletion Activities 2.PNG](https://images.zenhubusercontent.com/6165e35ca875bbca65fde762/9c02d60b-e5de-41b5-8a12-9a24b7098b83)
![Deletion Activities 3.PNG](https://images.zenhubusercontent.com/6165e35ca875bbca65fde762/13a8b573-d74f-45c1-9417-f7fd7c58defc)
![Deletion Activities 4.PNG](https://images.zenhubusercontent.com/6165e35ca875bbca65fde762/2a75973b-49ca-4f58-ae3a-fcd64824c224)
![ARO Cluster Removed.PNG](https://images.zenhubusercontent.com/6165e35ca875bbca65fde762/7b0009ad-5455-4e9b-b12d-c7dbe8cf790a)
