### ISSUE TITLE
Teardown of the Azure ARO cluster

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1137]
**Describe the issue**
The Platform Services team lacks permission to do a full cleanup of their former test ARO environment so they need a hand tearing it down.  The benefit is cost savings and less to maintain (Azure was notifying us about a pending needed ARO upgrade otherwise).

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Take a screencap of the activity in the ARO subscription(s) before any changes.
- Destroy the resources in the Plaftform Services Azure ARO space.
- Take a screencap of the activity in the ARO subscription(s) after the changes.
- Send a screencap of the activity monitor before and after the changes to Olena so her team can have confidence that the cluster, and any expenses is generates, is gone.

**Comment by jon-mc-git** [comment]
Duplicate item.. copied the additional context here for clarity in existing ticket and closed
