### ISSUE TITLE
AWS LZ0 Clean-up

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1141]
**Describe the issue**
We want to clean-up the current LZ0 root account and remove all existing resources before reusing it

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- resources of particular importance to be removed are all IAM users except for Julian and Warren. 

**Definition of done**
- Clean up is complete

**Comment by wrnu** [comment]
Management (root) account has been cleaned and all other accounts have been moved to the Ignored OU. The accounts in the Ignored OU are waiting to be closed.
