### ISSUE TITLE
20 project sets created in AWS LZ0

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1144]
**Describe the issue**
We want to create project sets for use in the Chekpoint Hackathon. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Reach out to Julian to confirm the handing out project sets

**Definition of done**
- These project sets have only Dev and Sandbox in them
- Hand 5-10 of the project sets to Chekpoint, AWS for prepping their cyber-range game events

**Comment by wrnu** [comment]
@MaxWardle Accounts have been created, we just need to give access to Checkpoint and AW.
