### ISSUE TITLE
Deploy OpenSearch dashboard to the security core account

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1150]
**Describe the issue**
Currently the dashboard is deployed in the workload account that belongs to CPF and we need to move it to the core accounts because we have a hypothesis that doing that would make it easier to access the data that it needs.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- we originally deployed this in a workload account in LZ2. 
- Now we have LZ1, we can safely deploy this in the LZ1 security account. (Once tested it can be moved to LZ2)
- We intend to add this to the layer automation so that it deploys with everything else automatically and will be tested in a torn-down LZ1 environment. 

**Definition of done**
- Deploy this in LZ1 security account

**Comment by ActionAnalytics** [comment]
Done upstream by Ryan J, coming in 2 patches
