### ISSUE TITLE
Azure MOU/Chargeback/Messaging

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1159]
**Describe the issue**
Azure billing needs to evolve to a quarterly state similar to what CPF does with AWS tenants.

**Additional context**
- CSAM handles the reconciliation and chargebacks at the moment
- There is a current backlog of chargebacks to deal with

**Definition of done**
- Meeting with CSAM to discuss how to support them
- Messaging in the onboarding material that clearly set tenancy billing expectations
- Link this with the existing MOU structure in the onboarding funnel (double check existing)

**Comment by sid-gov** [comment]
We have had the meeting and discussed that we are not going to put it in the onboarding. We have a ticket to communicate to the existing tenants.
