### ISSUE TITLE
Demo\Review Azure capabilities around Cost Analysis & how this could integrate with current billing

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1161]
**Describe the issue**
Azure billing has pre-canned analysis capabilities.  Review filter, export, and scheduling possibilities within these capabilities and this could be coordinated with current AWS billing processes.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
To review how this could be automated to either export to current CPF billing periodically for processing, or run on schedule simply as an advisement to our CPF Billing Administration on where projects stand according to client project\service budgets and\or agreed MOU's

**Definition of done**
- Identify capabilities available to us and which ones would be most useful
- Test any export configuration and scheduling capabilities  
- Demo findings for meeting discussion with Olena and team
- Discover what can be automated
- Decide if full export of billing details is necessary ie. for historical records (ie. any limitation on current billing info retention logs in place), OR if a simpler export could be sufficient for budget\MOU comparison and the Billing Administrator uses a static project link to the client's Cost Analysis dashboard can be used
- Set up additional tickets in accordance to results found

**Comment by wrnu** [comment]
Covered by other tickets
