### ISSUE TITLE
Technical intake process - SDPR Azure Data Factory project

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1167]
**Describe the issue**
Once the initial funnel meeting happens by Stuart and we understand which path we're taking (option 1: "let's stay in touch for later", or option 2: "interesting, let's proceed now").  If it's now, we have agreements signed by client, do the Technical Review to gain MVP understanding to be deploy the right stuff and pass on tips, and deploy the Azure workspace in accordance the solution needs
 

**Additional context**
Project is about bring data centralization and transformation capabilities to SDPR BI\analytics team, most optimally as an automated pre-process workflow that tranforms data types according to a centralized schema and exports regular updates into their PowerBI data repository and dashboarding system.  Project will likely involve the Azure Data Factory service

**Definition of done**
- Collaborate on the project team meetings with Stu
- Assuming that this proceeds, work with SDPR teams to coordinate and deploy the workspace
- Re-enforce that any configuration here should be exported and with the need to possibly rebuild it any time (DR-ready)
- Deploy Data Transformation environment and train, for transfer of its 'ownership' 
- Get team agreement that a migration to a SEA might happen and they would have to incur the migration costs.

**Comment by ActionAnalytics** [comment]
We think this is a duplicate with 1471.  If we're wrong, we will hear about it
