### ISSUE TITLE
Technical onboarding - NRM Mapping/GPU repo project

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1173]
**Describe the issue**
NRM needs to upgrade\replace its current Citrix-based Mapping\GIS farm of servers and would like to explore Azure GPU capability\functionality and services in this area for possible replacement of current farm

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- We do not have a start date

**Definition of done**
- Work with NRM on what they are exactly trying to solution\identify in this area 
- Deploy GIS\Mapping project workspace in accordance to what has been discussed

**Comment by ActionAnalytics** [comment]
Blocked per Julian getting up to speed on the funnel status.  Assume it's a go in next 6 weeks (if not we will throw back)

**Comment by ActionAnalytics** [comment]
Most likely this is stale, Julian to search old records

**Comment by jon-mc-git** [comment]
Looks to be stale, will discuss with Julian but may close if nothing further

**Comment by ActionAnalytics** [comment]
We made a CRM entry under NRIDS GPU Mapping, closing for now and will use this ticket for context on new tickets if needed.
