### ISSUE TITLE
Onboarding - NRM GPU Mapping/GIS repo project

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1174]
**Describe the issue**
NRM needs to upgrade\replace its current Citrix-based Mapping\GIS farm of servers and would like to explore Azure GPU capability\functionality and services in this area for possible replacement of current farm

**Additional context**

**Definition of done**
- Forms to be filled out and reviewed for approval and MOU's signed as per covering costs
- Once approved, transferred for Technical Review (#1173)
- Recall where landed and update the funnel records together with Julian as training

**Comment by scayzer** [comment]
Checked in with Adam 2021-12-07 - he has lots on the go and will pick this discussion up with Julian in the New Year.

**Comment by wrnu** [comment]
No longer relevant
