### ISSUE TITLE
Review TF 'plan' for Az SEA resource output if possible or Manually create to understand SEA baseline

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1176]
**Describe the issue**
Base analysis needed to quickly understand what cloud resources are being deployed with the various Terragrunt Terraform modules being executed within the SEA 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Knowledge here will be used to draw on for decisions and familiarity on how we can manage this space (Core & LZ's) and what areas we may need to make decisions on.  This will also be used during our naming convention discussions and decision making

**Definition of done**
- Meeting with Julian and Warren to knowledge transfer
- Produce a list of the resources being generated by the SEA script in Azure and classify them (filterable) for better understanding and decision-making going forward (filter by classification & and implementation area)

**Comment by jon-mc-git** [comment]
Ticket on hold until work on Azure SEA continues.

**Comment by wrnu** [comment]
No longer relevant
