### ISSUE TITLE
GCP Risk Terms Review 

### ISSUE THREAD

**Issue by fastaudra** [bcgov/cloud-pathfinder#1178]
**Describe the issue**
Review feedback from GCP on compliance work expected based on an update from Risk Management Branch (RMB)

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Coordinate with Risk Management Branch RMB
- Draft a response back to GCP

**Comment by sid-gov** [comment]
This is blocked until GCP responds
