### ISSUE TITLE
GCP Privacy Terms Review for Service Order

### ISSUE THREAD

**Issue by fastaudra** [bcgov/cloud-pathfinder#1180]
**Describe the issue**
This is to review the privacy terms for the GCP Service Order. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- PCT review of response/terms from GCP and feedback is approved
- PCT approval of terms/response from GCP
- GCP SO moves forward with LSB

**Comment by sid-gov** [comment]
This is blocked until GCP responds.

**Comment by fastaudra** [comment]
Requires further information for PCT's privacy solicitor.
