### ISSUE TITLE
Terraform Cloud compliance reviews

### ISSUE THREAD

**Issue by fastaudra** [bcgov/cloud-pathfinder#1184]
**Describe the issue**
Once we have decided on the subscription type, we will need to ensure Terraform Cloud is compliant for privacy, security, and legal. This is pending a decision on if we decide to change the terraform license.  

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Find existing STRA/PIA as it's likely someone would have done it already
- SOAR up for approvals
- PIA up for approvals

**Comment by ActionAnalytics** [comment]
Goes away for now until other options
