### ISSUE TITLE
Gain access for the CPF team to the OCIO SecOps SIEM 

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1185]
**Describe the issue**
The SecOps team has a Hadoop cluster fronted by Splunk dashboards we think.  Not that we are shipping our logs to that system, we would like to have access to view our own log data in the SecOps system because we've been told that they intend to keep long term historical log data.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Set up a demo meeting for the CPF tech and security members to attend
- Have each member of the above have individual access to the system
- Have the SecOps person in charge of granting access give us a walkthrough and provide us best practice lessons.

**Comment by ActionAnalytics** [comment]
Blocked because the logs are not fully transferred over.  Logs are partially transferred at the moment except for VPC logs which require conversion to JSON.

**Comment by ActionAnalytics** [comment]
Waiting for Austin to return from Vacation.  
Prabhu has done everything on our end, needs to be checked by Austin.
This is high priority for Julian because the network traffic is generating a noticeable higher expense.

**Comment by sid-gov** [comment]
@ActionAnalytics to escalate
