### ISSUE TITLE
Legal has reviewed and approved subscription terms for Terraform

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1186]
**Describe the issue**
We need to meet with Legal to review the subscription terms for Terraform. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Meeting with LSB happens
- LSB approves the terms

**Comment by ActionAnalytics** [comment]
Not doing for now
