### ISSUE TITLE
Features for new Login App

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1187]
**Describe the issue**
We want the login app to duplicate the functionality of the original login app except for the sort order of the displayed accounts. 

**Additional context**
Ideas for future design discussions with technical team: 
- Bonus points if it uses a widget for the user to change sort order. 
- Navigation Bar could have things like: 
- Projects, reporting, monitoring, documentation etc. 
- top-right will be user configuration, 
- In the project page, teams can self-serve their user access (automated reporting to the POs of who has access on a monthly basis)
- In the project page, it will contain accounts accessible in the project set and this is like a old login accordion. 

**Definition of done**
- In the new login app, the sort order defaults to alphanumeric by project name, environment. 
- We are going to additionally display the billing code, PO name as metadata. 
- Architected so that if page expires, the next thing you click on it redirects you to the keycloak login page

**Comment by wrnu** [comment]
No longer relevant
