### ISSUE TITLE
SPIKE: Plan public cloud app use across multiple environments

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1188]
**Describe the issue**
We need to factor that the login app will be reused and we wish to use it in the most effective way possible. 

**Additional context**
- Public cloud app is the new terminology for the login app
- We have 3 clouds
- We have 3 environments in each cloud: dev, test, prod
- Dev and Test are very low usage. Only Prod will be actively used. 

**Definition of done**
- Meeting with Max and Warren to discuss plan 
- 2nd meeting with Julian to review plan
- next step well-formed tickets are created.

**Comment by wrnu** [comment]
No longer relevant
