### ISSUE TITLE
Reserved Instances Legal Review

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1190]
**Describe the issue**
In order to be able to provide tenant teams the ability to save money by reserved instances, we need a legal review of the approach.

**Additional context**
- The time boundaries boundaries on NWPTA's $75k threshold is 1 year, so recommend we scope any Reserved Instances to 1 year or less
- Marisa J at GDX apparently has completed a procurement for Reserved Instances.  According to Dan P, it includes "proper cost accrual across fiscal years". Did GDX get legal approval?  Can we use it to help our legal work?

**Definition of done**
- Legal review complete
- Work with Shiho and Gordon D
- Introduce Julian to Danielle
- work can continue in background, but we will lay low on communicating in order to prioritize the contracts.

**Comment by fastaudra** [comment]
No legal assigned to this task yet. Reconvene next week.

**Comment by sid-gov** [comment]
Possible legal hand over?

**Comment by fastaudra** [comment]
Document from SSC received 25-01-2022

**Comment by ActionAnalytics** [comment]
We need to re-estimate this because it's waaaaaaayyyyy more than a 1

**Comment by fastaudra** [comment]
Transfer to Louise?

**Comment by wrnu** [comment]
No longer relevant
