### ISSUE TITLE
Login page tags loading very slow LZ2

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1192]
**Describe the bug**
The tags take 30sec to a minute to load now.  Before it was 3 seconds. This could be related to KeyCloak users that have lot of accounts in the login screen. 

**Additional context**
- Tags load fast in LZ0 and LZ1
- Tags load very slow in LZ2 (Browser: Firefox latest edition on OSX)
- This is low priority as there are few users and we plan to rearchitect the login page. 

**Definition of done**
- Find out what is causing the delay is and improve the performance

**Comment by sid-gov** [comment]
We are not doing this because we are rebuilding the page. This is a waste of time.
