### ISSUE TITLE
Update Onboarding Training Privacy Slides

### ISSUE THREAD

**Issue by AndreaBingham** [bcgov/cloud-pathfinder#1194]
**Describe the issue**
Andrea has joined the team and Holly is stepping away. We have a new contact person for teams that have privacy questions and PIAs. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Slide deck has been read, understood
- PPT slide is updated in Teams

**Comment by ActionAnalytics** [comment]
Andrea is starting to work on this
