### ISSUE TITLE
Andrea onboarding with folder of presentations

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1195]
**Describe the issue**
CPF client Team training has 8 powerpoint slide decks.  This would be valuable for Andrea to gain understanding about the other topics we train new tenants with.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Read each deck
- Collect any questions
- Book time and meet with various team members who present the deck in question and ask them whatever clarification you need (prompt them to improve the clarity of decks if there is anything super confusing). Connect with Oso when setting up these meetings.

**Comment by sid-gov** [comment]
This will be covered by Andrea attending the onboarding session.
