### ISSUE TITLE
Create SoAR and PIA for Cloud Pathfinder use of Google Forms

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#1198]
**Describe the issue**
In the course of investigating government-wide demand for AirTable vs alternate eForms solutions (ticket #1158), we found that SoAR and PIA have been done for Google Forms (by GRS) and it has several key advantages over AirTable for our onboarding Forms (strong support for validation of fields entered and ability for submitters to amend their submissions after hitting the submit button). The onboarding forms are now available in Google Forms and we just need to complete the PIA, SoAR and legal review of terms and conditions.

**Additional context**
- Content from existing GRS SoAR and PIA for Google Forms can be merged with content from our Airtable SoAR and PIA - quick to do with possible delay in getting the required approvals.

**Definition of done**
- SoAR and PIA completed and approved for Cloud Pathfinder use of Google Forms

**Comment by ActionAnalytics** [comment]
PIA covered, just the SoAR that needed to be done
