### ISSUE TITLE
Acquire Security and Privacy Incident report templates from other teams

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1202]
**Describe the issue**
We intend to make cloud focused Privacy and Security Breach templates for MPOs and MISOs in the App teams to use in the event of an incident. The intention is to provide them a link on the login page so that they can fill out a form or download a template to get them started in the hurried response to an incident.

**Additional context**
- 77000 incident response form (Ask Julian for contact person)
- OCIO SecOps
- PCT
- Platform Services / DXE
- NRM, Justice, Health
- Device Services (Michael G)
- Julian to show the PO key info card

**Definition of done**
- Reach out to partner teams across gov and collect any security or privacy incident templates.
- Try to find any that are meant to be used by App or Product teams
- Collect and store them in our teams folder under the Compliance section

**Comment by AndreaBingham** [comment]
We reached out to the other teams and received some related information. This has been saved in the Compliance section.
