### ISSUE TITLE
Create cloud focused incident breach templates for privacy and security

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1203]
**Describe the issue**
We intend to make cloud focused Privacy and Security Breach templates for MPOs and MISOs in the App teams to use in the event of an incident. The intention is to provide them a link on the login page so that they can fill out a form or download a template to get them started in the hurried response to an incident.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Review the collected forms from previous ticket
- Draft a form word doc in Teams
- Create a lightweight common form (super template) that can be used to describe an incident
- Talk to Julian for more about the new required fields pertaining to cloud environments
- Review with PO

**Comment by ActionAnalytics** [comment]
This is blocked because it's waiting for the collection of the sample incident reports

**Comment by AvneetKahlon** [comment]
Need to be reviewed by PO
