### ISSUE TITLE
Present/communicate new FOIPPA amendments to the CPF team

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1207]
**Describe the issue**
There are new FOIPPA amendments that the CPF team needs to be aware of.  

Just because the bill passed and removed some key concepts, there is a regulation that could very well keep things the way they are.  What does it mean for us in the services?

How does it impact our contracting processes?  Our PIAs and STRAs?

**Additional context**
- We will know more after Nov 25
- Audra and Stu brought back info from Matt's presentation

**Definition of done**
- 15 min presentation + 30 min open discussion to CPF team on the new changes
- Capture questions from the team to take away and help
- Aim for January when we're back post Jan 4th

**Comment by sid-gov** [comment]
This is optimistic depending on the dates and might not be possible.

**Comment by ActionAnalytics** [comment]
Can we use this ticket to have a team discussion?  There are many people on the team that have completed reviews of FOIPPA but people have arrived at many different interpretation which will impact the service and architecture that we provide our clients.  Do we default lock down the guardrails to canada only (GoC, Jon, Julian, SecOps all think so) with a mechanisms for exceptions, or do we allow use of any region and remove the region guardrails alltogether (Gen, Procurement/Audra, others?) ?
