### ISSUE TITLE
Experiencing Azure Service

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#1212]
**Describe the issue**
After interviewing Azure users and hearing their expectations and challenges, it will be helpful for service designer to go through the service to understand user's experiences and be more apprehensive during follow up interviews with our users.

**Additional context**
- Depends on early SEA environment

**Definition of done**
- ride-along with the 1st or 2nd team in SEA Azure
- go through some recommended reading from the team
- schedule a time with our team to go through Azure access and onboarding
- report back to team

**Comment by wrnu** [comment]
No longer relevant
