### ISSUE TITLE
Research solution for education and reminding users of the importance of compliant service and shared responsibility model

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#1214]
**Describe the issue**
After interviewing Azure users there was a clear need of educating and reminding our users of the 2 important issues:
- compliance and what does it mean?
- clear clarification of the shared responsibility model
- we need to know when and how much degree do we need to start messaging around this. 

it will be interesting to research what is the best solution to highlight those 2 issues.

**Additional context**
- Related but out of scope: Procurement compliance 

**Definition of done**
- Meet with the compliance members of the team, Jon, PO, Stu to discuss the order in which we will tackle compliance as it relates to the type of workloads that we are letting into the environment and the state of the environment itself
- Come away with a shared understanding

**Comment by wrnu** [comment]
No longer relevant
