### ISSUE TITLE
SPIKE: Design a change to the SEA Log Archive Lifecycle Storage Locations

### ISSUE THREAD

**Issue by unoah** [bcgov/cloud-pathfinder#1217]
**Describe the issue**
We know that the current SEA Log Archive Lifecycle Policies for the Log archive bucket policies are set to 90 days for the immutable log archive bucket.  We wish to increase the storage.

**Additional context**
- The current log archive is set to 90 days for cost reasons.  
- Cost of log storage is actually driven by several multiplicative inputs, it's a function of 
- - how many logging sources we are keeping, multiplied by
- - how many project-sets we have (or how many Ministry client applications), multiplied by
- - how much traffic and activity each of those applications have, with possibly 
- - how much parallelism exists in each teams' CI/CD (linear vs heavily PR-based)
- Based on the above, the likelihood of the log archive becoming prohibitively expensive is high 
- S3 log archive and cloudwatch are governed by policy
- Glacier does not provide us the ability to scan but it is a long term investigation backup.
- After the logs exit the current log archive, we no longer see them on the dashboard
- Curious to see how long the cloudgaurd dashboard persists it's data for the dashboards (unrelated to this ticket) 

**Definition of done**
- 2 year glacier logs desired (auto-reap after 2 years)
- Confirm if the AWS SEA lifecycle config.json is configurable to incorporate a glacier location to place logs after they expire from the current "hot" log archive.
- Meet with Ryan J and explain that we want to have a hot log archive that is currently set to 90 days along with a very cold (very cheap, glacier) long term log archive, and that we may even reduce the size of the 90 day archive to 30 days if the 90 day archive grows too large.  
- Create a solution that can be implemented at the SEA level and pushed upstream for SEA community benefit and so that we don't need to worry about fragility of our implementation through SEA patches.

**Comment by ActionAnalytics** [comment]
Prabhu noticed something interesting that there are two log buckets at the moment in LZ2 and one of them doesn't match the lifecycles defined in the config - Ask Ryan about this (Warren has notes on this)

**Comment by wrnu** [comment]
covered by other tickets
