### ISSUE TITLE
User needs assessment for cloud integration

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1218]
**Describe the issue**
We are looking to talk to internal stakeholders in BC to assess their perceived needs for workloads that span on-prem, cloud and they need to talk to each other. 

**Additional context**
- What are the patterns other teams are following? 
- Cloud to DC and vice versa

**Definition of done**
- Assess demand from BC stakeholders 
- Meetings with 4 stakeholders 
- Review/Share information that we have already with Greg
- Greg wants us to ask the 5 whys and what are they trying to do

**Comment by wrnu** [comment]
covered by other tickets
