### ISSUE TITLE
Review internal and external-research  of cloud integration results

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1220]
**Describe the issue**
We want to meet with the team and review the results from the internal and external research and rank based on how we interpret the validity of others approaches with respect to fit with BC Gov. 

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- 2hr min meeting with CPF team and Greg happens
- Ranking exercise in Mural
- A ranked interpretation of results and clean-up of data after.

**Comment by wrnu** [comment]
No longer relevant
