### ISSUE TITLE
Move Keycloak params and possibly other landing zone secrets to parameter store in the master accounts

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1227]
**Describe the issue**
Currently when a new team member is onboarded to the landing zones development, there are an amalgamation of secrets and vars files that team members pass around to be able to run the automation.

**Additional context**

**Definition of done**
- Meeting with Warren to define what should be in the parameter store and 
- Set up the pattern to make it happen
The following secrets and vars live in the respective master accounts parameter store:
- keycloak.tfvars

**Comment by wrnu** [comment]
done
