### ISSUE TITLE
Compile feedback on Cloud Security Schedule

### ISSUE THREAD

**Issue by fastaudra** [bcgov/cloud-pathfinder#1230]
**Describe the issue**
Bonnie is asking Audra and Julian for the CPT on the Cloud Security Schedule (CSS). 

**Additional context**
Vendors have challenges accepting some of the terms in the CSS. There is a file called CSS0updates-491-draft.docx
- Role based: Project/App > Platform > Labour > SaaS

**Definition of done**
- Audra and Julian meet to review and compile vendor and procurement pain points.
- Suggested changes to the CSS sent to Bonnie.

**Comment by ActionAnalytics** [comment]
We'll start this after the 22nd

**Comment by sid-gov** [comment]
Tickets to be created for the next steps.
