### ISSUE TITLE
Onboard Asghar into BC Gov Azure

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1231]
**Describe the issue**
We need help in dealing with the amount of Azure tickets and we want to onboard Asghar to start helping. 

**Additional context**
- We dont know how Asghar works so we want to give few tickets until we widen his scope of responsibility. 
- 

**Definition of done**
- Onboard Asghar with access only to ARO subscription

**Comment by jon-mc-git** [comment]
Ran through initial on-boarding of Asghar into BC Gov Azure and assigned him the DevExchange's ARO environment to programmatically cmd the shutdown of the ARO system-deployed resources (ARO is PaaS system).  This will automatically de-assign the OpenShift licenses we're being charged for, along with the resource infrastructure that was deployed
