### ISSUE TITLE
Post SEA Upgrade Validation

### ISSUE THREAD

**Issue by unoah** [bcgov/cloud-pathfinder#1234]
**Describe the issue**
Validation steps are needed following SEA version upgrade.  It's not enough that the SEA deploys in LZ1 Test, it also needs to be checked if it's working.   We don't want to do it manually every time, rather we'd like to have an automation layer that runs after the terraform config layer we have that runs a set of tests.  

**Additional context**
- The team currently have no standardized validation checks in place following an SEA version upgrade

**Definition of done**
- Put together series of validation checks following SEA version upgrade
- Automated solution written at the end of the terraform layer we run after each upgrade.  
- Configurable to toggle on or off (for example we may wish to run it in LZ0 or LZ2 to check it's status after an upgrade)
- Tests:
- - Deploy a single project-set {sandbox, dev, test, prod} involving the creation of the 4 accounts
- - Deploy a container demo app in the project-set and test its response via route (basic health check)

**Comment by ActionAnalytics** [comment]
Carles has a whole stream of work to address this
