### ISSUE TITLE
AWS SEA Terraform module for Checkpoint firewall routing

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1244]
**Describe the issue**
AWS SEA v1.5 released support for checkpoint firewalls. A terraform module is needed to automate the routing of traffic from the internet (perimeter network) to applications running in the workload accounts (project sets).

**Additional context**
- There is a chance that the v1.5 version of the SEA would have changed the way routing works. 
- Check Point provider has some examples. 
- https://github.com/BCDevOps/terraform-octk-aws-sea-routing

**Definition of done**
- Reach out to Ryan J, Chris B before doing this. 
- In scope: public repo with the code for terraform module that will configure check point firewall and be installed in Bc Gov terraform instance (used for configuring routing for a project set only).  
- Routing module created and tested in LZ1 that can route traffic for a project set (dns sub-domain that is configured by the dns module) to a specified internal fqdn.

**Comment by ActionAnalytics** [comment]
Putting this to sleep until the LZ upgrades are done
