### ISSUE TITLE
Clean up Hackathon leftovers from LZ0

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1248]
**Describe the issue**
There is a kube cluster and other deployments that were created as part of hackathon. We need to clean those up before they become expensive. 

**Additional context**
- There were 5 workloads that were handed out to the teams: 
ifh1r5 (Cloud Pathfinder LZ0 - 18)
km4tb2 (Cloud Pathfinder LZ0 - 19)
p4hmga (Cloud Pathfinder LZ0 - 20)
u0yes5 (Cloud Pathfinder LZ0 - 17)
srndm6 (Cloud Pathfinder LZ0 - 2)
pfcem0 (Cloud Pathfinder LZ0 - 21)
- Couple others in use: 

- Status tag will be: New (ready), Assigned, Refurbished, Broken, Unusable (To be determined)

**Definition of done**
- Clean the environment using a tool from Warren. (Ask Warren for latest tool)
- Tag the environment as Refurbished.

**Comment by ActionAnalytics** [comment]
Leave the leftovers up until January as Nick is still in there
