### ISSUE TITLE
VPN Client stopped working for Mines team

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1249]
**Describe the bug**
Teams need a pattern to securely access their databases and parts of their app. In conjunction with AWS, we provided them a pattern that used VPN client which was valuable because it did not leave any resources exposed to drive-by attackers on the web. 

**Additional context**
- SEA appears to have closed this mechanism in v1.5
 

**Definition of done**
- Fix the bug and re-enable this functionality even if it involves disabling a guardrail via the terraform layer that runs after landing zone upgrades

**Comment by wrnu** [comment]
Mines doesn't need the vpn anymore. In any case I tested it and it works.
