### ISSUE TITLE
SPIKE: Work with AWS to develop a definitive pattern for app development access

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1250]
**Describe the issue**
It appears in the newest version of the SEA that the VPN client approach might no longer work. We wish to work with AWS to use the most advanced secure pattern such that teams can easily connect to resources of databases without exposing assets to attackers on the web. 

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Meet with Ryan J and have him provide a high-level overview of this pattern, or get his blessing of the original vpn client pattern. 
- Create well-formed tickets describing the work to have a pattern moving forward and consider this as target for automation during creation of new project sets.

**Comment by MaxWardle** [comment]
Had a meeting with Ryan and Warren. A ticket was created capturing the solution we discussed and added as a dependancy to this ticket.
