### ISSUE TITLE
Security review of AWS Polly

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1253]
**Describe the issue**
The Falcon BC Parks would like to use the AWS Polly service to generate captcha audio and is asking the Polly be reviewed for adding to the "reviewed" list of self-serve tools available for teams to consume in their apps.

**Additional context**
- This would likely not impact the platform PIA and PO thinks that this use case is low-risk

**Definition of done**
- Review the use of AWS Polly for generating captcha audio
- Coordinate with privacy review
- Reach out to Ryan Jaeger from AWS (he's on Rocket Chat) and use this as an excuse to meet him (be aware Andrea is doing the same so perhaps coordinate)
- Work with Andrea and coordinate if/when ready to update the tile colour from orange (not approved) to green (reviewed)
- If there are concerns, bring forward to PO and discuss.

**Comment by AvneetKahlon** [comment]
Security review completed and tile turned green - Compliance pattern also stated for MPOs.
