### ISSUE TITLE
Revisit how CPF works

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1257]
**Describe the issue**
CPF Team and any new member of the team needs a guiding principle document to get an understanding of how we work and for the product/service we are building for Ministry teams. 

**Additional context**
- we aim for a presentation style format stored in Teams
- https://digital.gov.bc.ca/resources/digital-principles
- This might be used for a communication piece for dealing with our customers 

**Definition of done**
- Draft of the proposed explainer of how we work (Eg: We are working in the open so we assume anyone can get a hold of our material, we are also pathfinding and we have a fairly technical audience)
- Meeting to discuss and define the 'how' of how we work

**Comment by sid-gov** [comment]
We need a list of docs that need to be updated as we publish this deck.

**Comment by wrnu** [comment]
done
