### ISSUE TITLE
Review impacts of FOIPPA amendment and new regulations on Cloud Service Provider contracts 

### ISSUE THREAD

**Issue by fastaudra** [bcgov/cloud-pathfinder#1260]
**Describe the issue**
The bill for amendments to FOIPPA has ben passed in legislature. The amendments have impacts to compliance for data residency in Canada as well as data sovereignty. Impacts to the contractual language under the Service Orders need to be identified.

**Additional context**
- Andrea has stepped off the team to focus on other PCT tasks

**Definition of done**
- Review of GCFA - Annex A - Schedule 1 Privacy and Schedule 2 Security done
- Review of the suggested changes to the draft GCP Service Order with references to FOIPPA, data residency, and data sovereignty completed.
- Review of the draft Azure Service Order with references to FOIPPA, data residency, and data sovereignty completed.
- Any changes that are done for the 2 above CSPs should be noted and applied in a separate ticket. 
- Review with Julian and Avneet where we got to

**Comment by ActionAnalytics** [comment]
High confidence from Audra that from a contracting perspective the ticket is done.  We need to coordinate all the other perspectives (Privacy, Security, Platforms) in a separate effort

**Comment by ActionAnalytics** [comment]
Conversation so we know what to tell people who ask - maybe make a ticket to update the FAQs?
