### ISSUE TITLE
Get clear understanding for new data residency requirements from FOIPPA (consider GoC as well)

### ISSUE THREAD

**Issue by emilyjones430** [bcgov/cloud-pathfinder#1263]
**Describe the issue**
FOIPPA has had a series of amendments that potentially impact the work done by the CP team. We know of a few areas that will certainly impact the work (data residency, PIA process etc.) but there may be other sections of the Bill 22 that could affect the work. A review of the amendments should be done to ensure awareness of all relevant areas of the bill. 

**Additional context**
- Audra's ticket was focused on the contracts, but this could feed into her ticket
- https://www2.gov.bc.ca/gov/content/governments/services-for-government/cloud-computing-in-the-bc-government/foippa-amendments-related-to-cloud-computing

**Definition of done**
- Summary document outlining areas of relevance to CP Team in Bill 22. 
- Tickets or additional work may come out of this task, esp related to updating training material and processes.
- We need to focus on the guardrails that force teams to use compute and especially storage in the Canadian territory. 
- Is this still needed by FOIPAA? If not, why does the GoC lock down everything to Canada? Do we need to do the same still?

**Comment by ActionAnalytics** [comment]
@emilyjones430 possible to have an update here in thread about how this is going?
