### ISSUE TITLE
Rotate the keys in Terraform Cloud

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1264]
**Describe the issue**
AWS tokens are stored in each team's workspace.  There are a lot of workspaces (~600).  We need an automated approach to creating new tokens in AWS and updating them in TFC.  

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Lead the security effort
- Coordinate with the tech team to have someone co-create an approach (assume via Terraform code)
- Code needs to live in GitHub
- Coordination and communication will be required with each team
- No downtime for each team (tricky, be careful)
- Scope, this could be an automate script that is run manually every 6 months for now
- An rolling 6 month reminder in outlook for doing this on a regular cadence

**Comment by wrnu** [comment]
done

**Comment by wrnu** [comment]
done
