### ISSUE TITLE
SPIKE/DO - Pathfind a way to auto-unblock the TFC queue

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1269]
**Describe the issue**
The issue is that our current TFC is frequently blocked, usually by newbies teams that forget to add a certain (autoapprove) statement at the end of their scripts.  When that happens, the queue waits for a human to sign in and approve the run.  GitHub actions expire and times out.  Usually another team hits the logjam and asks us to unblock the queue via RocketChat.  This is not a good service experience nor a good pattern for teams.

Is it possible through some clever scripting for us to either 
A) detect and block runs that lack the autoapprove? or
B) can we have a piece of compute somewhere that is polling the service periodically, reading the name of the current job, and if it sees the same job for 2 polling periods, auto-kick the job / reset the queue.  Caution in case we get in a bot war with some other automation

Do we autopromote/approve or kick?

**Additional context**
- It is possible that this can't be done.  And that's ok.  This would be really nice if possible
- Rocket chat is easy - talk to Prabhu

**Definition of done**
- Coordinate with Max or Warren
- A mechanism exists and is deployed that auto-unblocks the queue so that we don't need to
- Set up notifications to rc channel "#public-cloud-tfc-queue", pull in the other tech team members so they can see the events
- Create a notification when the blocked queue is detected so that we have a history of events easy for us to see
- If permanent compute is needed, think about a maintainable, disaster tolerant way to host this (rebuildable by script, config stored in github, etc - consider the environment untrusted from the point of view of permanence)

**Comment by unoah** [comment]
- First pass with notifications to RocketChat can be found at [octk-tfc-queue-manager](https://github.com/BCDevOps/octk-tfc-queue-manager)
- Currently deployed to LZ2 operations account.
- Working on addressing false positives. Once completed, will extend with capabilities to auto-unblock the queue
