### ISSUE TITLE
Technical assistance with Key Rotation for TFC 

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1270]
**Describe the issue**
Avneet will be leading an effort to periodically rotate TFC stored AWS tokens. 

The challenge is that there are several hundred workspaces all with keys stored there.  Automation would need to be used.

**Additional context**
- GitHub Actions connects to TFC via a TFC team token
- Each TFC workspace contains a different AWS token for the corresponding AWS environment
abc234-dev in TFC connects to abc234-dev account in AWS

**Definition of done**
- Most likely will involve Terraform as the approach
- Proceed with extreme caution.  Possible in LZ1 on a small subset of workspaces.
- Create automation that doesn't affect stability for the teams using (test on a small set first)
- The automn will need to create a new token, update the team workspace setting secret in TFC 
- Consider friction points in AWS Parameter store
- Meant to be kicked of manually (but to the crawl the accounts/workspaces in an automated manner as a job) every 6 months or so.

**Comment by mitovskaol** [comment]
@NickCorcoran  Can you please review and confirm if it is still a priority. Otherwise, please close the ticket.

**Comment by wrnu** [comment]
No longer relevant
