### ISSUE TITLE
Collaborate with Audra on Contract FOIPPA amendment

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1271]
**Describe the issue**
FOIPPA changed.  What effect on contracts in flight?  Existing contract?

**Additional context**
- an amended version came back with a lot of strikethroughs, especially around FOIPPA

**Definition of done**
- Assist Audra with ticket 1260
- Provide research to Audra about changes and impact
- Provide comments into the Word document of the Service Order, which will then be closed out for each CSP's legal as an input.
- After the red line change highlighted by Audra, check if she needs anything else or else close it.

**Comment by sid-gov** [comment]
Title: Responding to GCP Service Order.
