### ISSUE TITLE
GCP SEA Terraform Modules

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1272]
**Describe the issue**
The GoC GCP SEA code doesn't perfectly meet our needs. Customized modules are required.

**Additional context**
- We need the following terraform modules
  - Folders
  - Projects
  - Core Audit (Org log sink)
  - Core Policy
  - Network Host Project

**Definition of done**
- Terraform modules are created and tested in "SEA Dev"

**Comment by sid-gov** [comment]
PO & SM have reviewed this ticket and because it's a long holiday sprint, an estimate of 8 is approved so the work can be managed for the next 6 weeks for creative time.
