### ISSUE TITLE
GCP SEA Dev Terragrunt for Core Platform

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1275]
**Describe the issue**
We want to deploy and test GCP SEA Dev environment using infrastructure as code. The GoC terragrunt structure does not align perfectly with our goals. We need to develop a custom terragrunt structure.

**Additional context**
- Use Terraform modules from GoC when possible 
- otherwise use BC Gov specific module created in ticket #1272

**Definition of done**
- Terragrunt is written to and infrastructure is deployed for the following
  - Folder structure
  - Custom Org IAM Roles
  - Policy for the org, platform folder, dev folder, test folder, and prod folder
  - Platform projects
    - Audit (log archive)
    - Dev Network Host
    - Test Network Host
    - Prod Network Host

**Comment by sid-gov** [comment]
PO & SM have reviewed this ticket and because it's a long holiday sprint, an estimate of 8 is approved so the work can be managed for the next 6 weeks for creative time.

**Comment by ActionAnalytics** [comment]
Google sent us code instead.  No longer needed
