### ISSUE TITLE
Identify Production (AWS LZ2) workloads that may be affected by Firewall Upgrade

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1277]
**Describe the issue**
Changing the firewall in LZ2 from Fortigate to Check Point may cause downtime for workloads that use VPC networking. We want to identify Production (AWS LZ2) workloads that may be affected.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Document project license plates in MS Teams doc that are affected
- reach out to concerned parties beforehand

**Comment by MaxWardle** [comment]
Identified two ALBs that were deployed in prod workload accounts that may be in use. Spoke to the admin contacts from both of those teams and they assured me that they were not in use. We can move forward with the Checkpoint firewall work without concern about affecting production routing.
