### ISSUE TITLE
Include team member IDIRs and roles in the Onboarding forms 

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1281]
**Describe the issue**
When we ask the new teams for information, it should also include the list of people (with IDIRs) that should be added to the new project set, and the permissions that they should have so that we dont need to follow up with them again. 

**Additional context**
- We have to consider that we are getting complaints about bloat in the onboarding forms, so perhaps strike some sort of balance
- Permission options are:
Admins
Billing Viewers
Developers
Security Auditors
Viewers

**Definition of done**
- Add the above info as questions in the onboarding forms
- This is more for knowing the roles on the team, the compliance people, tech leader role on the team

**Comment by ActionAnalytics** [comment]
This is a good idea and already in use on the platform registry.  We can definitely adopt this pattern

**Comment by ActionAnalytics** [comment]
We also already do this in the second onboarding event, the technical onboarding.  We don't share that info in a way that links back to the team though, so this ticket can still add some value in this area

**Comment by ActionAnalytics** [comment]
Decided to include the technical contact email instead as this accomplishes the same thing.  Done
