### ISSUE TITLE
SPIKE: research the potential creation of different personas based on clients' skills (Stage 1)

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1285]
**Describe the issue**
After discussing with Jon M for #945, we realized that the infrastructure delivery to our clients is based on their skill and what they want from Cloud. Therefore we need to test the hypothesis of redesigning the personas we currently have.  

**Additional context**
Stage 1: Planning the research and share it with PO
Stage 2: Book meetings with clients and team members to interview and deliver outcome to team

**Definition of done**
- Plan the research 
- Share plan and questions with PO
- Agree on approach and create a clients list
- Create additional tickets if required

**Comment by sid-gov** [comment]
Bahaa to categorize the developers with the users into the different categories based on their capabilities and what they are coming to do in the space (hypothesis is that teams want to develop an app, teams that they want to test the environment, and teams that are curious only)

**Comment by bharmouche** [comment]
we went through the interviews and some users mentioned of an existing personas from Microsoft which we will be looking at in the coming sprint.
