### ISSUE TITLE
Azure vNET Subnet creation to connect to on-prem resources - TRAN IoT

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1288]
**Describe the issue**
The TRAN IoT project needs connectivity to connect to a public IP front end (VIP F5). 

**Additional context**
- Coordination with TRAN to submit iStore VIP request. 

**Definition of done**
- Requirements gathering for subnet size
- Producing an appropriate size subnet
- Test VIP with TRAN IoT internal IP

**Comment by jon-mc-git** [comment]
Duplicate - closing
