### ISSUE TITLE
Azure vNET Subnet creation to connect to on-prem resources - TRAN EDW

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1289]
**Describe the issue**
The TRAN EDW project needs connectivity to zone B server resources.

**Additional context**
- Coordination with TRAN to submit firewall rules for zone B access from the intrernal Azure cloud IP. 

**Definition of done**
- Requirements gathering for subnet size
- Producing an appropriate size subnet
- Confirm the internal connectivity with TRAN

**Comment by jon-mc-git** [comment]
Duplicate - closing
