### ISSUE TITLE
Usability of the Cloud Security Schedule - buyers and vendors frequently require modification before using it in a contract.

### ISSUE THREAD

**Issue by fastaudra** [bcgov/cloud-pathfinder#1296]
**Describe the issue**
Vendors have challenges accepting some of the terms in the CSS.
The clauses are written to apply to the "contractor" but it is often not clear which obligations apply to each of the subcontractors in the stack and how. SaaS vendors are different than IaaS and PaaS vendors in terms of the obligations would apply.
Feedback has been provided to Information Security Branch (OCIO) who are the stewards of the CSS.

There is a file called CSS0updates-491-draft.docx

**Additional Info**
- Nick C has picked up a similar effort due to some rough experiences involving the CSS so there is motivation for change from our partner teams
- PHSA has two different security schedules (which we think makes sense) and we've passed that to Bonnie

**Definition of done**
- Coordinate with Nick C, Avneet, Bruce to make sure they understand why we are asking for changes, then take a team approach - if a particular party hasn't capacity, try to Pathfind without them and then agree to loop in later.
- Meet again with ISB to further develop/collaborate on instructional language to provide options and clarity to the end users (contract drafters).
- Recommendations are provided to Legal Services Branch, who are the "owners" of the CSS and have the authority to modify it.

**Comment by sid-gov** [comment]
This is problematic for vendors and the use of legal resources everytime they need to sign this contract. The buyer doesn't realize that a CSS document exists until the last stages of procurement which is very expensive to do.

**Comment by ActionAnalytics** [comment]
Bahaa: We are doing the workshop June 12, have other tickets for this now.  Let's close this ticket
