### ISSUE TITLE
Gov Azure foundation upgraded FW hub - Route testing

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1297]
**Describe the issue**
Work with SecOps to test various aspects of the routing to ensure they are seeing all traffic and identify any areas of necessary remediation

**Additional context**
- May not need routing updates but testing is necessary to ensure there is no Azure 'auto-routing' around the newly updated hub firewall set 
- Part of the SecOps post-fw update verification work

**Definition of done**
- Identify tests that would have to be run by SecOps to ensure the hub-spoke project workload network architecture and others on our end to verify those or test further
- Work with SecOps to have them run those tests\log reviews
- Work with Networks if SecOps lacks information from packet routing coming from on-prem
- Ensure direct routing to the Azure gateway occurs
- Share Azure diagram and compare to AWS diagram for interest and learning - team meeting to compare and discuss

**Comment by jon-mc-git** [comment]
Issue reviewed with SecOps concerning routing and their updated Checkpoint firewall.  There may be an issue with how routing is coming in from the gateway and the VPN BGP configuration.  Made request to Networks tier-3 group, however there was resistance to investigate.  Will attempt to explain the troubleshooting being done with them at next opportunity.  Have made the request and will move it forward however possible (may require raising the issues profile with that team at some point)

**Comment by jon-mc-git** [comment]
Issue has been roadblocked by NCCS -Tier 3 group availability to help us gather configuration information on the current BGP settings and troubleshoot, along with information on how VPN link disconnects are detected\treated.  Have asked David Ell to check in with Charles Middleton on this and try to get some of the Tier 3 team's time to go over this.  Assigning as blocked until this group's availability is resolved.

**Comment by jon-mc-git** [comment]
May bring this one in if I can secure a specialist route tester for other ticket to help with this and try to bypass blockage by OCIO Networking here

**Comment by wrnu** [comment]
confirmed by Jon, still relevant

**Comment by wrnu** [comment]
This will be needed once the equinix fabric is deployed

**Comment by jon-mc-git** [comment]
Now redundant due to parallel development process of the new LZ platform.  Closing ticket
