### ISSUE TITLE
Document and automate new patterns for developing on M1 Mac

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1300]
**Describe the issue**
The new Macs come with a new processor architecture called M1 which differs from the old Intel ones. It requires a new pattern to solve this for a variety of technologies like Teams or Terraform.

**Additional context**
- Shared cache plugin folder pattern for efficient folder space needed (tgclear alias that Warren shared - system-wide TF cache clear) but has nuances for multiple projects
- Turn on Rosetta
- two brews (a package manager like chocolatey, apt (deb), yum (rpm), pacman) enabled for each architecture

**Definition of done**
- Document the pattern in the readme.md file for the below repo
- Save to BC Gov GitHub https://github.com/bcgov/terraform-on-m1-mac
- add the apache 2 license we use on all our other repos
- Get reviewed from another team member for typos and clarity
- Share out via Rocket Chat #general

**Comment by wrnu** [comment]
No longer relevant
