### ISSUE TITLE
Move forward with Azure 

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1312]
**Describe the issue**
Given the rapidly changing landscape in the contract negotiation field we need clarity with what steps to do next with our partners. 

**Additional context**

**Definition of done**
- 3 3hr Meetings per week for the next 3 weeks with MSFT and other partners happen
- Next steps in Azure SO

**Comment by ActionAnalytics** [comment]
Blocked pending more info...
