### ISSUE TITLE
Communicate Azure Billing situation and upcoming changes

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1318]
**Describe the issue**
We have come up with a billing strategy for Azure.  Existing clients will want to know.

**Additional context**
- Jon provided additional feedback in email thread.  Will incorporate

**Definition of done**
- CPF communication to all Azure stakeholders - consult with Jon, Julian before sending
- ask who is your financial contact?
- Run past Justin before sending

**Comment by sid-gov** [comment]
ES CSAM is covering the bills for Azure until we transition everyone over the the new Azure environment (Azure SEA).

**Comment by ActionAnalytics** [comment]
Working on this with Jon
