### ISSUE TITLE
Add terraform-docs automation to terraform-octk-aws-sea-network-info  

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1321]
**Describe the issue**
Our terraform modules lack documentation and it is difficult to onboard new developers. To solve this we would like to use [terraform-docs](https://terraform-docs.io/) and github actions to automatically generate module definition docs.

**Additional context**
 - terraform-docs generates docs for module provider, input, and outputs from the terraform code.
 - this ticket is for https://github.com/BCDevOps/terraform-octk-aws-sea-network-info

**Definition of done**
- Module docs are generated using terraform-docs in a github action on push and committed to the repo
- A brief description of the module is written and added to the README

**Comment by osamudiamen-o** [comment]
Done!! https://github.com/BCDevOps/terraform-octk-aws-sea-network-info/blob/master/README.md
