### ISSUE TITLE
Completely resolve Teams access for CPF team members (esp contractors)

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1322]
**Describe the issue**
Something in Teams changed in the New Year.  Contractors cannot access chats (daily scrum), documents, or be pinged.  We also need to get on top of any changes coming to Teams because right now this keeps catching us by surprise where features stop working or streams of bugs come out.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Connect with the team behind Teams, find it there is are changelogs, release notes, or an early warning system of sorts of upcoming changes.
- Fix the CPF team members' access to teams so that everyone can access chats, documents, and show up in autocomplete.  This may require asking the Teams team to fix something, provide us a fix, or for us to fully switch daily usage over to IDIR only.  Or other.  TBD.

**Comment by sid-gov** [comment]
CPF team members have access to Teams now from their IDIRs.
