### ISSUE TITLE
Deprovision the Linux VM we were studying

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1343]
**Describe the issue**
We want to study the VM hardening measures to copy any best practices. That is our only purpose for using these expensive VMs. Once we are done extracting what we need, we will shut them down. 

**Additional context**
- We intend to keep the Windows for Jon's forward proxy ideas (easier to keep than to get another)

**Definition of done**
- Engage with the team that is managing the VMs for us and notify them that we no longer need. 
- Complete any istore request to formally shut down the environments

**Comment by ActionAnalytics** [comment]
Sean from DXE shared the security config settings and verbally updated me, so no need for this VM.  I will share with the team.

We no longer need these VMs, good to release them

**Comment by MaxWardle** [comment]
Got confirmation from Geoff J that the Linux VM "Pioneer" has been decommissioned!
