### ISSUE TITLE
Emergency Incident Response Plan version

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1356]
**Describe the issue**
We have a reviewed cloud incident response plan. This is for teams to get prepared before an incident happens. We want to have a plan that can be used after an incident happens so teams can quickly remediate the incident. 

**Additional context**
- Potential Attachments are added in the comments
- We need something consumable by users in a panic mode. 

**Definition of done**
- Response plan 1-2 pages giving instructions to teams on what should be done. 
- Information about the contact list and communication channels
- Consult with Bahaa as required to create a graphical/"cartoon version" of the plan, similar to the Fire exit diagrams attached below
- Review with PO

**Comment by AvneetKahlon** [comment]
This is what we want to create.![MicrosoftTeams-image (1).png](https://images.zenhubusercontent.com/6140d011b8118a5e7f9e6e6d/b66663a1-c533-4623-afc9-420453151f02)![MicrosoftTeams-image (2).png](https://images.zenhubusercontent.com/6140d011b8118a5e7f9e6e6d/4d026dd0-57cf-44f8-88a1-97f20cc980c9)[Uploading... MicrosoftTeams-image (3).png]

**Comment by AvneetKahlon** [comment]
![MicrosoftTeams-image (3).png](https://images.zenhubusercontent.com/6140d011b8118a5e7f9e6e6d/88bd6537-d1c3-49e4-9447-ce41440f9cf7)

**Comment by AvneetKahlon** [comment]
![MicrosoftTeams-image (2).png](https://images.zenhubusercontent.com/6140d011b8118a5e7f9e6e6d/678fe641-0482-4672-bc73-7f7c40a80678)
