### ISSUE TITLE
SPIKE: Investigate Equinix data and connection interchange 

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1358]
**Describe the issue**
We want to investigate currently available offerings in our data centers for direct connections to cloud services/SaaS providers. 

**Additional context**
- Hot wires from data center to data center (ExpressRoute, DirectConnect)
- Potential that Networks could own this, but we could pathfind this for them. 

**Definition of done**
- Meet with David Ell, PO, to make sure this doesn't interfere with efforts we may not know about
- Invite the PO for any meetings as above
- Evaluate current offerings and has anything changed
- Plan based on the above information, create tickets as necessary.

**Comment by wrnu** [comment]
covered by other tickets
