### ISSUE TITLE
Build Load testing spot in Azure

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1359]
**Describe the issue**
Jon and PO to lightweight onboard Brian to some space for load testing. 

**Additional context**
Could be need to extend this capability\service to other cloud platforms like AWS\GCP
 for alternate environment and\or cloud internal app perf testing
**Definition of done**
- Chat has been had that outlines the overall need for load testing service (OCIO internally at very least)
- Basic onboarding and automated IaC deploy of the load testing function
- Confirm deploy and functioning with Brian
- Demo of JMeter app perf test capability

**Comment by jon-mc-git** [comment]
Load testing was done on the SDN environment and will get demo\results of it soon, along with a demo on its operation

**Comment by jon-mc-git** [comment]
Method to generate tests through Azure's Load Testing service was run through and the JMeter script upload shown.  An additional full test demo was requested next time the SDN or other project required and and the documentation for the process was sent.  Closing ticket
