### ISSUE TITLE
SPIKE: Workflow ideas and solutions for an Approvals mechanism 

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1361]
**Describe the issue**
The idea is to provide an automated approach for new requests to be automatically processed. We currently get requests in RocketChat and we don't always know who the approver is. This will be useful for adding people, service accounts, connecting services together, enabling listeners for services, turning on support levels.

**Additional context**
- http://ec2-18-223-40-154.us-east-2.compute.amazonaws.com
- https://github.com/BCDevOps/devops-requests
- The solution implementation and technology is dependent on the outcomes of the CRM work that is happening in DPDD 
- Some of the potential CRM candidates are: DPDD Dan P Salesforce effort, Jira Service Desk Manager DPDD Team, OCIO ES Andy T ServiceNow, Platform Services GitOps, CPF Google AppSheet. 
- Timeframe for the Salesforce decision: end of fiscal

**Definition of done**
- Describe how the workflows would work
- Create a itemized list of as many workflows as you can think of.

**Comment by wrnu** [comment]
No longer relevant, covered by other tickets
