### ISSUE TITLE
Plan EPIC for how Cloud Services (individually) & CSP Platform Support could be handled at scale

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1362]
**Describe the issue**
A discussion needs to be had on how we could possibly decentralize access to each Cloud's ticket\support system (ie. to Ministry centralized support groups, etc?), and yet still maintain a centralized view into what is goes wrong on each platform and what state requests are in  - for prioritizing\identifying similar cases and building on learnings moving forward

**Additional context**
- Individual cloud service support should be fairly out of our hands as there are too many of these in each platform and more to come; however, we should have a method to maintain a view into this activity and coordinate similar\related issues where possible
- There is also cases where individual cloud service issues vs platform issues may not be easily identifiable or separable
- Cloud Platform-level support needs should be filtered to and maintained centrally for control and visibility on core issues with any of our Cloud Services platforms.  However, there are particular services within Azure that will have support issues\questions that arise (example: Video Analyzer, Cognitive, ML, etc.)

**Definition of done**
- Talk about possible ways to manage these two distinct support scenarios and what to do about the potential hybrid\difficult to identify situations
- Review the capabilities of each platform 
- See what main IT groups could take this on themselves and forward issues that may be platform level issue (act as our filters) and how we could leverage HelpDesk for some support with the rest
- Discuss possible ways to equip our front-line HelpDesk for problem classification\testing, info gathering and general Level 1 support if possible (perhaps med-long term?)
- Attempt to ascertain what weight of support would be required of us to handle Level 2 Cloud Support - Although our goal for scalability would be to handle only Level 3 (platform) issues it may be necessary to periodically handle Level 2 for the cumulation of smaller Ministries 
- Question: Could this be contracted out - To act as our filter? [ie. beyond normal HelpDesk support, but within Level 2 cloud specialized support]
- Additional tickets to be made on how this could proceed, depending on results of discussion

**Comment by ActionAnalytics** [comment]
Made an EPIC for this.  We can flesh out tickets when we do this ticket

**Comment by wrnu** [comment]
covered in other tickets
