### ISSUE TITLE
Deploy Azure workload landing zone with GoC code

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1367]
**Describe the issue**
We need a subscription vending machine for Azure SEAs. The GoC has a repo for managing workload landing zones. We want to know if this will work for our needs.

**Additional context**
- https://github.com/ssc-spc-ccoe-cei/template_workload-landingzones
- Under GoC terminology, a Landing Zone is similar to CPF term for a 'project-set'

**Definition of done**
- Workload landing zone is deployed to the Azure Dev SEA using the GoC code
- Document any concerns or issues that would prevent BC Gov from using this pattern.

**Comment by ActionAnalytics** [comment]
Will need a CIDR block just like we have in AWS so we don't have a collision later when the networks are eventually are connected.
