### ISSUE TITLE
AWS service order amendment

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1377]
**Describe the issue**
We wish to amend the AWS Service Order 

**Additional context**
- This relates to the cloud brokering service
- This is also about lowering spend, which is why the two tickets are linked

**Definition of done**
- Paperwork activities internally in OCIO and SSC portal
- AWS Service order is amended at SSC

**Comment by fastaudra** [comment]
SO placed 17 Feb 2022- confirmation https://gc-cloud-services.canada.ca/s/detail/5005o000005MQTmAAO
