### ISSUE TITLE
SPIKE: Find out what GoC is doing with Azure DevOps vs OSS

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1381]
**Describe the issue**
We need to figure out our messaging and patterns relating to Azure DevOps and GitHub usage as this is going to come up often.  If we don't get started on this, teams will make a mess.

**Additional context**
- GitHub has patterns and is mature
- Azure DevOps is undefined for patterns and could have a multiplicative effect quite quickly
- There is a BC Gov Azure devops organization - who manages this?
- can use GitHub as repo for code and Azure DevOps as pipelines

**Definition of done**
- Consider that we have 2 modes of usage that we are considering.
  - Core account or SEA deployment performed by CPF tech team (not in scope)
  - Workload usage by various Ministry client-tenant teams (in scope)
- Consider creating our own cloud azure devops org for clients to use
- Meeting to brainstorms and come up with preliminary patterns and decisions
- Julian, Jon, Warren

**Comment by wrnu** [comment]
No longer relevant
