### ISSUE TITLE
Add a Workaround for VPN Connection to Database to our Automation

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1383]
**Describe the issue**
The SEA has blocked users from connecting to databases directly, which is an issue for some teams who use this pattern to conduct their work. 

**Additional context**
After speaking with Ryan J from AWS we decided the best approach is for us to automate the creation of a VPN using an appropriate role with enough permissions so that it is unaffected by the SEA guardrails. The team in question will use this VPN to connect to their database.
- new guardrail prevents this
- we shouldn't be providing VPN any more

**Definition of done**
Landing zone automation is updated to create a VPN that will allow access to our teams databases.

**Comment by lukegonis** [comment]
This is no longer work that we should be pursuing, moving to closed
