### ISSUE TITLE
Legal review of Shared Services Procurement that needs to on the LAN

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1384]
**Describe the issue**
There is a Shared Services Procurement document that needs to have Legal services review before it is finalized and can go on the LAN.  Legal Services is reviewing the proc that GoC did, their output will be a document likely in the form of a Memo which will be added to the contract file.  The Memo is to advise on the Legal procurement risk of larger dollar value purchases from the cloud brokering service.

**Additional context**
- We expect that this is dependent on the availability and capacity of another team out of our control

**Definition of done**
- Legal review in order to raise the $75k threshold and document risks for audit compliance

**Comment by fastaudra** [comment]
Draft memo has been received and filed.
