### ISSUE TITLE
Migrate SSO to Gold Cluster

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1401]
**Describe the issue**
We are currently using SSO on an older system that is aiming to be decommissioned next year.  PO has met with SSO team and put our prod realm forward for migration to Gold to improve our reliability (SLA).

**Additional context**
- It's possible that realm license plate may change
- It's possible the base URL might change
- SSO Team board here https://app.mural.co/t/cgihumancentereddesign9508/m/cgihumancentereddesign9508/1643649054364/ae873e6319cbb99d446908417eb1c16170dd69dd?sender=ladamiaous0473

**Definition of done**
- We need to make sure our current role and group functionality is not removed
- Migrate from old to Gold cluster, hopefully without having to repoint everything to a new URL and realm

**Comment by mitovskaol** [comment]
closing as duplicate
