### ISSUE TITLE
Create CPF newbie User Persona for using to guide onboarding ticket work (not about tickets, about persona)

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1408]
**Describe the issue**
Onboarding is new team members to CPF (not Training Delivery for clients).

User Persona for CPF member joining the team. This will be internal info for helping us create resources for ourselves

**Additional context**
- This is assuming that the BC Gov admin staff have already accomplished the basics of IDIRs. equipment, VPN etc.  What does CPF have to do within our own team as next steps?
- The expectation is that there will lots of new onboarders as we grow the team

**Definition of done**
- Gather information from CPF team about Needs, Goals, Motivations (their sentiments, background prior to CPF, and onboarding experiences (this is more about understanding the people, less about creating todo list/tickets))
- Create a persona, which would actually be useful to be included in the onboarding material to help an onboarding person understand their own role.
- Do we actually have sub-personas or more than one (tech and non-tech)? - prefer one if possible, but we want to try to keep it generic (and maybe we can use it later to guide creation of tickets)

**Comment by bharmouche** [comment]
In the process we still have 2 interviewees and then will compile and create the profile/persona.
