### ISSUE TITLE
Create a Project Set Cleaning Tool

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1420]
**Describe the issue**
When we create lab accounts often times someone will use it for a week or less and it will never be touched again. We want to streamline the account cleanup process so that we can reuse lab accounts by creating a script and integrating it into our octk-cli toolkit

**Additional context**
- There are a couple of options and the method of choice will depend on [1419](https://app.zenhub.com/workspaces/cloud-pathfinder-5e4dbb426c3c6af8dcbf06a7/issues/bcgov/cloud-pathfinder/1419)
- If the nuke and rebuild method doesn't work we will have to explore the cloud cleaner (speak to warren), or another alternative
- Eventually we want this to be part of a later ticket that uses Cognito to KeyCloak which spins up a container (it's a tool, possibly running longer than 900s) that does the work in a predicable way.
- Has a blocking dependency on the CLI side

**Definition of done**
- a script is created to clean out a project set that is reusable by triggering a container for the task
- some history is stored in the metadata of the project set of what the state of the project set it (i.e. whether it is clean or dirty - already being done for the lab accounts)

**Comment by wrnu** [comment]
No longer relevant
