### ISSUE TITLE
SPIKE: Document the Approach to Implement Automatic Logout Before "Login to Console" in the AWS Login Application  

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1421]
**Describe the issue**
When you are currently logged into another AWS account and you click "login to console" to login another on the AWS login application it will take you to a page where you must "click here" to logout of your current session. You then have to navigate back to the login application and click "login to console" again. The number of clicks in this flow could be reduced from 3 to 1 if we implement some logic to automatically logout of your current session before every login attempt.

**Additional context**
- Scope: This will be added to the existing AWS login app only
- AWS SSO page already does this and we can get hints about how to get this done. Reach out to Warren about this. 
Add any other context, attachments or screenshots![Screen Shot 2022-02-10 at 2.52.56 PM.png](https://images.zenhubusercontent.com/600f0d1b7f6982f2c5a20033/c2446b9a-3ec7-4383-a95d-d448131f3c6b)![Screen Shot 2022-02-10 at 2.52.39 PM.png](https://images.zenhubusercontent.com/600f0d1b7f6982f2c5a20033/0471f17c-bf5b-49b1-9efa-c7ca06a6212d)!

**Definition of done**
- Meeting with Kevin and Max to discuss the approach
- Create ticket for this work documenting the approach

**Comment by abibat-adesina** [comment]
The implementation was carried out
