### ISSUE TITLE
Create summary/take away of onboarding next steps

### ISSUE THREAD

**Issue by AndreaBingham** [bcgov/cloud-pathfinder#1423]
**Describe the issue**
In the Feb. 9th onboarding training we received feedback that the volume of material presented was overwhelming. A summary/take away of onboarding next steps, shared at the end of the presentation, might help alleviate these concerns.  

**Additional context**
 - An example of what to include for privacy is, "complete your program PIA" and then include one of more links to help them get started (Pathfinders privacy contact, MPO list, link to PIA webpage)

**Definition of done**
- Meeting with PO, Bahaa to talk about how to handle the above concern and brainstorm a better process
- If above is good, consider adding this summary/next steps somewhere online as a standing resource and link to it at the end of the onboarding presentation.
- Add the summary as part of the Onboarding journey and point people to it during onboarding training.  Estimated to be a 1 pager just focused on the next steps

**Comment by wrnu** [comment]
This work will be tracked in other tickets
