### ISSUE TITLE
CPF Gameplan for Incident Event

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1425]
**Describe the issue**
Now that we have some early reusable material for Teams to have ready for incidents in cloud, Cloud Pathfinder needs to also have a gameplan for when we have an incident.

**Additional context**
- We already met with Megan and Clare Investigations Unit, Corporate Information and Records Management Office (CIRMO)

**Definition of done**
- DONE Meet with ISB, show what we have, get their contact info for us to use when we have an incident
- Create a 1 page internal guide or drawing for the Cloud Pathfinder team to follow when we have an incident
- - include which teams to notify
- - maybe have different versions depending on the nature of the incident
- Review with PO
- Show to ISB and CIRMO

**Comment by AvneetKahlon** [comment]
Gwen from ISB and Megan from CIRMO are on vacation.
