### ISSUE TITLE
Azure SaaS personas study

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#1430]
**Describe the issue**
While interviewing Azure users and discussion the actual personas that we have and the shared responsibility model, users mentioned that Azure has around 35 different personas for solution architects which are SaaS products that will be demanded in the future by users. For this reason it will be advisable to research and understand those personas and find the connection between personas, case studies and SaaS performance to build a document for users reference.

**Additional context**
- Bahaa thinks this is more research consumption, less about in-person interviews
- We need to meet with the SaaS team and figure out where BC Gov is going to draw the line between Paas, IaaS and SaaS tools (high-touch and low-touch). What is our own view on how each CSP differentiates it. 
- MSFT goes crazy with their personas because they don't believe in fullstack agile teams so we need to carve them down for Gov pov. 

**Definition of done**
- Check azure information and SaaS personas
- have a summary of a plan that includes card sorting 
- report to PO and Jon M

**Comment by ActionAnalytics** [comment]
Needs investigation, we'll wait a bit

**Comment by wrnu** [comment]
No longer relevant
