### ISSUE TITLE
Define scope for cloud pathfinder corporate Azure PIA

### ISSUE THREAD

**Issue by AndreaBingham** [bcgov/cloud-pathfinder#1431]
**Describe the issue**
 - We have an existing CITZ corporate PIA for Azure but it's not clear whether that will cover all of the services cloud pathfinders intend to use. 

**Additional context**

**Definition of done**
 - meet with Enterprise Services to confirm scope of existing PIA 
 - confirmation from Julian on whether services included in existing corporate PIA will cover services that cloud pathfinders plan to use

**Comment by wrnu** [comment]
not relevant
