### ISSUE TITLE
First draft of cloud pathfinder corporate PIA for Azure 

### ISSUE THREAD

**Issue by AndreaBingham** [bcgov/cloud-pathfinder#1432]
**Describe the issue**
 - Once scope is confirmed, cloud pathfinders will need a corporate PIA for Azure. It's possible that the existing corporate PIA is sufficient but that is TBD. 
 - Need to create a first draft of the corporate PIA

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
 - First draft of cloud pathfinders corporate PIA for Azure is complete

**Comment by mitovskaol** [comment]
Closing as we will not be pursuing Azure at this moment
