### ISSUE TITLE
Develop a CPF Incident Response process

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#1436]
**Describe the issue**
CPF team needs to be aware of how to act in an emergency and what steps to take and who to connect/inform. 

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Learn about their existing processes and check if we are compatible. 
- A version1.0 one page process for handling incidents
- A flowchart diagram to be used in an incident (examples could be: do we hear about incident from 77000 or do we hear from the team?)
- a single meeting with 77000 team, ISB, PCT Investigations for feedback
- QA is done and that means grammar, spelling, accessibility, colour themes and others checks are complete

**Comment by wrnu** [comment]
still a good priority

**Comment by wrnu** [comment]
@jon-mc-git Can you confirm this has been done? I think it has

**Comment by lukegonis** [comment]
We will rely on the existing corporate Incident Response process until further notice
