### ISSUE TITLE
Secure practice for sending passwords and other sensitive materials

### ISSUE THREAD

**Issue by AvneetKahlon** [bcgov/cloud-pathfinder#1437]
**Describe the issue**
CPF team needs to use secure method (encryption) of sending sensitive credentials via email or teams messages.

**Additional context**
- Use Magic-wormhole

**Definition of done**
- Interact with PO to get context
- Meet Warren or Max, learn best practices.
- Create a 1 page training guide (that we later hand out to teams during training as a means to help them distribute secrets)
- Connect with Austin H and share the practice with SecOps
- Work with Carles to create a little network sniffer test to show Austin
- Record the test to reuse it in the next community update

**Comment by wrnu** [comment]
no longer relevant
