### ISSUE TITLE
Process to check AWS spend vs procurement limits as part of cost recovery process

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1439]
**Describe the issue**
We need to make sure our total AWS spend remains under our procurement limits. During the cost recovery process we can look at the total cost and ensure this is the case.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Documented process for the cost recovery team to follow in order to determine the total cost
- Document spending limits that generate alerts (warning, threshold reached, etc)
  - Who is notified?

**Comment by mitovskaol** [comment]
We currently review the total AWS spend monthly as part of the financial reconciliation process and compare with the remaining funds on our accounts with SSC. So we already have a process in place for this.
