### ISSUE TITLE
Cloud Platform - SEA deployment QA testing framework discussion

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1440]
**Describe the issue**
For team to have a discussion on how we move forward with an ability to QA both our SEA Core and workload LZ deployments more easily, and report yellow\red flag issues using automation

**Additional context**
To move forward operationally we should create a framework whereby we build in certain testing modules that can more independently test whether a SEA Core update is functioning properly or an LZ workload gets properly hooked up to core security, networking and possibly extend into policy testing later on 

**Definition of done**
- Help Carles with learning debt around SEA deployments for better 
- Discussion on what could outline an initial QA design (a phase I - most critical components\functioning tests)
- Discussion on easiest way to maintain QA robust-ness, as modifications to SEA Core and workload LZ's occur
- How\when to deliver a first set of QA capability that would test the most core functionality\structures of our SEA environment (core routing, LZ-to-hub routing, firewall traffic blocking, for example)
- Testing sourced internally through deployed modules vs External testing by way of a service
- An Ops Cloud Dashboard concept, whereby we add new targets and it automatically deploys the external testing & possible internal test modules
- What might a 'next wave' of testing capability look like (ie. anything that might be more complex, more time consuming?)
- Discuss core\workload update automation possibilities (making it as easy to operate as possible), and automated way to back out of certain types of updates\changes 
- Other tickets will be produced as discussion progresses and initiatives begin

**Comment by crochcunill** [comment]
Please check the following items as they include work that can be useful for the discussion

- [#1445](https://github.com/bcgov/cloud-pathfinder/issues/1445) (1st spike): Includes lots of links and the first draft of the test plan. When this (#1440) discussion happens, let's use the latest test plan draft located in https://bcgov.sharepoint.com/:f:/t/01368-CPFScrumTeam/Eko5_wyXYLRJikoeHz8G3P0BfnALvghIvezUgepLe5kZDw?e=T80IW7
- [#1456](https://github.com/bcgov/cloud-pathfinder/issues/1456), [#1478](https://github.com/bcgov/cloud-pathfinder/issues/1478), [#1479](https://github.com/bcgov/cloud-pathfinder/issues/1479) (automated test for user end point -GUI-)
- [#1459](https://github.com/bcgov/cloud-pathfinder/issues/1459) (Integrate automated test in CI/CD pipeline with github actions)

**Comment by wrnu** [comment]
Will be covered by other tickets
