### ISSUE TITLE
Aquire a lab project-set, deploy an Accelerator app

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1442]
**Describe the issue**
We wish to train our new team member Carles in the patterns used by the Cloud Pathfinder customers and users as part of a general orientation around the AWS Secure Environment Accelerator platform that Carles will be providing initial test coverage over the SEA platform patch/upgrade process.  It would be useful for Carles to ride along with a few team sessions while they are receiving project-sets and technical onboarding.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Reach out to Max and ask for one of the existing or a new lab project-set to be assigned to Carles in AWS SEA Prod/LZ2 with the billing group being the CPF one Julian has. 
- Fork the https://github.com/bcgov/startup-sample-project-aws-serverless into your person github org so you have a copy ready to go for the onboarding. 
- Let the tech team know in standup to pull you in to the next technical onboarding session.
- Attend the onboarding session and try to follow without slowing down the pace of the session - if more time is needed, no problem, attend more than one session (there will be several this sprint)
- Successfully deploy the hello world app to your lab project-set
- Make a change to the header (insert the word "Carles"), run the CI/CD and demo to the team in the sprint review ceremony.  Prabhu or Ukeme can assist if there are any sticking points to doing this.

**Comment by crochcunill** [comment]
There is a second project that can also be installed in the laptop for the same training purpose. It it:
https://github.com/bcgov/startup-sample-project-aws-containers

**Comment by crochcunill** [comment]
Changed title and added more greetings
![image.png](https://images.zenhubusercontent.com/620eba1ac6937a4e70b34b15/bdebca31-2fd2-4fc4-958d-87015b43c493)
