### ISSUE TITLE
Update the QA repo in GitHub with the BrowserStack logo and get the free licenses

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1446]
**Describe the issue**
BrowserStack will provide 5 free licenses to any Open Source GitHub project that displays their logo in their ReadMe.md file.  One needs to do this first, then ask BrowserStack for the free license.

**Additional context**
- See example https://github.com/bcgov/mds (see bottom of this page)

**Definition of done**
- Copy the code from the MDS readme and apply to the https://github.com/BCDevOps/aws-sea-autotest repo

**Comment by crochcunill** [comment]
This respository contains a library of GitHub Actions to help  integrate test suites with the BrowserStack device cloud.
https://github.com/browserstack/github-actions

**Comment by crochcunill** [comment]
- Successfully enrolled  the https://github.com/BCDevOps/aws-sea-autotes site to BrowserStack free program

![image.png](https://images.zenhubusercontent.com/620eba1ac6937a4e70b34b15/f4e3c8d5-e1e3-4886-8d13-fa3b09e2c5fc)

- Modified ReadMe file to incorporate the logo 
https://github.com/BCDevOps/aws-sea-autotest/blob/main/README.md
