### ISSUE TITLE
Go over non AWS cloud tenants, invite to 3 CoPs

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1448]
**Describe the issue**
Give them biscuits!  We want to connect with them to engage and incentivize to win-win behaviours, via educational sessions & material (give them nice things - hence biscuits).  This is about the existing clients that we need to backfill.  For new clients, we are training them with the existing sessions along with AWS.

**Additional context**
- Backlog is large now (Jon votes to start sending links & discussions)
- Valuable to do this before the SEA is ready in GCP and Azure
- Aim for a practice of sending material in advance of the CoP and give them the floor to talk
- Use the CoP to focus questions from the materials shared earlier
- We feel this approach will allow teams to plan their fiscal roadmap with a lot of time.  Play on the emotions of setting them up for success.
- Expect ~60 clients-ish

**Definition of done**
- Work with Jon and Julian to create a priority list of people to pull in from GCP and Azure environments
- Focus first on transparency around the Shared Responsibility Model
- Start identifying who to invite to the regular onboarding sessions (maybe invite a few per session so as not to overwhelm ourselves)

**Comment by wrnu** [comment]
no longer relevant
