### ISSUE TITLE
Tech Onboarding GDX Analytics to AWS Prod

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1451]
**Describe the issue**
Search in the onboarding app for "gdx analytics" for the details

**Additional context**
- Deciding which app to use will be key

**Definition of done**
- Create the project-set and perform the onboarding training
- Schedule a meeting with their tech contact Mark W (see the app entry)
- The team says they want VMs, this one might be a first instance which could affect if we have a dedicated meeting only for this onboarding or if you batch them with the APS team (current though is better to separate but team decision)

**Comment by crochcunill** [comment]
Not sure who will be assigned to this task (Max?). but please include me. I would like to shadow you in the process to create the project set to be able to document the steps (with the goal of automating them if possible)
