### ISSUE TITLE
Onboard Mining Priority Projects

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1458]
**Describe the issue**
There is an entry in the CRM app under "Mining Priority Projects" that provides the details of this team.

**Additional context**
- The team has been made aware of the shared responsibility model and the additional responsibility on the team to self-solve and be tolerant of service counter delays due to the early state of Azure currently.  The team has agreed to these terms.

**Definition of done**
- Create the usual subscription spaces for a team in Azure
- Reach out and arrange time with Mano to provision his access

**Comment by jon-mc-git** [comment]
Connected with client and have updated email to address lack of ability to contact Mano.  Next meeting will be Technical review which has been set up for next week

**Comment by jon-mc-git** [comment]
Spoke with Fredo and Mano on this project and found out that they were just needing some technical onboarding to do with Azure DevOps, along with some best practices on its use, how to get it going and generate first projects, and how to set up their project and permissions properly with the individual teams.   Also advised that their use of this Power Platform\Dynamics365 low-code solution does not preclude them from having to generate the instances\settings configuration scripts for app instance DR considerations, as well as to ensure that data is preserved properly through backup capabilities within the platform and\or copies kept locally for possible re-hydration of the app instance if that became necessary.  Closing ticket.
