### ISSUE TITLE
Make an HTML Template for Billing Report Email Body 

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1461]
**Describe the issue**
Currently the billing reports are sent via email and the body is formatted via a jinja2 plain text template. It would be nice to have html formatting on the email body. 

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- make an html template for the email body in [the billing report repos template folder](https://github.com/BCDevOps/terraform-octk-aws-sea-billing-reports/tree/master/billing-report-utility/templates) 
  - should match existing email layout from email_body.jinja2 but with enhanced formatting
  - should match email layout guidelines from the Digital Office (get email template from Kaitlyn)

**Comment by abibat-adesina** [comment]
https://github.com/BCDevOps/terraform-octk-aws-sea-billing-reports/pull/17

**Comment by lukegonis** [comment]
The scope of this issue has increased, so this issue will carry over
