### ISSUE TITLE
Tech Onboarding for Nurses team to AWS SEA Prod

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1462]
**Describe the issue**
Search the CRM app for "Nurses" for detailed info

**Additional context**
- Use Pam S's Health billing account
- No technical onboarding needed; it's Will

**Definition of done**
- use the PO's email from the CRM as the billing contact for Wednesday billing notifications if possible, otherwise, ok to use Pam's
- Typical project-set and onboarding session
- Pull in Carles so he rides along

**Comment by MaxWardle** [comment]
Blocked as the automation is having issues right now.
