### ISSUE TITLE
Route 53 Compliance Review

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1463]
**Describe the issue**
We want to do a security review for Route 53 on AWS. Route 53 is AWS' domain name and routing service.

**Additional context**
- This one is tricky because it handles DNS which is pretty core to government.
- There is likely reusable Security and Privacy compliance already done on this available from Mark from the GDX Analytics team (see CRM app for details)

**Definition of done**
- Get prior compliance work from Mark 
- Route53 Compliance work is complete

**Comment by wrnu** [comment]
no longer relevant
