### ISSUE TITLE
Hitting Certificate limit on LZ2 ALB

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1464]
**Describe the bug**
When we try to create a new project set with a DNS layer in LZ2 it throws the error:
```
│ Error: error adding LB Listener Certificate: TooManyCertificates: The maximum number of certificates has been reached
│   status code: 400, request id: 9ee84dc9-6f5c-4ae4-a6ca-f92bd13d509d
│ 
│   with module.account_route["bi6s1c-dev"].aws_lb_listener_certificate.cert,
│   on modules/account-routing/main.tf line 76, in resource "aws_lb_listener_certificate" "cert":
│   76: resource "aws_lb_listener_certificate" "cert" {
│ 
╵
```

**Additional context**
- we may have to create a new ALB
- for short term we could remove unused routing on accounts with DNS layers
- the team has solutions

**Definition of done**
- resolve this issue so that we can create new accounts in LZ2 with a DNS layer

**Comment by ActionAnalytics** [comment]
Warren will discuss with Ryan to verify Warren's solution
