### ISSUE TITLE
Get Hands-on SecOps SIEM dashboard

### ISSUE THREAD

**Issue by AvneetKahlon** [bcgov/cloud-pathfinder#1465]
**Describe the issue**
Now that we have access to Splunk dashboard, explore it and utilize it to examine logs.

**Additional context**
- Bruce and Nick are working on similar activities, there may be opportunities for collaboration

**Definition of done**
- watch videos to understand how search can be conducted, dashboard can be created, etc.
- if required take help from team members.

**Comment by ActionAnalytics** [comment]
Unfortunately, the SecOps SIEM is not really usable as a log management service.  It is only a long term storage place with little visibily
