### ISSUE TITLE
Cost Reduction with AWS in the core accounts of all 3 SEAs

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1469]
**Describe the issue**
Audra has discovered a path to 1 year prepayment cost reduction opportunities in AWS and we would like to leverage them to increase our efficiency.  Ryan has some ideas on how to save money in the core.

**Additional context**
- PO has sample cost structure table to share
- See approach Tim O took to see benefits and savings

**Definition of done**
- Chat on RC with Ryan J about cost reduction suggestions
- Focus on Core Workloads to begin, especially virtual machines like the firewall appliances (disregard the Fortinet VMs as we intend to shut off after 1 successful SEA upgrade with the CheckPoints in place to ensure the CheckPoints survive SEA patching)

**Comment by MaxWardle** [comment]
Can probably spin down the Windows machines running Smart Console when we're not using them, and possibly the firewall manager

**Comment by prabhukiran9999** [comment]
- Reserved instances bought to achieve cost-saving(2 c5.large and an m5.large)
