### ISSUE TITLE
Add a Download as PDF Option for the Static website displaying our Study Material

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#1473]
**Describe the issue**
We have a Vuepress website that is hosted on [GitHub Pages](https://bcgov.github.io/cloud-pathfinder/) and we want to have a download as PDF Option for people who wants to download it to their local machine

**Additional context**
- Speak with Ukeme to get some context on the Vuepress Plugins available

**Definition of done**
- We have a working Download as PDF option

**Comment by ActionAnalytics** [comment]
Question about the PDF generation; does the PDF get generated on markdown update, or on user button-press?  I'm guessing the former
