### ISSUE TITLE
Deploy startup-sample-project-aws-virtual-machines apps

### ISSUE THREAD

**Issue by crochcunill** [bcgov/cloud-pathfinder#1480]
**Describe**
Similar to task #1442, this task is to deploy:
- startup-sample-project-aws-virtual-machines

The goal is to lean how to install these apps and then use them in the process of verifying the SEA upgrade/updates.

**Definition of done**
- install the apps
- Document the process
- Identify the tokens required to build the app in AWS
- Identify the url that allows access to the app

**Comment by ActionAnalytics** [comment]
Let's leave this out for now and focus on the containers app for now for the tests.  Once we have a pattern that is stable there, it should be easy to crack open the app.

**Comment by crochcunill** [comment]
Change in the title is due to sample containers app already installed, deployed and documented

**Comment by crochcunill** [comment]
Virtual machines sample apps is not going to happen, so this ticket makes no sense
