### ISSUE TITLE
SOAR/STRA for TFC

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1484]
**Describe the issue**
Terraform Cloud is an integral part of BC Gov's Public Cloud offering.  Now that we are sure that we have scalable pattern and wish to continue with it, we should investing the the compliance work.

**Additional context**
- Uh oh, we don't have a privacy person to do the PIA at the moment.  

**Definition of done**
- DONE Sanity check that there isn't a STRA/SOAR for Hashicorp Terraform Cloud TFC anywhere already
- DONE Reach out to PO for info on how it's being used if that helps
- Create very limited draft TFC review
- - All the document sections in place using a prior STRA/SOAR as an example
- - Skeletal structure of document done
- - Clearly show in highlighted TODO sections what is remaining to do

**Comment by bruce-wh-li** [comment]
WIP version STRA can be found in Team File Folder (Security)

**Comment by bruce-wh-li** [comment]
Close this ticket and create a new ticket as Skeleton of STRA is ready.
