### ISSUE TITLE
Work with Dana to get create/access to 3 more mailing lists

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1485]
**Describe the issue**
We would like to be regular with out Community of Practice (CoP) meetings for Expense Auths (Prod Owners, Proj Mgrs), Compliance (Security, Privacy, SecOps), Developers (Ministry Team members)

**Additional context**
- Dependent on Dana access which she doesn't yet have.  This is assuming she gets it within the next sprint.

**Definition of done**
- Dana learns how to do this (learning debt we need tackle)
- 3 mailing lists are set up
- PO has ownership, plus Dana have access (plus future Scrum Master later in a later ticket)
- PO doesn't know how to manage distribution lists and will require some training from Dana

**Comment by SmallDana** [comment]
3 Distribution List requests have been submitted and confirmation numbers have been received.

**Comment by ActionAnalytics** [comment]
Looks like the Distribution Lists are not visible on a Mac Outlook as the Global Address Book is missing.  Dana is helping by engaging with Tyler and seeing if it's possible to get a Windows machine
