### ISSUE TITLE
SPIKE: Privacy accelerator document bundle

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1487]
**Describe the issue**
Do we want to include documents like https://www.oipc.bc.ca/guidance-documents/3646#:~:text=Reasonable%20security%20measures%20to%20protect%20personal%20information%20Section,such%20as%20unauthorized%20collection%2C%20use%2C%20disclosure%20or%20disposal. in a toolkit for teams coming to cloud?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Review/coord with PCT about their take on above doc (a meeting, 30 min?)
- Propose other ideas for docs in a potential starter package (couple hours of thought)
- Create any tickets for following work

**Comment by wrnu** [comment]
no longer relevant
