### ISSUE TITLE
Change Billing Group to 5char license plate

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1488]
**Describe the issue**
All the meta data for each team is present in the CRM app now.  There is also now a billing group field in the CRM.  

**Additional context**
- The current license plates for project-sets are 6 chars which is a 2 trillion address space
- There will be a lot less billing groups than project-sets
- 5 chars provides a billing group address space of 60 million
- 6 chars vs 5 chars will stand out to platform admins, who will be able to tell the difference
- the motivation is to provide a generic ID, then we save conversations on the bill when people see their billing group (or requests to change the billing group name because they don't like the name)

**Definition of done**
- Identify any blockers that might break existing billing (or if we do this on or near the Fiscal Year cutoff)
- Convert all existing billing groups to 5 char license plates on end of fiscal
- Update the CRM app with both old billing group tags and new ones in the same Billing Group field.

**Comment by MaxWardle** [comment]
Removed dependancy to prioritize other work, and because we want to track this billing group name change as well, so no work is lost.
