### ISSUE TITLE
Get another block of IPs from Networks for ROSA

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1489]
**Describe the issue**
In AWS SEA Test we have a ROSA cluster with some randomly chosen IP blocks.

**Additional context**
- Not needed yet until we set up ROSA in Prod

**Definition of done**
- Connect with WAM(?) and ask for another block of IPs like we initially did with SEA Prod

**Comment by ActionAnalytics** [comment]
There's a meeting Julian is attending Monday for this, we will know more

**Comment by ActionAnalytics** [comment]
We've asked them in Rocket Chat #devops-rosa-operations

**Comment by ActionAnalytics** [comment]
Warren: We're not ready for this, too much in flux about the design.  The upgrade isn't going well and we need to sort this out.

**Comment by ActionAnalytics** [comment]
Waiting until we firm up our networking and until ROSA is ready to go to prod.  Changes to ROSA network possibly coming from Ryan J

**Comment by wrnu** [comment]
still relevant

**Comment by wrnu** [comment]
not relevant
