### ISSUE TITLE
QA the new Pre-Reading material 

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1504]
**Describe the issue**
We want the onboarding cloud journey to point to a dynamic set of pre-reading material content

**Additional context**
- https://developer.gov.bc.ca/Cloud-Pathfinder-Onboarding-Journey/Evaluation
- It's already live on cloud-pathfinder org

**Definition of done**
- QA for content flow and English etc by Dana (proof-read)
- QA for last details from PO after above QA

**Comment by SmallDana** [comment]
Working on the feedback today, will be sending @prabhukiran9999 initial edits by end of day 4/28 to make sure I'm on the right track with what he's looking for.

**Comment by ActionAnalytics** [comment]
Blocked due to availability

**Comment by ActionAnalytics** [comment]
Already shipped!
