### ISSUE TITLE
Pre-reading material can be understandable on it's own

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1505]
**Describe the issue**
Currently there are some heavy graphic slides that require a human to explain them.  We would like there to be accompanying text that removes the requirement for someone to explain.

**Additional context**
- Shared responsibility model, procurement value proposition, SEA as a service

**Definition of done**
- Do the changes on the fly live best draft effort
- Run it past Carles to see if it makes sense on its own
- PO quick QA

**Comment by wrnu** [comment]
Content has been migrated and re-written on the new website

**Comment by wrnu** [comment]
Content has been migrated and re-written on the new website
