### ISSUE TITLE
Coordinate Cloud FAQ into new cloud.gov... site

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1507]
**Describe the issue**
There is an existing Cloud FAQ somewhere.  Jon has pointed out there are a lot of new questions.  We have an opportunity to gain better edit access through the new cloud site.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Find out where the existing FAQ landed
- Coordinate with Olena for integrating or recreating over on the new site.

**Comment by wrnu** [comment]
New website is about to be deployed and the most popular question from rocketchat have been posted in stackoverflow
