### ISSUE TITLE
SPIKE: Reducing Long Wait Times Caused by TFC Queues

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1508]
**Describe the issue**
Users are sometimes having to wait 15 minutes for a TFC runner when there are runs ahead of them in the queue. As we grow and more teams come onto the platform this might become an issue. This ticket is to explore ways to reduce this wait time.

**Additional context**
![Screen Shot 2022-03-16 at 12.10.29 PM.png](https://images.zenhubusercontent.com/600f0d1b7f6982f2c5a20033/8faccbe1-4eb1-4e51-bbb2-3653afa71622)

- host our own runners?
- other technology?

**Definition of done**
- spend some time researching alternative solutions
- is there a setting we can pay more money for that increases the speed?

**Comment by ActionAnalytics** [comment]
Nothing we can do without more queue runners
