### ISSUE TITLE
Move Confluence data over for team oboarding

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1513]
**Describe the issue**
Julian has a lot of onboarding material in an old NRM confluence page (at risk of going away any day).  We can use this for our onboarding.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Julian to copy over our onboarding material to Teams

**Comment by wrnu** [comment]
Onboarding content has been updated and significantly rewritten
