### ISSUE TITLE
Review of GCP Acceptable Use Policy

### ISSUE THREAD

**Issue by fastaudra** [bcgov/cloud-pathfinder#1517]
**Describe the issue**
Legal requested the business area review of the CSP's Acceptable Use Policy from an operational and policy perspective.

**Additional context**
https://cloud.google.com/terms/aup

**Definition of done**
-read through terms
-identify any issues or risks, if applicable
-discuss issues/risk with Product Owner
-report back to Legal

**Comment by fastaudra** [comment]
no issues or risks

**Comment by ActionAnalytics** [comment]
we're already operating under the same rules per our gov rules
