### ISSUE TITLE
Review of GCP Service Level Agreements

### ISSUE THREAD

**Issue by fastaudra** [bcgov/cloud-pathfinder#1519]
**Describe the issue**
Legal requested a review of the Service Level Agreement(s) from an operational and policy perspective.

**Additional context**
https://cloud.google.com/terms/sla/

**Definition of done**
-obtain list of Cloud Platform Services that would be of interest to the Public Cloud Accelerator Service from Product Owner  (Hint: the list is in Teams under 'CPF Scrum Team > 007 - Research & Documentation > GCP Research')
-Review SLAs
-identify issues and risks and raise to PO
-respond to Legal

**Comment by fastaudra** [comment]
noted items for training: customer has to request credit using online form. max credit is 50% for the service that has a missed SL. credit to be claimed within 30 days. Customer must provide logs with outage information.

**Comment by ActionAnalytics** [comment]
If google misses a service, per the docs, we the client need to A) notice, and B) reach out to them to recoup credit for next month's bill.
