### ISSUE TITLE
Messaging to MCIOs on new orders for Azure

### ISSUE THREAD

**Issue by fastaudra** [bcgov/cloud-pathfinder#1523]
**Describe the issue**
Need a contract under which to order new Azure services. Province is in a holding pattern with MSFT on Service Order in the Cloud Brokering Service. The Public Cloud Accelerator Service is not able to meet customer requests for Azure until there is a mechanism in place for providing the space.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- draft letter to Ministry Chief Information Officers up to eApprovals
- coordinate with executive for timing

**Comment by ActionAnalytics** [comment]
Drafted, all reviewed, with Gen pending final exec +1

**Comment by ActionAnalytics** [comment]
@fastaudra I think this was accomplished?  Ok to close?
