### ISSUE TITLE
Create our own hardened AMI

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1532]
**Describe the issue**
We wish to create an Amazon Machine Image to the same standards as BC Gov's or better

**Additional context**
- We will need to consider the installation of the remote logging and monitoring software that BC Gov uses (possibly ncase agent) but hooking it up is out of scope for this ticket
- We have new specifications shared with us from the datacentre contractors in BC Gov

**Definition of done**
- Combine Prabhu's prior VM research and BC Gov's best practices into a living, scripted AMI
- Configuration stored in a bcgov-c repo

**Comment by wrnu** [comment]
since this service has not been request by any teams we will put this on pause until there is demand
