### ISSUE TITLE
Share GitHub patterns with Jon

### ISSUE THREAD

**Issue by crochcunill** [bcgov/cloud-pathfinder#1537]
**Description**
Similar to #1476, Carles to share his simple cheatsheet and approach to GitHub 

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Reach out and give Jon a heads-up, choose a time that works for her
2 or 3 screenshares (~5 h total) with Jon to help her practice and get up to speed in GitHub for her Cloud Custodian work.
Please store a copy of this material in 004 onboarding guides
Quick review with PO

**Comment by ActionAnalytics** [comment]
Trouble with Jon's schedule

**Comment by crochcunill** [comment]
Meetings Friday 22, morning and afternoon
Send notes/cheat sheet by email
