### ISSUE TITLE
Adding recovery information to Emergency response plan

### ISSUE THREAD

**Issue by AvneetKahlon** [bcgov/cloud-pathfinder#1540]
**Describe the issue**
We have Emergency response plan build till incident investigation. We want to add the next step on how to recover the  system and re-enable the services.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Add more information after investigation step because we didn't have a lot there yet
- The new step will be called "Recovering after an Incident" or something similar.
- The step will contain clear, concise and generic information on recovering after the incident took place.
- Review with PO

**Comment by wrnu** [comment]
No longer relevant, covered by other work
