### ISSUE TITLE
Azure space for AG - Use of Forms Recognizer service

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1541]
**Describe the issue**
There's what appears to be a lightweight use case for Justice: See CRM detailed notes, search for "Traffic Courts Online".

**Additional context**
- There are a lot of assumptions we're making and possible tech complications.
- The scope of this ticket is either that it IS as simple as described and we get it done OR that if there are any tech complications, then this is the first conversation of many and we take this at a pace that works for Jon's capacity.  We saw this potential happen with TRAN so possible here.

**Definition of done**
- Put on architect hat and see if what's described in the CRM notes makes sense, and if so
- Reach out to Ryan L and Chris M (contact info in the CRM notes), and
- Provision them some Azure space for this, otherwise
- Loop back to the PO and if it's not possible, we'll reach out to them and explain why.

**Comment by jon-mc-git** [comment]
In 'Traffic Courts Online' CRM link you'll note that it was recommended that they consider learning more about the on-prem integration being suggested and what it actually does locally (and what it just sends to the linked Azure OCR service).  Was also suggested to first move the service in a Phase 1 from their current NTT provider tenancy to our Gov tenancy and then in phase 2 focus on how they would link the on-prem OCR server(s) and what caveats are involved (ie. what can actually be done by this local server - as their current understanding of this may not be in sync with actual capability and\or the fact that on-prem versions of services normally have a capability gap or 'version stagger' that could change the way they architect the final service

**Comment by ActionAnalytics** [comment]
So AG is off thinking and reconsidering
