### ISSUE TITLE
GitHub 101 Training to the new CPF members joining the team (and client teams that need it)

### ISSUE THREAD

**Issue by unoah** [bcgov/cloud-pathfinder#1542]
**Describe the issue**
The goal is to have a repo that is like an interactive git course for CPF new team members or client teams that lack github capabilities.  
A GitHub 101 course for new members of the team. Potential areas to cover include:
  - Common Git workflows used by the team
  - Introduction to GitHub actions
  - Introduction to using PRs

**Additional context**
- The CPF team use multiple repos across a few GitHub organizations. The git workflow one follows when making updates depends on the repo being worked however, git feature branch and forking workflows appear to be relevant more often.
- For the forking workflow, we can have a simple repository with minimal code that can be used during the session. This should provide a more graceful ramp on GitHub workflows for newer folks.
- This would feed into a training meeting where they would fork the repo and follow the above steps

**Definition of done**
- Review and incorporate Carles' (step by step) and Julian's (draw the environments exercise) GitHub training
- Playground repo with minimal components. If including CSP resources, we keep it light
- - a hello world (something minimal without deploying to cloud) limited to GitHub Pull Request + GitHub actions
- High level markdown guide on using PRs with some practice steps
- High level markdown guide on using GitHub actions with some practice steps

**Comment by wrnu** [comment]
no longer relevant
