### ISSUE TITLE
Webhook to create ticket in GitHub/ZenHub

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1552]
**Describe the issue**
Somewhere in the onboarding process the incoming team fills out a form and data is captured about the team.  A webhook would trigger and generate an issue in the CPF repo.  

**Additional context**
- we have a bit of a balancing act around the private contents of the CRM vs the public aspect of the CPF repo issues

**Definition of done**
- When a team is preparing for onboarding and they input their info
- In the CRM we can have an approval step
- - a button that the PO or whoever could click to "approve" and create a ticket
- Fields in the ticket
- - name of the team
- - a way to find the entry in the CRM (without a direct link or leaking private info)

**Comment by wrnu** [comment]
no longer relevant because we will be using the registry
