### ISSUE TITLE
Create Tools and Lab OUs

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1553]
**Describe the issue**
We are currently using Sandboxes that have too much permissions and are leading community confusion.  We will swap them out for Tools which will have the same permissions as Dev, Test and Prod

![image.png](https://images.zenhubusercontent.com/5e98c26e92d4be32d8e29cb0/209358ed-5b46-492c-9ed6-35dd2bed92b0)

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Coordinate with on-prem, get more CIDR ranges like in the ROSA ticket
- Configure and define the networking up front using the CIDR ranges
- Create via automation as high in the stack as possible (AWS SEA config if possible) a Tools OU with the same permissions as the others.
- Make it applicable across LZ0, LZ1 and LZ2 (not hand bombed)
- - meet with Ryan J to figure out how

**Comment by wrnu** [comment]
- AWS ECF Dev:
  - Tools and Lab OU created
  - Tested project-set creation with tools account

**Comment by ActionAnalytics** [comment]
Waiting for Prod IP Range confirmation because we can't undo easily

**Comment by ActionAnalytics** [comment]
Holding off on deploying until official confirmation from iStore ticket

**Comment by ActionAnalytics** [comment]
We are blocked until we run the ASEA upgrades
