### ISSUE TITLE
Update automation to use Tools for new project-sets instead of Sandbox

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1554]
**Describe the issue**
We have a more secure and cleaner model to apply to new onboardees.

**Additional context**
![image.png](https://images.zenhubusercontent.com/5e98c26e92d4be32d8e29cb0/1e97b8a5-66a6-480a-87a0-2b1fc235f2d0)

**Definition of done**
- Change the vending machine automation so that when a project set gets created, it assigns Tools accounts from the Tools OU instead of Sandbox ones.

**Comment by mitovskaol** [comment]
Not relevant anymore
