### ISSUE TITLE
Prepare for and communicate for swapping out old Sanboxen for new Toolboxen

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1555]
**Describe the issue**
This will break a lot of teams' automation so we will need to stage this into at least two steps, first being to provide the new space, second to take it away.

**Additional context**
- requires a list of teams to contact
- can still use tools in the same way as sandbox was to host for example the ECR
- we would give the ministry teams several months to do it

**Definition of done**
- Communicate to each team that those new spaces exist, the purpose of the Tools account space and to please transfer their Sandbox assets to their Tools space within three weeks (and to let us know if they absolutely can't do this - we're open to hearing about exceptions)
- Write tickets to close the SandBox account

**Comment by MaxWardle** [comment]
Moved back to prioritized backlog as it was blocked for multiple sprints and doesn't align with sprint goals.
