### ISSUE TITLE
Run the automated test in BrowserStack from the CI/CD pipeline

### ISSUE THREAD

**Issue by crochcunill** [bcgov/cloud-pathfinder#1559]
**Describe the issue** 
Learn how run the automation test suite (#1456) for containers app in BrowseStack on the CI/CD pipeline in GitHub, so after building the application the test suite will run automatically.

**Additional context** 
BrowserStack provide a couple advantages over the geb/spock reports. 
- It saves a video of the test itself
- allows testing in many different platforms (OS/Browser/Appliance)

Currently I am accessing BrowserStack using my own account. Need to create a 'team' account to use

**Definition of done**
- Test run on the GitHub CI/CD pipeline and the results are available through BrowserStack
- Clean up and PR the code
- Improve the readme file (separate testing readme)

**Comment by ActionAnalytics** [comment]
Done (congrats!)

**Comment by crochcunill** [comment]
PR #78 https://github.com/bcgov/startup-sample-project-aws-containers/pull/78
