### ISSUE TITLE
Hook up CloudGuard CSPM minimally same as LZ0 demo

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1562]
**Describe the issue**
CloudGuard exists in a Canadian data center now, and we have a starter license for it.

**Additional context**
- Cloud Security Posture Management will be hooked up primarily via AWS SEA Prod.
- This single CSPM instance will cover eventually AWS SEA Dev, Test, Prod, GCP SEA Dev, Test Prod and Azure SEA Dev, Test, Prod

**Definition of done**
- Make sure any hooks in the environments are protected from team deletion (use of "PBMM-" prefix? New prefix?)
- Demonstrate that all workload environments are accounted for in CSPM
- move the hackathon TF module from the LZ0 repo in gov-c to the new repo BCDevOps/terraform-octk-aws-cspm
- initially hook-up AWS SEA Prod
- include the cloudguard role in the BC Gov guardrailed so that the teams can't delete it.  
- - we would like to prefix it "bcgov" if possible, otherwise
- - we will have to research if CSPM will require a specific name

**Comment by wrnu** [comment]
CSPM not available in Canada until June
