### ISSUE TITLE
Connect CSPM CloudGuard to SSO (admins)

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1563]
**Describe the issue**
We want keycloak to front CSPM so that we don't have to manage users in Cloud Security Posture Management.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Use the existing prod realm and create a new client (make sure the same MFA rules apply as per the login app)
- Be able to log in via the same IDPs as the login app (Only IDIR now, so direct AAD should be sufficient)
- Determine if authorization takes place through Azure AD app registration assignment, or in CSPM.

**Comment by wrnu** [comment]
CSPM not available in Canada until June

**Comment by ActionAnalytics** [comment]
Looks like we're right on schedule.  Have an initial setup meeting May 27, should be starting our journey at that point

**Comment by wrnu** [comment]
In order to setup SSO we need to verify ownership of @gov.bc.ca. We won't be able to do this. Setting up a meeting with CHeck Point to discuss options

**Comment by wrnu** [comment]
I discussed the issue above with Check Point today and they are going to take it to one of their SSO experts and get back to us.

**Comment by ActionAnalytics** [comment]
There are more than one BC Gov team, which may make this impossible

**Comment by NickCorcoran** [comment]
Discovered there is an Enterprise App registration for Azure AD, and ability to make connection within CSPM tooling.  To submit support ticket to ADMS for Azure AD enterprise app registration.

Once complete, to setup connection from CloudGuard CSPM and test.

**Comment by NickCorcoran** [comment]
App registration is now in place.  Next to configure on CSPM side.

**Comment by NickCorcoran** [comment]
App registration is now in place.  Next to configure on CSPM side.

**Comment by NickCorcoran** [comment]
Configuration complete.  sign-in requires use of a new URL, which is fine.  Authorization takes place within CSPM (or infinity portal).  More investigation into group constrained access to take place during CSPM refresh training next week.

**Comment by NickCorcoran** [comment]
Configuration complete.  sign-in requires use of a new URL, which is fine.  Authorization takes place within CSPM (or infinity portal).  More investigation into group constrained access to take place during CSPM refresh training next week.
