### ISSUE TITLE
Transfer of responsibilities for Public Cloud Brokering Services with Shared Services Canada to Sr. Director

### ISSUE THREAD

**Issue by fastaudra** [bcgov/cloud-pathfinder#1566]
**Describe the issue**
Justin Hewitt needs to be added as a Business Representative for the Province on the Shared Services Cloud Brokering Service.
Siddharth Bhaskara also needs to be removed as a contact for billing (replacement pending) to be replaced by Dana
Julian Subda needs to be added as a fallback for if/when Justin is away (Julian already has this - nothing to do here)

**Additional context**
There is a form that needs to be filled out and submitted to SSC.

**Definition of done**
- Form is filled out
- Form is signed internally by GCIO through eApprovals.
- Form is sent to SSC

**Comment by ActionAnalytics** [comment]
Justin is very busy, backup plan is to work through Gen

**Comment by ActionAnalytics** [comment]
This is problematic because our Sr. Director just left and we don't have anyone in this role
