### ISSUE TITLE
Draft web content on new cloud site main page

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1567]
**Describe the issue**
There is a new Wordpress site being set up, coming with branding and operational support from another team GDX. We would like to collaborate with the other teams to have a consistent landing page that has the same tone and plain language for the 3 main stream of services (Private Cloud, Public Cloud and SaaS). 

**Additional context**
- There is some sort of main landing page with links to 3 sub-websites.  The scope of this ticket is on the main page.

**Definition of done**
- Connect with the service designers and set the Tone and voice
- Draft a copy for the public cloud
- - Mostly focus on branding, look & feel and go light on written content
- Share with PO for approval
- Share with Justin

**Comment by bharmouche** [comment]
the landing page has been worked on and awaiting the document regulation collect by Martha and her team
