### ISSUE TITLE
Double check if we can pattern out false positives in TFC Queue channel

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1570]
**Describe the issue**
Warren thinks there may be false positives happening in the TFC Queue channel.  Max may have cleared them already but we're not 100% sure.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Identify false positives
- Update our filters to better screen out false positives if they exist

**Comment by unoah** [comment]
The alerts we're receiving are due to jobs submitted with `-auto-apply` set to false. I'll work with Warren to check if our current subscription supports setting the `-auto-apply` flag to true for all workspaces as he has an account on the orgs Terraform Cloud account.

**Comment by unoah** [comment]
Current subscription does not support setting `-auto-apply` policy after Terraform plan successfully run. We'd need to move to a different tier in order to have this capability.
