### ISSUE TITLE
Protect SEA created resources from deletion (eg AWS-nuke)

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1572]
**Describe the issue**
When running AWS-nuke, the SEA is supposed to have protections in place so that it's own components cannot be altered or deleted by ministry teams.

**Additional context**
- Congrats to Prabhu K for finding these security gaps and coming up with a way to close them
- The fixes we would make are at the automation we do to assign things to users, the SEA CDK is different and out of scope

**Definition of done**
- Talk to Ryan J about informing upstream letting them know that this is possible
- Create a pattern that works across all our AWS SEAs
- Talk to Prabhu about his notes on the subject, make public via the PRs and apply immediately to each SEA
- If Ryan is comfortable with it being a public issue, create an issue on the SEA GitHub

**Comment by prabhukiran9999** [comment]
- Most of the resources getting deleted are created by our terraform overlay except for the km keys created by the SEA
- we protected them with the new BCGOV Permission boundary 
- Raised an issue in the public SEA repo about the KMS keys
