### ISSUE TITLE
Export the logs from the Test Runner VM in GitHub over to Browser Stack

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1577]
**Describe the issue**
What Julian is hoping is that the nice UI in BrowserStack can serve as a one-stop-shop dashboard for presenting all the information needed (other than the GitHub code of course) to debug a failed (or successful) test run.

**Additional context**
- Not sure if it's possible
- We want to avoid emailing to gov accounts to avoid straining the gov email system
- We want to cut email out of the pattern completely (or only use for failed notification but click link to see logs in BrowserStack)

**Definition of done**
- Have the logs from the GitHub action test runner be stored and be readable in BrowserStack
- Ensure that the connection to transfer the files is encrypted the entire way

**Comment by crochcunill** [comment]
Does not seem to be possible to bulk export the GitHub logs to BrowserStack.

I have found the following article
https://www.browserstack.com/docs/automate/selenium/annotations#introduction
that indicates how to add annotation (log messages) to the Selenium logs. 

So, what seems straighforward is to add logs in the test code that will then show up in BrowserStack. These are messages generated by the code, and in this case the test code

**Comment by crochcunill** [comment]
It is not possible to send GitHub runner logs to BrowserStack

It is possible to send to BS customized log messages (see withAnnotation.groovy script stored in the sample containers app)

Another approach will be to encrypt the zip results folders that is sent to the user. See #1650

**Comment by crochcunill** [comment]
It is not possible to send GitHub runner logs to BrowserStack

It is possible to send to BS customized log messages (see withAnnotation.groovy script stored in the sample containers app)

Another approach will be to encrypt the zip results folders that is sent to the user. See #1650

**Comment by crochcunill** [comment]
Currently, the entries in BrowserStack look like
![image.png](https://images.zenhubusercontent.com/620eba1ac6937a4e70b34b15/02f4ed8d-67c0-4534-8629-a023d5608264)

Not sure if it will be available to any user, but the for a test that I have run using the withAnnotations.groovy script can be found at

https://automate.browserstack.com/dashboard/v2/builds/e7253300bb3df91f87b4893299152e0ee75a5686/sessions/eb69a0f209c2656d4164a9202b1719aaada79fdf
