### ISSUE TITLE
Security review of AWS services (EMR Serverless, Redshift, Kinesis, EC2 ) identified through GDX-Analytics CAPS

### ISSUE THREAD

**Issue by AvneetKahlon** [bcgov/cloud-pathfinder#1579]
**Describe the issue**
We identified some AWS services like EMR (Elastic Map Reduce) Serverless, Redshift, Kinesis, EC2 used by GDX-Analytics's Core Analytics  Pipeline Service (CAPS). 
We are looking forward to carrying out compliance work for these services and marking them as reviewed in the list of services available for our teams.
SoAR(PDF + word format) and PIA (PDF format) are shared by GDX-Analytics teams.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- review the use of the services
- coordinate with privacy review
- review with PO and like AWS Polly, make some tile updates

**Comment by bruce-wh-li** [comment]
GDX CAPS PIA Documents Copied to Privacy Folder for Gary H.

**Comment by wrnu** [comment]
not relevant
