### ISSUE TITLE
Cross skill the team (create cross knowledge documentation/primers)

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1580]
**Describe the issue**
The tech team finds the non-tech "boring" and likely vice versa.  It will be valuable to our users for all of our team members to understand the full nature of the work we do, including compliance/procurement etc because as our communities expand everyone will need to know enough to connect people to help them get answers, rather than just saying "I don't know".

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Create a few primers or cue cards for support issues that might not be tech related per se.

**Comment by wrnu** [comment]
not relevant
