### ISSUE TITLE
Add config mechanism to AWS ECS demo app

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1581]
**Describe the issue**
Ryan recently gave us another version of the containers startup sample app (aka demo app, aka accelerator app) that comes with Drupal installed on the ECS cluster.  This is really valuable in the short term to a team that wants to get going with Drupal.  It does create a code management quandary for the CPF team because updating the core ECS patterns will create a lot of work to keep parallel repos in synch.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Implement a clean and modern config option for teams deploying the solution
  - must work locally and in cloud
- The scope of the current work is to set up the config option defaulting to "hello world" demo startup app as in https://github.com/bcgov/startup-sample-project-aws-containers

**Comment by wrnu** [comment]
not relevant
