### ISSUE TITLE
Add Drupal as a setup config option in containers demo startup app

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1582]
**Describe the issue**
Currently https://github.com/bcgov/startup-sample-project-aws-containers installs hello world and https://github.com/bcgov/startup-sample-project-aws-drupal-containers installs Drupal.  Due to the similarities in the codebases, for maintenance effectiveness we want to collapse these into one code stream with config options to choose from like "hello app", "Drupal" and more.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Add a local and remote deployment option for Drupal to https://github.com/bcgov/startup-sample-project-aws-containers
- Add the Drupal functionality to https://github.com/bcgov/startup-sample-project-aws-containers from https://github.com/bcgov/startup-sample-project-aws-drupal-containers
- Get rid of https://github.com/bcgov/startup-sample-project-aws-drupal-containers

**Comment by wrnu** [comment]
not relevant
