### ISSUE TITLE
Add WordPress as an option to the containers demo startup app

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1583]
**Describe the issue**
Currently installs hello world and a ticket exists to add an install option for Drupal.  Due to the similarities in CMS functionality, we wish to add WordPress as another option along with Drupal.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Add a local and remote deployment option for WordPress to https://github.com/bcgov/startup-sample-project-aws-containers
- Add the WordPress functionality to https://github.com/bcgov/startup-sample-project-aws-containers copying the pattern used for Drupal

**Comment by wrnu** [comment]
not relevant

**Comment by wrnu** [comment]
not relevant
