### ISSUE TITLE
QA the new GitHub training

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1587]
**Describe the issue**
There is new GitHub training available for the team, freshly minted.  We would like to test it.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Have Jon, Dana, Bahaa be the first trainees to try the new GitHub training, and QA for typos, inconsistencies
- Ukeme and Carles to train and coordinate

**Comment by wrnu** [comment]
not relevant
