### ISSUE TITLE
Create a geofencing exception for BrowserStack and GitHub

### ISSUE THREAD

**Issue by crochcunill** [bcgov/cloud-pathfinder#1593]
**Description of the issue**
Unable to  execute a test using BrowserStack or GitHub servers

**Background**
BrowserStack promises to be a useful tool to enhance the testing of the Enterprise Cloud Factory and the applications build on top of it. However, it is a cloud infrastructure, and it seems the servers are distributed around the world. Because ECF is geofenced, we can not use BrowserStack to test most of the apps.

Contact Carles for full information about this issue

**Definition of done**
To create an exception that allows BrowserStack servers to load the apps hosted in the Enterprise Cloud Factory even if the requests are coming from outside Canada

**Comment by crochcunill** [comment]
Sent Julian these messages by Teams

> Hi Julian. Just created #1593 to record the geofencing problem with BrowserStack. While writing it I was a bit surprised that it worked all the time for the containers app but not for the serverless. I have test a bit more and when I use, for the container app, the Domain name https://d38zvtqpo438f4.cloudfront.net then it does not work, but when I use https://startup-sample-project.td5cou-dev.nimbus.cloud.gov.bc.ca then works.
> 
> The only option for the serverless app is the Domain Name, and it returns the above error.
> 
> This suggest to me that geofencing is working as expected for the Domain Names but not for the Origins. If the ECF users publish the Cloudfront Domain Names as the public url then all is fine, but if they were to publish the Origins, then there will be no geofencing.

**Comment by lukegonis** [comment]
No longer relevant
