### ISSUE TITLE
[BUG]: Serverless App: Sort the previous greetings 

### ISSUE THREAD

**Issue by crochcunill** [bcgov/cloud-pathfinder#1594]
**Description of the problem**
Currently, the serverless app does not sort the Previous Greeting Selection by date time

![image.png](https://images.zenhubusercontent.com/620eba1ac6937a4e70b34b15/28488830-b230-408a-934c-1aa7ced7466b)

What is even worse, is that I may submit a greeting, and the greeting is not displayed in the Previous Greeting Selections list. I assume this case is because the app only display ten rows, and if the latest greeting is not fetched, then it doesn't even show up in the list.

**Definition of done**
The list is sorted by DateTime showing the latest selected greeting first (same behaviour as the containers app)

**Comment by lukegonis** [comment]
Not high priority, but still worth the effort

**Comment by wrnu** [comment]
https://github.com/bcgov/startup-sample-project-aws-serverless-OIDC/pull/13
