### ISSUE TITLE
Add Pipeline to the Drupal Sample Application

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1599]
**Describe the issue**
Currently we have a [Drupal sample application](https://github.com/bcgov/startup-sample-project-aws-drupal-containers) that builds upon the [container based sample application](https://github.com/bcgov/startup-sample-project-aws-containers) but does not provide a working example of a CI/CD pipeline. 

**Additional context**
- This is important because the pipeline gives an example of how to interact with our Terraform Cloud and provides a recommended pattern for teams to use.

**Definition of done**
- Implement a CI/CD pipeline similar to those in the other sample applications.
  - Builds
  - Runs terraform on TFC
  - Deploys to Dev (Test/ Prod?)
- Pipeline is done to the same level of capabilities as the other demo app pipelines

**Comment by wrnu** [comment]
not relevant
