### ISSUE TITLE
Reimplement the GoC bucket guardrail test with CSPM configuration rule

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1609]
**Describe the issue**
There was a large set of artisenal autotests from the Government of Canada over at https://github.com/canada-ca/cloud-guardrails-aws that were evaluated and discarded in favour initially of CloudCustodian bcgov/cloud-custodian-policies, but then eventually settled on CloudGuard CSPM (Cloud Security Posture Management).

**Additional context**
- There exists an SEA guardrail that should prevent the creation of any public writeable buckets.
- Use the existing CSPM until the real CSPM is up in Canada by June
- We are ignoring CloudCustodian with the hope that CSPM is easier to use and more powerful in that it tells us if something is misconfigured or insecure in our current cloud posture.

**Definition of done**
- Factor in a lot of learning debt into this ticket
- Do this in ECF AWS Prod
- Create and define a CSPM rule with Bruce to ensure across all our Workload Environments that we don't have any public writeable buckets.
- Create an auto-test similar to https://github.com/canada-ca/cloud-guardrails-aws/blob/master/tools/prowler/checks/check_extragc61 using our AWS CLI that tries to create a bucket in one of our AWS guardrailled Workload Environments
-- after the test, check if CSPM can detect if anything is there
- Create an auto-test in the CLI same as above that tries to create a bucket in one of our AWS SandBox Workload Environments that are without guardrails
-- after the test, check if CSPM can detect if anything is there

**Comment by ActionAnalytics** [comment]
Poke around CloudGuard CSPM and see if you can detect a misconfigured account that has an S3 bucket publicly writeable - now this could be hard to test because the guardrails won't let you open a bucket like that but you can still write the test and we can simulate it later.  However, there may be an account still "misconfigured" on purpose from our hackathon.

**Comment by ActionAnalytics** [comment]
Poke around CloudGuard CSPM and see if you can detect a misconfigured account that has an S3 bucket publicly writeable - now this could be hard to test because the guardrails won't let you open a bucket like that but you can still write the test and we can simulate it later.  However, there may be an account still "misconfigured" on purpose from our hackathon.

**Comment by crochcunill** [comment]
[Yesterday 4:49 p.m.] Subda, Julian CITZ:EX

overly permissive security groups



[Yesterday 4:50 p.m.] Subda, Julian CITZ:EX

Trying to set up operational ruleset to find overly permissive security groups for visibility and compliance evaluation with an eye on remediation. Port 22 hunter.

**Comment by crochcunill** [comment]
Created a suite a of rules (https://secure.dome9.com/v2/compliance-engine/policy/682703) to find possible security problems
