### ISSUE TITLE
SPIKE: Research for test that the State Machine in the AWS ECF has run after a patch

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1610]
**Describe the issue**
The State Machine runs across all accounts in AWS SEA when either installing fresh or applying a patch.  Sometimes the State Machine fails and due to the enormous amount of logging output, we don't detect the failure due to the amount of logs.  So effectively it is a silent failure which is probably a bug in the SEA itself.  Or it fails and tells us, but we don't know what to do about it.

**Additional context**
- The State Machine is a set of ordered step functions, which is a massively distributed set of software
- We are not sure if this is possible, but perhaps it involves integration with the AWS CLI and API so that we can latch into the step function output.
- The SEA configures 1000s of items per account
- Julian has seen a screen from Ryan J that showed roughly 8 steps.

**Definition of done**
- Take a video of the patch running so that the team has a record of what the step functions look like.
- Meet with Ryan J and have him show us where the step functions live
- Plan a test equivalent to something that would look at one account before and after a patch and compare the logs or snapshot of the step functions to determine if they had failed.
- Timeboxed to a 5
- Create the actual tickets for the test

**Comment by OmoAttah** [comment]
Supplanted by ticket #2205
