### ISSUE TITLE
Create a CSPM or CloudCustodian test to detect long-lived jump host

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1611]
**Describe the issue**
Using System Manager to connect into it, developers can access their live DBs, which we know they are going to do.

**Additional context**
- we have documentation that says don't use VMs, jump boxes
- is there a bastion service?  no, this has no internet facing side
- if a team leaves it too long, they could lose context of what it is - then everyone is afraid to delete a live resource
- In AWS one possible way to detect a jump host could be if an ec2 instance has an instance profile role that includes SSM permissions which is used to allow connecting to the instance.

**Definition of done**
- Consult with AWS and CheckPoint on implementation details
- A video showing a scan of our Live ECF and showing that there are no exposed bashing host
- We need updated documentation to our onboarding security deck
- Detect if a team has deployed a jump box and left it up over 24 hours

**Comment by wrnu** [comment]
not relevant
