### ISSUE TITLE
SecOps-Exchange log offload in Azure - Review for possible onboarding

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1612]
**Describe the issue**
A proposed project by the SecOps and NCCS Exchange team as a solution to the problem of required 13 month log retention.  Exchange online keeps logs for approximately 30 days and SecOps' Azure Sentinel SIEM service can keep them for up to 90 days, which may either leave around 8 or 9 months of retention that needs to be addressed 

**Additional context**
- Per Dale L in a recent meeting with Julian S, he expressed that 13 months retention for cloud logs minimum
- Further details will be had at initial project meeting 
- Will discuss the tech involved, caveats and possible options

**Definition of done**
- PO would like to ride along in these meetings
- Surmise options after initial email-based review of situation and send feedback to the SecOps+NCCS teams
- Have a meeting to discuss this and any particular caveats around what could be done to accomodate this extended log retention
- Discuss with SecOps if there will be other projects that would need this type of offload from Sential or other services, and if creating a SecOps log repo with various storage tiers organized within and possible automation\auto-tiering the data the primary (hot or cool - allowing for quick ref to this data without IO extra cost, for a period of time), then the secondary (cool) and possibly an Archive layer
- Review any automation services MS may suggest as easiest for these tasks or have them inquire if not yet available 
- Post-analysis Technical Review meeting to be held seperately and discuss any remaining questions\decisions
- Depending on option chosen, the either config of Sentinel for extended storage or the IaC deploy of the RG and storage needed

**Comment by jon-mc-git** [comment]
Initial meeting held with Exchange & SecOps folks involved.  Lots of different discussion on the matter from each teams's perspective.  It was agreed that each group should go back and decide what they would prefer in this case (as per their vision or upcoming needs).  Once this is decided\discussed we can focus on the options that will enable these needs.  A follow up meeting will be held to discuss as follow up

**Comment by jon-mc-git** [comment]
Next scheduled meeting with the groups involved in this (SecOps, NCCS-Exchange, Public Cloud Platform Services [Pathfinder]) was pushed.  SecOps and Exchange were to evaluate not only current but future needs, so as to design a solution that is future focused as well as taking care of the current Exchange logging requirement.  Will continue to discuss this in next meeting to make decisions and move this forward

**Comment by jon-mc-git** [comment]
Second multi-branch meeting held and conclusion was that there are questions remaining.  Current default log retention is 90 days in Sentinel, and with premium enabled it adds 90 days extra no charge.  After this, Sentinel incurs storage charges so a plan needs to be put into place on how that will be handled.  As of now it was recommended to keep data on Sentinel temporarily until an offload solution is tested, final decision made based on that, and offloaded for all data past at least 180 days (6 months).  This covers the Exchange Group's requirement minimum of 90 days (having data online for investigations and troubleshooting), and provides extra time for SecOps and at least 6 months of possible security related patterns to be discovered.  Beyond this will depend largely on cost and the ability to still be able to query data after it has been offloaded from Sentinel

**Comment by jon-mc-git** [comment]
SecOps will work with the Exchange team now directly to see what is possible and what could work for both their needs when data is outside of Sentinel (offloaded).  The Sentinel offload process and post-offload data set analysis capability still has to be investigated.  SecOps will test as part of this next-phase how the Sentinel offload process works exactly, whether it can offload to a Azure Analytics (directly or indirectly), and what method will best work for querying and\or reporting off of this data (using their existing log parsing\search tools and\or Azure Analytics capabilities)

**Comment by jon-mc-git** [comment]
SecOps to work directly with NCCS Exchange group.  Waiting for decision\response still.  Putting on hold for now and assigning as blocked until further response from them on what they decide they need

**Comment by ActionAnalytics** [comment]
We've updated the CRM and linked back to this ticket.  We expect it will be a while before we see new requests; when we do, we will make new tickets and link them to this one.
