### ISSUE TITLE
Digital BC broken links

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1616]
**Describe the bug**
This page https://digital.gov.bc.ca/digital-framework is trying to link to https://www2.gov.bc.ca/gov/content/governments/services-for-government/bc-bid-resources/support-services/procurement-transformation but the original page is gone.

**Additional context**
- Procurement changed their website

**Definition of done**
- Find correct "Procurement strategy" link
- Contact team that maintains digital-framework
- Get it fixed
- Follow up with Paul O (ask Julian)

**Comment by fastaudra** [comment]
The contacts for this were Strategic Procurement and Steve Chapman. Both have been contacted. Strategic Procurement confirmed the correct link and it was provided to Steve to fix.

**Comment by ActionAnalytics** [comment]
Not doing.  No time

**Comment by fastaudra** [comment]
This is now fixed!
