### ISSUE TITLE
Acquire certificates for Contractors to lessen MFA workload

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1622]
**Describe the issue**
Contractors have to MFA multiple times a day for each Microsoft applications.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- See if it's possible to set up the certificates the same way the BC Gov staff FTEs have on their machines, or
- Escalate the time-to-live to 8 hours which is more reasonable (ask for policy adjustments)

**Comment by wrnu** [comment]
not relevant
