### ISSUE TITLE
Email Quarantine Issues

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#1625]
**Describe the issue**
- We want to be able to send Automated emails from external sources like app script for example under the gov.bc.ca domain.

**Additional context**
- Automated emails generated with gov.bc.ca domain gets quarantined as part of a security and authentication policy and needs to be manually released by people from istore 
- In order to keep them from being quarantined we need to submit a request to update DNS records 
- Julian has sent the email with instructions
- If we submit an iStore it may go to Adv Sltns while just calling up helpdesk could be faster because they deal with email issues all the time and will know the right ticket type to make
- PROTIP: word it like an incident rather than a big problem so that it gets immediate attention

**Definition of done**
- Call the helpdesk, we've been dealing with this, I'm the branch rep, and need a ticket created so that can proceed vs, get the iStore Consulting order screening questionnaire to request updating the DNS records 
- Coordinate with with Dana for help with the iStore ticket
- istore order made to Messaging team with Attached screening questionnaire

**Comment by ActionAnalytics** [comment]
We have a different ticket for this
