### ISSUE TITLE
Ride along a Ministry Team AWS Provisioning Session

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1626]
**Describe the issue**
We could be providing a new team some AWS space.  If we do, we can use this opportunity to train Bruce at the same time with the startup containers app.  Search the CRM for "Business Communications Solutions" 

**Additional context**
- If "Business Communications Solutions" does not come to AWS, we will use the next client that is provisioned

**Definition of done**
- Carles has a how to guide in Teams, please start there before the live session
- Max to provide a lab account for temporary use for Bruce with Admin role before the live session
- Bruce attends the 2 hour Provisioning session
- Maybe a bit of extra time with Carles, Ukeme or Prabhu to help get set up with the demo app

**Comment by bruce-wh-li** [comment]
Successfully spun up a sampler serverless app to register and upload photo to cloud storage.  Cloud Resource destroyed manually after test.

**Comment by bruce-wh-li** [comment]
Attended FW: ITSTRAT - Health IT Strategy AWS SEA Technical Onboarding Session
