### ISSUE TITLE
SPIKE: Investigate CloudGuard CSPM Network Security as a service

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1631]
**Describe the issue**
Figure out why this is valuable as Jon identified this as potentially useful in a multi-cloud scenario like ours

**Additional context**
- One of the capabilities is multi-platform IP-sec VPN detection / control
- Policies to detect or control in one or various environments
- Centralizes IPS
- Threat extraction or evaluation over to SecOps SIEM dashboards or our dashboards
- "automation so we don't have to talk to anybody"

**Definition of done**
- A clear writeup in MS Word store in teams that explains why this is valuable
- Presentation to the team during the internal demo
- Create some well-formed tickets if worth proceeding
- Cap effort to a 2

**Comment by ActionAnalytics** [comment]
CSPM turns on in June (expected)

**Comment by wrnu** [comment]
not relevant
