### ISSUE TITLE
Create additional AWS Security role to have no permissions to see keys or data

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1634]
**Describe the issue**
Not sure if this is possible, but we've had conflict between app teams and ministry compliance staff about access to app project-sets using the security viewer role because the role is too permissive in that it can see keystore contents and database/bucket contents.

**Additional context**
- There is a difference between viewer and reader so this may already be solved - we need to look into what's there.

**Definition of done**
- Connect with Ryan J and describe the situation
- Alter either the Security role or the Viewer role to limit their view permissions to not be able to see keys and data, or create a new custom role to provide ministries the option
- Let PO know and he will assign a team in which to test this setup
- Present to team in internal demo

**Comment by wrnu** [comment]
@NickCorcoran Do you think this is still a good priority?
