### ISSUE TITLE
IP range for AWS Tools, Labs

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1642]
**Describe the issue**
We need a Tools and Labs IP ranges so we don't collide with on-prem

**Additional context**
- We only ever expect to peer AWS ECF Prod
- In AWS we take a lazy path and reuse the same IP space for Dev and Test ECF
- Azure and GCP use one gateway, whereas in AWS we have 3 root accounts.  All have a central hub account
- AWS has a VPC per OU, so we peer the VPC structure
- We might need to redeploy Test ECF later once we have Equinix

**Definition of done**
- Coord with Jon so that we have a tidy set of IP ranges
- Max to coord with Warren, then Dana for an iStore request, likely ending up with Charles M's team (Julian has contact info to the persons on Charles' team - be clear we need to reserve this space so they register it on the router)

**Comment by wrnu** [comment]
Waiting for confirmation of iStore request

**Comment by ActionAnalytics** [comment]
This is high-priority, we need to chase this down and get unblocked

**Comment by ActionAnalytics** [comment]
We got unofficial confirmation, but need iStore ticket official confirmation.  Close off.
