### ISSUE TITLE
Revive Max's IDIR 

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1644]
**Describe the issue**
Max needs an IDIR to work.  This is blocking myPerformance, end of year training

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Max can log in with IDIR

**Comment by SmallDana** [comment]
Have spoken with 77000 regarding the issue, need to speak to @MaxWardle further to identify what's blocking him.
