### ISSUE TITLE
Create Demo sample of how the CLI could work with a hello world lambda on the API

### ISSUE THREAD

**Issue by unoah** [bcgov/cloud-pathfinder#1656]
**Describe the issue**
- Setup the API Gateway with placeholder Lambda - Platform Admin CLI Utility Related.  Setup API gateway and supporting infrastructure with placeholder Lambda that returns a 'Hello World'. 

**Additional context**
- This is a follow-up to Spike Ticket [1329](https://app.zenhub.com/workspaces/cloud-pathfinder-5e4dbb426c3c6af8dcbf06a7/issues/bcgov/cloud-pathfinder/1329)
- Documentation will be necessary but later on as we determine if this is the final approach

**Definition of done**
- Choose between Python or Javascript (both appropriate technologies for BC Gov to maintain)
- IAM protected regional API gateway provisioned with methods for get, create and update
- Methods are associated with placeholder Lambda functions that return sample data
- All resources are provisioned using Terraform
- Follow a similar CI/CD pattern along with the billing automation

**Comment by wrnu** [comment]
not relevant
