### ISSUE TITLE
SPIKE: Research using move ops we run locally to central admin compute resource in cloud

### ISSUE THREAD

**Issue by unoah** [bcgov/cloud-pathfinder#1657]
**Describe the issue**
- Lambda vs ECS for calls to GitHub - Platform Admin Utility Related
- The team is exploring developing an Admin Utility. Some operations would require interacting with GitHub repos using common git workflows (eg: git pull, git push).
- Need to perform discovery around using Lambda vs ECS with GitHub for git operations

**Additional context**
- We're contemplating using Lambda for these operations but not entirely sure about advantages/disadvantages vs using ECS.

**Definition of done**
- Survey what coding APIs and SDKs are available (depends on if we choose py or js)
- Put together recommendations/tradeoffs with using Lambda vs ECS for review by the tech team

**Comment by wrnu** [comment]
not relevant
