### ISSUE TITLE
SPIKE: Get enough info to estimate and create tickets for solving the Hana issue

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1662]
**Describe the issue**
Review of new Hana issue. Currently some sort of communications issue port ##### have an issue accessing from QP.  Jon is investigating what the purpose is, what they're doing

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Find out the details and create tickets if it's not an immediate resolution
- Cap it to 0.5

**Comment by jon-mc-git** [comment]
Pursued but ticket is now on hold until main technician gets back from holidays

**Comment by ActionAnalytics** [comment]
Hana has gone quiet, closing this ticket and if new Hana work comes up larger than a 0.5 or 1, we will create a new ticket
