### ISSUE TITLE
Try embed BC Sans or Open Sans in markdown to HTML browser

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1667]
**Describe the issue**
There is an issue with rendering the Open Sans in Shared Responsibility model.  Basically the font looks bad unless the user has Open Sans installed locally.

**Additional context**
- BS Sans is the best font for accessibility: https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity/bc-sans
- Supposedly DevHub might already be using BC Sans
- We may not have control over the DevHub CSS, but it's likely that it may already have BC Sans in it's CSS already because the documentation above lists DevHub as a user of BC Sans.
- This link has a guide on how to refer to BC Sans from within DevHub: https://developer.gov.bc.ca/Typography but we checked and BCSans never made to prod maybe? https://github.com/bcgov/devhub-app-web/pull/1215
- The HTML is very complex there due to the convolutions we have to take to go from our markdown to where it's rendered in DevHub
- Cap to a 2 effort

**Definition of done**
- Ask Olena's team if BCSans is ever going to be live?  See above links claiming it will
- Find someone on Olena's team (preferably other than Olena because she's busy) who can kick off DevHub builds for us (note that there are Dev, Test, Prod envs and we need it in Prod).
- See if we can improve the look of the Shared Responsibility model text so it smoothly renders with either BC Sans or Open Sans without requiring font package installation steps outside of the browser.

**Comment by wrnu** [comment]
not relevant
