### ISSUE TITLE
Onboarding timer for users

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#1670]
**Describe the issue**
Seems like our users want to know their place in the queue for onboarding. we are suggesting to add some sort of indicator to our onboarding funnel that shows how busy we are so people get feedback on where they are in the queue.

**Additional context**
- Problem:  We need to be able to refresh content on the DevHub site.
- We could do this in the Google Form with a label that we manually update once in a while

**Definition of done**
- Chase down the PO and get him to do the Google Form change, run it past Bahaa, test with 2 or 3 clients, ask them if it would have been helpful.

**Comment by wrnu** [comment]
not relevant
