### ISSUE TITLE
Technical onboarding for GDX Business Communications Solutions

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1671]
**Describe the issue**
We need a project-set for a session for GDX Business Communications Solutions (see CRM "Burbee")

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- They will want the container sample app
- Provision them with a new project-set
- The usual tech onboarding
- Invite Bruce and Kevin so they can silently observe

**Comment by wrnu** [comment]
not relevant
