### ISSUE TITLE
Platform Admin CLI API Authentication/Authorization

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1679]
**Describe the issue**
We are creating a a platform admin CLI and API for various admin operations. We will require authentication and authorization for this tool. 

**Additional context**
- This could be a handy mechanism to run custom billing queries

**Definition of done**
- Implement the basic CLI that does basic authentication
- Create Cognito
- Write it to KeyCloak
- Initial server side work (API)
- Add the Cognito/KeyCloak Group endpoint that allows for authentication

**Comment by ActionAnalytics** [comment]
Warren to flesh this out later

**Comment by wrnu** [comment]
not relevant
