### ISSUE TITLE
Find Privacy Certificates for Contractors

### ISSUE THREAD

**Issue by louisesmason** [bcgov/cloud-pathfinder#1681]
**Describe the issue**
Need to ensure all contractors have completed the Privacy Course and log the certificates. 

**Additional context**
- OCIO Contracts may have a list or the actual certificates but they are not the Record holders for contracts. All related contract documentation needs to be under the relevant LAN contract folders.

**Definition of done**
- List of all current contractors from PO
- Received all certificates from PO
- All the PDF certificates are stored under one folder

**Comment by ActionAnalytics** [comment]
We have 3 certificates of the 4 we need.  Still need Warren's

**Comment by ActionAnalytics** [comment]
Sent Louise Warren's privacy course file

**Comment by wrnu** [comment]
not relevant
