### ISSUE TITLE
CRM possible add-on - Ability to highlight team users that are NOT (yet) onboarded to Cloud

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1685]
**Describe the issue**
Create way to highlight (possibly visually) the users in our CRM tool

**Additional context**
- By being able to identify quickly if there are any individuals new to the team that may have been added by someone else an additional person can help, follow up if necessary with the client or ensure Cloud training is scheduled themselves
- Enables more of a team effort to training and allows for possible quick follow ups

**Definition of done**
- Show Jon the training list in Teams
- Identify what options exist within the CRM that may allow for this (colours, highlighting, bold\unbold names, etc.)
- Discuss potential best\easiest approach to a solution
- Can be added to new CRM backlog if not reasonably possible (create a 'New CRM Backlog' & add)
- If possible add a way to show as NOT yet onboarded but that are already scheduled for their training (highlight, colour, etc.)
- Implement if it is deemed possible and not too much time

**Comment by jon-mc-git** [comment]
Had meeting with Prabhu about this and a demo was worked out in the test enviro

**Comment by jon-mc-git** [comment]
Was put into our prod instance of Google CRM

**Comment by jon-mc-git** [comment]
Note that this ticket was in progress but left unassigned so missed last update: The functionality added in question helped identify new projects\teams that needed to onboarded and\or possibly teams that may have to be re-onboarded due to new team members.  However, it is not capable of identifying\tracking client team members individually when new ones are added within Ministries.  Will discuss further with Julian and if can't resolve currently we may close this and\or create other tickets if necessary

**Comment by jon-mc-git** [comment]
Possibly considering here to add in a 'Client Self-reporting' capability, that drops info directly into our CRM (possibly uni-directional - ie. they can sent it and it populates a field - Field history would have to be turned on due to client ability to overwrite previous information).  To start this could work for clients changing their teams up and new members needing cloud training\onboarding - Clients would go to a CPF Self-Reporting page and add the names of the new members and when they press Send it would update the appropriate 'Onboarding\Training Need' in the project's CRM entry - will see if possible as well

**Comment by ActionAnalytics** [comment]
Moving this back to the product-backlog so we can factor it in with capacity

**Comment by jon-mc-git** [comment]
An initial solution for our AppSheets CRM for this 'Client Self-reporting' mechanism has been identified, and Prabhu who believes it's fairly straight forward.  He will advise if any issues arise during a further short review period.  

The idea is that our Ministry clients have a web form that they can fill out to PO\team self-report changes in their group - training needs, team make-up and\or communicate other important info.  Once submitted by the client it will update a Sheets 'feedback\request' field automatically (field here will have history activated as well so every submission is back-trackable) and a client 'Submission time' stamp will be added. 

Note that the client PO\service lead will likely be required to submit this with the relevant project name, or some other known field and if an algorithm cannot match it to an existing project name (or ticket\Cloud request service#) then it would drop under an empty default project in our CRM and we would correct it upon review - empty CRM entry we would have to create this as part of the build for this functionality.  This would likely require an if\then capability within AppSheets which if not possible would require us to expose our Cloud request numbering system currently hidden and have it show up on every future Cloud Services\onboarding request submission in the future (on the post-submission PDF copy they receive by email), so the Ministry lead\PO could reference this in the 'self-reporting' form; However, this may be less ideal as names  are easier to remember, or a use of drop-down list could be implemented if it did not expose more info than necessary (ie. perhaps use a drop down of PO\service lead names in lieu & have all go to empty default project until processed or something similar)

**Comment by jon-mc-git** [comment]
Since this ticket has moved from an original intent of team individual training tracking into the 'Client Self-reporting' web form idea, we will close this ticket and create a backlog ticket to be activated when priorities allow

**Comment by wrnu** [comment]
not relevant
