### ISSUE TITLE
CIT project code transfer to BC Gov GitHub repo

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1687]
**Describe the issue**
CIT project team needs to transfer their Terraform-based CIT app\infra deployment code to the BC Gov owned private or public repo

**Additional context**
- New product owner may need some training (we're pulling her into training on the 26th of May)
- Current CIT Terraform code is in a repo run by the dev vendor NTT
- Next will be to move from them using Terraform sourced from an NTT laptop

**Definition of done**
- Meeting with Susan with Julian and Jon where we walk her through creating a github user (if needed) and making a repo for the CitV4 purpose
- Invite her to training after the 26th, and prepare her to pull in the code
- Create space in BC Gov GitHub for CIT project + people
- Onboard CIT folks involved (may need NTT resource participation, ICT group to coordinate)
- Transfer of CIT code from current repo to BC Gov GitHub repo

**Comment by jon-mc-git** [comment]
Met with Susan and discussed what needs to be done to help operationalize their CIT application.  She has now taken the training necessary and we'll be moving forward with creating a space for her teams code in the BC Gov GitHub repo.  More back and forth will be necessary for this and Susan will also have to bring in NTT as part of this.

**Comment by jon-mc-git** [comment]
It appears that the current CIT v4 is now closed and the Susan is trying to work out with them what might be next.  We recommended that move their current GitHub repo from the vendor created area to the BC Gov GitHub repo as a start.  They may likely choose to work with NTT to get the repo moved to the BC Gov space, but waiting on answer.

**Comment by ActionAnalytics** [comment]
As a matter of scrum practice, just make sure that I am the one pulling tickets into the sprint

**Comment by ActionAnalytics** [comment]
Looks like they have a repo
And there's a couple things we can talk to them about (make a var for this value, bit of security by obscurity)
https://github.com/bcgov/CIT/blob/c4d6023bd4255eacb09a0176c4c1859b17e41877/terraform/cit-prod/variables.tf#L42

**Comment by ActionAnalytics** [comment]
Jon to reach out to Susan, congratulate and make the above low-priority suggestion
