### ISSUE TITLE
CIT 'prod prep' issue - IaC PowerBI deploy

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1689]
**Describe the issue**
CIT is experiencing an issue using IaC and Terraform to deploy current enviro to a test enviroment

**Additional context**
Related to ongoing efforts\tickets to move CIT v4 to be 'prod ready' using all IaC, leverage using a BC Gov-based GitHub repo (current is open repo created by vendor NTT), the use of BC Gov Terraform Cloud, and possible centralized pipeline\ops management within Azure DevOps using a Terraform connector

**Definition of done**
- Communicate back that we are potentially tweaking our pattern, we will connect with them after we meet
- Troubleshoot issue w NTT
- Get status update if ongoing
- Resolve so they can move on in their CIT service prod preparations

**Comment by jon-mc-git** [comment]
Ticket will require some on-going check ups and coaching by our group to support ICT's CIT team and their PO Susan.  Increasing estimate in consequence.  With the above ticket dependencies taken care of we can likely be sure that the NTT process and problems around this will be taken care of

**Comment by jon-mc-git** [comment]
Putting on hold while the ICT group and the PO work out how they are going to move this operationalization work forward with NTT (need to contract with them further around this, as CIT v4 is coming to completion)

**Comment by wrnu** [comment]
not relevant
