### ISSUE TITLE
Create a New Rule to filter the emails with invoices in Cloud.Pathfinder@gov.bc.ca

### ISSUE THREAD

**Issue by SHIHO-I** [bcgov/cloud-pathfinder#1690]
**Describe the issue**
Need to capture all the invoices from AWS and the Shared Service Canada etc received in Cloud.Pathfinder@gov.bc.ca

**Additional context**
Cloud.Pathfinder inbox has over 200 unread emails and I would like to capture all the invoices without messing other emails in the inbox.
- Julian is waiting for a Windows machine from Dana because Outlook functionality on the Mac is not capable of doing this.
- Julian is working on getting through the 919 (today's number) unread emails.  It's high priority and will hopefully lower the urgency of this if he gets to the Cloud.Pathfinder inbox.  This week is sprint week so hard to find time as Julian is also covering the missing Scrum Master role.  Next week is looking promising.

**Definition of done**
- Meet with PO and have a session together to accomplish below steps
- Create a rule to filter emails: all emails with "invoice' in the subject should go to "DOCS Shared inbox - invoices" inbox

**Comment by wrnu** [comment]
not relevant
