### ISSUE TITLE
SPIKE: determine effect of EOL Python for AWS ECFs

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1694]
**Describe the issue**

We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Python 3.6 runtime.

We are ending support for Python 3.6 in AWS Lambda. This follows Python 3.6 End-Of-Life (EOL) reached on December 23, 2021 [1].

**Additional context**
- AWS email May 18 in Julian's mailbox
- There are a lot of lambda's we don't control because they're part of the SEA
- Security notification lambda is python, billing too

**Definition of done**
- Chat with Ryan J
- Hopefully we get this for free via an ASEA update. 
- "We recommend that you upgrade your existing Python 3.6 functions to Python 3.9 before August 17, 2022."
- Create well defined tickets if needed.

**Comment by wrnu** [comment]
not relevant
