### ISSUE TITLE
SPIKE: Low-Code\No-Code - Preliminary Enterprise considerations & investigation

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1695]
**Describe the issue**
(SPIKE?)Priliminary investigation, notes & summary of considerations around the increasing use of Low\No-Code solution app delivery platforms (Microsoft's Power Platform), including some basic ways to establish early governance across these platforms where possible (and to what extent)

**Additional context**
Increasing use of these platforms across the organization has affects by routing around some of the normal controls around security operations, networking, Information management, data\system access restrictions.

**Definition of done**
- Investigate known ramifications of Low\no-code platforms to the Enterprise
- Create a summary for discussion
- Decide if more research needed, other folks to bring in and\or what other further actions may be necessary
- Create well formed tickets for anything that could be done

**Comment by wrnu** [comment]
not relevant
