### ISSUE TITLE
Investigate AWS high security alert (we think it's not high) and sink it

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1707]
**Describe the issue**
Confirm that the May 16, 2022 (and others) warning in channel aws-security-high is being triggered by a user querying an API (not a high ranking incident).  Determine with AWS a way to filter out this warning.  Leave account and warning details out of this ticket.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Connect with PO for context
- Reach out to Ryan J to determine optimal approach to filtering out an error message

**Comment by lukegonis** [comment]
This issue is no longer relevant, moving to closed.
