### ISSUE TITLE
Sandbox admin permissions appear unable to apply AWS credits to the account

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1711]
**Describe the bug**
Julian is trying to apply a raft of credits to several health accounts.  Some of them work, but 2 of them do not and those accounts are sandbox accounts (correlated? small sample size but suspicious).

**Additional context**
Add steps to reproduce the behaviour or any other context

**Definition of done**
- talk to Julian for the specific accounts and the corresponding credits codes that are configured only for a specific account 
- first priority is on applying the credits
- second priority is on making sure that the admin role in the sandbox accounts is identical to the admin role in other accounts in the other OUs

**Comment by prabhukiran9999** [comment]
- We are not able to apply credits on the sandbox account due to the SCP's on the sandbox accounts.
