### ISSUE TITLE
Remove Core ALB from Project Set Creation

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1713]
**Describe the issue**
This is a cost saving ticket essentially.

Currently the Fortigate routing created a "default" Application Load Balancer (ALB) in each workload account that needs routing because the Core ALB e.g. "Core-B89n0cDev-C9EC02-alb" that the SEA creates takes place in the state machine, which runs after new accounts are created. That means we would have to create accounts, wait an hour or so, and then hook up the routing via the Core ALB. We want to use the Core ALB moving forward with the Checkpoint routing automation.

Originally we though the ALB features in the SEA weren't usable for us to use.  We thought we could take away the default one we create or the one the SEA makes.  Better to disable the SEA one because it doesn't scale and slows down deployment of new accounts requiring things to be done in stages.  Functionally the ALBs are identical.  Smoothing out the Ops part.

**Additional context**
- This isn't used by anything.  Waste of money to use the core ALB.  We also will need a ticket to clean out Core ALBs from existing customers.
- We want to minimize what we create with the state machine because it takes a lot of time
- Nothing on the routing will change
- In the example above "Core-B89n0cDev-C9EC02-alb" the C9EC02 section is generated somehow
- Having an extra ALB in workload accounts costs around $15/ month (this is partly a cost saving measure)
- Creating the "default" alb is additional, manual configuration

**Definition of done**
- Confirm in Forge if this deletes all automatically or if we need a garbage collection script
- Research ways to fully automate this process using the Core ALB
- Make the change to automation going forward
- See how many people are using these SEA created Core ALBs (we think it's only the VM demo app)
- Make changes to existing environments so we can remove them and save $$

**Comment by ActionAnalytics** [comment]
Aim for Sprint 48
