### ISSUE TITLE
Document Fleet Manager Setup

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1714]
**Describe the issue**
A Windows machine is required to install Checkpoint's Smart Console to interact with the Firewall Manager. Our current process for Linux and Mac users is to stand up a Windows VM in the Perimeter account and use AWS's Fleet Manager to remote in and set up the Smart Console. This pattern was Ryan J's idea, but is undocumented, and slightly complicated.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Document how to setup the windows VM and hook up to Fleet Manager
- Document how to setup Smart Console for default internet traffic to happen

**Comment by wrnu** [comment]
not relevant
