### ISSUE TITLE
Update the Sample Apps to Use Core ALB 

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1715]
**Describe the issue**
In the past we've provided teams with sample applications that use the "default" alb, but moving forward we want to use the Core alb e.g. "Core-B89n0cDev-C9EC02-alb". We want to update the sample app repo's to reflect this change.

**Additional context**
- Sample applications that use the default ALB
  - [containers](https://github.com/bcgov/startup-sample-project-aws-containers)
  - [drupal](https://github.com/bcgov/startup-sample-project-aws-drupal-containers)
  - [vms](https://github.com/bcgov/startup-sample-project-aws-virtual-machines)
- ALB name will be partially generated so we need to query AWS, we can search for the (full) ALB name or via Tags

**Definition of done**
- Query AWS to ger core ALB name
- Replace default ALB with core in all repos that use it
- Do not PR to main unless the Checkpoint firewalls are installed on LZ2

**Comment by ActionAnalytics** [comment]
No longer needed
