### ISSUE TITLE
Clean up Azure Billing notifications

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1718]
**Describe the issue**
At the moment Azure billing notifications are still landing with David E and Andy T.  We would like them to go to Cloud Pathfinder and CSAM roles.

**Additional context**
- Sample email is in Julian's Azure, Billing mail folder from date May 30, 2022, 1:01 PM

**Definition of done**
- Create or use existing CPF shared mailboxen
- Find out from Dean P if there's a shared mailbox or account he'd prefer to receive Azure billing notifications at
- Change the "Here is a summary of your Azure monetary commitment balance and unbilled charges." mails to go to the appropriate place.

**Comment by wrnu** [comment]
not relevant
