### ISSUE TITLE
SPIKE: Design Automated process for granting Lab account access

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1719]
**Describe the issue**
Individual developers sometimes need a playground to test ideas. We can provide this by creating an automated process for developers to request a lab account for e.g. 24 hours, grant access and then after the allotted time revoke access and run aws nuke on the account.

[CRC] Olena ask for a diagram about creating a self-serve app for teams to get their project set. This request overlaps with this ticket, for this reason instead of creating a new the same ticket will be used to do the design. Both requests differs only in minor details.

**Additional context**
There is a quota of 10% of the existing account for using the CLI as a tool to delete accounts. There is an alternative method that is quite time intensive. Some though needs to be put into the design of the app so the CPF team will not be flooded with abandoned accounts that will incur into monthly charges.

**Definition of done**
- Proposed technical design document created and reviewed by the team.
- Create higher level diagrams
- Two use cases: 
  - Teams requesting a full project set
  - Teams or individual contributors asking for temporary access

**Comment by crochcunill** [comment]
Document (SelfServeApp.docx) and diagrams (diagram.drawio) created and stored in  _![image.png](https://images.zenhubusercontent.com/620eba1ac6937a4e70b34b15/b42bfa0e-7bf8-4d81-a901-48c2f4a60b07)****_
