### ISSUE TITLE
AWS Billing Utility Forex component

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1727]
**Describe the issue**
We are using a forex component for converting USD to CAD for our billing.  It doesn't always work though.  We would like a fallback utility.

**Additional context**
- currently using Fixer service https://fixer.io/
- Accuracy is not important for weekly billing, this is a heuristic
- Bank of Canada, Oanda, Bureau d'Exchange, https://www.bankofcanada.ca/valet/docs

**Definition of done**
- Cloudwatch possible to log 3 fields [Service, Date, ExchangeRate] <- or save to Dynamo
- Use the exchange rate the day of the run
- Have 2 or 3 methods, falling back to each if one fails.  If all fail, use the last one from the log, notify by email to CPF or to a Rocket Chat channel instead.  We don't want to fail to send out a report though.

**Comment by wrnu** [comment]
not relevant
