### ISSUE TITLE
Implement Billing API through the Platform CLI for custom billing reports

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1728]
**Describe the issue**
We have Billing automation.  We have a Platform CLI that authenticates.

**Additional context**
- This API will serve AWS, GCP and Azure

**Definition of done**
- Billing, CSP, Start Date, End Date, Target recipient group
- Implement the back-end Lambda that actually sends it
- All requests should be Authenticated

**Comment by wrnu** [comment]
not relevant
