### ISSUE TITLE
Set overall date format for Billing and other comms

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1729]
**Describe the issue**
Use BC Gov standard for dates and Louise M's standard.

**Additional context**
- https://www2.gov.bc.ca/assets/gov/government/services-for-government-and-broader-public-sector/information-technology-services/standards-files/date_and_time_standard.pdf
- "For Date: Year (YYYY)-Month(MM)-Day(DD), for Time: Hour(HH 24 Hour)-Minute(MM)- Second(SS)"

**Definition of done**
- In our automation, update our date formats to use 2022-05-23 format (see above)
  - there an instance needed updating in the subject line of the weekly billing reports for example.
  - the hello world greeting displayed to the demo app user

**Comment by wrnu** [comment]
not relevant
