### ISSUE TITLE
SPIKE: Time Series Dashboard for Billing + Analytics

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1730]
**Describe the issue**
We want to provide a better service experience for people receiving billing info from us.  The value is in the aggregation and history.  Precision is not a high priority (CAD vs USD)

**Additional context**
Billing group is likely going to be our connective tissue across GCP, Azure, AWS
Currently AWS is the only example we have for now because that's the only one with data.
Variety of solutions exist:
- AWS Quicksight + Athena (backend)
- Cost Management (Cost Analytics) Azure
- Power BI 
- DataStudio (pres) + BigQuery (backend)

**Definition of done**
- Research solution that could allow teams access via SSO and for them to see their aggregated costs in cloud over time, and then 
- Define the bounds of what features we would offer vs the in-house cost explorer (we likely do not want to redefine the wheel)
- Cap to 3
- Meet and present to the team for 1 hr.

**Comment by wrnu** [comment]
not relevant
