### ISSUE TITLE
Testing the new "question driven" version of CSS 

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#1731]
**Describe the issue**
After the workshop of the CSS revision, we want to test the outcome of this new CSS version to our 3 identified users. Small/Medium businesses, teams building in ministries' environment and SaaS.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Identify list of participants to test the outcome
- We want to test at least one or two representative for each category (could be 3 to 6 tests)
- Set a testing sessions

**Comment by mitovskaol** [comment]
this work moved to the SaaS team
