### ISSUE TITLE
Analyzing and updating the new question driven version of CSS 

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#1732]
**Describe the issue**
After testing the new CSS with identified participant, we want to analyse income and update the CSS to a new more polished version.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Analyze insights
- Update the CSS (finalized, published)
- Share with  PO and community 
- Create a ticket to get the CSS online
- Create a ticket to link the CSS to our login app and our pre-reading material

**Comment by ActionAnalytics** [comment]
Bonnie reached out and said there is a coop being hired for Sept and they can test

**Comment by ActionAnalytics** [comment]
I have concerns about assigning QA of something this complex to a coop with zero context of all the users and processes in gov

**Comment by ActionAnalytics** [comment]
Possible our QA could take this on

**Comment by wrnu** [comment]
not relevant
