### ISSUE TITLE
Spend time with Gary W deciding on Functional Test Tech

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1734]
**Describe the issue**
Gary W, DevOps Guild lead, is looking for an improved functional testing component that is free to use, capable and doesn't require the constant updating that the current BDD (Behaviour Driven Development) stack requires.

**Additional context**
- Gary is targeting our accelerator apps because these imprint people as they go through our onboarding
- He wants a very simple low barrier of entry to automated testing

**Definition of done**
- Follow up with Gary on June 27th to prompt for this meeting (if it's too early, then we leave this ticket for next sprint)
- One or two meeting with Gary and his team
- Include Jon in the sessions
- Create well defined tickets for any changes we need to make to our accelerator apps

**Comment by ActionAnalytics** [comment]
Gary won't have time for this until start of August

**Comment by crochcunill** [comment]
This is an old ticket and Gary W seems to have other priorities. So it can be closed. If necessary can be recreated or reopened
