### ISSUE TITLE
Add destruction workflow to Demo Startup Apps

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1735]
**Describe the issue**
We have several accelerator apps, and Kevin noticed that there isn't a destroy workflow

**Additional context**
- Serverless app isn't using terragrunt, and has a destroy workflow
- Destroy workflow exists for the VM app
- This is a learning ticket addressing learning debt so we'll estimate high
- Destroy here via the CLI will be different from how Max destroys in the TFC UI.  But only a few of us have access to TFC whereas we want teams to have this capability via the IAC.

**Definition of done**
- Add a manual destroy workflow for the containers app
- Capable of accepting the workspace in the workload environment as an input
  - select the workspace to be removed
- A workflow that can destroy TFC workspaces
- Take a video with no sound of the workspace being tested demonstrating a successful destroy for us to use in the demo

**Comment by wrnu** [comment]
done
