### ISSUE TITLE
Reconnect Pathfinder SSO AWS Billing

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1740]
**Describe the issue**
We have an MOU for Pathfinder SSO again.  Search CRM for "Zorin".  We need to pull those workloads off CPF billing and over to their own unique billing (not sure if one exists or create needed).

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Pathfinder SSO team workloads now point to their own billing license plate

**Comment by MaxWardle** [comment]
I think this is already on it's unique billing group `c6zwf`:
https://www.appsheet.com/start/886d45a7-3de8-48f7-8bc7-a4604ca6740f#appName=CRMINTAKEFUNNEL-5621378&group=%5B%5D&page=detail&row=c6zwf&sort=%5B%5D&table=Billing+Group+History&view=Billing+Group+History_Detail
