### ISSUE TITLE
Cloud Pathfinder GitHub Documentation Site (scope bcgov org)

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1741]
**Describe the issue**
BC Parks has done a nice job linking their GitHub presences together.  We could reuse this.

**Additional context**
- https://bcgov.github.io/bcparks/projects
- Consider an internal version facing new CPF members, whereas we also need an external one that client teams can use

**Definition of done**
- Reimplement the BC Parks page in Cloud Pathfinder and have it display our resources in bcgov.  We will make later tickets for bcdevops.
- Make a visual track showing "first part" of documentation so people can easily navigate to where they need

**Comment by wrnu** [comment]
not relevant
