### ISSUE TITLE
SPIKE: Hybrid Cloud on-prem Internet access solution investigation -- Cloud service\SaaS public side connectivity + Testing\troubleshooting

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1747]
**Describe the issue**
Investigate and test a Checkpoint solution around controlled Internet access (similar to on-prem based blacklist-based Forward Proxy service), established at the cloud comm hub level (again, blacklist-based type + possible ability to change it over to a directly customized whitelist).

The value in doing this work is that it would greatly reduce the amount of repetitive bottlenecking support work needing to be done on an ongoing basis in Azure workloads.  It decouples us from any over-processed iStore\DXC based systems using on-prem Managed Services (DXC) as well.

**Additional context**
Current Hybrid Cloud situation relies solely an on-prem F5 Forward Proxy, which is good for on-prem prod, but bad for every other scenario involving technical support for Cloud Services access by cloud-based resources which may require a public connection to its service either temporarily (service registration for example) or in an on-going way (like ADF-IR preview functionality using public URL calls to work).  For more permanent scenarios Cloud Services often have to be troubleshot before a permanent solution can be found (then the F5 service whitelist-based service could be uses - Note that this has not yet been tested)
- there are 4 or 5 potential solutions in consideration in all this: completely Azure based, DMZ based, hybrid solutions, etc.)
- Note that this will require cooperation with the Security Operations group, and therefore need to be coordinated
(SecOps will have to enable\test equivalent type security processes that are currently standard for all Internet traffic (the BC Gov Data Centres 'SIS security service' technology stack - to be replicated to point where SecOps is comfortable)

**Definition of done**
- Investigate which option would be best
- Test capability
- Demo results of investigation and drawings to CPF tech team & PO
- Create additional tickets from this if necessary

**Comment by ActionAnalytics** [comment]
Jon is at capacity during planning for this sprint, but if he frees up before end of sprint, this ticket would be a good to pull in next.  Can pull in without PO meeting if all other tickets in sprint are closed

**Comment by wrnu** [comment]
not relevant
