### ISSUE TITLE
Tech onboarding for AG Ryan L 2 project-sets

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1749]
**Describe the issue**
Search the CRM for "DEMS" 

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Connect with Ryan L and confirm that these are the 2 workloads for AWS
  - Waiting for confirmation from Ryan about CFFMS, see related ticket
- Put them on the same billing group for now and we will determine if separate later
- Put the containers demo app in their onboarding

**Comment by MaxWardle** [comment]
Reached out to Ryan L and he said "Thanks for reaching out. Good to proceed with the DEMS onboarding, but CFFMS we are still waiting to hear from the vendor that AWS will work, their only experience is with Azure as it is a MS solution." I think I'm going to break this work out into another ticket.

**Comment by MaxWardle** [comment]
Blocked setting up a time for this team with a few people with busy schedules.
