### ISSUE TITLE
Onboard new MDS people to Power BI and subscription

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1750]
**Describe the issue**
Search the CRM for "MDS", choose the Power BI one.

**Additional context**
- Vyas is taking over for Jon F, Arturo looks more like he's a Power BI user/dev so maybe not the same access

**Definition of done**
- Onboard the several people listed in the CRM to the appropriate environments they are asking for in the CRM entry latest update field. (and inform the team if they can self-manage access to parts like their DB)

**Comment by ActionAnalytics** [comment]
For sure we want to help these folks

**Comment by ActionAnalytics** [comment]
We've reached to Rebecca and Vyas

**Comment by jon-mc-git** [comment]
Meeting with the new MDS team (Rebecca - PO now) held and a status of both MDS projects they have under them was gotten.  For the MDS Azure project it is fine and it is status quo for now (no planned improvement\updates coming so nothing happening with it currently), and the newer project MDS on AWS is currently on hold.  I updated our notes on that in CRM with further details.  Closing ticket now
