### ISSUE TITLE
SPIKE: Connect CheckPoint logs to CloudWatch using role based via AMI

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1752]
**Describe the issue**
CheckPoint logs can be stored in CloudWatch and for free, they will end up over in the SecOps SIEM, accomplishing some transparency and visibility.

**Additional context**
- We are assuming this is a role issue related to the AMI, not needed installation of CloudWatch agents
- Hopefully doable via the config.json in the SEA

**Definition of done**
- According to Prabhu's update today, the CheckPoint FW images are configured for CloudWatch already.
- Have a second meeting with CheckPoint to get the final steps to connecting to CloudWatch
- Verify that the logs are reaching the SecOps SIEM
- If the work involves installing CloudWatch agents, stop and come back to make tickets on how we will approach this (Ansible? Chef? Systems Mgr?)

**Comment by prabhukiran9999** [comment]
- Checkpoint instances do not have Coludwatch agent installed in them and they do not recommend installing them as they hardened their images
- Checkpoint supports the log export option to export logs to a SIEM service.
- We can also try and set up a proxy EC2 instance with an rysyslog service in that instance and export firewall logs to that instance and use it to stream logs to cloud watch
