### ISSUE TITLE
Integrate CheckPoint Firewalls with central SecOps Log & Management System (SIEM)

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1753]
**Describe the issue**
PO thinks that there is a central system for managing all the CheckPoint firewalls and interfacing/aggregating all their logs.   Michael V and Chris C know the details

**Additional context**
- This is lower priority than the CSPM work and the auto-policy test/approve pattern for ECF
- Long lived VMs
- Log rotation?  Hopefully
- A lot of concerns around the lifecycle management of these properties
- CheckPoint shared a pattern with Prabhu that shows how to connect the logs to the SIEM

WILL ESTIMATE once we have the documentation

**Definition of done**
- Connect with SecOps and connect our firewalls to their management system
- Will probably take a few meetings include Chris B and Jason G from CheckPoint

**Comment by wrnu** [comment]
not relevant
