### ISSUE TITLE
Get Bruce, Gary and Jon access to SecOps SIEM

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#1754]
**Describe the issue**
- SecOps have deployed a SIEM solution to which we send our logs 
- The Lambda function that exports the Log has been deployed in the Log-Archive account 
- Reach out to Prabhu if any questions about the Whole flow

**Additional context**
- Bruce, Gary and Jon needs to get the Access to SIEM, Possibly speak to Justin and get the access
- Bruce likely has access already, let's confirm and get access/demo for the others

**Definition of done**
- Bruce, Gary and Jon has access to the SIEM created by SecOps and access to the account where the lambda function has been deployed

**Comment by prabhukiran9999** [comment]
- Reached out to Austin a couple of times about the access and sounds like they are working towards building a reliable 
   endpoint 
- Waiting for the response back from the Secops

**Comment by ActionAnalytics** [comment]
Do we need a reliable endpoint to have access or can we get access to the unreliable VM SIEM that some of us have access to?
