### ISSUE TITLE
Have Jon, Bruce and Gary review all PRs in one sprint

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1756]
**Describe the issue**
We want to spread out and share the ability to review work as it goes by, learn about GitHub processes and prevent stagnation/rubber-stamping in our reviewer pool.  So we can add more people.

**Additional context**

**Definition of done**
- Watch the github review training video in our Teams internal onboarding folder
- Announce to the tech team at the start of the sprint
  - Tech team Teams messages the selected reviewer for each PR (because we expect that most people are filtering out GitHub messages)
- Anytime a PR is made, add one of {Jon, Bruce, Gary} to the approver list
- Reviews and discussions happen (learning dept will slow us down a bit and that's ok)

**Comment by wrnu** [comment]
not relevant
