### ISSUE TITLE
Port over Test Auto work from ECF Dev / CSPM USA to ECF Prod / CSPM CDN

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1763]
**Describe the issue**
We need to abandon the old hackathon non-regionally compliant CSPM environment in favour of the new CDN region compliant space.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Acquire a dedicated AWS workload environment suitable for the test-auto work
- Recreate the same tests over in the new CDN CSPM environment pointed at the above

**Comment by crochcunill** [comment]
There are two main components of the test plan affected by this ticket:
- Testing policies/roles: In this case, the only changes is to use the CA Checkpoint CSPM. It requires almost no effort, and it will be fully implemented when the scripts are refined.
- Testing the sample apps (they should continue working after the upgrade). At this moment they are using the dev environment of one of the **td5cou** workload account in LZ2. No action will be taken as, ideally, the test should happen in LZ1 (test). Currently LZ1 is not properly configured. The apps will be ported to LZ1 once is ready. I am creating a ticket to port the sample apps to LZ1

In this context, this ticket can be considered closd
