### ISSUE TITLE
Confirm that CheckPoint CSPM can run/compare reports before and after an event (like a patch)

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1765]
**Describe the issue**
We have too many test frameworks.  

The user persona of the test that Carles is aiming for at end of Sept is a Platform Admin who is performing an SEA patch on ECF Test and intended for ECF Prod.

We want to try to leverage CSPM so that we can hopefully snapshot state before the patch is run, snapshot after, compare and alert if different (assuming that the state changes in fail condition).

**Additional context**
- Assume that it is easy to get reports out of CSPM
- Assume that it is unlikely to do the comparison within CSPM

**Definition of done**
- Compare the output of a report pointed at an AWS workload environment to the output from the AWS CLI (check for completeness)
- Come up with a preliminary process using CSPM and perhaps even a manual step like running two output files in Meld (an opensource compare tool).
- Maybe CSPM has the ability to detect a state change and notify out.  That would make the next part below irrelevant.
- In scope, detect a difference before after.
- Out of scope, create automation for detecting the difference (this could look like an docker image to be defined and run locally with a Meld/diff compare, a test-auto framework, or some other approach.  Then even later, we host that as a service on AWS and run our tests there, notify out)

**Comment by crochcunill** [comment]
the following curl command lists all the roles, in this case AWS roles

curl -X GET \
  https://api.dome9.com/v2/CloudIamRole \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Basic YzE1ZjQyOGUtOTE1Yy00OWIwLWJhN2YtYTdlYTkxMzgwNWQ2Onh1bmNxaXc5a205aGU2ODViNnBveG90aQ==' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: visid_incap_1095475=5zkS+5mSSCOH3hYXv1Lrj9O7p2IAAAAAQUIPAAAAAAA+sXvGbBuzh5XDpc1rtOML; nlbi_1095475=P1i2HKLrrQd4vv5qQ7IvqQAAAADLwCYtsTYZ/MvKw+8xEWVS; incap_ses_8078_1095475=AgCkTxnachJAFVLbp9IacL/Bp2IAAAAA/wfsnDAAFICA0asDcvVHDA==' \
  -H 'Host: api.dome9.com' \
  -H 'Postman-Token: b0bd8f7e-ceb4-4b13-b843-98c9705cd2d4,b7145329-965a-47f3-9d2a-101058a0c744' \
  -H 'User-Agent: PostmanRuntime/7.19.0' \
  -H 'cache-control: no-cache'

**Comment by crochcunill** [comment]
> Compare the output of a report pointed at an AWS workload environment to...
CheckFront Cloudguard does not seem to have the possibility to create reports, however, the API collection allows to download the appropriate information. And from here reports can be built

The AWS IAM CLI function also allow to extract useful information for each account. Hopefully it will also allow to extract the information for all account associated to user when login as such user

> Come up with a preliminary process using CSPM and perhaps even a manual ....
See attached file

> Maybe CSPM has the ability to detect a state change and notify out.
Going through the interface it does not seem this feature exists. I am also login to an instance with expired license and not sure if it is up to date.

> In scope, detect a difference before after.
Currently this is implemented by comparing selected fields from the files obtained using e the Cloudguard API and the AWS CLI (see attached file)
Not sure how the information may change after a SEA upgrade/update.  i will need to check after such operation. Hopefully there may be no changes in artifacts that exist before and after the upgrade and the differences will be limited to known changes

> Out of scope, create automation for detecting the difference (this could look like....
Currently the steps are manual. However, with a long live AWS account all the steps can be part of an automated test script[https://app.zenhub.com/files/241742911/8911afe0-28b3-4820-95fa-2e9a92834e05/download](https://app.zenhub.com/files/241742911/8911afe0-28b3-4820-95fa-2e9a92834e05/download)
