### ISSUE TITLE
Ministry use of SaaS products that require subscriptions for cloud billing or simple storage services 

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1767]
**Describe the issue**
Investigate the new use case presented by the Identity group as part of project they are working on, with clients using SaaS products like dynamics online and related apps (like Microsoft application Lifecycle Management - LCS prodect) 

**Additional context**
This is around AG's use now of the Microsoft LCS product - which is built around Dynamics Online, as a module of this
- relates to the Usage Type label in the CRM
- another example is piping of billing data that Chris F wants to implement and use a dashboard in Azure
- this is strategy work around how we do cloud, involves the roadmap and the PO.  It affects our capacity, the messaging around Azure relating to the contract and is affected by hiring

**Definition of done**
- Investigate the LCS service and how it uses Azure Subscriptions exactly
- Meet with Identity team to understand the ministry demand pressure behind this.  Include PO
- Create a drawing in draw.io that illustrates the pattern clearly and store the files in our teams drawings folder 
- Review drawing with PO
- Meet with Identity team to communicate the action via the above drawing to the Identity team based on this (how we deal with this Subscription-wise in the Azure space and how it relates to our current standardized infrastructure)

**Comment by jon-mc-git** [comment]
Had meeting with AG and ADMS group on this.  Found out that in their particular case of needing to install the Microsoft LCS cloud service integration into their on-prem Dynamics applications instances, the Azure subscription for billing was not needed.  Waiting to find out how that goes and ADMS group is working with them and I will meet with them for update on moving forward soon or if nothing more from this will close soon

**Comment by ActionAnalytics** [comment]
Please pull me in for all the meetings as per DoD (we already missed one so would like to connect)

**Comment by ActionAnalytics** [comment]
Jon says if we don't get any feedback from them, and it's on-prem only for now, so if we don't hear back from them, we will likely close the ticket.  I'll put in out of the way in "blocked" for now just to show we've done work and are waiting

**Comment by ActionAnalytics** [comment]
Changed my mind, let's close this and create a new ticket if they come back to us.
