### ISSUE TITLE
Draft documentation for Teams new region flexible PIA changes

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1773]
**Describe the issue**
We will need to create guidance for Ministry Teams about how to add an Assessment document to their existing cloud app PIAs to include the use cases in regions outside of Canada.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Gain understanding of the PIA non-Canadian PIA + Assessment process
- Gain understanding of the technical work in the two linked tickets
- Draft Word Doc or PowerPoint PIA guidance as a document stored in the CPF Teams files
- Review proposed changes with PO

**Comment by lukegonis** [comment]
- Ministry Teams may consider aspects of this work in the future and may bring this to our attention at a later date. Closing for now
