### ISSUE TITLE
Security training session for Gary

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1776]
**Describe the issue**
The usual part of onboarding a team member

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Skip the Google part as Gary doesn't need it yet and Julian needs to provide the physical keys
- Focus on the rest (apps, keypass/macpass, secure practice discussion)
- Wait until Sprint week 2 as Gary has a lot on his plate the first week (equipment, IDIR, access to other systems) that he needs to do first

**Comment by bruce-wh-li** [comment]
Gary has just received his new laptop.   Recommend he to enrol to intune mdm and install ms defender asap.
