### ISSUE TITLE
Take snapshot of latest version of the ASEA upgrade for comparison later

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1777]
**Describe the issue**
It's been a while since we've patched the AWS Dev, Test, Prod

**Additional context**
- The Prod LZ2 upgrade will likely be done by Friday the 12th, this may be possible to accomplish that day or the day after.  Coordinate with the folks running the upgrade patch

**Definition of done**
- Manually create a project-set and install a demo app (maybe have Carles do that) after the patch to check everything still works.
- Save the record, use it later next upgrade

**Comment by crochcunill** [comment]
Snapshots taken for the three LZ. They can be found at 

LZ0
https://bcgov.sharepoint.com/:f:/t/01368-CPFScrumTeam/ElqQ897Z3JRKuuw14-UJu9cBrUXMcoNpOX9rBp9tIxUnFA?e=pJ2Bd8

LZ1
https://bcgov.sharepoint.com/:f:/t/01368-CPFScrumTeam/EtaruDOVJtxGvTK5CEtVyyYBIN6Qdu3mv9VW5iSKjqOoHg?e=7KXRrY

LZ2
https://bcgov.sharepoint.com/:f:/t/01368-CPFScrumTeam/EqvejPq4h7JAm4w1KHgA6MUBf3UHLrvXkxnrMbNdqd8aGA?e=f0uNBD
