### ISSUE TITLE
SPIKE: Pathfind a pattern that allows for cross-account communication in the ASEA

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1781]
**Describe the issue**
Currently the ASEA that is used as the base for the BC Gov AWS ECF routes traffic up and out.  This is handy for working with the firewalls and for isolation of concern between the workloads of different teams or even of the same team (we want to avoid situations that could lead to a team accidentally linking their test DB to a prod front-end for example).  

There are a few teams that have created services that are meant to support other teams within the ECF.  These teams have an interest in efficiency in having the ability to have data flow directly across from one workload environment account into another within the same ECF.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Team meeting to collaborate on design that could work within an ASEA-based ECF
- Review with AWS
- Connect back to Michelle D, Nithin K, Johnathan B as a focus group for any proposed solution
- Create well-formed tickets (DoD, estimated) for any implementation work

**Comment by wrnu** [comment]
not relevant
