### ISSUE TITLE
Find demand for Multi-Region services

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1784]
**Describe the issue**
Factor in demand for non-US services in order to determine if Ministry Teams require non-VPC services or if they actually need network-supported services (containers, VMs)

**Additional context**
- We're about to perform some expensive changes to the ASEA
- We may be able to satisfy the demand for US/foreign services
- Proposed is setting up default-MR, then using detective processes to warn MPOs to make sure that their PIAs have the extra outside-of-canada assessment doc

**Definition of done**
- Find out which Ministry Teams are after AWS services from regions outside of Canada
- Find the list of services they want
- Give this info to Julian and Warren in order for them to determine if there are services that require custom networking or if all these services can be enabled as non-VPC

**Comment by wrnu** [comment]
not relevant
