### ISSUE TITLE
SPIKE: SEA Not Deploying Target Groups on Perimeter ALBs

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1785]
**Describe the issue**
In the `config.json` where each LZ's SEA configuration lives (in the management account's code commit) there is a section called "mandatory-account-configs" > "perimeter" > "alb" where the Perimeter account's ALBs are defined. in the "Public-DevTest" and "Public-Prod" ALBs we specify listeners, but these listeners never get created. We've consistently had to create these listeners manually, so there is some issue with the config of these.
 
**Additional context**
One thing that we tried was deleting the targets `"targets": []` but this didn't fix the issue
- This happened when redeploying LZ1, the listener on the public-facing ALB is not being created and we don't know why.  We manually create them after.  Related to Fortinets now missing?

**Definition of done**
- Try to figure out what is wrong with the configuration of these ALBs in LZ0 or LZ1
- Possibly meet with Ryan J to debug this issue
- Create well formed tickets for any new work to address this (if the solution is .5 or less just do it after checking with Warren)

**Comment by wrnu** [comment]
not relevant
