### ISSUE TITLE
Reach out for Scrum Master training for the FTEs on the team

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1790]
**Describe the issue**
There is training available from Alluvial Consulting via the Digital Academy.  Let's try get some for the people on the team that do not have it.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Reach out to Dana and ask her to book Scrum Master training for the following people:
- Omo, Dana, Bruce, Jon, Gary, Max, and Catherine for SM course (Sept 20/21). Omo, Bahaa, and Jon for PO training (Oct 25/26)
- Read the Scrum Guide https://scrumguides.org/docs/scrumguide/v2020/2020-Scrum-Guide-US.pdf

**Comment by ActionAnalytics** [comment]
Reach out to Mack Adams on Rocket Chat, he's the owner of Alluvia.  Kristi Meredith is also an Alluvial rep on Rocket Chat

**Comment by garymatics** [comment]
Will be forwarding the names/e-mails of participants to Alluvial as soon as approval for course fee is received from Audra G.

**Comment by garymatics** [comment]
Attendee names/contact info forwarded to Alluvial.

**Comment by garymatics** [comment]
Jon signed-up for PO training on Digital Academy (07/26/22). 
Gary signed-up for SM training on Digital Academy (07/26/22). 
Bahaa has confirmed that he has signed-up for the PO training.

**Comment by ActionAnalytics** [comment]
Gary will follow up with anyone who hasn't signed up
