### ISSUE TITLE
SPIKE: Explore Outside Team Contribution to the AWS SEA/ECF

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1796]
**Describe the issue**
Recently I onboarded a team that expressed interest in contributing to an OU that fit their use case of just storing an S3 bucket.  

**Additional context**
- CPF develops in the open but there's no easy path for other teams to make contributions
- The empty SEA costs $4500/month to run empty, so difficult for teams to create a dev env

**Definition of done**
- Determine if it is feasible for team's that are not CPF to contribute to the AWS SEA/ECF
- Create a PowerPoint Slide for our demo deck that has a message to the community about this (could be a solution, could be that it's too hard to have a solution)

**Comment by wrnu** [comment]
not relevant
