### ISSUE TITLE
SPIKE: Create messaging on pattern for teams that just want storage in S3 and similar service use card

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1797]
**Describe the issue**
Recently a team was onboarded that just wanted S3 bucket storage and we had no other pattern than to deploy for them a project set for an application living in AWS. This includes routing, security, and other costs adding to around $200/ month, which seemed excessive for their use case. They don't need any of the routing, they probably don't need a sandbox environment, and they man not even need dev, and test.

**Additional context**
- The networking and load balancers do incur a cost
- Is there a way to provide a switch within the accounts
- This will affect what our service offerings

**Definition of done**
- "maybe we do it, maybe we don't, but at least we have a story to tell people who ask for it"
- 60 minutes meeting define a pattern for a team who only wants to use S3
- Max, Warren, Jon, Julian, Kevin
- Create tickets to create the necessary OU's if necessary

**Comment by wrnu** [comment]
not relevant
