### ISSUE TITLE
Tech Onboarding for Business Communications Solutions

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1804]
**Describe the issue**
Tech Onboarding session for Jeremy B and his team. Search "Business Communications Solutions" in the CRM app

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Deploy and give access to new project set
- Tech onboarding session for Business Communications Solutions team

**Comment by ActionAnalytics** [comment]
The team wishes to complete the install of the demo app

**Comment by MaxWardle** [comment]
Tried deploying container based sample application with this team and could not, need to debug what the issue is
