### ISSUE TITLE
Team design on New Pattern for organizing Azure before SEA

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1805]
**Describe the issue**
Azure is getting messy, we need to be able to see new workloads and have a clean way to sort/store them.  We want to plan how this would fit with a future Azure SEA/ECF pattern.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- 1 hour meeting where Jon shows the nature of the current problem, shares proposed solutions, and team discusses with respect to SEA fit (or cutover)
- In the discussion will be Jon, Max, Warren, Julian
- 30 minute meeting to refine tickets for next stages (assuming work drops out of this) and to coordinate with external resources (like Jesse's team that has key permissions needed) if needed.

**Comment by wrnu** [comment]
will be tracked in a different ticket
