### ISSUE TITLE
Team review and discussion around need for LMS-type functionality for client training (w our future CRM)

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1815]
**Describe the issue**
Discussion and investigation into a possible Learning Management System (LMS) that could help us not only automate the training\documentation update process for current and future clients, but also to re-distribute the training responsibility out from entirely our team to client teams

**Additional context**
There seems to be an indication from our own public cloud group client training management situation, along with the private cloud group (Digital Academy) that there is a possible common component solution to both.  LMS solution, or LMS-like (ie. Salesforce 'content management' component additional) would have to integrate into our new CRM platform (Full CRM coming: possibly Salesforce, MS Dynamics online, etc.) to become an integral part of regular client management functionality. 

**Definition of done**
- Meeting 1: 1hr - Bring team together to discuss what type of LMS functionality could be most useful, and whether we simply need Content Management module or a full LMS w distributed team management capability (Client project owners manage their own teams learning process, in accordance to the standard and material that we provide 
- Discuss whether we might need custom\type training additions\limitations in accordance to the type of project\team this is (ie. Application team, Cloud Infra-only project team, Cloud Storage use only, Billing-only type of request, etc.)
- Outcome: a diagram suitable for sharing with other teams like Digital Academy and others
- Create well formed additional tickets may be required

**Comment by wrnu** [comment]
this is a larger initiative and can be tracked in other work.
