### ISSUE TITLE
Review of contract documentation for Public Cloud services in order to advise CLBC on privacy compliance.

### ISSUE THREAD

**Issue by fastaudra** [bcgov/cloud-pathfinder#1816]
**Describe the issue**
CLBC asked OCIO to provide guidance on the appropriate privacy terms for their contract with a vendor to provide public cloud services.

**Additional context**
CLBC approached OCIO to onboard to the Managed Public Cloud in the pilot stage and OCIO was not ready to onboard external public sector organizations at the time. A commitment was made to support CLBC with advice on their requirements for privacy and security once CLBC had selected a vendor via a procurement process. CLBC has specifically requested that a comparison of the vendors proposed Enterprise Agreement is reviewed for privacy compliance.  PCT provided some high level advice but is not prepared to do the necessary legwork to review the vendor's proposed terms.

Originally we sent CLBC away when they asked us for cloud space.  CLBC did their own procurement.  We committed to sharing the Privacy and Security compliance.  Took a long time to get the NDA in place.  We are not allowed to share our terms as these are GoC terms under our own NDA.  

OCIO gave them the CSS and Privacy Cloud Schedule.  The vendor has provided comment on these.  We need to do a 4 way comparison in order to provide them advice whether their contract is ready to go.

Terms from Privacy Protection Schedule, AWS' Feedback, make a new third column for the EA, other comment from SSC, risk evalution, final column his (OCIO) comments (eg, this is aligned to terms in cloud agreement)

**Definition of done**
- obtain the documentation from CLBC: Vendor Enterprise Agreement, CLBC Table of commentary on Privacy Schedule
- obtain the GC Framework Agreement and relevant Annexes (A, D) - especially Annex A Schedule 1- Security Obligations and Schedule 2 - Privacy Obligations; and the Additional Terms to SO for the BC Government, and Indemnity (memorandum)
- Review the documents for comprehension and to get a sense of the work estimate for planning.

**Comment by ActionAnalytics** [comment]
We will need to break this up @OmoAttah , we can 1:1 and help Gary as this seems to be a bigger piece than expected
