### ISSUE TITLE
CP Forward Proxy for Cloud+service testing\troubleshooting 

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1817]
**Describe the issue**
A clear need has been identified for a blacklist-based Forward Proxy service, that CP can rely on for testing and troubleshooting, since the previous test instance run by SecOps was shut down.  Currently the BC Gov does not have an OCIO run Blacklist-based Forward Proxy service (current is whitelist only)

**Additional context**
Current on-prem service run by DXC is a whitelist based service that even if viable required the slow process of submitting iStore's even when outbound service calls\types are unknown, and also involves DXC unnecessarily.  Note that Forward Proxy service is for server outbound calls only - a service calling it service source for version updates, or other functionality (calls originating outside on the Internet still cannot reach inbound).  

Once troubleshooting has been completed and all know outbound server-based service calls to public side Azure service endpoints are known and tested, a client can then be instructed to establish the longer term solution by way of them creating an iStore\MySC service ticket that has DXC managed service technicians configure the Province's F5 based Forward Proxy service with a whitelist that covers these or a custom whitelist for this purpose.  

Also an additional capability should be added to the CP temp Forward Proxy service\server that ensure we can trace all calls\call types going through it - as easy post-analysis to confirm what exactly is needed for the client so they can submit their istore for the OCIO Forward Proxy whitelist service (Wireshark, or possibly simpler tool that quickly reports current activity)

**Definition of done**
- Discuss issue at hand
- Create near-term solution plan
- Explore possibility to establish a temp blacklist-based FP solution and then change it to whitelist service as needed to test conclusions and proposed configuration to be permanently established using OCIO FP service
- Review possibility of longer term add-on or replacement solution (per cloud solution, or single solution such as this)
- Order DMZ-based on-prem server or use existing if already owned
- Create Forward Proxy instance on server, with desired config and tools
- Create access for all CP tech folk

**Comment by lukegonis** [comment]
Closing this as all multi-cloud work will take place after the second cloud PaaS is available
