### ISSUE TITLE
To Get Terraform Cloud STRA & SoAR Signed Off

### ISSUE THREAD

**Issue by bruce-wh-li** [bcgov/cloud-pathfinder#1820]
**Describe the issue**
Complete TFC STRA and SoAR v1.0 and get signed off.

Living document, point in time assessment (snapshot)

**Additional context**
- Nick is away on vacation back July 19 and we need his help to finalize this (not enough time in July 4 - 22 sprint, will do the sprint after)
- Assume TFC is the only way to deploy to AWS for the future
- If/when we have a new pattern, we will create new revisions to STRA/SoAR docs

**Definition of done**

- Complete STRA and SoAR
- Share with PO, Nick and Tech Team 
- Incorporate review comment 
- Get STRA and SoAR number from IMB
- Submit for Approval

**Comment by ActionAnalytics** [comment]
not enough time in July 4 - 22 sprint, will do the sprint after

**Comment by ActionAnalytics** [comment]
There's no rush to get this signed off, it's just for our own peace of mind

**Comment by ActionAnalytics** [comment]
Review meeting booked
