### ISSUE TITLE
Mechanism for deploying developed tools to Core OU accounts

### ISSUE THREAD

**Issue by unoah** [bcgov/cloud-pathfinder#1823]
**Describe the issue**
- We need to develop a standard deployment approach for tools developed internally by the CPF team
- One of the POCs reviewed was developed around the billing utility
- It will be beneficial for the team to have a general solution that is not tied to a single utility

**Additional context**
There are two approaches being considered:
###### Distributed Services Model
- In this model, Terraform state file, OIDC Identity Provider and associated role exists on each AWS ECF Core OU account.
- This model provides multiple entry points for deployment to the AWS ECF -- one for each Core OU account. - Depending on the permissions model used by the OIDC assumed role, complexity on this approach would increase with added Core OU accounts and deployed resources. 
- An illustration of this model with the Core OU accounts: Operations and Management is presented below
![distributed_services_model.drawio.png](https://images.zenhubusercontent.com/615b61049dea840b7e0abf1b/29302c79-a3ce-4093-8b4f-a35aabe4fbd0)

###### Shared Services Model
- For this model, Terraform state file, OIDC Identity Provider and associated role exists on a single AWS ECF Core OU account (eg: operations account). 
- This model provides a single entry point for deployment to the AWS ECF -- deployments to other account will be using cross account role permissions.one for each Core OU account.
- Terraform state files for all Core OU deployments will be saved in a single account
- The IAM role associated with the OIDC Identity Provider will need cross account permissions in order to deploy resources to accounts other than the one hosting the OIDC Identity Provider and role.
- An illustration of the shared services model with the Core OU accounts: Operations and Management is presented below
![shared_services_model.drawio.png](https://images.zenhubusercontent.com/615b61049dea840b7e0abf1b/5d9e15e9-4c3b-4754-8f4a-665c6b6f8c3d)

**Definition of done**
- Identity which model we'd adopt
- Ideally, review and identify how tradeoffs on each model affects the team. Few areas that come to mind: 
  - Permission boundary for deployment roles in target Core OU accounts
  - Implications with troubleshooting failed deployment
  - Kill switch option (easier with the shared services model)
- Implementation of model agreed on

**Comment by ActionAnalytics** [comment]
Nice to have, not urgent at the moment

**Comment by wrnu** [comment]
not relevant
