### ISSUE TITLE
New Legal Review on options for closing procurement legal risk

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1826]
**Describe the issue**
We are rejecting the legal opinion as we did not provide enough background info and set the context for the opinion.  We wish to get consensus with legal so this is a new tact.  This is about the supply arrangement about the cloud services from the GoC brokerage.

**Additional context**
- Very high priority for us to get this support and alignment

**Definition of done**
- Email legal, requesting legal opinion
- Amend current process diagram with Bahaa (see related ticket)
- Meet with legal and provide walk-through of how the process works (hopefully one and done)

**Comment by fastaudra** [comment]
Amended legal review received with recommended options for closing procurement legal risk on 5 August 2022.
