### ISSUE TITLE
Service Design refresh of Ordering Through Cloud Brokering Service diagram

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1827]
**Describe the issue**
Audra needs to go to legal and train Ya-Shin, so this Service Design refresh of Ordering Through Cloud Brokering Service diagram will be helpful

**Additional context**
- Julian thinks that the old diagram might need a complete redo

**Definition of done**
- Retrieve the old diagram file from teams (likely in Paul's files and goodies)
- Connect with Audra to update it to reflect the current/actual process
- Test with Ya-Shin and Audra, then over to Audra for legal

**Comment by wrnu** [comment]
not relevant
