### ISSUE TITLE
Apply new containers github repo structure and workflows to Serverless demo app repo

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1828]
**Describe the issue**
Compare the new workflows from the containers app last sprint with the existing serverless app and try to port over as much common utility as possible.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Re-implement as much as possible from ticket 1744 and clean up the Serverless app deployment workflow if possible.
- Add deploy test and prod to serverless
- Aim for consistent workflow, given one is terragrunt and one is terraform

**Comment by wrnu** [comment]
not relevant
