### ISSUE TITLE
Containers Demo app new environments for Pull Requests

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1835]
**Describe the issue**
PR-based pipelines are valuable because they allow hotfixes to jump over other PR in a traditional sequential pipeline.  This will help teams get to a performing state rather than present each team with the task of solving this problem themselves.

**Additional context**
![PR Based Pipeline vs Blocking Pipelines.drawio.png](https://images.zenhubusercontent.com/5e98c26e92d4be32d8e29cb0/4535f676-7298-4623-bf46-a7e6859881f3)
- Blocked by current CI/CD pattern, might need new OIDC pattern or some equivalent

**Definition of done**
- Get sample code from github bcgov from other teams doing PR based pipelines already (in OCP)
- Figure out pattern around 1:1 TFC Env to Workload Env, or TFC workspace per PR
- PR would have it's own subdomain (naming convention something like "my-appname-pr-34")
- Environment destroyed on PR closed
- Ability to skip deploy

**Comment by ActionAnalytics** [comment]
Probably better if we wait until we know if the GitHub OIDC approach is suitable to replace TFC, because we would need a lot of TFC environments if we implemented this pattern

**Comment by mitovskaol** [comment]
@Sana Please check with the team if this ticket is still relevant and document the decision in a comment.

**Comment by wrnu** [comment]
not relevant
