### ISSUE TITLE
SPIKE: How would we take over from a team using GitHub Direct CI/CD Pattern

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1838]
**Describe the issue**
With TFC, we have the ability to take over a team's deployments if something goes wrong with the team (possibly a bad handover between an old team and a new team).  This is the "Break Glass" option in the diagram we're workshopping in the related ticket.

**Additional context**
- Not nuking, this is for if a team "smoke-bombs" and disappears but their workload is considered important enough to continue without service interruptions and we have to get involved 

**Definition of done**
- Talk to Warren as he has ideas
- A documented set of steps outlined in a word doc stored in Teams that we would present at the next CI/CD internal pattern workshop

**Comment by unoah** [comment]
Added writeup to the CPF-1838 subfolder under the "Research & Documentation" folder in MS Teams
