### ISSUE TITLE
Security review of GitHub Direct CI/CD

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1841]
**Describe the issue**
We are proposing a new CI/CD pattern for deploying to AWS from GitHub. Review the security of the GitHub CI/CD architecture.

**Additional context**
- requires our architecture to be done first, the demo app working example, and the documentation for the users so that security can validate the ease of use of the documentation
- https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

**Definition of done**
- Identify any security risks to this architecture

**Comment by OmoAttah** [comment]
No longer relevant - Olena
