### ISSUE TITLE
SPIKE - Quick assumption check that GitHub actions better than AWS pipeline

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#185]
**Describe the issue**
We want to make sure we are choosing the pipeline with the least amount of vendor lock-in and the best capabilities for our future dev team's needs.

**Which Sprint Priority is this issue related to?**
Milestone #2

**Additional context**
- We have working GitHub Action code over in our bcdevops/managed-ocp repo.
- Ryan J has offered us workshop on AWS pipelines

**Definition of done**
- A short minimally technical powerpoint slide on which pipeline is best for our future clients (using the current Demo App as a test case)

**Comment by sheaphillips** [comment]
For reference: https://www.terraform.io/docs/github-actions/setup-terraform.html
