### ISSUE TITLE
Generate Report of all AWS Assets via CSPM

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1858]
**Describe the issue**
Hackathon fun ticket - be creative, have fun

We want either a live filterable dashboard view in CSPM that shows us our entire cloud asset posture for Workload Environments, or a denormalized filterable Excel export similar to our weekly billing report excel spreadsheets.

**Additional context**

**Definition of done**
- Create an essentially a nice looking landing page dashboard view in CSPM that shows the known types of assets
- Ask support and try to export the data behind the above view in some format (csv, json, xml).  Explain to support that the UI supports export but there doesn't seem to be an API.  It's ok that the dashboard exist alone and is never exportable, we're just checking because this is a nice to have.
- If the above isn't possible, the data source of the view is something like get-protected-assets, so see if we can export or get a snapshot of this dataset. We don't care if there is no API at the moment, it is fine to do manually.

This was the original ask that was impossible:
- a live filterable dashboard view in CSPM that shows us our entire cloud asset posture for Workload Environments, or a denormalized filterable Excel export similar to our weekly billing report excel spreadsheets.

**Comment by unoah** [comment]
Tested presenting extracted data using a local metabase instance. Validated we can also retrieve data from via API calls.
