### ISSUE TITLE
Create first draft of CSS

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1864]
**Describe the issue**
A whole lot of effort has recently gone into a new consensus-driven approach to the CSS in order to get multi-stakeholder buy-in.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Consolidate the stakeholder feedback into a new draft version of the CSS
- Review first with Suzanne
- Review with PO, Bruce, and Gary
- Review with Security team

**Comment by ActionAnalytics** [comment]
Still at the review stage, meeting booked this sprint to review with me

**Comment by ActionAnalytics** [comment]
Waiting for time with Don.

**Comment by OmoAttah** [comment]
closing this ticket as I confirmed from Bahaa, who noted that:
the security team has been given the first draft in mural
