### ISSUE TITLE
FOIPPA Documentation on how Ministry Teams in the AWS ECF can use US services

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1866]
**Describe the issue**
Teams will need a clear guide to how to acquire and consume FOIPPA compliant US AWS services 

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Create a small draw.io diagram showing the steps needed to enable US cloud services in the BC Gov ECF
- Author a markdown file for including in the pre-reading material
- Get another teammate to review the work (QA for spelling, content, brevity, flow)
- Review the material with the PO
- With the help of a teammate, add the file to the pre-reading material in GitHub

**Comment by wrnu** [comment]
not relevant
