### ISSUE TITLE
Lightweight Azure Billing assistance service

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1870]
**Describe the issue**
When a team like CiTv4 comes to us asking for help organizing their billing dashboard, accounting in cloud, we want to be able to quickly show them how to self-serve find the info.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Create a video using either Azure Phase II or our own Azure Dev (playzone) that shows a non-technical expense authority how to direct their technical team members to get the cost usage info easily for themselves using Azure's interface.
- Use the example training videos like Prabhu's video in Teams, General, Files, Workshops and Accelerators for Partners, Training Videos, Howto-Magic-Wormhole or Health Billing Example

**Comment by wrnu** [comment]
This will be covered in future tickets
