### ISSUE TITLE
Define a new Billing policy

### ISSUE THREAD

**Issue by crochcunill** [bcgov/cloud-pathfinder#1882]
**Describe the issue**
See _#1872 BillingViewers cannot view the Cost & Usage Reports subsection of AWS Billing_
One of our users (Andrew, ITSTRAT team) complained that he can not create AWS Cost and Usage reports. 

Looking at the policies, we associated the billing accounts to the **_BCGOV_WORKLOAD_billing_License Plate_** role, and this role has only one permission                 
> aws-portal:ViewBilling

However, the standard AWS **_Billing_** permission policy has the following permissions:

> “aws-portal:Billing”,
> “aws-portal:Usage”,
> “aws-portal:PaymentMethods”,
> “budgets:ViewBudget”,
> “budgets:ModifyBudget”,
> “ce:UpdatePreferences”,
> “ce:CreateReport”,
> “ce:UpdateReport”,
> “ce:DeleteReport”,
> “ce:CreateNotificationSubscription”,
> “ce:UpdateNotificationSubscription”,
> “ce:DeleteNotificationSubscription”,
> “cur:DescribeReportDefinitions”,
> “cur:PutReportDefinition”,
> “cur:ModifyReportDefinition”,
> “cur:DeleteReportDefinition”,
> “purchase-orders:PurchaseOrders”

The two policies that start with cur (Cost Usage Reports) are the ones that will grant the permissions to create cost and usage reports.

So, the easy path to grant Andrew the capability to create a Cost and Usage reports is to add the Billing role to the account, however, as Warren pointed out. the Billing role currently grants permissions like 

> “aws-portal:PaymentMethods”

in addition, it has modified some AWS template permissions adding wild characters, for example
>"aws-portal:*Billing"

In this context, this task is to define a new **_BCGOV_WORKLOAD_billing_License Plate_** role that will allow users to create reports but prevent them from changing, for example, the payment method

**Definition of done**
A list of the policies for the **_BCGOV_WORKLOAD_billing_License Plate_** role

**Comment by ActionAnalytics** [comment]
Yes we want to do this
