### ISSUE TITLE
Replace the existing Billing-Viewer policy with the new one

### ISSUE THREAD

**Issue by crochcunill** [bcgov/cloud-pathfinder#1883]
**Describe the issue**
Associate the new permissions to the _**BCGOV_WORKLOAD_billing_LicensePlate**_ accounts so the users, in addition of being able to View existing reports, can also create Cost and Usage reports.

The new permissions have been set by ticket #1882

**Additional context**
Check the following tickets
- Requires Warren
- Define a new Billing policy#1882
- BillingViewers cannot view the Cost & Usage Reports subsection of AWS Billing#1872

**Definition of done**
- The new policies are associated to the role
- An account with **_BCGOV_WORKLOAD_billing_LicensePlate_** role can view existing reports and create new ones.

Note: 
After implementing this change, connect back to Andrew D (ITSTRAT team, search the CRM for that term) to communicate the problem he reported has been solved. An alternative way to contact him is by Rocket chat,  #aws-tenant-requests thread started July 8 2022, get him to test the solution so he's unblocked

**Comment by prabhukiran9999** [comment]
- Scoped out the policy required 
- The Policy requested by the team is bit strong to attach it to the billing_viewer policy, So we decided not to change the existing policy
