### ISSUE TITLE
Update the CPF training material after switching to the new IaC pattern

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#1884]
**Describe the issue**
- We have decided to transition from Terraform Cloud to GitHub OIDC to manage the IaC. 

- The current training material needs to be changed to reflect this transition.

**Additional context**
- Prabhu had made a list of training materials that needs to be changed with their location on teams and stored it in the 
   Reaserch&Documentaion folder on teams.

**Definition of done**
- Create the draw.io (stored in Teams) architectural diagram explaining the new approach
- Update the material(PPTs, PDF, etc.) with the respective architectural diagrams and slides.
- Update the pre-reading material site with the new changes.

**Comment by lukegonis** [comment]
This is work has been completed/duplicated in other issues.
