### ISSUE TITLE
Get Access to BC Gov Systems

### ISSUE THREAD

**Issue by OmoAttah** [bcgov/cloud-pathfinder#1885]
**Describe the issue**
Onboarding to various platforms and tools.
As the scrum master of this team, I would require a list of systems so I can work effectively with the team.

The value proposition of this ticket to the service is that the team needs to grow and part of that is to onboard new team member and at the same time train them to onboard others.

**Additional context**
- I haven't received my machine yet
- Omo needs to pay extra attention to this because she would be involved in onboarding new people the same way

**Definition of done**
- Able to create a ticket in ZenHub
- Able to communicate with the team on rocket chat
- Able to access MS Teams channel
- Able to access the training material on MS Team
- Take notes about improvements that could be made to the onboarding experience
- Note should be in a word document in our teams onboarding training folder - Talk to Julian for info

**Comment by ActionAnalytics** [comment]
Omo has successfully created her first ticket
