### ISSUE TITLE
Place an order with AWS Snowcone

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1887]
**Describe the issue**
There is an expected two week lead time for ordering AWS Snowcone and getting the device shipped.

See the CRM search for "Health Insight" for who to talk on this ticket (Neil S, Rick C, Sorin P).

**Additional context**
- Will require collaboration with ADSL
- Who handles receipt of the device
![AWS Snowcone Sneakernet.drawio.png](https://images.zenhubusercontent.com/5e98c26e92d4be32d8e29cb0/617b20aa-b4f2-42a2-a33b-773611824092)

**Definition of done**
- We need an exact delivery date
- Cloud Pathfinder to speak to AWS rep and ask for support at their end
- Have Ryan J join the initial meeting with ADSL in order to shortcut any concerns

**Comment by mitovskaol** [comment]
This work will be tracked in other tickets as the scope changed.
