### ISSUE TITLE
Aid Health with iStore submision

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1888]
**Describe the issue**
In order to submit the iStore ticket, we need to determine who will be able to receive the device in Calgary.

We need someone at ADSL or hosting services with physical access to CDC in order to receive the AWS Snowcone device.  See the CRM search for "Health Insight" for who to talk on this ticket (Neil S, Rick C, Sorin P)

**Additional context**
- high priority
- UPDATE: The Team has sent the ticket to Istore
- The CDC is managed by Equinix
- Health intends to use a real dataset from Calgary (the data quality extract)
- The DXE and hosting folks will not have likely seen a device like this before.  They will have questions
- SecOps might get pulled in as well.  CPF currently has a good relationship with SecOps and we think we may be able to get support quickly (hopefully).
![AWS Snowcone Sneakernet.drawio.png](https://images.zenhubusercontent.com/5e98c26e92d4be32d8e29cb0/c64cd48c-293c-4647-978e-beef1bd8a823)

**Definition of done**
- Meet with Julian and Sorin P to share the settings with Sorin, have him create the ticket in his name (because there are charges associated with the ticket) (DONE)
- Help Health create iStore ticket (ask for 20h consultation - they will quote), meet DXE (via the iStore process)
- We need a name and an address to ship the device to
- We need an exact delivery date
- We might need a service request in iStore or ServiceNow (we want to try avoid iStore and ServiceNow for as long as possible instead reaching out directly to Directors in Hosting - CPF is finding that a lot of tickets are getting lost at the moment)

**Comment by jon-mc-git** [comment]
See ticket #1930 - confirming this and will proceed accordingly once reviewed on provider's end and summary info received

**Comment by ActionAnalytics** [comment]
Kevin worked on this and got the draft iStore over to Sorin & co in Rocket Chat channel.  We are waiting for Rick C to add some team members to the channel to provide their feedback on the iStore ticket.  Sorin is away on holiday.

**Comment by ActionAnalytics** [comment]
@jon-mc-git to please get up to speed after vacation with the Rocket Chat conversation and reconnect with Sorin to let them know we're still here for them

**Comment by jon-mc-git** [comment]
Got update and ADSL should have proper folks in by next week to get us the needed info

**Comment by ActionAnalytics** [comment]
The diagram might be out of date as we've heard now that the data could be coming from Kamloops

**Comment by jon-mc-git** [comment]
Some key ADSL have been away but they have now brought this up among their team and are reviewing how this could be done within their current high security procedures and considering locations necessary within their network infrastructure to allow large transfer rates yet apply considerations for limiting port\connectability for this and possible future cloud data transfer situations.

**Comment by ActionAnalytics** [comment]
Brian P is our main contact in Technical Stewardship

**Comment by jon-mc-git** [comment]
Hosting is held up with Advanced Solutions currently on figuring out a solution for this and future requests of the same type (data extraction from DC's by way of data boxes - procedures\processes, security, etc.)

**Comment by jon-mc-git** [comment]
Service development is in process by OCIO - Still in works

**Comment by jon-mc-git** [comment]
This has been unblocked now that the Snowcone service is being kickstarted.  This topic has advanced with Health and meetings have been scheduled to move things forward.  Have discussed elements of what was needed here with Health and they will be working with Hosting for any remainder questions around this.  Closing ticket
