### ISSUE TITLE
Mounting and access of Snowcone for Health Insight

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1889]
**Describe the issue**
We need to connect, power up, and ensure that configuration.  See the CRM search for "Health Insight" for who to talk on this ticket (Neil S, Rick C, Sorin P).

**Additional context**
- https://docs.aws.amazon.com/snowball/latest/snowcone-guide/snowcone-getting-started-snowcone.html
- Daniel S will be focused on this
- As soon as it is connected it will give an IP and other settings, we will need someone physically there
- Assumption: the 45w USB-C PSU is lying around the CDC and is on site.  Or a portable battery.  
- An ethernet cable is required (guaranteed on site already)
- We may need a subnet to the server room (if they don't put it in the subnet, or the incorrect one, the scope of this work will be a lot more)
![AWS Snowcone Sneakernet.drawio.png](https://images.zenhubusercontent.com/5e98c26e92d4be32d8e29cb0/550e6985-1fdd-4a9d-9d2d-071f0c146cb6)

**Definition of done**
- Need an IP (no DHCP, will require one assigned), need someone to set that up on the device
- Acquire and supply a 45w USB-C PSU that is not included - we need to provide
- Someone is required to be there to read the IP and settings (Noel for IMT has gone through this and is not here for DoD writing, we're assuming a couple hours)
- Communicate to IMT who will be logged in to a console at AWS and connecting from there
- It will need to be mounted on a subnet (talk to Neil for details)
- NFS Mount

**Comment by wrnu** [comment]
not relevant
