### ISSUE TITLE
Return Snowcone device once the work in the CDC is done

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1891]
**Describe the issue**
Once the transfer of Health Insight data from the CDC to AWS is done, the device needs to be sent back to AWS.

**Additional context**
- Someone on the Health Insight project team will need to communicate that the transfer was complete. (could be 1 - 5 TB)
![AWS Snowcone Sneakernet.drawio.png](https://images.zenhubusercontent.com/5e98c26e92d4be32d8e29cb0/07d74ba5-d55a-48cc-b9fe-dc79f05a2c27)

**Definition of done**
- Get the address and details for shipping
- Whoever is on site at the CDC (see dependency tickets) pack up and ship the device back to AWS
- Close off and return any items to Hosting/ADSL/Equinix staff that we borrowed (PSU, cables, etc)

**Comment by mitovskaol** [comment]
This work is tracked in other tickets
