### ISSUE TITLE
Close accounts in the Ignored OU

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1892]
**Describe the issue**
In AWS ECF Prod we have several accounts in the ignored OU that we want to close (delete).

**Additional context**
- Previously accounts needed to be closed using the root account.
- There is now a CloseAccount API
  - https://docs.aws.amazon.com/organizations/latest/APIReference/API_CloseAccount.html
- These accounts are separate from our IaC so we're handling them as one-offs

**Definition of done**
- (We think) log in to the root account via the API, run delete once per account (5 accounts)
- All accounts in the ignored OU are closed using the API
- Make rough notes and use knowledge to help with 1861

**Comment by MaxWardle** [comment]
Closed all accounts in ignored OU in LZ0, LZ1 and LZ2 via the web console. Possible from the AWS organizations console.
