### ISSUE TITLE
Define SecOps processes in relation to managing cloud firewalls

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1894]
**Describe the issue**
CPF is strong in IaC and DevOps around cloud based infra, whereas SecOps bring to the table strength in policy updates and cross firewall management.  We want to combine the two without affecting production stability.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Meet with the CPF team for 30min (Jon, Bruce, Max, Warren, Julian, Gary)
- Create a draw.io diagram outlining the proposed approach
- PO to bring the approach forward in the tri-weekly secops meeting, gather feedback.

**Comment by bruce-wh-li** [comment]
Jon is away for first 2 week of Aug and Julian will be on leave in 3,4th week of Aug as well.

**Comment by bruce-wh-li** [comment]
Let's have a mural meeting tomorrow Aug 11th.
