### ISSUE TITLE
Service design blueprint for Azure

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1898]
**Describe the issue**
We have AWS in our service design blueprint, but not Azure

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Initialize the board
- Meet with Jon, Julian and extract onto the board the info they have in their brains as tiles on the board
- 3 x 1hr meetings

**Comment by wrnu** [comment]
not relevant
