### ISSUE TITLE
Service Design Blueprint started for GCP

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1899]
**Describe the issue**
We have AWS in our service design blueprint, but not GCP

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Initialize the board, copying over the AWS board (if the AWS board isn't available to copy, we can make a fresh one)
- Pull in Bahaa to work together on this
- Meet with Julian and Jon and extract onto the board the info they have in their brains as tiles on the board
- book 3 x 1hr meetings with Julian and Catherine
- At the end of the sprint, the board is not finished but starts to accurately describe the current processes over in GCP

**Comment by gautammalhotra21** [comment]
Session 1 - Cancelled
Session 2 - Julian, John, Gautam and Bahaa Attended

**Comment by ActionAnalytics** [comment]
Closing for now.  Will create new tickets for future sprints
