### ISSUE TITLE
Remapping draft billing process diagrams into easy to understand visual

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1900]
**Describe the issue**
There are some diagrams from a meeting between Finance, Admin, and PO that outline the current AWS billing structure.  We want to create a long lived resilient diagram that shows the process and identifies opportunities for efficiency.

**Additional context**
- Missing from the draft diagram is the parties involved, the flow of documents between these parties, most importantly the areas where this goes wrong (eg. no way to see if a bill actually got paid or not)
- Recent situation where bills not getting paid for 4 months and we had no idea because they're in another department.
- Major painpoint because vendors unhappy and it's a lot of manual work for CPF to track down missing payments

**Definition of done**
- 1 hr meeting with CPF Admin, Finance, PO, SM.  Go through process & understand how documented and how it works (cross train SM).
- Updated diagrams stored in Teams diagrams (draw.io or powerpoint format)

**Comment by wrnu** [comment]
not relevant
