### ISSUE TITLE
Billing Utility knowledge transfer

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1901]
**Describe the issue**
The deployment of the billing utility to LZ0 and LZ1 was manual and there is a fair amount of knowledge with Ukeme at the moment.  Since Ukeme is leaving, we would like to pass this knowledge on to the team for the next work.

**Additional context**
- keep S3 as we fixed the name conflict collisions in S3 buckets
- when performing deployments to LZ2, a new bucket will be created for generated reports, however original bucket will be kept for historical archive purposes.
- the repository is already documented

**Definition of done**
- this has to happen the first week of sprint before the 29th of July
- 3 hrs of meetings to walk Kevin, Prabhu and Max through the deployment in LZ0 or LZ1, running reports
- Document as much as possible along the way either in the repo itself or in the cloudops private repo
- Dev on the team is familiar with deploying the billing utility on any of the landing zones.
- The next dev is conversant with running manual billing report generation
- When phasing out the old billing mechanism in LZ2, dev is familiar with resources that need to be removed or replaced.  Clean up the older resources and remove ones with similar names.  Remove glue crawler (now handled by terraform IaC), athena components)

**Comment by unoah** [comment]
Had 1 hour meeting on Monday. Provided a high level overview of the revised design. Second meeting scheduled for Tuesday, July 26.

**Comment by unoah** [comment]
Had additional meetings on the 26th and 27th. Validated manual deployment to LZ0 and also generating reports for arbitrary time frames. Closing on that note.
