### ISSUE TITLE
Make checkov work in the Community Version without a "spammy" first experience

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1903]
**Describe the issue**
We want the new cloud developer to have a simple path to using the Infrastructure as Code (IaC) scanner in checkov.  

The value proposition is that Bruce's dev environment is dirty and he needs a clean environment to create a clean checkov implementation.

Checkov provides missing coverage to scanning the IaC portion of the demo app cloud deployment pipeline.

**Additional context**
- Bruce says that there it is possible to use checkov without signing up in CI/CD mode
- He also says that once signed up, checkov's company Bridgecrew team will contact the email provided with a fair amount determination (do you need help, demo, etc with the obvious intent of signing up new paying customers)
- There is a prompt to "Level Up" to cloud edition, we don't want this.  We want a clean implementation

**Definition of done**
- Reach out to Prabhu and have him share his info about checkov (he's done some work too)
- Spin up a clean environment to using either VirtualBox or docker locally, or ask the team for a temporary lab account in AWS with a throwaway VM scoped only for this work (and then discarded right after).
- Take a snapshot of the clean environment before experimenting so you can save time and revert
- In the clean environment, create clean community version based checkov demo
- create a video to share with team

The main goal is to have checkov not be a confusing experience for new devs when running the demo app.  Not a "wall of red".

**Comment by bruce-wh-li** [comment]
It appeared that after remove api key under .bridgecrew, you can remain using checkov locally as community version.   The TF can be modified to suppress the check checking that will be enforced by ASEA.
