### ISSUE TITLE
Create automated test scripts to poke the guardrails

### ISSUE THREAD

**Issue by crochcunill** [bcgov/cloud-pathfinder#1914]
**Describe the issue**
Currently I have a collection of tests that using the AWS API retrieve data from AWS, like the number of accounts, the number of policies... This script uses an account with admin rights in the corresponding LZ

Another script that I have in mind is to use a common workload account, like dev and try to execute actions that are not allows, for example create a new EC instance. In this case the expected result is not possible. Another test can be to create a S3 bucket, that I think is possible.

Ticket 1923 will compile the list of rules to be checked, this ticket is the creation of a test suite that will probe each of the rules in the list.

**Additional context**
This test checks the guardrails from a workload account user point of view

**Definition of done**
- Test scripts (one or more) that using  workload account credentials will be able to poke different guardrails rules checking if they are allowed or not. 
- The scripts can save the result in a json file format and this file can became part of the guardrail-snapshot folder that describes the state of the snapshot in that moment in time
- If possible, create a template that will facilitate future extension
- Iterate the script using different accounts and different roles in the account
- Documentation

**Comment by ActionAnalytics** [comment]
The vending machine / project-set creation is blocked pending some automation.  We don't care that the entire test is a mix of automation and manual steps.  So ok to do this

**Comment by crochcunill** [comment]
Before executing this task, make sure you have a list (even if it is a partial list) of rules to be tested.

Also make sure the prototype (#1676) is done and hopefully can be templated, so it would make it easy to add more rules to the list of rules to be tested.

**Comment by crochcunill** [comment]
Script and associated files created. Files can be found in the following repo: https://github.com/bcgov-c/aws-ecf-probing-scp

**Comment by crochcunill** [comment]
Script and associated files created. Files can be found in the following repo: https://github.com/bcgov-c/aws-ecf-probing-scp
