### ISSUE TITLE
AWS Billing auto-messaging troubleshoot 

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1916]
**Describe the issue**
User getting auto-sent AWS billing messages and does not know why they are still receiving them.  Would like to be removed.

The user is the former Admin Andy T. which had LZ access at one point and is likely on a mailing list.

**Additional context**
Should see where the user got added and understand how best to 

**Definition of done**
- Investigate where user was added to AWS billing
- remove user from auto-email list
- PO to meet with Dana to check mailing lists
- Jon to get AWS access, Julian to share how to find where this is originating from

**Comment by ActionAnalytics** [comment]
Duplicate, already done in different ticket
