### ISSUE TITLE
Summarize the GCP Contract data privacy clauses

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1917]
**Describe the issue**
NRIDS privacy has questions about Google using data for training general Google AI.  We want to get up to speed on the Google privacy clauses in the contract about to be signed and summarize it for the Wildfire Team (context search the CRM for "Wildfire Service").

**Additional context**
- CPF had a meeting with GCP and they confirmed they use their own photos for training AI/ML, not GCP customers.  

**Definition of done**
- Acquire a copy of the draft about-to-be-signed GCP contract from Audra
- Read and review the privacy clauses around the use of customer data
- - find the section where it says "We Google will not use your data, we don't even have access to your data, here is why: control 1, control 2,..."
- Create a brief summary to be for the ministry team audience that has heard rumours that Google will use all data to train their AI, stored in teams under the Privacy section, in a word doc or powerpoint.
- Review with Jon

**Comment by ActionAnalytics** [comment]
We were provided a couple paragraph excerpt of the GCP contract privacy terms that was enough to unblock us but to be clear, Gary never got access to the GCP contract privacy terms

**Comment by garymatics** [comment]
Summary completed. Discussed summary with Jon and feedback received.
