### ISSUE TITLE
AWS Billing and automation review

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#1918]
**Describe the issue**
A better understanding around billing is needed, and Jon would like to review this process - especially around current and possible future automations

**Additional context**
Cumulative billing, billing history, Qualified Receiver verifications processes and automations for AWS are of particular interest here

**Definition of done**
- Review current billing structure of AWS with PO and SM
- Jon would like to review and understand where the automation(s) are, and better understand the whole process
- Jon to discuss, compare and contrast billing in Azure with current AWS process
- Review current state but also what is to be improved or should likely be improved

**Comment by wrnu** [comment]
not relevant
