### ISSUE TITLE
Improve the security of the credential usage of the guardrail scanner

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1928]
**Describe the issue**
Carles has a draft AWS guardrail scan using credential placeholders but they are likely too permissive.  Ukeme might have time to show an AWS SDK (nodejs, python boto3, etc)

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- new version is public in https://github.com/BCDevOps/aws-sea-guardrail-scanner
- Provide document with compiled notes and additional reference, created as a Word doc in Teams under the QA

**Comment by unoah** [comment]
Ran a demo on using Boto3 for calls to S3, IAM and also using the STS to assume roles. Provided an overview of IAM Trust Relationships, IAM roles and IAM policies.

**Comment by wrnu** [comment]
not relevant
