### ISSUE TITLE
CSS Wireframe for testing 

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#1935]
**Describe the issue**
After drafting the first CSS with the security team, we would like to try an open source wireframe to prep for testing the it with users.

**Additional context**
- Ideal is reusable format that we don't need a license (Pencil, Penpot?)
- https://alternativeto.net/software/figma/?license=opensource
- https://alternativeto.net/software/penpot/about/
- learning debt as this is a new research on the app hence estimating higher

**Definition of done**
- look for open source alternative to Figma to use and recommend for the team 
- embed the CSS in the open source
- test it and deliver
- Share it with the team in the internal sprint demo

**Comment by wrnu** [comment]
not relevant
