### ISSUE TITLE
Create a ECR Registry for AWS ECR Image scanning test in CloudGuard CSPM

### ISSUE THREAD

**Issue by bruce-wh-li** [bcgov/cloud-pathfinder#1937]
**Describe the issue**
Need to create/'find' a Private AWS ECR Registry Image in LZ2 for CloudGuard CSPM Scanning

**Additional context**
gxxxxx-dev 

**Definition of done**
- Created a Repo in new created ECR Registry 
- Launch EC2 Instance w/ Security Group, Role, Policy, Key Pair  configured
- Update bootstrap at user notes in the new EC2 instance definition and Click Review and Launch
- EC2 instance running without issue with AmazonEC2ContainerRegistry related Access 
- Follow ECR Push command to install docker community in EC2
- Create Docker Image and vi docker file such that the user directive is not in dockerfile on purpose
- Docker Push to the ECR repo created 
- ECR Repo Image should be found in CSPM

**Comment by lukegonis** [comment]
This was completed in a previous sprint, moving to closed
