### ISSUE TITLE
Draft Wireframe a new multi-cloud version of the login page

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1941]
**Describe the issue**
The login page is getting older and we have some tickets to add in new functionality, eg linking to the CSS page, countdown timer feature, etc)

**Additional context**
- depends on the choice of the mockup tool
- depends on if GCP can support keycloak
- we may with to have AWS and GCP options within?

**Definition of done**
- get access to the existing login page (keycloak setup, plus a demo project-set) via a 15 min meeting with Max or Julian
- Buddy up with Carles and get a walkthrough of all the pieces and why they are there.
- design workshop with the whole team (1 hr incl PO and SM) - factor in technical limitations
- draft wireframe a new version of the login site (an entry page plus the site inside)
- show the team during the internal demo review

**Comment by wrnu** [comment]
not relevant
