### ISSUE TITLE
Design Public Cloud Wordpress Site

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1942]
**Describe the issue**
The private cloud team has launched a new site that is part of an effort to replace devhub with something that is easier for their maintenance capabilities.

**Additional context**
- There is a website at https://cloud.gov.bc.ca which currently doesn't exist but redirects to https://cloud.gov.bc.ca/private-cloud/
- The intended structure that Justin had is
- - cloud.gov.bc.ca
- - - private-cloud
- - - saas
- - - public-cloud
- - - mobile-and-developer-experience
- the idea is that cloud is the greeting page, and the visitor is offered a choice to the present services run by each team
- we wrote the content
- there is general theming already done on the site that is good to reuse for consistency's sake

**Definition of done**
- Cloud Pathfinder PO and the tech writer contractor for platform services has drafted the public-cloud site
- Get hold of the draft site, update with PO, and set up a minimal place-holder
- Create one sub-section, empty with a link pointing to devhub as a holder for the journey to cloud https://developer.gov.bc.ca/Cloud-Pathfinder-Onboarding-Journey/

**Comment by mitovskaol** [comment]
tracked in other tickets
