### ISSUE TITLE
Enable FX conversion on new automated billing application

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1943]
**Describe the issue**
The new billing utility as currently deployed does not have the conversion from USD to CAD enabled. Our clients expect bills in CAD. Enable the FX (Foreign eXchange) conversion in the billing utility.

**Additional context**
- The FX api fails on occasion
  - When the bills we're run manually we could just run it again.
  - Now that that it is run by automation we need better error handling and alerting
- involves python code writing and getting up to speed on the work that Ukeme left us
- Oanda used to be a stable FX provider (may be out of date)

**Definition of done**
- Decide on an endpoint for FX
- Modify the FX feature to retry 3 times in case of API failure
- Send Alert in RC & Teams if all three retries fail
- Redeploy the changed version in LZ2/ECF Prod

**Comment by ActionAnalytics** [comment]
Deploying today
