### ISSUE TITLE
Small update to the AWS PIA describing access of AWS Enterprise Support

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1945]
**Describe the issue**
AWS Enterprise Support is about to be engaged by PO in order to provide a smoother support experience for Cloud Pathfinder Platform Admins and Devs.  Currently the issue is that we have to enable support one at a time for each of the several hundred environments we have.  There are delays doing it this way and it does not scale.  We enable AWS Enterprise Support once and all our environments are covered.

**Additional context**
- Audra, Julian and David have looked at the AWS terms and under the proposed pay-as-go AWS Enterprise Support model, there are no contractual changes.
- We know that AWS Enterprise Support will not have access to any ministry team workload environment or data.  They will just be invite only with whatever scope of temporary access we give them for the scope of the support ticket, exactly as now.
- There is an existing AWS Program level PIA (Privacy Impact Assessment) that we have and OCIO Privacy Compliance and Training (PCT) has a copy on file
- First time working on the AWS PIA (bit of learning of debt)

**Definition of done**
- Connect with Julian and get the existing information (15 min meeting), he has some screengrabs that he shared with Audra related to the description of the service from an authenticated AWS view.
- We want to clearly reassure ministries who may have questions about the access of AWS Enterprise Support via the PIA, where we will clearly communicate the above in a brief section.
- Get the PIA reviewed by PO, then Audra, then submit new PIA to PCT for permanent storage

**Comment by garymatics** [comment]
MPO feedback received. MPO shared SOAR. Amendments to PIA required.

**Comment by garymatics** [comment]
IMB review of PIA concluded. PIA will shortly be forwarded to PCT for final review/approval.
