### ISSUE TITLE
Get Bruce & Gary up to speed on current security tools

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1951]
**Describe the issue**
Currently in AWS we have an overwhelming amount of log and security data flowing from all accounts to some central areas.  There several summary channels in RC that begin with the prefix "public-cloud-security-aws-ECF..." and then we are also shipping all logs down to the SecOps SIEM service.

**Additional context**
- The SecOps SIEM has currently limited operational capacity and support (frequent downtime) and it cannot be queried.  The SecOps SIEM logs are kept for a long time (forever?) but the SIEM ingests the logs as a single JSON blob field, so all the effort CPF put into crafting a nice queryable JSON log format cannot be leveraged.
- We also have a new internal SIEM in AWS with this latest upgrade.  This is an OpenSearch solution (not magically deployed - see related ticket) but it is preconfigured to be easy to deploy.  This one is stable and queryable.
- We also have CSPM as a snapshot view of our Posture stance, along with a time-series record in Quicksight.

**Definition of done**
- One person will own this ticket, they need to create all the meetings early in the sprint
- Meeting with Austin H for access to SecOps SIEM (new password resets)
- Access to RC Channels (meeting with Prabhu)
- Access to the Quicksite CSPM summary dashboard (Kevin)
- Use password manager to store custom credentials (change the default pw asap)
- Bruce and Gary get hands-on permanent access to all systems in additional context (except the OpenSearch one because that one is not deployed yet) plus the RC channels
- They are comfortable accessing and can start to view events and logs, with the limited scope of getting ideas for future tickets (not solving all security problems)

**Comment by prabhukiran9999** [comment]
- Had a chat with Gary, Bruce, and Kevin. we had a chat about our current account structure and how we used them to create some solutions
- Unfortunately, most of the solutions are still in the dev phase. But Gary and Bruce have access to SecOps SIEM and RC channels.
