### ISSUE TITLE
Onboard access CPF Compliance with Defender/Azure Sentinel security dashboard tool

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1955]
**Describe the issue**
Azure has a very well built, mature security dashboard.  Not only are we interested in the security events themselves, but we are also interested in the cross-pollination of ideas and possibly even collapsing other security initiatives into less.

**Additional context**
- We are unsure of what level of monitoring of Azure Sentinel is happening with SecOps at the moment (see second DoD).  We know they've been very busy and would like to know their intended directions/plans for Sentinel.

**Definition of done**
- 30 minute meeting with Jon for initial context and conversion, fast demo
- Quick heads up/approval from Olena for the form
- Nick C, Gary, Max, Julian and Bruce can see the dashboard same as Austin

This came into the ticket somehow but now Jon and I don't understand if it's needed:
- Fill out the "Azure Cloud Updated Access Request Form" from ADMS

The main point of the ticket is that our teammates have access to see the Sentinel feed

Will create a new ticket for interacting with SecOps:
- Meet with SecOps for current status and questions (Julian S, Chris C, Austin H, Jon M, Gary H, Bruce L) 

*****************************************************************************************************************
@ActionAnalytics As per our discussion in MS Team, here is my suggestion to what the scope of this ticket might be, it is up to you as a PO to decide what scope to go with, from my experience I can just say that keeping the ticket scope clearly defined and narrow will increase the possibility that the ticket will be completed within a single Sprint and won't get spilled over multiple Sprints:

Olena's suggestion for the scope of this ticket (please help fill in the gaps that are highlighted in italic). 
**Title**
Document the process for obtaining access (*Do you know what level of access is needed?*)  for CPF to Azure Sentinel

**Why this work is needed?**
Azure has a very well built, mature security dashboard.  Not only are we interested in the security events themselves, but we are also interested in the cross-pollination of ideas and possibly even collapsing other security initiatives into less. CPF Team need to have access to Azure Sentinel to *monitor security events pertaining to the product team work in ECF and ???*.

**Additional context**
Access to Sentinel is currently controlled by SecOps, a meeting is needed with the SecOps team to find out what the process is for requesting access to Sentinel for the CPF team: what form to use to submit a request for access, how to submit, who should approve it and the timeline for processing the request.

DoD:
- Identify and document in this ticket all steps that the CPF team needs to take to request access to Sentinel

**Comment by ActionAnalytics** [comment]
This is becoming a higher priority because we have some email threads ongoing between SecOps and Azure platform folks to understand and close potential legacy instances that are getting connection attempts.

If the VM is flagged, they get shut down by Jon (and future CPF Compliance stakeholders/platform Admins)

**Comment by jon-mc-git** [comment]
Needs on the ticket were clarified with PO.  A PIM-based process was set up in cooperation with ADMS group to provide system\dashboard access to 'Defender for Cloud' for our Cloud Security & Compliance team as well as for our PO and for Platform Administration.  The ADMS form that was indicated was found and filled out, but it will be clarified by ADMS during next PIM ticket if actually needed by them for this.  
Access to the Azure Defender for Cloud main dashboard was tested and the people were added.  There was an issue during testing with Gary, and his access will be restored once PIM troubleshooting is completed in next PIM ticket (#2162), as there are nuances to PIM that have to be investigated.  Ticket follow up for discussion with SecOps was created (#2154)

**Comment by jon-mc-git** [comment]
Closing
