### ISSUE TITLE
Modify routing module to support ROSA

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#1957]
**Describe the issue**
ROSA requires routing two domains to separate internal load balancers so that the cluster can be accessed from the public internet.  Our current routing module does not support the domain structure required by ROSA.

api.example.com -> internal openshift api lb (this is already possible)
*.apps.example.com -> internal application lb (not supported)

**Additional context**

**Definition of done**
- add support for additional subdomains (*.apps)

**Comment by ActionAnalytics** [comment]
This ticket was used as a bit of a bucket.  When the main routing piece is done, please make any tickets for any extra work that needs to be done that is ticket sized
