### ISSUE TITLE
Meet with Charles M about Azure Billing questions

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1959]
**Describe the issue**
Charles M from NCCS has a side area of Azure outside of Phase II.  He has some questions about how to use the billing reports in Azure.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Limit to one 30m meeting with Charles to assist with any easy answers we can provide, and or
- Create tickets for any additional consultation Charles may need and schedule it for next sprint

**Comment by ActionAnalytics** [comment]
Let's please ping Charles and put a placeholder meeting - the meeting can happen later in sprint, but Charles has been waiting a while

**Comment by jon-mc-git** [comment]
Reached out to Charles on this and waiting for reply with timing for a touch base session for his Azure questions

**Comment by jon-mc-git** [comment]
Have reached out twice so far and had no response yet from Charles so will be putting on hold for now until he gets back on this.

**Comment by ActionAnalytics** [comment]
Jon is sending a "we're for you when you're ready email" and we're closing the ticket
