### ISSUE TITLE
Clean up and Publish draft Cloud 101

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1960]
**Describe the issue**
There is a draft cloud 101 course we have online but not published.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Fix the content to the best of your ability, looking for clarity of writing, spelling errors, and making sure images are attributed or made by us
- Review with a team member (15, 30 minute walkthrough)
- Review with PO (15 min meeting)
- Publish online along our pre-reading material (this page or it's WordPress successor https://developer.gov.bc.ca/Cloud-Pathfinder-Onboarding-Journey/Evaluation)

**Comment by wrnu** [comment]
not relevant
