### ISSUE TITLE
Block EKS in AWS ECF environments

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1962]
**Describe the issue**
AWS has the capability to block services.  Let's try it with EKS

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- ECF Dev is capable of blocking EKS
- This is accomplished in a reusable manner for Test and Prod
- Demo to Warren
- Create tickets for Test and Prod if accepted by Warren
[ESTIMATE with team]

**Comment by wrnu** [comment]
not relevant
