### ISSUE TITLE
Tools deploy for existing project-sets

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1964]
**Describe the issue**
Teams with old Sandboxes need to be migrated to new Tools.  Let's automate the first step of this.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Create automation that for each project-set (including lab) that have a sandbox and no tools in their project-set, deploy a new Tools account with the same project-set tags and billing linkage.
- Ok for teams to have [Sandbox, Tools, Dev, Test, Prod]. 
- Create tickets for migration away from Sandboxes (will likely give teams several months and time for any stragglers).
- Create tickets for closing the sandbox accounts

**Comment by MaxWardle** [comment]
Moved back to prioritized backlog as it was blocked for multiple sprints and doesn't align with sprint goals.
