### ISSUE TITLE
Downtune frequency of network traffic to CSPM

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1966]
**Describe the issue**
We are sending too many notifications to CSPM and it is generating expense in our users' project-sets.

**Additional context**
- assume that they have functionality for this
- Warren checked the Terraform API, no setting for that.  Let's direct questions to Checkpoint.  CSPM is reading/calling API's in our accounts, they choose when to do that.  Let's downtune at CSPM

**Definition of done**
- Work with Checkpoint CSPM support to reduce the CSPM update frequency to once every hour from it's current setting.
- Meeting with Checkpoint and work in RC channel #cloudpathfinder-checkpoint-howto-support
- Verify before after screenshots of billing

**Comment by bruce-wh-li** [comment]
Need PO to share the before billing

**Comment by bruce-wh-li** [comment]
CheckPoint requires NDA (Non Disclosure Agreement) sign to release a list.

**Comment by bruce-wh-li** [comment]
Will revisit when appropriate if needed
