### ISSUE TITLE
Set up ROSA project-set within LZ1 ROSA OU

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1970]
**Describe the issue**
ROSA will need to permanently exist in a separate OU because networking issues (Private Hosted zones not enabled in other OUs)

**Additional context**
- Currently we have 1 workload environment for that team in the ROSA OU
- We are lazy developers and want to avoid managing multiple OUs for this one custom thing
- Establish pattern first in LZ1 Test until things stabilize, then apply to Prod later

**Definition of done**
- provision 4 environments (tools, dev, test, prod) ALL in the ROSA OU
- Notify the RedHat team that they have a /16 for ALL of the 4 environments, and leave it up to them how they allocate

**Comment by MaxWardle** [comment]
Deployed Test for now as they just need to deploy one new instance and will be moving to LZ2 eventually. Gave them access and asked them to let us know when they've deployed so we can help setup DNS
