### ISSUE TITLE
Walk through billing report with ROSA team

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1971]
**Describe the issue**
The ROSA team needs to understand billing because they will take our format, and use that as a starting point to sub-divide the total AWS Account workload environment bill into smaller-grained Openshift bills for individual Openshift Namespace workload environments.

AWS ROSA OU
| (AWS Accounts)
[AWS Tools WE, AWS Dev WE, AWS Test WE, AWS Prod WE]
...
[AWS Prod WE]
| (Openshift Namespaces)
[ROSA Tools WE, ROSA Dev WE, ROSA Test WE, ROSA Prod WE]
+
[AWS RDS/S3 created with Namespace specific naming structure]  <- this is ROSA team's task
**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Provide a sample of their last 3 bills
- The ROSA team just needs the weekly totals and then they sub-divide according to their cost distribution.
- Our bill will have some names of instances, they can ingest the excel

**Comment by MaxWardle** [comment]
Spoke to Phil T and Casey R from redhat about this billing walkthrough and they said this meeting is not a priority for them right now, they're going to deploy the new cluster and go from there.

**Comment by wrnu** [comment]
not relevant
