### ISSUE TITLE
Terraform Seminar

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1977]
**Describe the issue**
The team would like to normalize, compare and learn about what other team members are doing around Terraform.  In our Pulse Review, the team expressed an interest to learn how Warren does it and compare to their own ways, seek opportunities for new ways.

**Additional context**
Add any other context, attachments or screenshots

**Definition of Done**
- Warren has booked a meeting with the team
- A one or two session meeting happens where the focus is on sharing practical tips and how to debug and untangle when seeing errors
- Julian to document a draw.io diagram and share with the team
- The team leaves with a shared understanding of practical use of Terraform

**Comment by wrnu** [comment]
Not relevent
