### ISSUE TITLE
SPIKE: Review Service Control Policy (SCP) to ensure permission required by CloudCSPM is not denied

### ISSUE THREAD

**Issue by bruce-wh-li** [bcgov/cloud-pathfinder#1987]
**Describe the issue**
There is a warning that we see every time we log in to use Check Point CSPM (Cloud Security Posture Management).  

We think it impacts functionality but we don't understand if this is to blame for things not working in the Canadian CSPM instance we're using.  Some things aren't working right now, this could be one of many potential sources of error.  It could just be a visual bug.

We see bugs in the container workload environment.  Missing ECR list repository permission for example. 

We don't know if the bug is on our side or theirs.  

In our ECF environment, we have created the Role CloudGuardConnect with attached "SecurityAudit" and Custom Policy "CloudGuardRead", CloudGuard CSPM still encountered missing permission.  We want to review  the SCP to ensure, the required permission is not blocked.  We are not sure if this will solve the problem, but if we check it, then we can go back to Check Point and look at the next potential source of the problem.

**Additional context**
- We have no logs from CheckPoint so very hard to debug.
- Anyone on the team with Admin role can look at the management account for browsing the SCP
- The SCPs don't exist in the workload accounts
- The SCPs are additive so several apply.  We can look at the config.json file (tech team member) for the ECF to see which apply where.  https://github.com/aws-samples/aws-secure-environment-accelerator/tree/main/reference-artifacts/SCPs
- Meet with Warren to get started 

Review SCP requires Org Master Account

1. Hovering column status in Environments Splash Screen shows 'This Account has missing permissions'
1. Click the the any environment, the error message 'Missing Permission for CloudGuardConnect'
1. Click on show more, the list of related resource, permission group, action that CloudGuardConnect needs permission is displayed. 
1. CheckPoint would like to have Screen Share once we have reviewed the SCP is the root cause. 

Related CheckPoint TAC Support Ticke is 6-0003369490.   

**Definition of done**
- Cap to a 2 effort (reason: we can't solve this, we need info)
- Get logs from CheckPoint because we need more info to find the SCP on our side.
- Meet with someone on the tech team who can show you where the source code that defines the SCP lives and which settings apply
- Identify problematic SCP and bring back to team to discuss (recall this likely may be a non-issue on our side, likely a bug on their side.  Possible one of the CloudGuardConnect permissions we're giving is blocked by the SCP)
- Screen Share with CheckPoint TAC Support if needed
- Make well-formed tickets if the fix is one our side.

Bonus if easy to fix (but not required):
- CloudGuard CSPM does not hit 'Unauthorized Operation' Error when clicked the listed Environment.

**Comment by bruce-wh-li** [comment]
Need to have OU Management Account Access to be able to browse SCP.   In spite of that, based on error shown in CloudGuard CSPM, the unauthorized operation error might not be related to SCP disallow.

**Comment by bruce-wh-li** [comment]
Found ecsCluster, EcsTaskDefinition on rescource: * with an explicit deny in SCP (not region related).  Warren U. please take a look in CSPM.   Thanks

**Comment by ActionAnalytics** [comment]
Verified that out of regions are being blocked by SEA while CSPM is trying to scan all regions.  Therefore this makes sense. Messages tell us can't see ECS clusters but we see the right clusters.  We are just getting an error message about the other regions.  Closing the ticket.
