### ISSUE TITLE
TFC Queue Manager Missed 2 Stuck Runs

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#1994]
**Describe the bug**
Aug 31st I got a message from David S in tenant requests asking to kill a run that had been stuck in cost estimation since yesterday. I went to check it and there were two runs from different workspaces stuck in cost estimation. There were no messages in the public-cloud-tfc-queue rocket chat channel so I think there might be an issue with the queue manager.

**Additional context**
- Ukeme was having issues with false positives before and it looked hard to solve (the TFC API isn't stateful and would require a database to record current state)
- Living with the false positives was determined to be less effort than building a new app to track the state.
- We may be moving to new deployment patterns so this could be thrown away. 
- https://github.com/BCDevOps/octk-tfc-queue-manager

DIFFICULT TO DEBUG requires a TFC account then block it.  How do we generate an event we don't know what it is.

Leave in backlog until we know more or we hear more screams.

**Definition of done**
- Investigate why the queue manager didn't catch those runs
- Have the blocked events that were found show up in the channel public-cloud-tfc-queue (right now they don't)
- Investigate candy/Wade B public-cloud-tfc-queue entries and if false positive, filter them
- Fix the issue
- We may need to recreate the rocket chat webhook if it's still linked to Ukeme's handle
- Cap to a 3 (see additional info)

**Comment by mitovskaol** [comment]
@MaxWardle  Can you please confirm this is still relevant

**Comment by wrnu** [comment]
not relevant
