### ISSUE TITLE
New naming convention for ECF environments

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#1998]
**Describe the issue**
Problem:  We use the same words to describe environments at different levels of our product stack which leads to confusion among our users and team members.

ECF has Dev, Test, Prod but so do the Project-Sets we assign teams with their Tools, Dev, Test, Prod. 

It is a natural (and incorrect) assumption to presume that Dev Workload Environments would live in the ECF Dev environment when this is not the case.

**Additional context**
![CPF Rosetta Stone-Common Terminology - White BG.drawio.png](https://images.zenhubusercontent.com/5e98c26e92d4be32d8e29cb0/a2cf3c42-deda-4733-9c3b-a0f3f541d0e8) 
- suggestions from PO are 
  - ECF Dev becomes ECF Break - Breaking Changes happen here
  - ECF Test becomes ECF Patch - New Upstream Patches are tested here
  - ECF Prod becomes ECF Stable - This is kept stable because our teams have their project-sets there
- suggestions from Jon
  - ECF Alpha (Platform), Beta Platform, & Prod Platform
  - ECF Staging (Platform), Pre-Prod, & Prod Platforms

**Definition of done**
- Meet with Team for 30 minutes and ask for suggestions / improvements
- Gain consensus on a new naming convention that does not reuse Dev, Test, Prod and avoids confusion
- New names are one word and reflect the function of the ECF environment (no pet names, colours).
- Get access to the source files for the draw.io rosetta stone diagrams and update them.
- Identify which decks and websites need updated versions of the diagram and create the tickets to update them

**Comment by gautammalhotra21** [comment]
Team came to a consensus for the new naming convention:

1. ECF Dev - **Forge**
2. ECF Test - **Assembly**
3. ECF Prod - **Live**

![Naming Convention.png](https://images.zenhubusercontent.com/6307c4aa2add875ea872e409/d51ed0c5-5174-410f-8dd4-db436aecb1fd)
