### ISSUE TITLE
Modify SecOps SIEM to work alongside AWS SIEM

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#2000]
**Describe the issue**
- In order to deploy AWS SIEM Prabhu had to get rid of event notifications attached to Log-Archive S3 buckets which broke the SecOps SIEM log exporting solution

**Additional context**
- Amazon S3 Notifications currently does not support duplicate S3 Event configurations, thus limiting options to have multiple Lambda targets for S3 Notifications. The solution is to implement a fan-out architecture using SNS. Instead of having S3 Notifications invoke Lambda, they are published to an SNS Topic, and the Lambda(s) is subscribed to receive those messages.

**Definition of done**
- Buddy up with Kevin on this one, will require explanation of the SEA and all the SIEM efforts and a bit of history why we're in this current ticket
- Modify the IaC to implement the above solution and test it out 
- Modify Lambda function to take the file info from the SNS message
- Make sure the SecOps team is receiving our logs

**Comment by OmoAttah** [comment]
due to the excessive cost of the transfer, the logs will be parsed at the source in AWS - Olena
