### ISSUE TITLE
Billing Dashboard prototype in Quicksight

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2010]
**Describe the issue**
Eventually we'd like to have a billing dashboard for users in ECF with SSO and views constrained to their environments.  That is out of scope.

An MVP for this sprint is to have a QuickSight board that reads and stores the billing data we send to teams and displays it in a queryable time-series data dashboard.

**Additional context**
- In a single QuickSight instance, what kind of access exists for access to data sets?  We may not be able to pathfind a way to solving this.
- We may not want everyone logging into our QuickSight instance in our operations account either.  We may need to redesign if this is a problem.

The scope of this ticket is presentation of billing data such that we can see trends over time and filter.  Even if only our PO and admins can use this, this is still valuable and we can come up with a different solution for the community if this one doesn't work.

**Definition of done**
- Data storage for the billing report data is designed and implemented
- A minimal update pattern is designed and implemented (could be that when the billing automation runs and sends emails, it also at the same time writes to the billing report data storage)
- A basic dashboard is created
- The PO is granted access to the dashboard
- An SSO ticket is created that is well defined and estimated

**Comment by mitovskaol** [comment]
No longer relevant
