### ISSUE TITLE
Main page for new Wordpress site

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2011]
**Describe the issue**
DevHub is being replaced with Wordpress, we need to begin to move over.

**Additional context**
- Julian and some others worked on a basic webpage for Wordpress
- Start with Mural if blocked by not having Figma
- There are existing Wordpress templates that the other teams are using but our PO is open to creativity

**Definition of done**
- Work closely with Gautam in several shared sessions using this as an opportunity to train and onboard
- Turn on the website (meet with Julian and he will bring in a contact from the team hosting the site)
- Enable the first page.
- Meet with Julian to create tickets for what we need to transfer over from DevHub
- Begin a draft wireframe (we really mean very little work here)
- Plan user feedback exercises as tickets with Julian
- Make well-formed tickets for next sprint to acquire, review and if needed update the Wordpress templates (this keeps this ticket at a 3).  Make tickets for user testing

**Comment by bharmouche** [comment]
Gautam and Bahaa Met and did a Card sorting exercise to share with Julian and after approval will make wireframe
