### ISSUE TITLE
Move Wiki contents from Teams General area to Team CPF Scrum Team area

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2015]
**Describe the issue**
We have a small knowledge-base of terms, acronyms and handy links.  

The problem we're trying to solve is that this was created in a part of our Teams environment where everyone across government can see it and we have content in it that is not ready to be shared.  It is meant for internal usage on the team only.

We need to copy over the contents and rebuild it in the CPF Scrum Team area.

**Additional context**
Copy data from:
![Screen Shot 2022-09-01 at 3.03.16 PM.png](https://images.zenhubusercontent.com/5e98c26e92d4be32d8e29cb0/4c55c049-a965-4a6c-a47f-d6443f3aaed4)

To:
![Screen Shot 2022-09-01 at 3.03.07 PM.png](https://images.zenhubusercontent.com/5e98c26e92d4be32d8e29cb0/0c32322e-3d09-4497-8818-e8a13c0e40c6)

**Definition of done**
- Access the content via Teams
- Merge or fix any sections that aren't clearly named or have duplicate content
- Lightly read and understand why we have a link or description in this Wiki entry
- Copy it over to the new area shown in the "Additional Context" above
- Leave the original content where it is, ask Julian to review (make a 15 minute calendar invite) when done and he will delete the original content

**Comment by snowflakebunny** [comment]
I did the DOD. Reviewed with Julian. I am closing my ticket.
