### ISSUE TITLE
Catherine gets access to 2 team emailboxes

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2016]
**Describe the issue**
We would like Catherine to start observing what kind of emails we get and how we handle them so that we can start planning how to better be responsive to our customers and increase the value we deliver them.

In order to do so, Catherine needs to get access to the mailbox.

**Additional context**
- iStore is an internal BC Gov ticketing system for all kinds of core government services (IDIRs, HR, equipment, access, building access)
- There currently is a new "iStore replacement" called ServiceNow and some tickets have moved over to ServiceNow, but it's unclear if this will continue or one will replace the other.
- One needs to be a special role in order to deal with iStore tickets.  That role is called an "iStore Preparer".  Dana has that role.  Julian does not. 
- the "@g.b.c" is of course wrong but we do that to avoid spam collectors
- pathfinder is not our emailbox but we use for some of the old cloud services which were set up years ago when there was only one team called pathfinder.
- Assume Catherine gets her Employee ID at the start of sprint (otherwise this is blocked)

**Definition of done**
- We want Catherine to have access to: pathfinder@g.b.c and cloud.pathfinder@g.b.c
- Ask Dana for access (15 to 30 minute meeting) - she will have to make an iStore access request for you (if she has time, she may even be able to train you but that will be a later ticket as Dana is currently very busy)
- Let Julian know once the iStore ticket is complete.
- Screenshare with Julian your Outlook setup (30 min meeting) and he will teach you how to install and access the new mailboxes.

**Comment by snowflakebunny** [comment]
Employee ID received. Registered the required training. Waiting for approval.

**Comment by snowflakebunny** [comment]
OCIO My Service Centre (My SC) - Authorized User Training Approved, and eLearning in progress.

**Comment by snowflakebunny** [comment]
Completed online learning OCIO My SC - Authorized User Training - Module 2.
Dana said, based on her own experience when she first onboarded, it took a few WEEKS to have the iStore preparer request approved.

**Comment by snowflakebunny** [comment]
Dana have sent a request email to our ministry contact who handles iStore preparer status authorizations (including that I have completed the required training already), and Dana will keep me updated.

**Comment by ActionAnalytics** [comment]
There is probably an iStore ticket from Dana to get you access to the mailboxes.  Now that you have iStore permissions, you can probably look the iStore ticket and try move it forward.

**Comment by snowflakebunny** [comment]
Catherine have access to: cloud.pathfinder@g.b.c.
Because Catherine did not specify two email addresses to Dana when asking about access to these two emails. Dana has to put another iStore ticket asking for request for Catherine to get access to pathfinder@g.b.c.

**Comment by snowflakebunny** [comment]
Catherine have access to: pathfinder@g.b.c.
