### ISSUE TITLE
Catherine acquires the iStore Preparer role

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2017]
**Describe the issue**
It will really help the team to have another person who can prepare and manage iStore tickets (this is typically an admin role, Intake Clerk is a good fit).

Dana is overloaded and is expressing to Julian that she wishes that Catherine could take on some of the work for her.  Julian's plan is to first have Catherine focus on the email backlog and customer service with him, unfortunately for Dana this delays getting her help (but Julian is doing other things to lighten the load for Dana like consolidating the AWS invoices).  Eventually once Catherine has mastered the intake customer service with Julian (likely 6 months), then we can start helping Dana more.

However, it is good to get iStore preparer status early as this will help Catherine in many of the tasks she will need to do.

**Additional context**
- Assume that the request is something that can be approved

**Definition of done**
- Request iStore preparer status from Dana
- Once the iStore preparer status is acquired, ask Dana for a good time within the current sprint (see dates to the right) for a couple hour session to train how the iStore system works and the duties and capabilities of an iStore preparer.
- Take the training session with Dana

**Comment by snowflakebunny** [comment]
Waiting for Catherine's employee ID to register required training in order to up with iStore authorized user.

**Comment by snowflakebunny** [comment]
Employee ID received. Registered the required training. Waiting for approval.

**Comment by snowflakebunny** [comment]
OCIO My Service Centre (My SC) - Authorized User Training Approved, and eLearning in progress.

**Comment by snowflakebunny** [comment]
Complete online learning of OCIO My Service Centre (My SC) - Authorized User Training - Subscription Software

**Comment by snowflakebunny** [comment]
Completed online learning OCIO My SC - Authorized User Training - Module 2.
Dana said, based on her own experience when she first onboarded, it might take a few WEEKS to have the iStore preparer request approved.

**Comment by snowflakebunny** [comment]
Dana have sent a request email to our ministry contact who handles iStore preparer status authorizations (including that I have completed the required training already), and Dana will keep me updated.

**Comment by ActionAnalytics** [comment]
Catherine to follow up with Dana to get the training meeting finished.

**Comment by snowflakebunny** [comment]
iStore system training in process. Dana to train Catherine.
