### ISSUE TITLE
Refactor lz workspace live repos

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#2019]
**Describe the issue**
Changes to files in the lz workspace live repos need to be manually copied across the repos. This is error prone and not best practice for software development. We want to refactor the workspace live repos to use a git submodule and create another repo to store the common code. The common code repo would be used as a submodule in the workspace live repos.

**Additional context**
- Uses Terragrunt for the base layers
- Salted with platform specific content, needs to be parameterized.
- 5 or 6 files, each having configuration in them needing to be pulled out
- Project Admin files too, any file that is common would be affected by this

**Definition of done**
- Refactor the environment specific settings as configuration files using parameters in 3 GitHub repos so that they are generalized
- Use Git Sub-Modules (one Git repo can have another as a child)
- Run a terragrunt all-plan and see that there are no changes
- Review the PR and the above line with Max or Prabhu

**Comment by ActionAnalytics** [comment]
LZ0 and 2 are done, 1 had to wait for ROSA stuff, ready now
