### ISSUE TITLE
Post incident review with SecOps\CIT teams

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2022]
**Describe the issue**
Turns out CIT's VMs were not the ones causing Defender alerts with SecOps so we want to communicate, explain how the IPs are reused, and use this as an opportunity to have the CIT team improve their environment.

**Additional context**
- We noticed that the CIT team had very little awareness of their own assets/footprint and this is likely due to the transitions within the team and some overdue cleanup needed

**Definition of done**
- Book a meeting with Chris M, their PO (Search the CRM for "CITv"), Julian, Jon, Quinn, Gary, Bruce
- Deliver the above messages in the Description
- Complete investigation into Azure VM security incident
- Create presentation on what happened to share with other teams involved
- Add in learnings for us and all teams, and conclusion on what can improve
- Delivery presentation and follow up where needed

**Comment by jon-mc-git** [comment]
Investigation was completed and stand-down was concluded on our end as the VM gettting the constant log in attempts was isolated and log in appeared to never have been actually achieved.  Issue finding VM concerned using initial information was noted for future learnings with SecOps group (ie. just getting a name and\or IP address can not be enough at times as these can be re-used in Cloud - so concluded that more context around the offending VM\cloud asset would help for a quicker investigation next time.  Also noted was that a 'Cloud Investigation Request' type of form should be created and used between our teams, as well as an eventual shared Defender system dashboard that SecOps and Cloud Service could centrally reference and work from\reference when submitting these Cloud Investigation Requests to us - To provide better context and same source of truth dashboard in the future.

**Comment by jon-mc-git** [comment]
Closing ticket
