### ISSUE TITLE
Form for Compliance Incidents

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2025]
**Describe the issue**
Security and Privacy incidents in cloud require having key information ready about the workload environment that the event occurred/is occurring in, who are the parties that are working in the environment, and what kind of information and capabilities are affected.

**Additional context**
- We already have a Word Document form version 1 that was created and distributed to our compliance community by Avneet.  This would be a good starting point for our next version. We can use the same name "Cloud Security and Privacy Breach Reporting Form"
- The form is located in our Teams.  General, Files, Workshops and Accelerators for Partners, Compliance Accelerators, Cloud Security Incident and Privacy Breach Reporting Form
- Completely separate online spreadsheet from the CRM
![CPF Rosetta Stone-Common Terminology - White BG.drawio.png](https://images.zenhubusercontent.com/5e98c26e92d4be32d8e29cb0/63dc371e-b1b0-4af1-a7b9-798ad00067e6)
- Feel free to test and make "dirty" the form as much you wish, it's easy to clean off entries before we go live.

**Acceptance Criteria**
- Julian created an empty Cloud Security Incident and Privacy Breach Reporting Form stub form in gDrive for Jon to start prototyping
- Copy over the existing word form (additional context above) contents to the gForm
- Add the specific fields and instructions that we learned in our recent event that would have clarified and accelerated the quick identification of the affected team and workload.
- Try to make the language match the Rosetta Stone vocab above (perhaps include the diagram somehow in the doc) and be useful for Azure, GCP and AWS.  For example, you can make a reference to the affected "Workload Environment" but then provide examples for all three clouds like (Azure: your SubscriptionID, AWS: your LicensePlate or AccountID, GCP: your ProjectID)
- Demo to Julian, Gary and Bruce before Community Update
- Make a ticket to demo to SecOps (quick 30min meeting or less)

Bonus:
- Steal formatting and images from the existing form https://forms.gle/hZhHZBorMNpdJtmX7

**Comment by ActionAnalytics** [comment]
FYI Gautam will have an updated diagram (see the one in the ticket)

**Comment by jon-mc-git** [comment]
Reviewed the older sec and privacy breach template and pulled info from this that could help our new process around this Google form automation process.  Along with a review of info from the previous SecOps Cloud incident investigation request we received, both sets of these needs were incorporated into the creation of a draft Security and Compliance Investigations submission request form

**Comment by jon-mc-git** [comment]
Previous feedback was incorporated into draft and put into presentation form for our Sprint Demo to the community to show some of the initial work here.  Tickets will be created from this to continue work from this baseline (example o process exploration, automation options, etc.)

**Comment by jon-mc-git** [comment]
New feedback has been received from Nick C. today and will be incorporating that feedback before closing this ticket

**Comment by jon-mc-git** [comment]
New feedback from Nick incorporated and ticket for SecOps communication, demo and feedback has been created.  Closing ticket
