### ISSUE TITLE
SPIKE: CSPM CloudGuard capabilities review

### ISSUE THREAD

**Issue by OmoAttah-zz** [bcgov/cloud-pathfinder#2033]
**Describe the issue**
Need to have a 'working output' review of CloudGuard CSPM and how this will meet operational security needs, including how to make it as easy to use as possible (reports, pre-prepared dashboards) and an investigation into any new\unfamiliar CSPM capabilities built into the product, in order to best understand how it will fit into a Multi-cloud future

**Additional context**
CSPM's have to be connected to all Gov Pubic Clouds production environment so it's important that we take a look at what value, longer term is there, including where the product momentum is and what possible future needs could be addressed by the product.

**Definition of done**
- Do latest training with CheckPoint on current and upcoming CloudGuard capabilities
- Investigate latest product materials to understand current situation
- Connect with Nick\Bruce on our own CloudGuard situation and compare
- Work with Bruce\Nick to review relevant dashboards, capabilities, integrations and possible future architecture around its use in a Multi-cloud environment 
- Better understand possible Multi-Cloud capability with CloudGuard, architecture needs, 'single dash' capability across multiple clouds (AWS, GCP, Azure)
- Understanding potential possibilities and product limitations, problems and potential for the future (possible dev on CheckPoint side TB discussed)

**Comment by jon-mc-git** [comment]
This process+the training with Checkpoint was completed, although questions remain on some aspects, especially Multi-Cloud.  A post-review had with Nick on Cloud Security and ways to move us forward with this, including initial discussion on a plan to move us forward towards Multi-Cloud architecture.  Additional tickets will be created to discovery more around this important operations aspect, and a plan for the other Clouds will follow.  Closing ticket
