### ISSUE TITLE
Ensure billing alerts going to the right people

### ISSUE THREAD

**Issue by OmoAttah** [bcgov/cloud-pathfinder#2034]
**Describe the issue**
There has been some trouble around automated billing alerts which we will be troubleshooting and also better understanding around this automated capability

**Additional context**
- Billing alerts are still going to the wrong people so a review of this will be held and better understanding on its capability for possible improvement and/or refinement
- There are 2 kinds of billing alerts, ones that we send, and once that AWS sends according to AWS settings.
- We suspect that the billing alert issue is the one from AWS which is a settings issue that Julian needs to solve, not Max
- Julian has checked all three AWS root accounts for Forge, Assembly and Live environments.  There are no billing alerts there so we'll need to work backward from the notification mail that someone (likely Andy T) is getting.

**Definition of done**
- Meet with Julian and determine if this is a Julian AWS settings issue, or a Max billing automation issue.
- Review current AWS billing process with Max
- Spending time to better understand the billing/alert system
- Making corrections/improvements where possible

**Comment by ActionAnalytics** [comment]
Hey Jon I think this one is done.  I had to speak to Andy about something else and I brought this up and he said "yeah I just went into the email and unsubscribed".  Going through the email backlog with Catherine, I found the matching email where he unsubscribed from root account for AWS ECF Assembly.  This makes sense because we used to call it LZ1 because it was the first SEA deployment we had.  He must have signed up for those budget alerts and it was buried in there.  I think it would have taken us forever to find it.  I'll leave this here for you to read - if you agree it's done, go ahead and close it please.

**Comment by jon-mc-git** [comment]
Thanks Julian for digging into that with Andy and figuring that part out.  Looked into rest of billing around AWS and the complexity around the AWS weekly billing report auto-generation sent to project\service owner of the associated billing group.  Liked the fact that PO's and finance folks can detect any significant change on a weekly basis around their cloud workloads as this shifts this monitoring to the owners.  The complexity in running and summarizing these numbers is a small concern, and it would be nice to be able to take a weekly report and compare summarized reporting charge to a manual portal-based query on the same week in question for a particular set of workload accounts (service).  This would allow us to periodically verify reporting and the proper functioning of the automation, as well as keep warm the verification process (and possibly improve on this moving forward).  As of yet am not familiar with much of AWS cost management management capabilities but we can create other ticket(s) in future to address these questions.  Created diagram to represent the Billing-investigation\logging process as follow up.  Closing ticket

**Comment by jon-mc-git** [comment]
The complexity in running and summarizing these numbers is a small concern, and it would be nice to be able to take a weekly report and compare summarized reporting charge to a manual portal-based query on the same week in question for a particular set of workload accounts (service).  This would allow us to periodically verify reporting and the proper functioning of the automation, as well as keep warm the verification process (and possibly improve on this moving forward).  As of yet am not familiar with much of AWS cost management management capabilities but we can create other ticket(s) in future to address these questions.  Created diagram to represent the Billing-investigation\logging process as follow up.  Closing ticket
