### ISSUE TITLE
SPIKE: Find out who will be building the CPF website

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#2035]
**Describe the issue**
After testing the prototype of the CPF and adding the iterations, we will move to the actual building of the website. 

**Additional context**
- the CPF team will be allocating an external team or a local team, therefore the Service design team will need to connect to whoever is taking the initiative to pass the prototype.
- Preference is for the public cloud team to self-manage

**Definition of done**
- Talk to Bahaa and find out how the SaaS team and Platform services team are doing it
- If another (GDX?) team is hands-on building the WordPress, meet with the CPF tech team and see if we want to do it the same way 
- Need to have a kick-off meeting with the designated team
- connect with the designated team to pass the wireframe for building the website
- Create well formed tickets from what we learned

**Comment by gautammalhotra21** [comment]
The CPF Team will need to build the website internally on Wordpress. Connected with Tyler K, who mentioned that the GDX team would only provide the keys to Wordpress, the site build has to be done by the team internally.
