### ISSUE TITLE
Follow-up with Microsoft for Azure tenancy special subscription deletions

### ISSUE THREAD

**Issue by OmoAttah-zz** [bcgov/cloud-pathfinder#2036]
**Describe the issue**
There are two legacy subscriptions in the BCgov tenancy that cannot be deleted and we will have to address this with Microsoft and coordinate with the ADMS group

**Additional context**
Subscriptions were produced by Microsoft automation around the time that Office 365 enterprise capabilities were being implemented and are no longer needed
 
**Definition of done**
- Coordinate with the ADMS group
- Troubleshoot Azure ticket submission issues
- Submit support tickets to Microsoft when submission issue resolved
- Follow-up with ADMS

**Comment by jon-mc-git** [comment]
Issues getting to the bottom of how this could be dealt with and involving support took longer than expected as the problem did not seem to be well understood by the people discussed with, nor by MS Support at first.  Eventually a resolution was found and we confirmed with one of the original owners of the legacy\undeletable subscriptions that there was no longer any need for the two in question.  Support then confirmed their lack of use and empty of resources now so they were removed by Microsoft.  Closing ticket
