### ISSUE TITLE
Community of Practice, Training and Community Update Mailing Lists

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2038]
**Describe the issue**
We need to reengage with our 3 CoPs (these correspond to our users):
 - Product Owners/ Expense Authorities - customers, people who pay, 
 - Compliance (Security, Procurement, Privacy)
 - Developers (Full stack, testers, DevOps, Front-end, etc)

We also have a list of attendees for training and a final one for the Community Update/Demos

We currently have paused the CoP sessions we used to have.

We don't have an up-to-date mailing list for these people.  

We want to use mailing lists so that if someone declines the series, we can remove them (otherwise we end up hammering them with invites they don't want)

**Additional context**
- Factoring in learning Dept

**Definition of done**
- Go through the CRM
- Create a spreadsheet in the CRM (talk to Julian to do this - he will help speed this up so it's not all on the person doing the ticket)
- The spreadsheet/table view will contain the 5 mailing lists
- Create a well formed ticket about making specific community channels in both Teams and Rocket Chat as Service Design informs us to use the email sparingly as people are swamped with emails.

**Comment by ActionAnalytics** [comment]
We've made a spreadsheet tool to track info.  We have 2 tabs in the spreadsheet that are "good enough" and we've made those green.  We have 2 other tabs that have problems in that the emails are not unique to a row.  We want 1 email per row.  Those tab we marked red.  Catherine to spend some time and sort out these red tabs so they are usable.

**Comment by snowflakebunny** [comment]
Work with Julian in a session on which people need training

**Comment by ActionAnalytics** [comment]
There are a few crumbs remaining but we will make smaller tickets to deal with specifics as this is largely done
