### ISSUE TITLE
Wordpress plug in for CPF website

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#2039]
**Describe the issue**
the private team has gone through their website design, we would like to connect with the website team to ask them about the Wordpress plug in they used and why so we can leverage the work they went through in building the CPF website.

**Additional context**
the service design team is checking if the Wordpress template used by the private cloud team, will fit what the Public cloud team have in mind. 

**Definition of done**
- connect to Tyler K or Theresa and ask her about the plug in used
- share outcome to the CPF tech team and PO
- ask the team to share the Wordpress template they used for the service design team to take a decision for using it or building something totally different.
- share the credential of the Wordpress account to look for alternative templates if needed.

**Comment by gautammalhotra21** [comment]
Discussed the wordpress dev requirements with the tech team, need to have a discussion with PO to go ahead with wordpress or another platform. Will require some front-end dev skills.
