### ISSUE TITLE
Learn Pre-Reading Material and Onboarding Training

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2040]
**Describe the issue**
The Pre-reading material and Onboarding are very important because they define what we do and how we provide our service.  This impacts how we respond to requests in the channels (Shared Resp Model) as well as what presentations we present.

**Additional context**
- Pre-reading material: https://bcgov.github.io/cloud-pathfinder/Documentation/Pre-reading-material/000100_who_are_you.html#take-a-look-at-your-team

**Definition of done**
- Learn who are users are
- Really know the Shared Responsibility Model
- Review the #aws-how-to and #aws-tenant-requests channels from the point of view of the Shared Responsibility Model.
- 30 minute discussion with Catherine, Gautam and PO

**Comment by mitovskaol** [comment]
not relevant anymore

**Comment by mitovskaol** [comment]
not relevant anymore
