### ISSUE TITLE
Testing CPF Website after Building- Preparation

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#2041]
**Describe the issue**
After the tech team finishes building the Public Cloud website, the service design team will plan the testing of the website and collect feedback for final round before publishing the website.

**Additional context**
we are hoping to have diverse users for testing varying from tech to non tech, to ensure that we are being inclusive in our design and true to the diverse users that will use our website.

**Definition of done**
- connect with PO to get a list of potential users to connect with.
- prepare the questions and task that we will use in the testing sessions
- schedule time with users

**Comment by lukegonis** [comment]
This was completed by Gautam
