### ISSUE TITLE
Final CPF Website Testing (after tech team Building it on Wordpress)

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#2042]
**Describe the issue**
After the website is built on Wordpress by the tech team, the UX team will test it on users to compile all feedback needed before building the actual website.

**Additional context**
we are hoping to have diverse users for testing varying from tech to non tech, to ensure that we are being inclusive in our design and true to the diverse users that will use our website.

**Definition of done**
- conduct the user testing sessions
- analyze and compile the finding 
- share it with tech team for final iteration and discuss the in-scope iteration needed before publishing
- the final website will be share in the CoP.

**Comment by ActionAnalytics** [comment]
Can this be broken into 2 tickets please?  The workshop first, then the analysis + presentation?  Let's refine a bit more in the next session
