### ISSUE TITLE
Make internal training video on how to find a team client in the CRM

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2043]
**Describe the issue**
We will be onboarding more people and having some CRM training material will save us time.

**Additional context**
- Fair amount of learning debt in this ticket
- This is internal facing, so nothing for the demo (the CRM is private)
- The video is intended to be "clicking around and doing stuff"
- There could be a PPT slide or two mixed in if Text is needed

Start demo by opening an example ticket like https://app.zenhub.com/workspaces/cloud-pathfinder-5e4dbb426c3c6af8dcbf06a7/issues/bcgov/cloud-pathfinder/1804
then going over to the CRM, search for the entry in 1804 above, and show the fields, what they mean, then click edit, and make a new update to the "Latest Update" field.  Also demonstrate how to add a person to one of the email fields (open a new mail in outlook, autocomplete their email and name, copy paste it into the CRM in the right field, then add a semi-colon after, hit save).  Then show how to copy paste from the CRM contact field into an email, explaining that's why we use the format of email and semi-colon separator.

**Definition of done**
- Video about how a new team member can find an entry in the CRM to help them with their ticket in ZenHub.
- Meet with Julian and get trained on the below items
- Figure out with the team's help how to make a video in Windows (what format, how to edit and stitch together etc)
- Try to capture the clicks, or a doc accompanying with clicks.  QuickTime on Mac yes, but on Windows?
- Narrated training video demonstrating filters, how to find a particular entry, the different data views, how to edit
- Have a section explaining gotchas (known bugs, little problems that could surprise a new user)

**Comment by snowflakebunny** [comment]
Might need to create a storyboard to outline and visualize what we plan to show.

**Comment by snowflakebunny** [comment]
If using synthesia for AI avatar, there will be monthly fee 30 Dollars for personal account. For corporate account, need to book a demo.
Now using the free software Clipchamp. It makes Text to Speech video for free.

**Comment by snowflakebunny** [comment]
Had a review session with Omo. Went through the DOD. Need to add a part for demonstrating filters. Wait for Julian back for adding a section explaining gotchas (known bugs, little problems that could surprise a new user).

**Comment by snowflakebunny** [comment]
Added the part for demonstrating filters. Wait for Julian back for adding a section explaining gotchas (known bugs, little problems that could surprise a new user).
