### ISSUE TITLE
GCP service BluePrint - Future state

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#2045]
**Describe the issue**
After capturing the current state of the GCP service process, the service team will collaborate with the PO / or team to brainstorm on the future state. 

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- connect with PO to decide who from the team will be valuable to participate in the sessions
- book meeting with the designated members
- capture all the sessions into a clear service blue print

**Comment by ActionAnalytics** [comment]
I think we need to refine this one a bit more.  This currently reads as "solution GCP" and that's an epic.  I think let's focus on the website work and we will pick this up in the estimate.

**Comment by gautammalhotra21** [comment]
Closing this and creating a new ticket with the updated template.
