### ISSUE TITLE
Automatic or Semi Automatically sketch the network diagram based on AWS CLI network related enquiry result

### ISSUE THREAD

**Issue by bruce-wh-li** [bcgov/cloud-pathfinder#2051]
**Describe the issue**
Check Point CloudGuard only provides network configuration under the workload account

**Additional context**
Draw.io is able take csv and converted to a nice diagram
There are OSS available for this purpose such as cloudcraft
This is not the same as HUB and Spoke diagram for network traffic monitoring
Warren U. suggests the following tools:
https://aws.amazon.com/solutions/implementations/aws-perspective/
https://nubenetes.com/cloud-arch-diagrams/

**Definition of done**
1. Export AWS network configuration from json to csv
2.  Import CSV to DrawIO
3. Check the best available OSS.

**Comment by lukegonis** [comment]
Closing this issue as it is no longer within out scope
