### ISSUE TITLE
SPIKE: Design production ready ROSA compatible SCPs and deployment workflow

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#2054]
**Describe the issue**
The current SCPs that were modified for ROSA are not production ready. Design a set of SCPs and a deployment workflow that is production ready (PBMM compliant)

**Additional context**
- The current ROSA SCPs were modified to get the installer to work without much thought towards compliance
- We are assuming that this is the solution, Ryan J might have another idea that expands the scope

**Definition of done**
- Meet with Ryan J and document any PBMM violations due to the current ROSA SCPs
- Work with Ryan J to design new SCPs that allow ROSA to be deployed and are still PBMM compliant
- Document any resources such as AWS roles that would need to be created by the ASEA or by the BC Gov automation as part of the account provisioning
- Document any violations

**Comment by ActionAnalytics** [comment]
We might not need to do this based on new info from the RedHat Black Belt team (Warren investigating, needs to be validated though)

**Comment by wrnu** [comment]
Here is a link to the blog the outlines the ROSA deployment without modified SCPs

https://mobb.ninja/docs/rosa/rosa-asea-landing-zone/
