### ISSUE TITLE
Terraform Cloud PIA

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2057]
**Describe the issue**
Bruce has reviewed TFC extensively for a STRA/SoAR so there is a lot of material to reuse.  We would like a PIA that covers the current usage of TFC.

**Additional context**
- Keep in mind that the current usage might be replaced by another pattern.  We are having trouble getting this pattern ready though, so it's worth it to create a PIA to cover our current way of using TFC.

**Definition of done**
- Book a 2hr meeting with Bruce and have him walk through TFC, the way that CPF uses it (there are a lot of features we ignore which will help with the scope reduction of the PIA as TFC is a huge product)
- Pull down a new PIA template and the old AWS template and try to keep to the same level of high level concepts rather than detailed minutia.  This will require gaining a good understand from Bruce first about the team usage patterns.
- Review the PIA draft with PO in a half-hour session.

**Comment by garymatics** [comment]
Met with IMB & PCT to review draft. Shared revised draft (addressing PCT questions) with IMB & PCT for further review.
