### ISSUE TITLE
Manage access to FW appliances

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2061]
**Describe the issue**
The ability to reach the Firewalls needs to be further constrained.  

The people on our team that work with the FWs are working from remote locations outside of BC Gov's internal network and some of them don't have VPN capability.

**Additional context**
- FW's need updates and are connected to the internet gateway
- Update server domain names should be easy to find, and we just need to configure features correctly.
- It might be time to push back on Check Point on the original specification of NOT updating the firewalls and instead re-running the AMI.  The patches should be done at the AMI level.

**Definition of done**
- Book a 30min meeting with Ryan J, Warren and Julian to discuss any SEA config changes that would need to made to close off the access
- Try in ECF Forge first
- Deny list priority first, Allow second (zero trust model)
- Contact Check Point and get a stable update URL/IP that we can enter into the allow list (we don't want to have to keep updating it)
- Save before/after by screenshots in a private browser mode (we might show SecOps in an update)
- Save a snapshot of the traffic log, we can look again later and confirm it's working.

**Comment by bruce-wh-li** [comment]
The list of Check Point Cloud Server List to be connected to get update is as follow: https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk83520

**Comment by bruce-wh-li** [comment]
List of Applications and their category to be reviewed in order to decide what is bad application needs to deny access: https://appwiki.checkpoint.com/appwikisdb/public.htm

**Comment by bruce-wh-li** [comment]
List of Url Filtering Categorization to be reviewed in order to decide to allow or deny : https://urlcat.checkpoint.com/urlcat/categories.htm

**Comment by bruce-wh-li** [comment]
List of Url Filtering Categorization to be reviewed in order to decide to allow or deny : https://urlcat.checkpoint.com/urlcat/categories.htm

**Comment by bruce-wh-li** [comment]
Kibana graph looks promising.   https://www.elastic.co/guide/en/kibana/current/graph-configuration.html

**Comment by bruce-wh-li** [comment]
We have completed enforcing the blocking internet access to fw in ECF Forge.   Will need to continue on Assembly and Live.

**Comment by bruce-wh-li** [comment]
Enabled URL Filtering and Application Control Blades.   Added the url filtering rule.
