### ISSUE TITLE
Front Counter training

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2062]
**Describe the issue**
The users need responsive customer service and the needs more people responding to users/prospective customers.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Attend 5 or more meetings with the PO to get to know the processes (apprentice approach to learning)
- Cap to a 3

**Comment by snowflakebunny** [comment]
Attended second training session on Sep 29th. with. Julian trained Catherine to add three templates in outlook using Quick Parts. The templates are copied in Teams CPF Gov FTE Internal "Front Counter" folder.

**Comment by ActionAnalytics** [comment]
Still ongoing but will close next sprint
