### ISSUE TITLE
SPIKE: Loop in with SAP\Hana group to see if connections issues

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#2064]
**Describe the bug**
Regarding connectability to their current Azure-based project instance, the SAP\Hana group is in the midst of testing whether or not they would move from an on-prem SAP infrastructure currently in place to an entirely Cloud-based SAP solution.  They have generated an SAP environment in Azure and are having either periodic connection issues and\or sustained issues from certain Government locations, and need both a solution to these as well as to see if general connection quality can be improved going forward

**Additional context**
SAP\Hana group still exploring the possibility of using Cloud-based SAP.  Overall they have been experiencing different types of connection issues to their environment and have escalated these issues to Hosting\David Ell so they can be addressed sooner than later.  David already let them know that this is all on a 'best effort' basis however has asked that we follow up with them to help to either resolve them or provide guidance on what further would be necessary to improve their situation.  David also mentioned that if they did 3rd party out this Azure SAP\Hana instance to a vendor that we will eventually bring online a capability to possibly direct-connect with their remotely hosted SAP enviro but that this would be a fairly long way off at this point.  For now we will try to address what can be done and if there is any further improvement that can be made to their situation we will attempt to draw that out

Search CRM "4HANA" for details.

Priority is being drive by Jon realizing it's been a while since we helped them, wanting to follow up.

**Definition of done**
- Timebox to 2 hours
- Reach out to the SAP/4Hana team and see if they still have connection/issues
- Receive summary of current issues to start
- Eval issues and prioritize
- Follow up with Hosting (Brian Price) to discuss situation
- Get back to SAP group with initial recommendations
- Follow up with SAP group and prioritize once more details known
- Get back to David Ell with light email/teams message saying "Search CRM "4HANA" for details" summary and path forward once this becomes clear and he may follow up with their Director
- Decide if any further tickets\actions need to be created as follow up here and create as necessary

**Comment by ActionAnalytics** [comment]
Please hold off on this until it is prioritized into sprint.

**Comment by jon-mc-git** [comment]
SAP\Hana team has not mentioned any continued issue around connectivity so problem is considered solved.  Closing ticket
