### ISSUE TITLE
SPIKE: Investigate Separating AWS Workload Login Roles by Environment

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#2067]
**Describe the issue**
The Forest Client API team has brought up a security concern. They want to be able to separate access to a project set by account (dev/test/prod) instead of having the same, universal access to the project set. This is a concern because a developer might want to be an "Admin" user in the dev account, but should not have those same permissions in the Prod account. Even the "Developer" role has the ability to delete things in the dev, test, and prod workload accounts.  

**Additional context**
- The only difference between "Developer" and "Admin" roles is the ability to create AWS Roles and Policies

**Definition of done**
- Investigate how to make this change to our infrastructure
  - See comment section of this ticket 
- Investigate what migrations (if any) might need to take place
- Meeting with the tech team to discuss our current role structure (is there a need for both "Admin" and "Developer" roles, or can they be amalgamated?)
- Create tickets for this work to be completed

**Comment by MaxWardle** [comment]
Warren proposed we change to the structure of the roles that I think accomplishes both goals of isolating production as well as making the "Developer" role more useful (both of these issues have been brought up by multiple teams). The solution was to:
- Increase the access levels of "Developer" from "PowerUserAccess" to "AdministratorAccess"
  - This would allow the developer role to be useful as they could create roles and policies which are needed to create and manage a lot of other AWS resources.
- Remove all Prod account access from the Developer role and limit them to Tools, Dev, and Test
  - This addresses the security concern that not all developers should have access to production

**Comment by ActionAnalytics** [comment]
Interesting.  Administrator role would then be the one to access Prod only.
