### ISSUE TITLE
Embed StackOverflow in the FAQs section of the new public cloud website

### ISSUE THREAD

**Issue by gautammalhotra21** [bcgov/cloud-pathfinder#2068]
**Describe the issue**
In order to better manage the FAQs section on the new public cloud website, the CPF team wants to check if it is possible to embed the StackOverflow page on the Wordpress. 

**Additional context**
The StackOverflow page will help to manage questions/queries from users without needing to manually maintain the FAQs on the wordpress site.
[](https://stackoverflow.developer.gov.bc.ca)

**Definition of done**
If GDX team is building the wordpress site, get confirmation from team whether StackOverflow page can be embedded in the new public cloud website or not.
If the StackOverflow page can be embedded, check whether it is fully functional within the wordpress site.

**Comment by mitovskaol** [comment]
I don't see the need to embed the Stackoverflow page in WordPress, we can just include the link to the SOF site from the WP.
