### ISSUE TITLE
Patch ASEA before Nov 14th (this is a mini Epic - need to refine with Team)

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2069]
**Describe the issue**
NodeJS12 is being deprecated Nov 14th by AWS but is used throughout the ASEA.  We need to run the patch that will be coming out soon that fixes this issue. 

The patch just came out October 6th and is ready for us to get working on it.  We need to break down this ticket in Refinement so we can coordinate together.

**Additional context**
- https://github.com/aws-samples/aws-secure-environment-accelerator/issues/1033
New version is now released and ready for use: https://github.com/aws-samples/aws-secure-environment-accelerator/releases

**Definition of done**
- **Update login app from NodeJS 12 to latest  [Max]**
- **Run pre-patch test measurements  [Carles]**
   - Baseline pre-patch is done  [Carles]
- Pull down patch and apply to Assembly [Warren, Prabhu, Max]
- **Notify community, apply to Live, notify community all is well [Max]**
- Custom query in CSPM for NodeJs version [Prabhu] or 
  **- [Might not need if above works] Scan and see which teams are using Lambda's using NodeJS12 [Carles?  Possible within time?  Look for Lambda's other than PBMM]**
for 3 ECFs in order - if we run out of time we may need to break the process and focus on Live because we don't want workloads going off]
- **Run post-patch test measurements (hopefully no breaking changes)  [Carles]**
   - **Regression test after patch is done (including project set, sample app deployment)  [Carles]**
- **If breaking changes, fix in Forge, repeat above in Assembly until tests pass [Prabhu]** 
- **Serverless demo app uses NodeJS12 and break - needs to be updated [Warren]**

**Comment by wrnu** [comment]
Close, no longer relevant (and done)
