### ISSUE TITLE
SecOps Defender - VM public IP investigation

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#2070]
**Describe the issue**
Aid in the investigation or wrap up the investigation if enough progress cannot be made with current TRAN parties involved.  

This is an idea Jon had after a collaboration with SecOps on the use of public IPs in Azure and Defender's configuration capabilities.  There is no client specifically asking for this but this is a "poke-and-prod" idea that Jon had.

**Additional context**
- Originally there was a policy that said you can't spin up a public IP
- If someone spins up a non-conforming VM but it's not connected to anything else, then Jon says ok to have someone deploy a public facing VM image.
- RDP based issue - Public interface
- This is an idea to see if there is something better we can do, this one is "low-priority", dependant on Azure status

**Definition of done**
- Investigate any remaining issue(s) needed
- Help resolve investigation request
- Aid TRAN in preventing this in the future where possible

**Comment by lukegonis** [comment]
Closing as this issue is no longer relevant
