### ISSUE TITLE
SPIKE: Determine a KeyCloak Realm Architecture for Multiple Cloud Platforms

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#2080]
**Describe the issue**
The SSO Pathfinder Team has informed us that having multiple custom realms is not scalable for them and the KeyCloak is only designed to handle around 40 - 50 realms. WE currently have two realms (one for AWS and one for Azure/ GCP) in their silver cluster, but when we move to their gold cluster they're asking if its possible for us to scale back to using one realm to manage all of our platforms. 

**Additional context**
- Consider edge cases like having different contexts if you need to different configurations, you require more than one realm.
- SSO model cannot support multi configs
- This is not considering the gold migration
- Moving Forge and Assembly to the Live realm would probably be the easiest way to go as to not disturb our users
- You can export/ import KC realms

**Definition of done**
- Find out what version it is and tell Warren as it will help him over in GCP land (we're looking for the name-ID-mapper feature)
- Determine if it's possible/ reasonable to use one KeyCloak to manage all of our platforms
- Make a diagram or document describing the design and migration process if we're going to use one realm
- Make tickets for any implementation work

**Comment by MaxWardle** [comment]
Moved back to prioritized backlog as it was blocked for multiple sprints and doesn't align with sprint goals.

**Comment by lukegonis** [comment]
This is no longer needed
