### ISSUE TITLE
To create a HUB and Spoke Graph to visualize VPC Traffic in ECF Live

### ISSUE THREAD

**Issue by bruce-wh-li** [bcgov/cloud-pathfinder#2081]
**Describe the issue**
To enhance AWS SIEM Dashboard to add a HUB-Spoke Graph

**Additional context**
Prerequisite : Kibana x-pack graph
In private tenant
- This would be a very nice to have item for Onboarding SecOps Compliance Users

**Acceptance Criteria**
- The HUB-Spoke network traffic diagram can be filtered by 
 - Account, VPC
 - Source IP
 - Destination IP 
 - Accept Traffic
 - Deny Traffic
- Screenshot of the updated Private Dashboard

**Comment by lukegonis** [comment]
Closing as we have shut down the AWS SIEM
