### ISSUE TITLE
Create a internal training video on how to use CRM

### ISSUE THREAD

**Issue by OmoAttah** [bcgov/cloud-pathfinder#2082]
**Describe the issue**
We want to save time for future users to onboard CRM and understand how to navigate through.

**Additional context**

- Fair amount of learning debt in this ticket

- This is internal facing, so nothing for the demo (the CRM is private)

- The video is intended to be "clicking around and doing stuff", no voice or face work.

- There could be a PPT slide or two mixed in if Text is needed

**Definition of done**

- Meet with Julian and get trained on the below items

- Figure out with the team's help how to make a video in Windows (what format, how to edit and stitch together etc)

- Silent screen recording training video demonstrating filters, how to find a particular entry, the different data views, how to edit

- Have a section explaining gotchas (known bugs, little problems that could surprise a new user)

**Comment by ActionAnalytics** [comment]
Dup, no problem, pls see 2043
