### ISSUE TITLE
Tune Cloud.Pathfinder email autoresponder

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2102]
**Describe the Issue**
We have an autoresponder in place but it's too agressive in that it responds to calendar response events (for example, someone accepts a meeting invite from cloud.pathfinder and sends the autoreply about accepting the meeting, they will trigger the other autoresponse from cloud.pathfinder)

**Additional Context**
- Unknown if this is even possible
- The automation happens on the Exchange Server, we may not have control.  Might be possible to make a request to the Exchange Admin via a 77000 request.

**Acceptance Criteria**
- reproduce by creating a meeting invite from cloud.pathfinder to your personal gov email, accept the invite, see if it generates an autoresponse
- tune the auto-responder in cloud.pathfinder so it doesn't spam every meeting accepted response
- test after fixing by creating a meeting invite from cloud.pathfinder to your personal gov email, accept the invite, see if it generates an autoresponse
- if not possible, create tickets to create a separate mailbox only for calendar invites.

.
.
.
.
.
.
.
.

**Extra Template Info**

***Definition of Ready***
These set of conditions will need to be met in order to bring a ticket into the sprint and start work. Protects the team from unclear requirements.
Issues (Task/Story/Spike) aligned to an EPIC and linked appropriately.
Assigned to the appropriate CPF MEMBER (and is not left blank in ZenHub) at the start of sprint (1st day of the sprint)
Acceptance has been defined for the issue and has been reviewed with CPF team and approved by the necessary approver.
Has been sized and estimated by the delivery team.
Detailed breakdown of the steps required to complete the story in the additional context
Any additional specifications have been documented, reviewed with CPF and approved by the necessary approver.

***Acceptance Criteria***
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.
It should be testable with no room for interpretation
It should be either “pass” or “fail”
It should be clear enough for business stake holders to understand
As part of the user story, it should be written from the user perspective
A well written acceptance criteria is great for 
- managing expectations
- defining scope
- reducing ambiguity
- establishing testing criteria for QA
Given (Pre-condition) 
When (Action)
Then (Outcome)

***Definition of Done***
These set of conditions are met for work to be considered as complete on an issue.
All acceptance criteria(s) have been validated.
All the necessary documentation for the issue has been uploaded to Teams.
Functionality has been tested when applicable.
Functionality has been demonstrated to the relevant stakeholders (where applicable).
Story has been scheduled for a Sprint Demo/community update and impacted teams invited to the Demo.
Stories accepted by PO and documented for potential sharing with impacted users.
- Documented = Captured in Community Update (CU) deck
- Release notes = aspirational goal of providing a bulleted list of features and changes that our users can touch. Was going to store them in our Cloud Pathfinder repo. Can also display to users in the CU

**Comment by snowflakebunny** [comment]
Created a meeting invite from cloud.pathfinder to my personal gov email, accepted the invite by " Send the Response Now", it did not generate an auto response.

**Comment by ActionAnalytics** [comment]
Looks like we have a bug in OSX (Mac) Outlook where even if we turn on the autoreply it doesn't stick.  If we turn it on from Windows Outlook it works.

**Comment by snowflakebunny** [comment]
Called 77000, the suggestions is to manually turn auto response on and off.

**Comment by snowflakebunny** [comment]
Close this ticket with Julian, we tried, and it did not work.
