### ISSUE TITLE
Organize a kick-off meeting with Technical Stewardship (in prep for Snowcone beta)

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2111]
**Describe the Issue**
Brian P is our main contact in Technical Stewardship.  We're wanting his help to working with Advanced Solutions.

**Additional Context**
- Predict emails back and forth to manage, and some extra effort to keep forward momentum
- Pre and post discussion to get Health going.  Procedural, Authorization; resolve those
- 3 slide presentation from Advanced Solutions on their solution for Snowcone usage in the data centres
- Invite Brian P (ask him to please forward to ADSL (Advanced Solutions)), David E, Rick C, Sorin P, Julian S, Nick C, Olena M.
- Meeting should be to discuss this request which we have already sent in and settle it so blocked ticket is addressed 

**Acceptance Criteria**
- Request to Tech Stew a ADSL presentation on proposed solution for AWS Snowcone data transfer 
- Ensure invite sent for this meeting at the start of sprint, meeting can occur later in week 1 or 2.
- Meet with Rick and\or Sorin for pre-meeting discussion
- Prep technical notes pre-meeting 
- Facilitate meeting to drive outcome to resolution
- Answer any quick questions that ADSL may have to remove obstacles

.
.
.
.
.
.
.
.
.
.
.

**Extra Template Info**

***Definition of Ready***
These set of conditions will need to be met in order to bring a ticket into the sprint and start work. Protects the team from unclear requirements.
Issues (Task/Story/Spike) aligned to an EPIC and linked appropriately.
Assigned to the appropriate CPF MEMBER (and is not left blank in ZenHub) at the start of sprint (1st day of the sprint)
Acceptance has been defined for the issue and has been reviewed with CPF team and approved by the necessary approver.
Has been sized and estimated by the delivery team.
Detailed breakdown of the steps required to complete the story in the additional context
Any additional specifications have been documented, reviewed with CPF and approved by the necessary approver.

***Acceptance Criteria***
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.
It should be testable with no room for interpretation
It should be either “pass” or “fail”
It should be clear enough for business stake holders to understand
As part of the user story, it should be written from the user perspective
A well written acceptance criteria is great for 
- managing expectations
- defining scope
- reducing ambiguity
- establishing testing criteria for QA
Given (Pre-condition) 
When (Action)
Then (Outcome)

***Definition of Done***
These set of conditions are met for work to be considered as complete on an issue.
All acceptance criteria(s) have been validated.
All the necessary documentation for the issue has been uploaded to Teams.
Functionality has been tested when applicable.
Functionality has been demonstrated to the relevant stakeholders (where applicable).
Story has been scheduled for a Sprint Demo/community update and impacted teams invited to the Demo.
Stories accepted by PO and documented for potential sharing with impacted users.
- Documented = Captured in Community Update (CU) deck
- Release notes = aspirational goal of providing a bulleted list of features and changes that our users can touch. Was going to store them in our Cloud Pathfinder repo. Can also display to users in the CU

**Comment by ActionAnalytics** [comment]
2 week hold until contract renewal process on the hosting side.  Due to vacations on other teams.  Jon to email Sorin and Rick, let them know we're pausing this for 2 weeks.  Book an appt for two weeks from now to signal to them that we won't forget.

**Comment by jon-mc-git** [comment]
Discussion held with Health on latest with this.  A meeting is now scheduled as a first step in a kickoff process with their consultant which will be attending, and the next with Hosting will follow.  Closing ticket
