### ISSUE TITLE
Create the mailing lists in outlook

### ISSUE THREAD

**Issue by snowflakebunny** [bcgov/cloud-pathfinder#2119]
**Describe the Issue**
We want to use the updated mailing lists so that if someone declines the series, we can remove them (otherwise we end up hammering them with invites they don't want).

It also makes communicating with our Community much easier

**Additional Context**
- We will need to keep the Exchange Server hosted mailing lists manually up to date with the excel file below.  What this means is if someone Declines the invite or requests to be removed, we need to remove them also from our excel list (or if they are still in the cloud, maybe make a column and filter that says 'requested to be removed' with a little note explaining why).

**Acceptance Criteria**
- Log in to Outlook on a Windows machine
- Go to manage the mailing lists
- Copy the mailing list from Teams Excel (Front Counter/Mailing Lists/Mailing Lists.xlsx) into Outlook

.
.
.
.
.
.
.
.
.
.
.

**Extra Template Info**

***Definition of Ready***
These set of conditions will need to be met in order to bring a ticket into the sprint and start work. Protects the team from unclear requirements.
Issues (Task/Story/Spike) aligned to an EPIC and linked appropriately.
Assigned to the appropriate CPF MEMBER (and is not left blank in ZenHub) at the start of sprint (1st day of the sprint)
Acceptance has been defined for the issue and has been reviewed with CPF team and approved by the necessary approver.
Has been sized and estimated by the delivery team.
Detailed breakdown of the steps required to complete the story in the additional context
Any additional specifications have been documented, reviewed with CPF and approved by the necessary approver.

***Acceptance Criteria***
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.
It should be testable with no room for interpretation
It should be either “pass” or “fail”
It should be clear enough for business stake holders to understand
As part of the user story, it should be written from the user perspective
A well written acceptance criteria is great for 
- managing expectations
- defining scope
- reducing ambiguity
- establishing testing criteria for QA
Given (Pre-condition) 
When (Action)
Then (Outcome)

***Definition of Done***
These set of conditions are met for work to be considered as complete on an issue.
All acceptance criteria(s) have been validated.
All the necessary documentation for the issue has been uploaded to Teams.
Functionality has been tested when applicable.
Functionality has been demonstrated to the relevant stakeholders (where applicable).
Story has been scheduled for a Sprint Demo/community update and impacted teams invited to the Demo.
Stories accepted by PO and documented for potential sharing with impacted users.
- Documented = Captured in Community Update (CU) deck
- Release notes = aspirational goal of providing a bulleted list of features and changes that our users can touch. Was going to store them in our Cloud Pathfinder repo. Can also display to users in the CU

**Comment by snowflakebunny** [comment]
In Outlook, Click "People" and then "New Contact Group"; Give a name and add members from Address book, the paste the email list from excel.

**Comment by ActionAnalytics** [comment]
Looks like no easy way to bulk insert, especially for people outside our org, so one at a time unfortunately.  Thanks in advance

**Comment by snowflakebunny** [comment]
![Screenshot 2022-10-19 232421 (2).png](https://images.zenhubusercontent.com/6307c50c59d10067e80d218c/164ccb8f-600e-4d58-9e6f-b6c85940f27d)

**Comment by snowflakebunny** [comment]
![Screenshot 2022-10-19 232421 (2).png](https://images.zenhubusercontent.com/6307c50c59d10067e80d218c/2d632e05-dbf5-42b5-bf3f-3f84ebfdc2ec)

**Comment by snowflakebunny** [comment]
Completed PO Cop list and Compliance Cop list, need one or two hours to make a list of emails that are not in the GAL for Developer Cop list.

**Comment by snowflakebunny** [comment]
Acquired ownership of three lists. Tested, remove membership in Outlook is allowed. Add membership in Outlook it not allowed. Still need to create MySC tickets.

**Comment by snowflakebunny** [comment]
Attached the mails contacts that are not in the GAL in the MySC ticketing System. Tested, it did not add membership to the distribution list from the attached spreadsheet.

**Comment by snowflakebunny** [comment]
Did some research in My SC portal and found Manage External Email/Mailbox. Will make a ticket to add mails contacts that are not in the GAL.

**Comment by snowflakebunny** [comment]
A user can only have either a government email address OR an external email address, not both.

**Comment by snowflakebunny** [comment]
Create another ticket for the rest of External Email/Mailboxes that are not able to add to the GAL.
