### ISSUE TITLE
First pass validation testing for New OIDC deployment documentation

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#2150]
**Describe the Issue**
There is a new pattern for demo app deployments that we wish to have the community switch over to that addresses key rotation and avoids blocking pipelines.

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- Follow the documentation instructions in a clean project-set in AWS ECF Forge
- Place yourself in the mental mindset of our compliance and product owner users
- Pick Containers sample app (recall there will be a new repo to focus on)
- Validate the documentation for ease of use, clarity and no missing steps.  Cap to a 3 effort, make additional tickets if more effort needed.

**Comment by crochcunill** [comment]
Project set **s7g5b4** (dev and tools) was created in Assembly (Forge was experiencing problems ) with the github-oicd layer

Using OIDC authentication, the sample containers app was deployed in the previous project set. It was found the policies crafted in #2149 didn't allow to deploy the app. The policies were edited to allow the deployment, however there is still one step that does not work with the current policies. Bug #2250 was created to look into it and create a policy (in tools) that will allow to execute the _docker_build_ step

**Note**: sample containers app was successfully deployed by using a permissive policy to bypass the problematic step. This approach was used to probe the problem arose from a too restrictive of a policy and not a problem with the app itself.

Extensive notes to document the procedure will became part of #2226
