### ISSUE TITLE
Cross-compare Azure environments with what is in CRM to ensure the CRM is representative of what is currently running

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#2155]
**Describe the Issue**
To ensure there is no discrepancy between what we have in CRM and what is running in Azure

**Additional Context**
David Ell asked us to ensure there is alignment here as he gets calls and needs to know that the CRM is up to date and aligned with what is currently running under us in Azure

**Acceptance Criteria**
- BC Gov Azure tenancy review
- Verify what is currently running as workloads in Azure has representation to an appropriate CRM entry
- Verify if CRM has any that no longer have an environment in Azure, or need a status update

.
.
.
.
.
.
.
.
.
.
.

**Extra Template Info**

***Definition of Ready***
These set of conditions will need to be met in order to bring a ticket into the sprint and start work. Protects the team from unclear requirements.
Issues (Task/Story/Spike) aligned to an EPIC and linked appropriately.
Assigned to the appropriate CPF MEMBER (and is not left blank in ZenHub) at the start of sprint (1st day of the sprint)
Acceptance has been defined for the issue and has been reviewed with CPF team and approved by the necessary approver.
Has been sized and estimated by the delivery team.
Detailed breakdown of the steps required to complete the story in the additional context
Any additional specifications have been documented, reviewed with CPF and approved by the necessary approver.

***Acceptance Criteria***
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.
It should be testable with no room for interpretation
It should be either “pass” or “fail”
It should be clear enough for business stake holders to understand
As part of the user story, it should be written from the user perspective
A well written acceptance criteria is great for 
- managing expectations
- defining scope
- reducing ambiguity
- establishing testing criteria for QA
Given (Pre-condition) 
When (Action)
Then (Outcome)

***Definition of Done***
These set of conditions are met for work to be considered as complete on an issue.
All acceptance criteria(s) have been validated.
All the necessary documentation for the issue has been uploaded to Teams.
Functionality has been tested when applicable.
Functionality has been demonstrated to the relevant stakeholders (where applicable).
Story has been scheduled for a Sprint Demo/community update and impacted teams invited to the Demo.
Stories accepted by PO and documented for potential sharing with impacted users.
- Documented = Captured in Community Update (CU) deck
- Release notes = aspirational goal of providing a bulleted list of features and changes that our users can touch. Was going to store them in our Cloud Pathfinder repo. Can also display to users in the CU

**Comment by lukegonis** [comment]
This is a priority, would be great to get into the next Sprint.

**Comment by jon-mc-git** [comment]
CRM and Azure tenancy review completed, and summary documentation created for review by team.  Future service design/planning tickets will be created from these results.  Closing
