### ISSUE TITLE
Automate setup of AWS budgets and alerts

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#219]
**Describe the issue**

Within public cloud environments, the charge model fro many services is "usage based", rather than fixed/upfront.  With this model, charges accrue over time based on traffic, time, or other attribute.  Additionally, deployment of applications in public cloud environments may involve usage of many, many services, each with their own cost and usage model. The result is that costs for a given application within a given time period may not be predictable at deployment time.  Often, teams will find out about usage costs only at the end of a billing cycle, typically at the end of a month.  If the usage has not been inspected prior to month end, the charges may be at an unexpected level, but it will be too late to mitigate the cost by adjusting service or application parameters since bills are retroactive.

AWS provides budgeting functionality that allows teams to configure limits at which they will receive alerts about costs or consumption.  This is a useful feature that can help teams avoid unexpectedly large bills.  However, budgeting and alerts are not set up by default within AWS organizations/accounts.

We would like to provide a facility within our account provisioning automation to include simple configuration of budgets and alerts so teams do not need to manually configure budgets.  This could provide a sort of "financial guardrail" for every account.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**

Organization-level budgets and notifications have been created (manually) as a separate activity and the Cloud Pathfinder team will receive these notifications.

**Definition of done**
- Terraform code is developed and tested, and included in the project provisioning "stack"
- Update the project_set_admin.py script to support budgets
- Code is documented and committed to GitHub

**Comment by mitovskaol** [comment]
A good priority for the next Sprint Jan
