### ISSUE TITLE
To verify that all egress traffic is routed through the firewall

### ISSUE THREAD

**Issue by bruce-wh-li** [bcgov/cloud-pathfinder#2199]
**Describe the Issue**
As a security analyst, we want to verify that all egress traffic is routed through the firewall

**Additional Context**
- To do this in forge
- use smart consoles to view the logs

**Acceptance Criteria**
- Create manual test cases which will do the following
From an EC2 instance in a workload account, verify that egress traffic is routed though the firewall. Provide screenshot of firewall log

**Comment by crochcunill** [comment]
Possible test case:
- Log in to m9tvhw-dev account
- Go to EC2 instances, and open **ssp-finer-mutt**
- Click the _Connect_ button
- Select _Session Manager_ tab
- Click the _Connect_ button
- In the terminal like screen, create some egress traffic, for example

> curl https://www.google.com

- Open a AWS console for the perimeter account for the zone

**Comment by crochcunill** [comment]
Test case successful. The egress traffic from EC2 instance is routed through the firewall
