### ISSUE TITLE
SPIKE:  CRM data - Review CITZ IMB possible use-case 

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#2239]
**Describe the Issue**
Review possible use-case of sharing internal team CRM data outside of our organization stack, to in this case CITZ IMB 

**Additional Context**
Normally CRM data for any organization is considered internal, and if there is sharing to happen for certain fields within the larger org it's through more sophisticated platform CRM tools.  Our internal Pathfinder CRM is not very evolved, so the idea here is to share where necessary some internal info with our Ministry's IMB.  Note that client data submission is normally for Pathfinder to coordinate, onboard and execute the Cloud workload environment.  Use of it outside of this has not yet been considered.

**Acceptance Criteria**
- Gather requirements from CITZ IMB
- Review the need of sharing certain info (still within our Ministry) outside Pathfinder
- See if there is any other way to get CITZ IMB what they need
- Review the client internal information contained within their submissions and its original purpose and take this into consideration - ie.They submit this data for the purpose of getting onboarded and receiving a Cloud enviro to work within, so the current request\use-case (still within our Ministry) will be considered 
- Check-in with Gary 

.
.
.
.
.
.
.
.
.
.
.

**Extra Template Info**

***Definition of Ready***
These set of conditions will need to be met in order to bring a ticket into the sprint and start work. Protects the team from unclear requirements.
Issues (Task/Story/Spike) aligned to an EPIC and linked appropriately.
Assigned to the appropriate CPF MEMBER (and is not left blank in ZenHub) at the start of sprint (1st day of the sprint)
Acceptance has been defined for the issue and has been reviewed with CPF team and approved by the necessary approver.
Has been sized and estimated by the delivery team.
Detailed breakdown of the steps required to complete the story in the additional context
Any additional specifications have been documented, reviewed with CPF and approved by the necessary approver.

***Acceptance Criteria***
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.
It should be testable with no room for interpretation
It should be either “pass” or “fail”
It should be clear enough for business stake holders to understand
As part of the user story, it should be written from the user perspective
A well written acceptance criteria is great for 
- managing expectations
- defining scope
- reducing ambiguity
- establishing testing criteria for QA
Given (Pre-condition) 
When (Action)
Then (Outcome)

***Definition of Done***
These set of conditions are met for work to be considered as complete on an issue.
All acceptance criteria(s) have been validated.
All the necessary documentation for the issue has been uploaded to Teams.
Functionality has been tested when applicable.
Functionality has been demonstrated to the relevant stakeholders (where applicable).
Story has been scheduled for a Sprint Demo/community update and impacted teams invited to the Demo.
Stories accepted by PO and documented for potential sharing with impacted users.
- Documented = Captured in Community Update (CU) deck
- Release notes = aspirational goal of providing a bulleted list of features and changes that our users can touch. Was going to store them in our Cloud Pathfinder repo. Can also display to users in the CU

**Comment by lukegonis** [comment]
Closing this issue as it can now be done via the Registry.
