### ISSUE TITLE
Deploy Serverless Sample Application in ECF Live, Project Set hjywb9

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#2262]
**Describe the Issue**
To finish the technical onboarding the last step is that we get teams to deploy a sample application into their new workload accounts. The extra infrastructure to deploy the [Serverless sample application](https://github.com/bcgov/startup-sample-project-aws-serverless) has been deployed into hjywb9.

**Additional Context**
- This application uses "infrastructure as code" in the form of a GitHub Actions pipeline, Terraform, and Terraform Cloud to deploy all resources into your AWS accounts
- Some resources on the team:
  - Carles has deployed many of these sample apps before
  - Prabhu, and Warren wrote this application and pipeline if you have any technical questions 

**Acceptance Criteria**
- Fork the serverless sample application repository into your GitHub account
- Setup the `LICENCEPLATE` and `TFC_TEAM_TOKEN` environment variables as stated in the readme
- enable GitHub actions in your repository
- Edit the codebase, a suggestion is to [change the title of the page here](https://github.com/bcgov/startup-sample-project-aws-serverless/blob/455feb584943bb9be5facce9607d35246adcbba9/client/public/index.html#L8)
- Make a pull request to the main branch on **YOUR FORKED REPOSITORY**
  - By default the pull request will go to the bcgov repository's main branch but this will trigger the GitHub Actions pipeline there instead of your fork
  - This pull request will trigger the [pull request workflow](https://github.com/bcgov/startup-sample-project-aws-serverless/blob/455feb584943bb9be5facce9607d35246adcbba9/.github/workflows/pull_request.yml#L6) and will start a [terraform plan](https://github.com/bcgov/startup-sample-project-aws-serverless/blob/455feb584943bb9be5facce9607d35246adcbba9/.github/workflows/pull_request.yml#L47) visible in the [GitHub Actions tab](https://github.com/bcgov/startup-sample-project-aws-serverless/actions) of your fork.
- Once you've looked through the plan, you can merge the pull request which will trigger the [push workflow](https://github.com/bcgov/startup-sample-project-aws-serverless/blob/455feb584943bb9be5facce9607d35246adcbba9/.github/workflows/push.yml#L6) and start the [terraform apply](https://github.com/bcgov/startup-sample-project-aws-serverless/blob/455feb584943bb9be5facce9607d35246adcbba9/.github/workflows/push.yml#L44) and actually deploy the resources into your dev account 
- if all goes well you should be able to see your resources deployed in `hjywb9-dev` and the site should be live at the cloudfront distribution's domain. The domain should be output at the bottom of the logs in the GitHub Actions push run, or you can find it in your dev accounts AWS Web Console > CloudFront.

.
.
.
.
.
.
.
.
.
.
.

**Extra Template Info**

***Definition of Ready***
These set of conditions will need to be met in order to bring a ticket into the sprint and start work. Protects the team from unclear requirements.
Issues (Task/Story/Spike) aligned to an EPIC and linked appropriately.
Assigned to the appropriate CPF MEMBER (and is not left blank in ZenHub) at the start of sprint (1st day of the sprint)
Acceptance has been defined for the issue and has been reviewed with CPF team and approved by the necessary approver.
Has been sized and estimated by the delivery team.
Detailed breakdown of the steps required to complete the story in the additional context
Any additional specifications have been documented, reviewed with CPF and approved by the necessary approver.

***Acceptance Criteria***
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.
It should be testable with no room for interpretation
It should be either “pass” or “fail”
It should be clear enough for business stake holders to understand
As part of the user story, it should be written from the user perspective
A well written acceptance criteria is great for 
- managing expectations
- defining scope
- reducing ambiguity
- establishing testing criteria for QA
Given (Pre-condition) 
When (Action)
Then (Outcome)

***Definition of Done***
These set of conditions are met for work to be considered as complete on an issue.
All acceptance criteria(s) have been validated.
All the necessary documentation for the issue has been uploaded to Teams.
Functionality has been tested when applicable.
Functionality has been demonstrated to the relevant stakeholders (where applicable).
Story has been scheduled for a Sprint Demo/community update and impacted teams invited to the Demo.
Stories accepted by PO and documented for potential sharing with impacted users.
- Documented = Captured in Community Update (CU) deck
- Release notes = aspirational goal of providing a bulleted list of features and changes that our users can touch. Was going to store them in our Cloud Pathfinder repo. Can also display to users in the CU

**Comment by sanakhvn** [comment]
Hi
