### ISSUE TITLE
Design model for shared responsibilities from security(audit, logging, MFA, etc)

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder#231]
**Describe the issue**
We wish to be able to go from a high level shared responsibility model diagram all the way down to the code.
Enumerate Security subdomains (etc)
Capture relevant guidelines from ISB (>>security schedules<<, AWS recommended controls)
We don't have MFA for IDIR, so where is supporting policy around that?
- a design of the system for logging and notification
- addresses lack of security detail in the Shared Responsibilities Diagram
- have a visual representation of the security at the different levels (CSP--OCIO--Ministry)
- a diagram that has security automation pieces captured on it
- responsibility of the ministry and the OCIO on it
- Multi Factor Authentication (MFA)

**Which Sprint Priority is this issue related to?**

**dependencies**

**Value to the MVP**
- Applies to policy, security adoption 
- A document that will help for early adopters

**Additional context**
- Is this to be as a part of the shared responsibility model?
- wish to avoid impedance/mismatch with master diagram.

**Definition of done**
- a PDF containing diagrams
- tied very closely to the Shared Responsibility Diagram
- a draft document that has been reviewed from security, privacy and Cloud Pathfinder at the different layers
- Is Cloud Service Provider CSP agnostic
- Includes up to protected B data.

- Review with Holly and privacy

**Comment by ActionAnalytics** [comment]
Needs to be broken down or re-scoped before approval to work on this item.

**Comment by sid-gov** [comment]
@bluemel-gov - this needs to be broken down to separate tickets i believe since you have enough points on this sprint already. Moving this to product backlog and discuss when you are back.

**Comment by sid-gov** [comment]
Review during Sprint 15 Refinement. @bluemel-gov  @ActionAnalytics
