### ISSUE TITLE
SPIKE: Determine What can be Automated in the Onboarding Process

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#2313]
**Describe the Issue**
We want to automate as much of the Onboarding process as possible. This scope is larger than the "technical" onboarding process.

**Additional Context**
- service blueprint might be out of date, add stickys for updates based on continuing work.
- speak to Carles about technical flow chart

**Acceptance Criteria**
- review the service blueprint and for each step determine whether it can be automated/ streamlined.
- create a flow chart for the "full" onboarding process
  - incorporate Carles's flow chat for the technical process
- create tickets for this work

.
.
.
.
.
.
.
.
.
.
.

**Extra Template Info**

***Definition of Ready***
These set of conditions will need to be met in order to bring a ticket into the sprint and start work. Protects the team from unclear requirements.
Issues (Task/Story/Spike) aligned to an EPIC and linked appropriately.
Assigned to the appropriate CPF MEMBER (and is not left blank in ZenHub) at the start of sprint (1st day of the sprint)
Acceptance has been defined for the issue and has been reviewed with CPF team and approved by the necessary approver.
Has been sized and estimated by the delivery team.
Detailed breakdown of the steps required to complete the story in the additional context
Any additional specifications have been documented, reviewed with CPF and approved by the necessary approver.

***Acceptance Criteria***
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.
It should be testable with no room for interpretation
It should be either “pass” or “fail”
It should be clear enough for business stake holders to understand
As part of the user story, it should be written from the user perspective
A well written acceptance criteria is great for 
- managing expectations
- defining scope
- reducing ambiguity
- establishing testing criteria for QA
Given (Pre-condition) 
When (Action)
Then (Outcome)

***Definition of Done***
These set of conditions are met for work to be considered as complete on an issue.
All acceptance criteria(s) have been validated.
All the necessary documentation for the issue has been uploaded to Teams.
Functionality has been tested when applicable.
Functionality has been demonstrated to the relevant stakeholders (where applicable).
Story has been scheduled for a Sprint Demo/community update and impacted teams invited to the Demo.
Stories accepted by PO and documented for potential sharing with impacted users.
- Documented = Captured in Community Update (CU) deck
- Release notes = aspirational goal of providing a bulleted list of features and changes that our users can touch. Was going to store them in our Cloud Pathfinder repo. Can also display to users in the CU

**Comment by crochcunill** [comment]
Check ticket #1719. I already created a document that hopefully will save you some work.

The document (SelfServeApp.docx) and diagrams (diagram.drawio) created and stored in 
![image.png](https://images.zenhubusercontent.com/620eba1ac6937a4e70b34b15/bd92198a-385a-4c29-8079-c3bde0b007e7)

**Comment by lukegonis** [comment]
Closing this issue as most of the onboarding process has been automated through the registry
