### ISSUE TITLE
Design the web form for project set provisioning in Registry

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/cloud-pathfinder#2320]
CPF Team is building an automated project set provisioning in AWS SEA using the Platform Registry app that is a self serve service for BC Gov employees to submit provisioning requests for the Private Cloud Openshift platform and soon for the public cloud environments. The REgistry service is available at https://registry.developer.gov.bc.ca/ 

The CPF team needs to design a web form for provisioning requests for AWS SEA. The wireframe will be passed to the Registry team for coding and adding to the Registry app .

Definition of Done:
- [ ] a mockup/wireframe for the web page that includes all fields and checks

**Comment by gautammalhotra21** [comment]
https://www.figma.com/proto/llP34TwOrBUjUGey9PUu6c/Platform-Registry?page-id=222%3A16736&node-id=222%3A17162&viewport=1239%2C538%2C0.04&scaling=min-zoom&starting-point-node-id=222%3A16737
