### ISSUE TITLE
Create a list of free AWS Trainng resources for product teams 

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/cloud-pathfinder#2321]
As a product team coming to develop in AWS SEA or maybe only contemplating using AWS SEA as a hosting environment for a new app, I would like to have access to the AWS training resources to better understand how to build apps in AWS SEA.

The CPF Team needs to put together a list of free AWS SEA training and make it available to the product teams on the Public Cloud website.  The list much include SEA specific resources but can only include the generic AWS resources as well.

Tentative plan:
- meet with the tech resources on the team, collect all informational and educations resources that the team is aware of
- meet with Ryan from AWS to review the list and add other resources that he recommends For example, [this blog](https://aws.amazon.com/blogs/publicsector/building-serverless-web-application-architecture-aws-secure-environment-accelerator-asea/) would be a good resource to add to the list.

Definition of Done:
- [x] create a list of AWS and AWS SEA training for product teams and add it to the Technical Docs in GitHub Pages at https://bcgov.github.io/cloud-pathfinder/Documentation/Pre-reading-material/ (add it as a new menu item linking to a new page)
- [x] Add a Q&A about this new resource. Example:  Where can find information about the training available for AWS SEA? The answer is the link to the new pages in the Tech Docs.

**Comment by sanakhvn** [comment]
Hello Olena!
I have collected ASEA Document links upon recommendations and research, I have made a list of ASEA training resources that would be useful to product teams! With the assistance of Prabhu, we've changed the layout to create a new category and incorporate questions and answers page by redirection. Here is the link to the public cloud training resources for SEA. https://bcgov.github.io/cloud-pathfinder/Documentation/Pre-reading-material/001200_training.html
