### ISSUE TITLE
Create service cost profile for all key services used in AWS

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/cloud-pathfinder#2322]
As a Product Owner of the Public Cloud Accelerator  I need to have a better understand of the financial impact of using various services in AWS, existing as well as the services identified for the use in future.

For each service identified in the [Cost Optimization deck] e.g. OpenSIEM, AWS account, Checkpoint firewall, etc -  create a service overview document that includes the following details:

- a 1-2 sentence plain language description of the service and what it is used for
- a 2-3 sentences describing the business value of the service (why it is important for the CPF team or product teams or both to use this service)
- the base monthly cost for using the service e.g. the minimum amount for the service cost
- the current monthly cost of the service
- trend line impact from onboarding new customers (will stay same, will increase, how much will the increase be if known)
 - considerations on whether the cost of the service can be cost be recovered from product teams ( if yes, what are the options - all cost can be recovered or only a portion?)
- consolidation of these parts into an initial ECF-SEA Common Components Summary draft for working review (new ticket)

Include any other services that have not been included in the Cost Optimization deck that generate expenses in AWS today and also include the new services that do not exist today but planned to be purchased in the FY 23/24
DoD:
- [ ] a spreadsheet with the services and the cost analysis is created in the Team's space in MS Teams and the link is included in this ticket.

**Comment by jon-mc-git** [comment]
The results of this cost profiling will be ported into ECF-SEA common component doc drafting\final review work in coming Sprint #2418.  This information will not be presented in spreadsheet now but will be in doc format.  For its purpose as a major component profile summary, it will be focused on the major components and ones that represent the most important costs.  Closing ticket
