### ISSUE TITLE
Refactor Sample App into re-usable Terraform Modules and apply any other best practices

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#233]
**Describe the issue**
We want our Early Adopters to avoid redoing work that was done in the Sample App.  We wish to enable abstractions such that the new teams can take advantage of them.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- The Terraform for the sample app consumes the new modules instead of the more inline code and thus is greatly simplifed
- The modules are present in their own individual repos in github separate from the sample app

**Comment by wrnu** [comment]
**Repo:**

https://github.com/bcgov/startup-sample-project-terraform-modules

This makes a module of the entire app that can be used by Terraform or Terragrunt.

**Done:**
- Network has been moved to use the new network module
  - https://github.com/BCDevOps/terraform-octk-aws-sea-network-info

**Todo**
- Use new alb module
  - https://github.com/wrnu/terraform-octk-aws-workload-alb
- create modules for ECS
