### ISSUE TITLE
Update MOU template

### ISSUE THREAD

**Issue by snowflakebunny** [bcgov/cloud-pathfinder#2371]
**Describe the bug**
The current MOU reviewing process.
1. Catherine to download each submitted form from the google drive.
2. Catherine revise the form and send to Julian for review. After Julian approved, Catherine will send to other team's EA and QR to sign. The process is time consuming. We need to update the MOU template for long term use.

**Additional context**
As Jon pointed out, that how can the MOU does not imply to clients that we are directly monitoring their spend in accordance with the amount specified in this MoU agreement. We do not monitor that closely, so will have to re-word and put tool\automation in place that possibly injects this baseline monitoring into their deployment (possibly, or we just advise them that it’s ‘in their hands’ and they’re still responsible for whatever charges that get produced in the end.

**Definition of done**

- Connect with Julian and Jon to have a discussion 

- Draft a modified version

- send back to Julian and Jon for review

- the final outcome is to remove the step 2

**Comment by OmoAttah** [comment]
we are considering automating the MOU process in the future, the template would be updated at the time when we have a better understanding of what the new process would look like - Olena
