### ISSUE TITLE
Unable to deploy serverless app in LZ0, LZ1 and LZ2

### ISSUE THREAD

**Issue by crochcunill** [bcgov/cloud-pathfinder#2396]
**Describe the bug**
Using accounts with and without OIDC  layer, the deployment of the serverless app failed with the following error

> Node.js v18.14.1
> Error: Process completed with exit code 1.

See 
https://github.com/crochcunill/startup-sample-project-aws-serverless/actions/runs/4246013208/jobs/7382281734#step:6:118

**Additional context**
I found this problem while testing the SEA upgrade to 1.5.5. First I tested in Assembly/LZ1 and all was fine and well. Testing in LZ1 happened before Feb 17, 2023. Days later I started testing in LZ0 and LZ2, and then the problem appear.

Prabhu has already look into it and it look the following tweak 

>   "scripts": {
>     "start": "CI=true PORT=4000 react-scripts --openssl-legacy-provider start",
>     "build": "react-scripts --openssl-legacy-provider build",
>     "eject": "react-scripts --openssl-legacy-provider eject"
>   },

in client/package.json does the trick

After finishing testing LZ0 and LZ1, i tried to redeploy serverless in LZ1 using a package.json that didn't include the openssl-legacy-provider flag. It failed.
After that I added the flag and it worked as expected

The conclusion are
- The change does not seem related to the ASEA upgrade: I was able to redeploy serverless in LZ1 that was the first LZ to be upgraded with no trouble. A couple weeks later, I was unable to redeploy in LZ1.
-  Something changed that require the _--openssl-legacy-provider_  flag

**Definition of done**
My original definition of done was
- User is able to deploy the serverless app (regardless if the account has the OIDC layer implemented)

But now that it is working using the --openssl-legacy-provider the goals are
- to learn exactly what has changed
- how the change has been introduced
- Decide what to do when this change happens: try to reverse the change? warn the users?...

With the current behaviour the end user will simply notice they can not redeploy the app even when their code has not been modified

Note: At the moment of writing this bug report Prabhu and I have spend in total about 3 points. However, I am unable to estimate the forensic work of finding what change and how it was introduced

**Comment by lukegonis** [comment]
This work was completed in February 2023
