### ISSUE TITLE
Simplify Serverless Sample App Code

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#2397]
**Describe the Issue**
As a developer I want a clean and clear example of an AWS ECF serverless application so that I can easily understand how a serverless application can be developed and deployed to the AWS ECF using GitHub Actions.

**Additional Context**
- The original serverless sample app is an evolution of the container app which itself is a stripped down version of an openshift web app.
- Because of the evolution of the app there is a lot of unused code and unneeded complexity.
- This is just regarding the application code, not terraform or pipeline work.

**Acceptance Criteria**
- Maintain all existing functionality
- Remove all unused code
- Simplify the code architecture
- Ensure all libraries are updated
.
.
.
.
.
.
.
.
.
.
.

**Extra Template Info**

***Definition of Ready***
These set of conditions will need to be met in order to bring a ticket into the sprint and start work. Protects the team from unclear requirements.
Issues (Task/Story/Spike) aligned to an EPIC and linked appropriately.
Assigned to the appropriate CPF MEMBER (and is not left blank in ZenHub) at the start of sprint (1st day of the sprint)
Acceptance has been defined for the issue and has been reviewed with CPF team and approved by the necessary approver.
Has been sized and estimated by the delivery team.
Detailed breakdown of the steps required to complete the story in the additional context
Any additional specifications have been documented, reviewed with CPF and approved by the necessary approver.

***Acceptance Criteria***
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.
It should be testable with no room for interpretation
It should be either “pass” or “fail”
It should be clear enough for business stake holders to understand
As part of the user story, it should be written from the user perspective
A well written acceptance criteria is great for 
- managing expectations
- defining scope
- reducing ambiguity
- establishing testing criteria for QA
Given (Pre-condition) 
When (Action)
Then (Outcome)

***Definition of Done***
These set of conditions are met for work to be considered as complete on an issue.
All acceptance criteria(s) have been validated.
All the necessary documentation for the issue has been uploaded to Teams.
Functionality has been tested when applicable.
Functionality has been demonstrated to the relevant stakeholders (where applicable).
Story has been scheduled for a Sprint Demo/community update and impacted teams invited to the Demo.
Stories accepted by PO and documented for potential sharing with impacted users.
- Documented = Captured in Community Update (CU) deck
- Release notes = aspirational goal of providing a bulleted list of features and changes that our users can touch. Was going to store them in our Cloud Pathfinder repo. Can also display to users in the CU

**Comment by OmoAttah** [comment]
Moving to the PB to accommodate higher priority work

**Comment by wrnu** [comment]
https://github.com/bcgov/startup-sample-project-aws-serverless-OIDC/pull/13

**Comment by wrnu** [comment]
https://github.com/bcgov/startup-sample-project-aws-serverless-OIDC/pull/13
