### ISSUE TITLE
STRA for AWS Transfer Family Service 

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#2400]
**Describe the Issue**
Karim and Vyas from the Common Payments Processor team have requested a PIA and STRA be conducted on the AWS Transfer Family service. This ticket is to look into this request.

**Additional Context**
- I informed them it would take some time and would be integrated into a future sprint by priority
- There is still some development work on our end that needs to be done before this is a viable solution for their team
- https://docs.aws.amazon.com/transfer/latest/userguide/what-is-aws-transfer-family.html

**Acceptance Criteria**
- STRA conducted on the AWS Transfer Family service

.
.
.
.
.
.
.
.
.
.
.

**Extra Template Info**

***Definition of Ready***
These set of conditions will need to be met in order to bring a ticket into the sprint and start work. Protects the team from unclear requirements.
Issues (Task/Story/Spike) aligned to an EPIC and linked appropriately.
Assigned to the appropriate CPF MEMBER (and is not left blank in ZenHub) at the start of sprint (1st day of the sprint)
Acceptance has been defined for the issue and has been reviewed with CPF team and approved by the necessary approver.
Has been sized and estimated by the delivery team.
Detailed breakdown of the steps required to complete the story in the additional context
Any additional specifications have been documented, reviewed with CPF and approved by the necessary approver.

***Acceptance Criteria***
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.
It should be testable with no room for interpretation
It should be either “pass” or “fail”
It should be clear enough for business stake holders to understand
As part of the user story, it should be written from the user perspective
A well written acceptance criteria is great for 
- managing expectations
- defining scope
- reducing ambiguity
- establishing testing criteria for QA
Given (Pre-condition) 
When (Action)
Then (Outcome)

***Definition of Done***
These set of conditions are met for work to be considered as complete on an issue.
All acceptance criteria(s) have been validated.
All the necessary documentation for the issue has been uploaded to Teams.
Functionality has been tested when applicable.
Functionality has been demonstrated to the relevant stakeholders (where applicable).
Story has been scheduled for a Sprint Demo/community update and impacted teams invited to the Demo.
Stories accepted by PO and documented for potential sharing with impacted users.
- Documented = Captured in Community Update (CU) deck
- Release notes = aspirational goal of providing a bulleted list of features and changes that our users can touch. Was going to store them in our Cloud Pathfinder repo. Can also display to users in the CU

**Comment by NickCorcoran** [comment]
Before starting this ticket, I would like the requesting client to provide the general service architecture and describe intended use.  They can also identify general risks for using the service.
Our team can then review the architecture/services and assess how they will integrate into our LZ architecture and any identify any platform specific risks.

**Comment by lukegonis** [comment]
PIAs will be completed by Ministry teams as they own the data that will be transferred through this service

**Comment by bruce-wh-li** [comment]
As per the discussion with Warren U., "current architecture is not supported with AWS Transfer family in the ASEA and would only work once we have AWS DirectConnect."
