### ISSUE TITLE
Service Design for Billing in AWS

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/cloud-pathfinder#2401]
As a CPF team we need to understand our internal and client requirements for generating and processing bills for expenses in AWS.

Suggested steps:
- interview existing AWS and GCP clients to document what bills they receive from the CPF team today, in what format and with what frequency. Is it one bill per project set (a combined set of dev, test, prod and tools accounts) or one bill per environment (one for dev, one per prod, etc).  Do we receive aggregated bills e.g. grouped by Expense authority or Product Owner?
- how do they process bills on their end? 
-  check if they would like to make any changes to the current billing?

Repeat the interview with the CPF team members (Warren and Max) and document how process looks like on the team's side - what steps are manual and what are automated.
Ideally, we want to have one billing process for AWS and GCP that works for most customers. We can address edge cases and non-standard requirements separately, outside of the standard billing 
process.

Additional context:
The diagram outlines the billing process as it was designed a couple of years ago, it needs to be updated based on the outcome of the interviews:
https://app.mural.co/invitation/mural/cloudpathfinder2329/1660318317049?sender=u1d0b96ff3161eda8f0f38743&key=dd241527-7d51-4a85-9984-1ae409c7bfa6

Definition of Done:
- [ ] documentation that includes flow charts that describes the current billing process in AWS and includes options for improvement based on the new/updated requirements from the clients and the CPF team.

**Comment by mitovskaol** [comment]
@gautammalhotra21 Can you please add a link to the diagram documenting the billing process to this ticket before closing it.

**Comment by gautammalhotra21** [comment]
AWS Billing Mural - [Link](https://app.mural.co/t/cloudpathfinder2329/m/cloudpathfinder2329/1680725366630/876806e89f12cdfd356766f1882305d1d1691650?sender=u8342006053601c648fc56681)
