### ISSUE TITLE
Test the edit Functionality to the Provisioner tool 

### ISSUE THREAD

**Issue by crochcunill** [bcgov/cloud-pathfinder#2450]
**Describe the Issue**
We have a provisioner that creates a project set, we would also want the provisonor tool to be able to edit some of the project set configurations. This new functionality needs to be tested

This is a continuation of #2455 focusing, this time, in the Edit functionality

**Acceptance Criteria**
- Test cases for each. of the configurations that we allow to edit
-  Execute the test cases

Note: we need to decide the frequency of the regression test for this feature. It is not linked to the SEA upgrade, but at least the test cases should run each time the provisioner tool is touched

**Comment by crochcunill** [comment]
Created two documents (same information in different format)
- techSitemap.xlsx
- techSitemap.docx

They are both stored in the following section of the sharepoint folder

![image.png](https://images.zenhubusercontent.com/620eba1ac6937a4e70b34b15/9ba84d4f-6388-4023-b261-837cd43c7f48)

**Comment by crochcunill** [comment]
Not done because Oamar was too busy during this sprint to finish implementing the Edit functionality

**Comment by lukegonis** [comment]
No longer relevant
