### ISSUE TITLE
Testing the Migrated Python Script and Updating Documentation

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#2451]
**Describe the Issue**
After successfully migrating the project set admin script from Bash to Python, we need to thoroughly test the new Python script to ensure that it performs all administrative tasks as expected. Additionally, we need to update the documentation to reflect the migration to Python and provide guidance on using the new Python script.

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- The Python script is tested to ensure that it performs all administrative tasks as expected and aligns with best practices for - Python development.
- Documentation is updated to reflect the migration and usage of the new Python script, and stakeholders are informed of the changes.

**Comment by crochcunill** [comment]
Application tested and test case document created: project.doc SetAdminAppTestCase.doc stored in
