### ISSUE TITLE
Test upgrade Live to 1.5.6

### ISSUE THREAD

**Issue by crochcunill** [bcgov/cloud-pathfinder#2453]
**Describe the Issue**
We have a new SEA release, And we need to test this update before June
Additional Context
SEA 1.5.6 
(https://github.com/aws-samples/aws-secure-environment-accelerator/releases/tag/v1.5.6)

**Acceptance Criteria**
Execute in Live LZ the regression test plan on the ASEA after Upgrade to 1.5.6

**Comment by mitovskaol** [comment]
closing as complete
