### ISSUE TITLE
Update and Revise AWS Cost Breakdown Examples for Billing Page

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#2460]
**Describe the Issue** 
The current AWS cost breakdown examples provided on the Billing page require updates and revisions to reflect accurate and current pricing. Additionally, the t-shirt analogy used in the examples needs to be replaced with an overview of the application architecture to provide better context. The updated examples should also include a row that represents the monthly cost multiplied by three, to account for the three accounts in a project set (development, testing, and production).

**Additional Context** 
- The original cost breakdown examples can be found in the pre-reading material on the Billing page. The original examples show costs for a small, medium, and large application in AWS, and mention that it costs about $200 US per month to have a project set in AWS without using additional services.
- Emma B has requested this information for the new PO website
- Ask Warren for a link to the Google Doc that Emma provided

**Acceptance Criteria**  

- [ ] The revised cost breakdown examples have been created and sent to Emma. 
- [ ] The t-shirt analogy is replaced with a short overview of the application architecture in each example. 
- [ ] The prices in each example are updated to reflect current AWS pricing. 
- [ ] An additional row is added to each example that multiplies the monthly cost by three, representing the cost for development, testing, and production accounts. 
- [ ] Include a section explaining how customers pay for hosting services in AWS. 
- [ ] All changes are reviewed and approved by Olena and Emma.

.
.
.
.
.
.
.
.
.
.
.

**Extra Template Info**

***Definition of Ready***
These set of conditions will need to be met in order to bring a ticket into the sprint and start work. Protects the team from unclear requirements.
Issues (Task/Story/Spike) aligned to an EPIC and linked appropriately.
Assigned to the appropriate CPF MEMBER (and is not left blank in ZenHub) at the start of sprint (1st day of the sprint)
Acceptance has been defined for the issue and has been reviewed with CPF team and approved by the necessary approver.
Has been sized and estimated by the delivery team.
Detailed breakdown of the steps required to complete the story in the additional context
Any additional specifications have been documented, reviewed with CPF and approved by the necessary approver.

***Acceptance Criteria***
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.
It should be testable with no room for interpretation
It should be either “pass” or “fail”
It should be clear enough for business stake holders to understand
As part of the user story, it should be written from the user perspective
A well written acceptance criteria is great for 
- managing expectations
- defining scope
- reducing ambiguity
- establishing testing criteria for QA
Given (Pre-condition) 
When (Action)
Then (Outcome)

***Definition of Done***
These set of conditions are met for work to be considered as complete on an issue.
All acceptance criteria(s) have been validated.
All the necessary documentation for the issue has been uploaded to Teams.
Functionality has been tested when applicable.
Functionality has been demonstrated to the relevant stakeholders (where applicable).
Story has been scheduled for a Sprint Demo/community update and impacted teams invited to the Demo.
Stories accepted by PO and documented for potential sharing with impacted users.
- Documented = Captured in Community Update (CU) deck
- Release notes = aspirational goal of providing a bulleted list of features and changes that our users can touch. Was going to store them in our Cloud Pathfinder repo. Can also display to users in the CU

**Comment by abibat-adesina** [comment]
https://docs.google.com/document/d/1tlH-jMcCOOj5ST4fCBVbIvhBWcd965GWO0mqfD6hodQ/edit
