### ISSUE TITLE
Billing Utility Quarterly Reports Don't Run

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#2473]
**Describe the bug**
The quarterly reports don't run in Live, but the event is triggering properly and the fargate instance runs. The logs go until "Summarizing query results" which should be the third last log output, but instead the logs just stop with no error. 

**Additional context**
Add steps to reproduce the behaviour or any other context

**Definition of done**
- Quarterly reports run in live or the issue is identified and a ticket is created for the necessary work.

**Comment by abibat-adesina** [comment]
Prabhu was able to add the logic, the quarterly code is running now. I am just waiting for the code to be pushed to Live environment
