### ISSUE TITLE
Create a list of request types for Platform Admins

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/cloud-pathfinder#2479]
As the CPF Team is working in replacing manual processes with automation, we need to have a better understanding of what types of requests are currently implemented manually by Platform Admins.

**Additional Context**
The information about the current requests that product teams submit to the Platform Admins on the CPF team can be found in the #aws-tenant-requests channel in Rocketchat and in the cloud.pathfinder mailbox and by asking other team members

**Acceptance Criteria**
 - [x] document a list of different requests types that product teams submit to the CPF in this ticket
 - [ ] have the list reviewed by Max and Warren 
 - [ ] present to the CPF Team

**Comment by mitovskaol** [comment]
Please add the list of the requests to this ticket.

**Comment by ThibaultBC** [comment]
Meeting to be scheduled by Marisa to list request types
