### ISSUE TITLE
Create lightweight process to Security/Privacy review services as they progress through their lifecycle

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#249]
**Describe the issue**

The Cloud Security Schedule (CSS) was an evolutionary outcome of a brick and mortar schedule and may have some gaps with respect Cloud Service Providers.  There is a desire to improve the CSS.  A CSP when signing up must comply with either BC standards or equivalent (GC Protected B Medium Medium (PBMM), Fedramp, CSA*, Schedule G).

Understand the current compliance against cloud security schedule against AWS

We want to define a mechanism or tooling for reviewing CSP services

**Value to the product/MVP?**
It would help with onboarding further services to cloud services, including MVP, and any early adoptors.

**Which Sprint Priority is this issue related to?**

**Additional context**
- Security/Privacy needs to be getting notification from CSP as services are changed by the CSP
- The feds have an existing process that we can reuse (acknowledge and extend existing ways of compliance the Feds are doing)
- GC Brokering services continuously reviews services and accepts requests from customers to include new services

**Definition of Done:**
- A document that lives in Teams
- A review of the CG Brokerage service handling process (how does one process get in and get out through its lifecycle)
- Peer reviewed (Holly)

**Comment by bluemel-gov** [comment]
- Not started yet due to work on #213

**Comment by sid-gov** [comment]
PO says that this is done. Every new service that comes in is sent to the security, privacy team member for review.
