### ISSUE TITLE
Update tax registration number in all AWS accounts

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/cloud-pathfinder#2505]
Our finance team currently have to process up to 200 separate tax invoices that accompany primary invoices that we receive from AWS. Processing that many invoices is time consuming and is prone to human error. We approached AWS asking to consolidate our tax invoices into one. These are the instructions they responded with:

**See the case that Jon submitted through Support portal for more detail.**

`We would need to add the TRN (tax registration number) in the tax setting for all accounts. Once added, AWS will be able to consolidate the invoices.  These are the instruction for adding the TRN: https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/manage-account-payment.html#manage-account-payment-update-delete-tax-numbers '

Acceptance Criteria:
- [ ] **all** our accounts in AWS have been updated with the TRN number. Contact Carlos, our Financial Advisor, to obtain the TRA number for the Province.

**Comment by wrnu** [comment]
There is no  API for the tax settings but there is a setting to enable tax settings inheritance from the root account. We can set the tax registration number (TRN) once in each of the LZ root accounts and the TRN will apply to all child accounts in the org 

https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/manage-account-payment.html#manage-account-tax-linked-accounts
