### ISSUE TITLE
Create sitemap for the Tech documentation site

### ISSUE THREAD

**Issue by crochcunill** [bcgov/cloud-pathfinder#2510]
**Describe the Issue**
As a product owner I would like to see a visual representation for the Public Cloud Tech doc site.

The resulting document can be modelled after the equivalent document from the private cloud  
https://docs.google.com/spreadsheets/d/1Kcp45DF63nOpkeBncsynuIh91Tj9AzSOwwp76F4GX3Q/edit#gid=804907029
(note: third tab)

**Additional Context**
The public cloud site will include several sections, from how to provision account to understand how the service is billed. 

This ticket will focus on the technical details. In some moments it will overlap with other sections, but should be focused on the technical aspects of the Public Cloud. Different topics would be
- Architectural documents
- Security layers
- How To's documents
- Access to logs and heartbeats 

**When content already exists elsewhere, e,g, on the public cloud website or on Internet, we will not duplicate the content but will link to other sources instead.**

**Acceptance Criteria**
- A document (spreadsheet) modelled, after the private cloud, that includes all technical topics the  group would like to share with the users, the document is reviewed and approved by the CPF Team

**Comment by MaxWardle** [comment]
Meeting for knowledge transfer

**Comment by crochcunill** [comment]
Created two documents
- techSitemap.xlxs
- techSitemap.docx

The word document includes suggestions on how to fill in the content. The spreadsheet is the visual representation of the word document’s TOC.
Both documents are stored in the following Teams site

![image.png](https://images.zenhubusercontent.com/620eba1ac6937a4e70b34b15/04f8ac5b-3800-4796-b754-cf615cb43373)
