### ISSUE TITLE
Investigate JIRA Service Manager for private ticketing

### ISSUE THREAD

**Issue by NickCorcoran** [bcgov/cloud-pathfinder#2549]
**Describe the Issue**
Some tasks require a more private repository to track and communicate with SMEs.
Other Ministry teams have used JSM for this purpose.

Workspace in Sandbox for our testing.   
https://citz-imb-sandbox-564.atlassian.net/jira/servicedesk/projects/DEVSECPRIV/queues/custom/40
John D.  can help for any issue.

AWS Security HUB and Jira Cloud Integration : 

https://docs.aws.amazon.com/smc/latest/ag/jsmcloud-config-security-hub.html
https://docs.aws.amazon.com/smc/latest/ag/config-security-hub.html

https://www.youtube.com/watch?v=uEKwu0M8S3M

CG and Jira Connector : 

https://github.com/chrisbeckett/cg-jira-connector

**Acceptance Criteria**
- [x] Obtain access to a test space
- [x] Create some test tickets
- [x] Create some email chains
- [x] Create some notifications/alerts
- [x] Report on findings

.
.
.
.
.
.
.
.
.
.
.

**Extra Template Info**

***Definition of Ready***
These set of conditions will need to be met in order to bring a ticket into the sprint and start work. Protects the team from unclear requirements.
Issues (Task/Story/Spike) aligned to an EPIC and linked appropriately.
Assigned to the appropriate CPF MEMBER (and is not left blank in ZenHub) at the start of sprint (1st day of the sprint)
Acceptance has been defined for the issue and has been reviewed with CPF team and approved by the necessary approver.
Has been sized and estimated by the delivery team.
Detailed breakdown of the steps required to complete the story in the additional context
Any additional specifications have been documented, reviewed with CPF and approved by the necessary approver.

***Acceptance Criteria***
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.
It should be testable with no room for interpretation
It should be either “pass” or “fail”
It should be clear enough for business stake holders to understand
As part of the user story, it should be written from the user perspective
A well written acceptance criteria is great for 
- managing expectations
- defining scope
- reducing ambiguity
- establishing testing criteria for QA
Given (Pre-condition) 
When (Action)
Then (Outcome)

***Definition of Done***
These set of conditions are met for work to be considered as complete on an issue.
All acceptance criteria(s) have been validated.
All the necessary documentation for the issue has been uploaded to Teams.
Functionality has been tested when applicable.
Functionality has been demonstrated to the relevant stakeholders (where applicable).
Story has been scheduled for a Sprint Demo/community update and impacted teams invited to the Demo.
Stories accepted by PO and documented for potential sharing with impacted users.
- Documented = Captured in Community Update (CU) deck
- Release notes = aspirational goal of providing a bulleted list of features and changes that our users can touch. Was going to store them in our Cloud Pathfinder repo. Can also display to users in the CU

**Comment by NickCorcoran** [comment]
CITZ IMB set up 3 staff with access to JIRA, JSM and Confluence as part of Atlassian Cloud.

**Comment by bruce-wh-li** [comment]
We can either integrate JSM (Jira Service Management) with AWS Security HUB directly but will require an IAM user.   Alternatively, we can have CSPM send report to JSM for the same effect.

**Comment by NickCorcoran** [comment]
lets do cspm

**Comment by bruce-wh-li** [comment]
- User need to added Jira Service Management before you can assign or share the issue & request.    
- Can mention people using @ in comment. 
- Can copy the issue and paste the link and share the link using email
