### ISSUE TITLE
Explicitly create and use log groups for Sample App

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#255]
**Describe the issue**
The Sample app does not use log groups created by Terraform - it uses a NodeJS library to create log group JIT and logs to this group.  A better practice is to create the log groups using terraform and the app should log to STDOUT / STDERR and get flowed into log group.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Code updated to remove explicit creation of log groups and to instead use log groups created by terrafrom

**Comment by sid-gov** [comment]
@sheaphillips @ActionAnalytics - is this still in progress or can we close this? Seems to have been opened a long time ago.

**Comment by sheaphillips** [comment]
It is at least partially complete.  I believe there is still an outstanding
item to remove some redundant code from the app. <--  @wrnu  I think that's
accurate?

**Comment by wrnu** [comment]
You are correct, there is some work to do refactoring the app code. I think this got lost along the way because it didn't have the technology label. I suggest we move this to the product backlog, it is not particularly important.

**Comment by sid-gov** [comment]
@ActionAnalytics - fyi to be discussed based on the above comments in the capacity adjustment meeting tomorrow

**Comment by mitovskaol** [comment]
No longer relevant
