### ISSUE TITLE
Training Approvals

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#257]
**Describe the issue**
PO and SM require training.  Currently lacking approval & $$

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Ability to sign up for training without barriers

**Comment by sid-gov** [comment]
Moving to Product backlog: To follow-up when budget ($$) opportunities arise.
