### ISSUE TITLE
Define Billing Utility

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#2611]
**Describe the Issue**
We want to create a description/ model of all the functionality of the billing utility so that we can clearly define our needs to an external resource.

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- [ ] define the billing utility in some form of diagram/ documentation
- [ ] Review existing readme file for billing utility and ensure it reflects current architecture of billing utility app

**Comment by ThibaultBC** [comment]
Appears to be a pre-Proserve ticket - potentially no longer relevant.
Follow up: Khurrum's ticket to research billing information needs: interview 2 POs.
