### ISSUE TITLE
Create "Deploy an app to BC Gov's AWS Landing Zone"  page for Tech Docs website

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/cloud-pathfinder#2629]
Create a page outlining steps for deploying a sample app to the BC Gov's SEA guardrails in AWS. Check the existing content in Pre-reading material and in the docs that Carles put together.

Acceptance criteria:
- [x] create a draft page on Google Drive for how to deploy an app to the SEA environment for 3 sample apps: serverless, container and VM (re-use the existing content as much as possible but try to shorten/simplify if possible)
- [x] sign off by Warren and Max
- [x] hand over to Pilar to finalizing

**Comment by abibat-adesina** [comment]
https://github.com/bcgov/public-cloud-techdocs/blob/main/docs/deploy_an_app_to_bc_govs_aws_landing_zone.md
