### ISSUE TITLE
Training Page for Product Owner Website

### ISSUE THREAD

**Issue by abibat-adesina** [bcgov/cloud-pathfinder#2632]
**Describe the Issue**
As a platform admin having a training resources for newly onboarded teams, introducing them to cloud services

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- Create a new page in WordPress for the new Public Cloud website (work with Pilar on this)
- Create the content for the new page: re-use the training announcement email content + the list of free AWS training from the StrackOverflow
- Sign off by Olena

**Comment by lukegonis** [comment]
Blocked until Content Design team resolves a technical issue- Resolved https://digital.gov.bc.ca/cloud/services/public/get-support/

**Comment by ThibaultBC** [comment]
Hi @abibat-adesina, could you please remind me why this ticket is blocked, are you waiting for Pilar?

**Comment by Pilargit12** [comment]
Provided page to review today - confirmed - page is now live https://digital.gov.bc.ca/cloud/services/public/get-support/#training
