### ISSUE TITLE
Exclude SCP Permissions to Allow Viewing of CloudWatch Logs

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#2644]
**Describe the bug**
Users cannot view cloudwatch logs even with admin permissions in the SEA. This is due to SCPs blocking this action according to Ryan J. He suggested that we exclude the relevant SCP permissions to allow this action.

**Additional context**
Add steps to reproduce the behaviour or any other context

**Definition of done**
- [ ] Add relevant SCP to the exclusion list for SEA Forge
- [ ] Add relevant SCP to the exclusion list for SEA Assembly
- [ ] Add relevant SCP to the exclusion list for SEA Live

**Comment by lukegonis** [comment]
We won't pursue this issue until the LZA Migration, and will have a manual workaround until then.
