### ISSUE TITLE
Service Blueprint version 2

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#265]
**Describe the issue**
This is important because we intend to use the Service Blueprint as a conversation starter/Comms tool to collaborate with OCIO and other BC Gov teams.

Cloud Pathfinder, OCIO and Ministries need to understand, and be able to address user expectations and requirements for managed cloud services. Ministries need to understand their share of responsibilities for compliant use of cloud services. Our stakeholders will benefit from knowing what to ask from us.

**Which Sprint Priority is this issue related to?**
1

**Additional Context**
- centres on the customer journey
- the customer is the Early Adopter
- front stage focuses on touch points between the customer and our service
- backstage is what is needed behind the scenes to make the above possible

**Definition of done**
- Blueprint diagram updated with front end activities and adapted to Bjorn's journey
- Map and transit lines redrawn such that it accurately reflects the BC Gov and CP landscape (input needed from PO)
- Reviewed by PO prior to demo

**Comment by ateppin** [comment]
Created v2 trying to be CSP agnostic - https://miro.com/app/board/o9J_kmmxJv0=/

Also removing all references to early adopters.  We will learn & shape v2 based on the lessons learned from the EA work

**Comment by ateppin** [comment]
The V2 I created in Miro is now out of date & will create a new V2 in Mural in the next sprint

**Comment by ateppin** [comment]
Updating the blueprint based on the comments & feedback from the team during the walk thru

**Comment by scayzer** [comment]
Completed 2020-12-23, reviewed with PO 2021-01-05
