### ISSUE TITLE
Review of operational platform Change Management needs and create a solution for client request tracking and general feedback tracking

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#2660]
**Describe the Issue**
Review platform Change Management needs for Enterprise-Ready operations, and create a solution/process that allows for easy tracking\reviews, and approvals flow

**Additional Context**
To be part of Operations documentation\processes and when possible turned into an automated process eventually through the use of new ticketing/service management software

**Acceptance Criteria**
- Review Public Cloud platform Ops change management needs
- Review and incorporate any best practices 
- Review possibility to have a Change Management request process actually built into internal ticketing software
- Create Change Management initial draft documentation for discussion and follow up with further tickets

**Comment by jon-mc-git** [comment]
Needs for an Enterprise-Ready Change Management operations process were reviewed and draft documentation was completed along with workflow for upcoming discussions.

**Comment by jon-mc-git** [comment]
Closing

**Comment by mitovskaol** [comment]
@jon-mc-git Can you please include the path to the documentation in this ticket.

**Comment by jon-mc-git** [comment]
Old ticket - was closed and re-opened again.  Any questions on the ticket were addressed at the time.  Ticket should be closed
