### ISSUE TITLE
Improve billing report

### ISSUE THREAD

**Issue by KhurrumBC** [bcgov/cloud-pathfinder#2665]
**Describe the Issue**
The cloud consumption report email template that is sent out weekly needs a UX review to ensure its easy to read and understand.

**Additional Context**
I will need to speak with Max to better understand constraints of what is possible in terms of auto-populated information such as recipient and bill period.

Questions to answer:
- Can we address recipient by name rather than email address?
- Can we display the pay period in an easier to read format?
- Can we have a button that links to the report rather than having it as an attachment?

**Acceptance Criteria**
Pass a quick review with my service design peers to see if there are any further recommendations.
- [x] License Plate # displayed in Email Subject

**Comment by abibat-adesina** [comment]
Working with Prabhu to write the logic code to have the License plate display in email subject and address recipient by name rather than email

**Comment by abibat-adesina** [comment]
https://github.com/BCDevOps/terraform-octk-aws-sea-billing-reports/pull/24
