### ISSUE TITLE
Create a "Technical Architecture" page for Tech Docs website

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2668]
Create a page outlining the technical architecture for the AWS landing zone. Check the existing content in Pre-reading material and in the docs that Carles put together.

Acceptance criteria:
- [ ] create a draft page on Google Drive for Examples and Best Practices (re-use the existing content as much as possible but try to shorten/simplify if possible)
- [ ] present to tech team for discussion/modifications [Warren, Prabhu, Max, Abi]
- [ ] when ready hand over to Pilar to finalizing 

_Context: Selected as a top 10 article for technical documentation:
https://app.zenhub.com/workspaces/cloud-pathfinder-5e4dbb426c3c6af8dcbf06a7/issues/gh/bcgov/cloud-pathfinder/2590_

**Comment by jon-mc-git** [comment]
Graphics and what will be necessary/instructions for the tech architecture doc page were sent to web design.  It was determined that more work will be necessary for this.  Will follow up with them and continue this work with the design\integration ticket. Closing

**Comment by ThibaultBC** [comment]
@jon-mc-git Is this done, ie. there is an page published with this title? If not let's reopen or open another ticket. @lukegonis do you have context on this?
