### ISSUE TITLE
Create a "Provision a project set" page for Tech Docs website

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2669]
Create a page outlining steps to provision a project set. Check the existing content in Pre-reading material and in the docs that Carles put together.

Acceptance criteria:
- [ ] create a draft page on Google Drive for Examples and Best Practices (re-use the existing content as much as possible but try to shorten/simplify if possible)
- [ ] sign off by Warren and Max
- [ ] hand over to Pilar to finalizing 

_Context: Selected as a top 10 article for technical documentation:
https://app.zenhub.com/workspaces/cloud-pathfinder-5e4dbb426c3c6af8dcbf06a7/issues/gh/bcgov/cloud-pathfinder/2590_

**Comment by wrnu** [comment]
@MaxWardle I added some guideline is a comment on the linked ticket

https://app.zenhub.com/workspaces/cloud-pathfinder-5e4dbb426c3c6af8dcbf06a7/issues/gh/bcgov/cloud-pathfinder/2749
