### ISSUE TITLE
Create a "Networking" page for Tech Docs website

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2670]
Create a page outlining network in the AWS Landing Zone. Check the existing content in Pre-reading material and in the docs that Carles put together.

Acceptance criteria:
- [ ] create a draft page on Google Drive for Networking. Include info on private subnet structure and creating public access using API Gateway(re-use the existing content as much as possible but try to shorten/simplify if possible)
- [ ] sign off by Warren, Abi and Max
- [ ] hand over to Pilar to finalizing 

_Context: Selected as a top 10 article for technical documentation:
https://app.zenhub.com/workspaces/cloud-pathfinder-5e4dbb426c3c6af8dcbf06a7/issues/gh/bcgov/cloud-pathfinder/2590_

**Comment by wrnu** [comment]
I have created a PR with the guidelines. You can fully develop this doc inside of the PR

https://github.com/bcgov/public-cloud-techdocs/pull/11
