### ISSUE TITLE
Research and list Azure projects/contacts in priority sequence for inquiry on potential needs

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2677]
As part of the service design research, list contacts that we have identified as interested in Azure Compute and Storage services.

- [ ] Research and create list of Azure projects and where they are (subscription/Gov Phase II infra/etc.)
- [ ] Prioritized projects in accordance to importance/activity/spend/type
- [ ] List PO/users related to each of these projects and include ability to cumulate by Ministry 
- [ ] Which services where relevant or note other relevant factors
- [ ] Initial investigation on what are they used for where possible, and use to prioritize a contact list for further inquiry where necessary and upcoming Service Design work

**Comment by jon-mc-git** [comment]
Azure projects investigation was done to create an initial list, and then it was prioritized working with Thibault so that we have a priority list of Azure users for us to work with moving into the Service Design work and interviews that will be necessary.  Closing
