### ISSUE TITLE
Upgrade Firewalls to R81.2 for bug, security fixes, and new features including support SAML Authentication for Admin, and bug, security fix 

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder#2686]
**Describe the Issue**
We need to update Firewall, Firewall Manager to newer version for added features, bug, security fixes

**Additional Context**
- Two Firewalls
- Backup before Deployment
- ECF Forge and Assembly First.   Live in another ticket
- Same VPC, TGW, ALB/GWLB, Scale Set ?

**Acceptance Criteria**
- [ ] No or very minimal downtime to firewall cluster 
- [ ] Firewall updated to the newer version, e.g. R81.2
- [ ] Firewall Manager updated to the newer version, e.g. R81.2
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.  See below for team agreement details.

**Comment by bruce-wh-li** [comment]
As SECOPS (Chris C.) is taking firewall update/migration up, firewall ticket become irrelevant.
