### ISSUE TITLE
Review CloudGuard firewall config with Check Point and discuss best practices for use

### ISSUE THREAD

**Issue by NickCorcoran** [bcgov/cloud-pathfinder#2689]
**Describe the Issue**
Our current cloudguard firewalls are default config.  We need to engage Check Point specialists to discover best practice use and monitoring.

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- [x] Setup meeting w/ Check Point to discuss
- [x] Capture details on best practice and changes required
- [x] Make a plan to try in Forge

**Comment by bruce-wh-li** [comment]
C. Biernacki suggests to add custom policy to enable threat prevention modules (antibot, antivirus, ips, threat emulation, threat extraction) in learning mode.   Otherewise, everything is pretty much locked down.   C. Biernacki to send all the suggestions to Bruce L.

**Comment by bruce-wh-li** [comment]
I manually did a system backup locally (this appliance) in GAIA for Firewalls and Firewall Manager.   Multiple Tickets created to automate the process.  Can scp to s3 allowed by guardrail in ASEA?   FW to host or host to FW, fw to s3 direct.  host to aws s3
