### ISSUE TITLE
Developing User-friendly Interface for IAM User Management

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#2691]
**Describe the Issue** 
To enhance user experience, a user-friendly front-end interface needs to be developed in the Project Registry to allow users to easily request IAM user creation, deletion, and management.

**Additional Context** 
- The interface should be intuitive, reducing the learning curve for new users.
- Consider the inclusion of tooltips or help sections to guide users in creating or managing IAM users.

**Acceptance Criteria** 
- Development of a functional and user-friendly interface within the Project Registry for IAM user management.
- Users are able to successfully request IAM user creation, deletion, and management with ease.
- User testing to ensure the interface is intuitive and meets user requirements.

**Comment by lukegonis** [comment]
This issue is to track the work being done by the Private Cloud Team

**Comment by lukegonis** [comment]
Once the Private Cloud team has finished their work on this, we can close this issue

**Comment by wrnu** [comment]
We have decided to pursue an architecture that no longer requires registry integration. This is no longer relevant
