### ISSUE TITLE
Create a "Requirements to build your application" page for Tech Docs website

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2700]
Create a page outlining an overview of the requirements to build an application. Check the existing content in Pre-reading material and in the docs that Carles put together.

Acceptance criteria:
- [ ] create a draft page on Google Drive for Requirements to build your application. (re-use the existing content as much as possible but try to shorten/simplify if possible)
- [ ] sign off by Warren, Abi and Max
- [ ] hand over to Pilar to finalizing 

_Context: Selected as a top 10 article for technical documentation:
https://app.zenhub.com/workspaces/cloud-pathfinder-5e4dbb426c3c6af8dcbf06a7/issues/gh/bcgov/cloud-pathfinder/2590_

**Comment by abibat-adesina** [comment]
https://github.com/bcgov/public-cloud-techdocs/pull/17/files
