### ISSUE TITLE
[Spike] Investigate effort to enable AWS Lambda@Edge

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2704]
**Describe the Issue**
Investigate feasibility, effort, and requirements to make the AWS Lambda@Edge service available to our customers in SEA.

**Additional Context**
Requested by a current AWS customer, it would allow them to significantly improve their user experiences. 
https://aws.amazon.com/lambda/edge/

**Acceptance Criteria**

- [x] Validate feasibility
- [x] Draft a list of steps and any requirements
- [x] Estimate effort

**Comment by wrnu** [comment]
The list of steps and estimate are available here

https://bcgov.sharepoint.com/teams/01368-CPFScrumTeam/_layouts/15/Doc.aspx?sourcedoc={0ffa0be2-e7d8-4019-9890-57930eac895e}&action=edit&wd=target%28ZenHub%20Issues.one%7Cc1d0e927-b128-4825-b484-56c0231622c7%2F2704%7Cfab6b386-e0e2-4e7d-976a-98a826a4b9b8%2F%29&wdorigin=703
