### ISSUE TITLE
Outreach to participants and scheduling

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder#2711]
**Describe the Issue**

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- [ ] reach out to SD community about scheduling tool
- [ ]  Outreach to participants and scheduling

**Comment by KhurrumBC** [comment]
This portion was delayed as we had to wait to receive a list of questions previously asked through a survey to ensure we are not repeating questions that we had already asked in the past.
