### ISSUE TITLE
Service Design Analysis and Report

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder#2713]
**Describe the Issue**

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.  See below for team agreement details.

**Comment by KhurrumBC** [comment]
This ticket is on blocked as I'm waiting for some stakeholder from our last interview to respond to some questions that didn't get answered due to time constraints, I have sent a gentle reminder and will wait 2-3 days prior to moving forward with this ticket.
