### ISSUE TITLE
Teams are Getting Billing Reports Even if a Project Sets is Closed

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#2714]
**Describe the bug**
Karim G has brought up that a project set that has since been closed "l3rmlh" is still being detected by the billing utility. The email shows $0 charged for the time period, but is still being sent. I've also checked that the accounts are no longer "suspended" so presumably the 90 day period has expired. This is one of the first times we've closed live accounts so likely this has always been a dormant issue.

**Additional context**
- Email: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa08yIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5bcea239729b8ca3c074535953e1a0e570a599d9/Screen%20Shot%202023-09-19%20at%2011.38.31%20AM.png)
- Note that this may be an issue with AWS. I'm not even sure how these are still in the organization as they are no longer searchable. They don't exist in the OU UI, so may be phantom accounts or something. It could also be the way we are gathering accounts.

**Definition of done**
- [x] Weekly billing report emails are NOT sent for $0 invoices.
- [x] Test a scenario of this case to make sure it doesn't happen

**Comment by ThibaultBC** [comment]
Updating acceptance criteria from "Not sending to closed project sets" to "Not sending for $0 invoices".
