### ISSUE TITLE
Forge Billing Utility Deployment Doesn't Send Emails

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#2716]
**Describe the bug**
The billing utility deployed in Forge no longer sends emails to gov.bc.ca inboxes. We think this may be due to some change in the gov email policy as we no longer even receive them in our quarantine inbox. The difference between the billing utility deployment in Forge and the one we use in Live is that the one in Forge does not have a "production" SES service. We are still on the free-tier in Forge and that means that the emails are less "trusted". We need to be able to test updates to the billing utility easily so that we can make confident changes and avoid error.

**Additional context**
- Pricing for production SES is $0.10/1000 emails - https://aws.amazon.com/ses/pricing/

**Definition of done**
- [ ] Upgrade the Forge SES instance to production
- [ ] Ensure emails can be received using the manual run

If they still are not being received:
- [ ] Open another bug ticket to investigate the issue further

**Comment by abibat-adesina** [comment]
SES instance upgraded to production Emails received using manual run
