### ISSUE TITLE
Update Onboarding Deck

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2721]
**Describe the Issue**
The onboarding presentation deck needs updates with new processes in place (Github OIDC instead of Terraform Cloud), as well as other items with regards to the newly available technical documentation
**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.  See below for team agreement details.

**Comment by abibat-adesina** [comment]
https://bcgov.sharepoint.com/:p:/r/teams/01368-CPFScrumTeam/Shared%20Documents/CPF%20Scrum%20Team/006%20-%20Diagrams,%20Technology,%20Documentation/Training%20Sessions%20and%20Resources/Technical%20Onboarding.pptx?d=w5a5df21e6c804f0b9a2c5a48cb0aa25b&csf=1&web=1&e=ZacQoV

**Comment by abibat-adesina** [comment]
Work will continue with this ticket #2774
