### ISSUE TITLE
Update the user management code to handle project set user access management

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#2736]
**Describe the Issue**
- we want to include user management to all the available roles in aws through product registry

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- service design is done for the new UI changes 
- Nats message format is designed 
- Usermanagement code is modified to handle all the roles

**Comment by lukegonis** [comment]
Need to discuss this issue with Nick C to validate it

**Comment by lukegonis** [comment]
We are no longer pursuing this architecture
