### ISSUE TITLE
Define UI changes and NATS message format for project set access management

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#2737]
**Describe the Issue**
- we need to define the UI and the nats message format so we can work on the code for project set self serve user access management

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- Meet with Khurum to finalise the UI changes 
- Meet with Oamar to discuss the Nats message format

**Comment by lukegonis** [comment]
We are no longer pursuing this architecture
