### ISSUE TITLE
Service Design for Public cloud registry website to enable self serve user management

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#2739]
**Describe the Issue**
- UI Design has to be done for the new self serve user management through public cloud registry website

**Additional Context**
- [ ] Create a Figma mockup of potential UI enabling administrators to add users to select roles for an AWS landing zone.
- [ ] Share first iteration of design early with Warren, Prahbu, Abi and Max to ensure alignment before getting too deep into the design work.
- [ ] Consider feedback and iterate on design if needed.
- [ ] Share with registry team to implement changes on front end.

**Acceptance Criteria**
- Design is created and given to the registry team to implement the changes on the front end.
-

**Comment by KhurrumBC** [comment]
Figma Design has been reviewed with Warren, Abi and Thibaut. Next review scheduled for week of October 23rd with Oamar Kanji.

**Comment by KhurrumBC** [comment]
Design iterations made based on feedback from Zhanna, next review scheduled for Dec 4th, 2023
