### ISSUE TITLE
Check Point GAIA firewall manager upgrades and log shipping - connect with Check Point

### ISSUE THREAD

**Issue by NickCorcoran** [bcgov/cloud-pathfinder#2744]
**Describe the Issue**
Pervious conversations were had with Check Point on this issue but no resolution was provided.  Including individuals that implemented in ASEA would be helpful.  This is to re-start that conversation.

**Additional Context**
Previously, Check Point advised NOT to install agents to ship logs from the firewalls or manager.  
Current connectivity restricts to tcp, but need udp for syslog endpoint.
Include SecOps Cloud Security Architect in coversation.
Is via Market Place a must 

**Acceptance Criteria**
- [x] Setup meeting w/ Check Point 
- [x] Understand how logs can be shipped to immutable source
- [x] Understand upgrade path (non-manual)

**Comment by bruce-wh-li** [comment]
According to the checkmate thread TCP to transport syslog is possible.

**Comment by bruce-wh-li** [comment]
According to the checkmate thread TCP to transport syslog is possible.

**Comment by bruce-wh-li** [comment]
There is checkmate thread detailed how to forward log to AWS cloud watch

**Comment by bruce-wh-li** [comment]
Based on AMI image, we are paying PAYG.  
Therefore, we should update Firewall instance by updating AMI in the launch template in auto scaling group ? 
How about firewall manager ?   Ansible or any OSS automation can be used as playbook to provision log forwarding and cloudwatch installation, log backup, firewall back up.

**Comment by bruce-wh-li** [comment]
Chris B. offered biweekly Meeting with checkpoint.

**Comment by bruce-wh-li** [comment]
Nick C., Chris L C., and Bruce had attended Checkpoint Cloud Security training (pre CCSA prep) and learnt valuable knowledge on how to use CloudFormation stack to deploy single fw, clustering fw, fw in auto scaling group  in AWS.

**Comment by bruce-wh-li** [comment]
Dan M. advised "Upgrades in the ASG are done when scaling out. This will update to the latest version (Unless it was hardcoded in the accelerator)"
