### ISSUE TITLE
Email Sent from Registry on Project Set Closure

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#2746]
**Describe the bug**
We are not receiving email alerts when a project set it closed from the registry. We want to be notified via the cloud.pathfinder@gov.bc.ca inbox when this happens so that the platform admins can go in and delete the AWS accounts manually.

**Additional context**
Add steps to reproduce the behaviour or any other context

**Definition of done**

- [ ] Speak to Oamar on the registry team to see what is in place and explore options
- [ ] Find the best place to add email notifications and implement the change

**Comment by ThibaultBC** [comment]
Hi @prabhukiran9999 is this still blocked? Anything we can do to help unblock it?

**Comment by ThibaultBC** [comment]
Prahbu: Ticket mostly waiting on App dev team.

**Comment by ThibaultBC** [comment]
Hi @prabhukiran9999 , is this still on the app dev team board?
