### ISSUE TITLE
Azure Monitor Type fix due to Deprication

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#2747]
**Describe the Issue**
Azure Monitor instance that monitors the current Azure VPN connection to the Data Center will be deprecated - To fix Gateway monitoring 

**Additional Context**
The monitor in question verifies that the VPN connection between the Azure Gateway and the Data Center is live

**Acceptance Criteria**
- Review of Azure Monitor full deprecation information
- Review current Azure Monitor general configuration and new method(s)
- Review current Monitor
- Test generate a new monitors for functionality compatible with current standards
- Increase functionality if possible due to any new capabilities - Test
- Deploy final configuration and export code for incorporation into IaC pipelines (Azure DevOps)
- Update code deployment for the new Azure Monitor in the Azure DevOps resource catalog
- Where possible update code in current Phase II infrastructure pipelines - test in Test/Dev
- Test new Azure Monitor instance and implement

**Comment by mitovskaol** [comment]
@jon-mc-git  We will not be implementing MCCS in Azure as part of the MVP. Please close the ticket or move back to Backlog.

**Comment by mitovskaol** [comment]
This work will be carried out by the Azure dev team and tracked in a separate board.
