### ISSUE TITLE
[Doc Guidelines] Provision a project set

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2749]
**Describe the Issue**
Warren to provide a structure and guidelines for the Provision a project set Technical documentation

**Acceptance Criteria**
- [ ] Provide guidelines and/or a list of items to structure that document.

**Comment by wrnu** [comment]
This one should be pretty straight forward.

Screenshots of all sections that can be filled out with a description of what they do.

For the PO and tech lead, describe that they are added to the Admin Role on which gives them Admin in all AWS accounts in the project set

For the budget section we should describe that AWS budget alerts are created in each account corresponding to the budget and that email alerts are set at 50%, 80%, and 100% of the budget
