### ISSUE TITLE
Trim non-prod firewall instances to save cost

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2754]
**Describe the Issue**
There is a substantial amount of non-production instances that can be cleaned up and deleted. Try to get closer to the baseline cost
**Acceptance Criteria**

- [x] Review instances in the non-production environments
- [x] Identify instances that can be removed or decreased
- [x] Trim unnecessary spend and measure $ reduction if possible
- [x] Alerts are only triggered when there are fewer than the expected number of instances

**Comment by ThibaultBC** [comment]
Warren: Probably taken by Prabhu or Warren

**Comment by wrnu** [comment]
https://github.com/BC-Gov-PaaS-Platform-Services/aws-ecf-cloudwatch-alarms/pull/11

**Comment by wrnu** [comment]
Reduced firewall gateways and rsyslog clusters to 1 instance is both forge and assembly

**Comment by ThibaultBC** [comment]
Estimate saved cost - $800/month
