### ISSUE TITLE
Close unused project sets in Forge and Assembly

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder#2764]
**Describe the Issue**
There is a substantial amount of non-production instances that can be cleaned up and deleted. Try to get closer to the baseline cost

This issue might require additional effort with closing accounts due to permission issue identified previously.

**Acceptance Criteria**

- [ ] Keep one project set for Forge and Assembly
- [x] Run the session with Abi/Max/Bruce
- [x] Record the process and save it in the team documents for future reference
- [x] 2 projects left in Forge
- [x] 2 projects left in Assembly
- [x] Run a check with Warren before deleting
- [x] Delete all other projects

**Comment by ThibaultBC** [comment]
PL - Nov 20 - 
Forge: Keep 2 projects
Assembly: 2 projects

**Comment by ThibaultBC** [comment]
Main assignee: Max
