### ISSUE TITLE
SPIKE: Investigate effort required to close unused project sets in Forge and Assembly

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder#2767]
**Describe the Issue**
There is a substantial amount of non-production instances that can be cleaned up and deleted. Try to get closer to the baseline cost

This issue might require additional effort with closing accounts due to permission issue identified previously.

**Acceptance Criteria**

- [ ] Meet with Ryan J to determine next steps

**Comment by MaxWardle** [comment]
Tested this on tk72yo in Forge, and was able to manually delete an account
