### ISSUE TITLE
Close unused project sets in Live

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#2780]
**Describe the Issue**
We want to reduce the amount of unused AWS accounts in Live to reduce our cost going forward. There are project sets in the "projects-to-close" folder that we can remove. Additionally there is an "Unclassified" account in "tnfhhm" that are no longer in use and can be removed.

**Additional Context**
- We want to use this opportunity to train Abi and Bruce on the process of deleting accounts as we'll be going through each of the three deletion processes in this ticket. 

**Acceptance Criteria**
- [x] Close project sets in the "projects-to-close" folder
- [x] Close the "Unclassified" account in "tnfhhm"

**Comment by abibat-adesina** [comment]
https://github.com/bcgov-c/aws-ecf-live-workspaces-settings-stack/pull/294

https://github.com/bcgov-c/aws-ecf-live-workspaces-settings-stack/pull/296
