### ISSUE TITLE
Create a simple onboarding deck

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2783]
**Describe the Issue**
Create a presentation deck for the new onboarding experience, that highlights the key information to go through during the meeting
**Additional Context**
That should include Core elements, such as: Asking for ministry team project description/pitch, Steps to take (MoU, Registry), shared responsibilities, billing and cost recovery explanation, Q&A, where to find help, rocket chat, documentation. 
Content can be added later on as contextual supporting slides, but additional content shouldn't block this ticket to be done.
**Acceptance Criteria**
A set of pre-defined requirement that need to be met in order to mark the user story as “done”.  See below for team agreement details.

- [x] Core slides ready (Project Pirtch, steps, reponsibilities, cost, communication channels, help, documents).
- [ ] Review during a 30-min meeting with Abi, Max and Thibault.

**Comment by ThibaultBC** [comment]
Main assignee: Abi

**Comment by ThibaultBC** [comment]
Hi @abibat-adesina @MaxWardle - If this is ready to be reviewed, could you please schedule a time to meet and go over it together? Thank you!

**Comment by abibat-adesina** [comment]
[Technical Onboarding Slide](urhttps://bcgov.sharepoint.com/:p:/r/teams/01368-CPFScrumTeam/Shared%20Documents/CPF%20Scrum%20Team/006%20-%20Diagrams,%20Technology,%20Documentation/Training%20Sessions%20and%20Resources/Technical%20Onboarding.pptx?d=w5a5df21e6c804f0b9a2c5a48cb0aa25b&csf=1&web=1&e=wDmALel)
