### ISSUE TITLE
Implement/validate correct logout function/flow to AWS LZ login.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#279]
**Describe the issue**
Users should be able to log out of AWS console and have their KeyCloak session terminated.
This is important because it prevents from people being logged in than they should. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Logout function from the AWS console destroys the keycloak session

**Comment by sheaphillips** [comment]
Further research required on this as it is not well documented on the KeyCloak or AWS side.  Currently "Logout" from AWS Console kills AWS session, but does not appear to terminate KeyCloak session, so a user who has already successfully logged in may not need to re-authenticate until the KeyCloak session has expired on its own.  The Keycloak session is not long-lived ,but there is an opportunity to clarify the functionality and provide a better experience for users.

**Comment by wrnu** [comment]
I don't think we want to do this. In order to switch between AWS accounts on the AWS Console (web ui), AWS requires that the user logs out before signing into a new account. If we implemented this the user would have to login into Keycloak with MFA every time they switched between accounts (e.g. dev, test, prod).

**Comment by wrnu** [comment]
Moved to blocked so we can revisit the requirements of this ticket.

**Comment by sid-gov** [comment]
We have determined this as not to be implemented as described but instead to upload the documentation.
