### ISSUE TITLE
Quicksight Dashboards - Taking ownership

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2795]
**Describe the Issue**
Take ownership of the AWS Quicksight now that the Proserve work is complete.

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- [x] Take ownership of the code
- [x] Receive and review documentation from Consultants for any feedback\questions
- [x] Organize internal meeting to discuss\review the documentation to org our thoughts/inquiries into a single set of questions for the consultants - aim is to better understand what has been done, and provide clarification
- [x] Ensure diagram created in doc(s) handed over to easily explain the AWS code framework/structure and its execution 
- [x] Understand through the documentation how we can hide/remove graph types in this Quicksight UI 'Cloud Information Framework' used, and most specifically in the Billing UI tab coded infrastructure
- [x] Understand what can easily be modified (ie. through a variable/configuration file) and what should not -- so we can understand our flexibility and options with the UI's presentation (ie. which don't involve core code changes), if any (ie. tab order, hiding tabs or objects within a tab, etc.)
- [ ] Deploy current dashboard version (in Dev - by AWS Consultants) to Test ourselves, and check everything works as intended/documented
- [ ] Review ability to edit user/permissions, project names, and other key project/PO metadata info types where possible

**Comment by ThibaultBC** [comment]
Follow-up tickets:
- Keycloack terraform integration
- Deploy in Assembly
- Automation of steps

**Comment by wrnu** [comment]
Deploying to assembly will be done as part of other tickets in the epic
