### ISSUE TITLE
Acquire and Review GC LZ code

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#280]
**Describe the issue**
The issue is that before we can create tickets on how to merge the Government of Canada (GC) landing zone (LZ) with the BC Gov landing zone, we need to have access to GC LZ, and we need to compare it to what we have already.

**Which Sprint Priority is this issue related to?**
Landing Zone Updates & Merging with GC 

**Additional context**
- A pre-requisite is the security review over the BC Gov LZ

**Definition of done**
- Introduce and explain the current LZ model to Bahram
- Acquire the GC LZ code and place in source control
- Well-defined tickets covering the work to get the best fit for the above definitions

**Comment by ActionAnalytics** [comment]
Still waiting on AWS to acquire the code

**Comment by sid-gov** [comment]
AWS is expecting to follow up after 3 weeks. Putting it back in the backlog.

**Comment by ActionAnalytics** [comment]
AWS open-sourced the codebase today, we can unblock this ticket
