### ISSUE TITLE
Move CheckPoint firewalls to BYOL in Forge

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#2830]
**Describe the Issue**
We want to consolidate our CheckPoint licensing through SecOps, to do that we need to move from on-demand licensing to "bring your own license" (BYOL)

**Additional Context**
- The firewalls are deployed and managed by the ASEA and can be configured in the `config.json`

**Acceptance Criteria**
- [x] Backup forge management server
- [x] Update management server to use BYOL AMI
- [ ] Update the gateways to use BYOL AMI
- [x] Restore management server data post update

**Comment by wrnu** [comment]
Blocked waiting for the Check Point licensing

**Comment by ThibaultBC** [comment]
Thanks for the update @wrnu, when do you expect to get licensing from CheckPoint? Anything else we can do to help unblock this?

**Comment by ThibaultBC** [comment]
Waiting for procurement. ETA March 2024
