### ISSUE TITLE
BC Gov Azure Tenancy - Department review for possible cleanups

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#2831]
**Describe the Issue**
List all existing projects in Azure to prepare for transfer to new infrastructure and registry integration

**Acceptance Criteria**

- Review of Gov Azure tenancy/EA controls 'Departments'
- Decide what could be cleaned up as an initial effort here (can follow up later)
- Complete the deletions where possible 
- Update end-of-project summary on what was able to be done for the report out results

**Comment by ThibaultBC** [comment]
Hi @jon-mc-git , I added a description and acceptance criteria for this ticket. This is what will be required to move forward with these existing projects.

**Comment by jon-mc-git** [comment]
Wrong ticket was updated by Thibault so copied over base acceptance criteria to the proper ticket and corrected this one (Departments were referring to Azure Enterprise Agreement level 'departments' in this case, not the client workload areas)

**Comment by jon-mc-git** [comment]
Departments and structure at the tenant org level were reviewed.  What could be cleaned up now was removed and items remaining can be reviewed again when objects beneath them are either deleted or removed in the future.  Information was summarized within the end-of-project doc and presented.  Closing ticket
