### ISSUE TITLE
Create a process for managing Service Control Policies (SCPs)

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2834]
**Describe the Issue**

**Additional Context**
Manual process, write a documentation about the process

**Acceptance Criteria**

- [ ] Operational for operating SEA Updates

**Comment by wrnu** [comment]
https://github.com/BC-Gov-PaaS-Platform-Services/aws-ecf-bcgov-overlay-settings-stack/pull/34
https://github.com/BC-Gov-PaaS-Platform-Services/aws-ecf-forge-overlay-settings-stack/pull/32
https://github.com/BC-Gov-PaaS-Platform-Services/aws-ecf-assembly-overlay-settings-stack/pull/24
