### ISSUE TITLE
[Dashboard] Keycloack terraform integration

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2842]
**Describe the Issue**

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**

- [x] create clients (lambda + quicksights)
- [x] create role (reader/admin)
- [x] create identity provider
- [x] token management
- [x] Test

**Comment by prabhukiran9999** [comment]
https://github.com/bcgov/terraform-aws-quicksight-billing-dashboard-configuration/pull/1
