### ISSUE TITLE
Test New registry UI and usermanagement feature for public cloud in forge and live 

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#2845]
**Describe the Issue**
- Test the new changes made to registry in forge and also test the new user management features
- work closely with the app dev team on pushing changes to live

**Additional Context**
**Acceptance Criteria**
- New changes are tested and changes are pushed to live
- Have a plan and set date for opening this new feature to the community

**Comment by ThibaultBC** [comment]
Hi @prabhukiran9999 , is this still in blocked, waiting for the App dev team? Do you have any update from them on timelines or progress?
