### ISSUE TITLE
Rename test project sets with Forge/Assembly/Live

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2850]
**Describe the Issue**
As title suggests, add the environment to project set name so that we have a clear view of which project generates which cost.

**Acceptance Criteria**

- [x] Forge Projects renamed
- [x] Assembly Projects renamed
- [ ] Live Projects renamed

**Comment by abibat-adesina** [comment]
Projects in Forge ECF are renamed. There is no billing code in ECF Assembly. No need to rename project-sets in ECF Live.
