### ISSUE TITLE
Review Live Project Sets for Dome9 Layer

### ISSUE THREAD

**Issue by MaxWardle** [bcgov/cloud-pathfinder#2852]
**Describe the Issue**
We want to make sure we have the dome9 layer deployed on all live project sets. 

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**

- [x] Review all projects sets in Live
- [x] Check for dome9 layer
- [x] If it doesn't exist, add it
- [x] Make a pr to run automation

**Comment by abibat-adesina** [comment]
https://github.com/bcgov-c/aws-ecf-live-workspaces-settings-stack/pull/324/files
