### ISSUE TITLE
Bug in Provisioner Workflows on not bundling image for dev on the latest commit

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#2857]
**Describe the bug**
- We build an image for dev name space upon PR, But that does not build the image with the latest commit, which is still not morged

**Additional context**
- We can build the image for dev upon push and not PR and image build for prod can stay the same which is build upon release

**Definition of done**
- Workflows updated accordingly

**Comment by MaxWardle** [comment]
https://github.com/bcgov-c/aws-ecf-provisioner/pull/13
