### ISSUE TITLE
AWS Support Entitlements -- Operational Management Review + follow-ups

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2872]
**Describe the Issue**
AWS Support Entitlements -- Operational Management Review and follow-ups for next fiscal year

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- Review of AWS entitlement usage and how they fed back into our CI processes
- Plan for improved use of these benefits and set these within future operational processes
- Set out plan with AWS how we will use these benefits this next fiscal year and schedule them

**Comment by jon-mc-git** [comment]
Research the latest on the AWS Enterprise Support benefits and review changes.  This years new benefits involve a change to the AWS IEM support service.  It has evolved and takes a broader approach to customer event management with a more wholistic approach.  Will either be able to use this for a broader review of our scalability analysis (and potential cross-regional deploys in future) and get additional potential resourcing in support of the the new platform base in development, or have our clients take advantage of this for any one of their projects.  Discussed aspects of this with the AWS rep team as well as reviewed our previous benefit use with our TAM.  Reviewed the potential for what could be coming in this next quarter as well, where we will settle planned usage for the rest of the fiscal once more progress has been make on the next platform's development.  Closing
