### ISSUE TITLE
List Frameworks elements for Enterprise Ready Operational Management

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2898]
**Describe the Issue**
We need to start with a definition of Operational Management in an Enterprise Ready state, for the Public Cloud Landing Zone products.

**Acceptance Criteria**

- [ ] List and define the procedures, checklists, and any other element that are known to be required to organize our operational management.
- [ ] The above acceptance criteria is only to provide a list with a name and brief description (a few sentences at most).
- [ ] List and define elements that are potentially on the map - but not sure if required.
- [ ] Review with Product Owner.

**Comment by jon-mc-git** [comment]
Researched and assessed standards for an initial service operations framework draft.  Listed and provided summarized review of each.  Reviewing with PO all framework elements and finalizing draft.  Had initial meeting on this and will finalize draft after final meeting to review

**Comment by jon-mc-git** [comment]
Completed review of the broad operationalization areas of focus with PO and associated updates in preparation for next stages.  Closing ticket
