### ISSUE TITLE
User Principals for subscription creations - Special permissions investigation

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#2908]
**Describe the Issue**
User principal creations subscription creation - Special permissions investigation

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- Creation of 3 User Principals in the Azure tenancy (Dev, Test, Prod)
- Investigate special tenancy permissions to create subscriptions off of our EA
- Work with ADMS group for special permissions additions
- Test permissions on User Principals
- Addition of specified permission to the 3 User Principals

**Comment by mitovskaol** [comment]
Closing the ticket as all Azure work will be tracked in a different board.

**Comment by jon-mc-git** [comment]
Investigated the special tenancy automation account permissions required.  Created the three required user principals and worked with the devs in applying them to the tenancy infrastructure deploy area.  Permissions assigned by code and there was some troubleshooting necessary to try to get these automation accounts working in the landing zone code.  Completed troubleshooting with the devs and further testing was successful.  Closing
