### ISSUE TITLE
Operations artifacts - repo organization 

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#2916]
**Describe the Issue**
Operations artifact repo organization & development for future

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- Review current repo structure with team
- Research for best practices on Ops repo management (tools, documentation, procedures, templates, etc.)
- Ops team discussions to decide how we are to organize this going forward
- Develop out the Operation's team semi-finished repo concept and present it to the larger team for feedback
- Incorporate feedback where necessary

**Comment by jon-mc-git** [comment]
Reviewed current structure and noted areas of improvement.  Had discussions with the team on how this could be done and the first ways we might go about it.  An initial framework was implemented in our Operations repo where we will focus on keeping ops artifacts organized and have a location for future operational processes as we develop them out.  Closing

**Comment by mitovskaol** [comment]
@jon-mc-git Please include the location of the repo in the ticket.

**Comment by jon-mc-git** [comment]
Links not in ticket due to changed ticket norms but not necessary here as the solution is a concept, with only the base developed out so far (the teams files base).  Can include short path - Teams Ops base:  007..\Operations.  Solution as a concept involves add-ons to Teams (adding interactive elements to our central file repo like drawing, snapshots, issues, notes, external links, all with metadata used in such a way that these elements can be searched freely later) - to be developed out further.
