### ISSUE TITLE
Review of Critical Systems details for planning alignment with Enterprise-Ready initiative

### ISSUE THREAD

**Issue by jon-mc-git** [bcgov/cloud-pathfinder#2917]
**Describe the Issue**
Review of Critical Systems info for planning alignment with Enterprise-Ready initiative

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- Review Private Cloud CS attestation document
- Assess the material, standards and processes discussed to align our Operations processes with these
- Summarize needs or potential additional requirements to possibly achieve it
- Discuss with PO

**Comment by jon-mc-git** [comment]
The Critical Systems attestation information was review along with some of the key requirements to do with both Incident Management and Change Management and incorporated into the needed process flows, from the future north star vision version to the planning for upcoming planning for Incident Management near-term

**Comment by jon-mc-git** [comment]
Closing

**Comment by mitovskaol** [comment]
@jon-mc-git Could you please include more detail around what requirements from Critical Systems attestation were identified for inclusion into the Incident Management and Change Management  diagrams.

**Comment by jon-mc-git** [comment]
Old ticket - was closed and re-opened again.  Any questions on the ticket were addressed at the time.  Ticket should be closed
