### ISSUE TITLE
Obtain and apply Check Point licenses

### ISSUE THREAD

**Issue by NickCorcoran** [bcgov/cloud-pathfinder#2924]
**Describe the Issue**
Licenses for CSPM and cloud firewalls procured.  Need to get licenses and apply in cloud environments.

**Additional Context**
Have reached out to Check Point on steps to take.

**Acceptance Criteria**
- [x] Procure licenses
- [x] Obtain licenses
- [x] Apply licenses
- [x] Verify new expiry dates

**Comment by bruce-wh-li** [comment]
1. Purchase order is to obtain license of 4 Core of vcpu for Firewall in ECF Live (IaaS), CSPM (SaaS)800 protected assests, and premium support.   
2. The license and support purchased mistakenly under SecOps's UC account not CPF's UC account.
3.  None of CPF team member has role to SecOps's UC.  Therefore, It is needed to contact the distributor (MNP) to  to raise request with sales admin support (SAS) team and only then It can be moved our product/service to CPF's UC account. 
4.  Jason G. of Check Point is going through internal channel to get us EVAL license for CSPM shortly.  Will check with Check Point if they can move our Purchase Order to CPF's UC account internally. 
5.  Firewall is using PAYG license model for now and need to test out in ECF Forge to ensure backup/restore work as expected before change it to BYOL to use the new purchased 4 core license for firewall in ECF Live.

**Comment by bruce-wh-li** [comment]
Health Check verified both firewall in Live & Forge, and cspm are all up and running still.    Will update again once formal license for CSPM is applied after Check Point move the license to our UC account.

**Comment by bruce-wh-li** [comment]
Health Check verified both firewall in Live & Forge, and cspm are all up and running still.    Will update again once formal license for CSPM is applied after Check Point move the license to our UC account.

**Comment by bruce-wh-li** [comment]
Jason G. of Check Point will update once MNP/TD Synnex resubmit the Purchase Order.  CSPM is still displaying dashboard as normal.

**Comment by bruce-wh-li** [comment]
All the purchased firewall, firewall manager, cspm licenses appeared in CPF's UC account. 
CSPM license expiration date updated to Mar. 2025.   Firewall, Firewall Manager change to BOYL will be covered in another ticket.   Closed
