### ISSUE TITLE
[LZA Forge] Set up a new management (root) AWS account

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2934]
- [x] Look at existing root accounts for configuration of things like names and addresses, tax setup, consolidated billing, etc.
- [x] Connect to Shared Services Canada for billing
- [x] MFA setup
- [x] Document step/decisions (internal)

**Comment by ThibaultBC** [comment]
Needs help from Catherine for Pcard setup

**Comment by prabhukiran9999** [comment]
- I have added my MFA for now as part of the dev process, will remove it and max has creds to reset MFA and Password once done.
