### ISSUE TITLE
Contact and assess existing teams about transition

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2936]
Acceptance Criteria:
- [x] Prepare communication with benefits and considerations
- [x] Check content with Comms team before sending
- [x] Contact existing project 
- [x] List

**Comment by MaxWardle** [comment]
I've received a "transition readiness assessment" document from Kelvin, and we've decided to turn it into a survey to send to teams via email. I've also written a small script to list all project sets and related contacts, I'll be sending one email per project set so teams with multiple know to fill out the form separately for each one.
