### ISSUE TITLE
Quick Spot Check for new Terraform License model

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#294]
**Note for Planning/Triage**
I have assigned 4 potential assignees to this ticket, with the intent that one person takes this and does the work to inform the others and Executive if necessary.

**Describe the issue**
Hashicorp Terraform has launched a new Terraform Cloud offering called [Cloud Business](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-cloud-business/?mkt_tok=eyJpIjoiT1dJM1pURmxOemsyWkdRMiIsInQiOiJWbGk5MDFwRXZXTmVyc3R3ZStsZ2pJcnNUSHU4T204d0pEWGdXd0I4NXRDcURGSXZhV2xUUFZUdVcxaWIxd3JkbTR2MGJLSlRUWkJMZExFcVVJbmozN0lDaTZoSjFtYnQzak1RNURxUjA4SHQ0S25MOWJwRUFHWUJqOWhVZlwvZWkifQ%3D%3D)

Hashicorp presented this to us several weeks ago but at the time the cost structure was in a preliminary form that didn't fit our needs.  

We want to check the cost structure of Terraform Cloud Business because if it will end up being within the same range of our current cost footprint for Terraform Cloud, the features of Terraform Cloud Business have some appeal to facilitating the management of Terraform code org wide. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- [Product brief](https://www.hashicorp.com/blog/announcing-hashicorp-terraform-cloud-business/?mkt_tok=eyJpIjoiT1dJM1pURmxOemsyWkdRMiIsInQiOiJWbGk5MDFwRXZXTmVyc3R3ZStsZ2pJcnNUSHU4T204d0pEWGdXd0I4NXRDcURGSXZhV2xUUFZUdVcxaWIxd3JkbTR2MGJLSlRUWkJMZExFcVVJbmozN0lDaTZoSjFtYnQzak1RNURxUjA4SHQ0S25MOWJwRUFHWUJqOWhVZlwvZWkifQ%3D%3D)

**Definition of done**
- Confirmation that the cost structure is the same as what was shown to us before, or if not
- A brief synopsis of how much it would cost us under the new cost structure vs what value we would get

**Comment by sid-gov** [comment]
The District Manager for Terraform left and we are going to meet with them when they get reorganized.
