### ISSUE TITLE
Create first draft of LZA configuration files (to be reviewed by AWS team)

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2941]
- [x]    Decide on use of ControlTower
- [x]    OU structure
- [x]    Core accounts
- [x]    Networking
- [x]    Perimeter and Inspection VPC
- [x]    Gateway load balancer (LZA will not deploy CP FWs)
- [x]    Hub/Spoke
- [x]    Determine the size of the VPCs for each account type
- [x]    SCPs
- [x]    Compare to ASEA SCPs (and modify as needed)
- [x]    Currently we have made an exception for lambda in us-east-1

**Comment by prabhukiran9999** [comment]
- Deployed all the configs except the network config.
