### ISSUE TITLE
QuickSight hide views in custom cudos dashboard and update filters and filter chaining.

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#2945]
**Describe the Issue**
- we need to hide some dashboards in QuickSight as they showcase core account resources
- Order of filters Ministry Name, Project Set , Linked Account, Account Name 
- Remove payer account, remove charge type filter
**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- Update the existing analysis and hide the dashboards, we can deploy that as the same dashboard or create a new dashboard
- If new dashboard is created, make sure to update the config.json in the overlay repo with the new dashboard id

**Comment by prabhukiran9999** [comment]
@wrnu , Can you please review it.

**Comment by wrnu** [comment]
Look great, thanks @prabhukiran9999
