### ISSUE TITLE
Change Management Document - near term implementation plan

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2951]
**Describe the Issue**
Describe our Change Management procedure with an initial diagram and high level document

**Additional Context**
This is an initial step focusing on the near-term and we will add iterations to this document with time.

Description: Change management is about the implementation of processes and procedures that help not only manage platform changes but also communicate these planned events, while ensuring that any modifications are well understood, tested, planned for and documented_

Change Management diagram - business requirements:
Need to create a diagram documenting change management for the AWS landing zone. A change defines an event when the state of an existing service changes, either by introducing a new version of the existing service (i.e. upgrade), or a brand new service/feature (a new release) or decommissioning an existing service. The diagram should document the process the team follows if they need to make any change to the production environment for the Cloud landing zone.

Audience: The diagram is intended to be shared with our clients that using the AWS landing zone currently, who want to know how our team is managing changes in the landing zone production environment.

Process Scope: The change management flow in the diagram should reflect what improvements to the current change management process  we can introduce "tomorrow" without developing any additional code (ie. near-term).  The change management should only focus on the "landing zone"-level change,  client application changes are out of scope. 

**Additional requirements from Olena**
The diagram/process should include the steps for 1) intiating a change i.e. a Change Request in a written form including the steps to implement and test the change as well as a rollback plan, 2) getting approval for the change i.e. from the Public Cloud PO, 3) scheduling the change for implementation in a non-prod environment i.e. create a ticket in ZenHub, 4) implementing the change in the non-prod environment i.e. create a PR and assign for review 5) approve the change for implementation in the the non-prod environment, 6) review the change to confirm there is no negative impact and 7) repeat the steps 3-6 for production environment. The process should also address what safety controls are in place to ensure only approved and reviewed changes are applied to prod i.e. a papertrail of the PO sign off and the approval for the PR before it is merged into the main branch. I would also like to see confirmation that all changes in prod are applied "as a code" i.e. no human can log in and click the buttons and there are safety controls that prevent humans from making unauthorized changes to the prod environment.

**Acceptance Criteria**
- [x] High level description (List format) (maximum 1 page)

**Comment by jon-mc-git** [comment]
Updated the business requirements (below Description) for this upcoming ticket, per our meeting with Olena today

**Comment by mitovskaol** [comment]
Please include the information about the controls that the team has in place to ensure all changes are tested and reviewed/approved before applied in production.

**Comment by jon-mc-git** [comment]
Review of second draft of change management document with PO and post-review comments being incorporated. 
 Discussions from the Platform Admin perspective are forthcoming on this process and a larger team discussion has been scheduled for this draft.  A review with Olena will be scheduled when completed (targeted to Monday).  Thereafter as per PO discussions the following will occur:
- Refinement of change management process as per the discussion with Olena and team comments
- Second Change Management process test run (separate ticket)
- CM post-Change process review for learnings/latest updates (ticket as above)
- Results discussion and CM final draft process approval by Director for publication (ticket as above)
- Process moved to visualization/publication stage (separate ticket - to coordinate with web design/publication group and publish diagram with Accessibility in mind)

**Comment by jon-mc-git** [comment]
Final draft was reviewed with Warren for the dev perspective.   Will review with Private Cloud for thoughts and a standards perspective with that team just before going to the visual process creation with the web design team

**Comment by jon-mc-git** [comment]
Private Cloud review of Change Management draft process took place and meeting discussion held.  It's ready for the visual flow creation.  Sending this finalized version to web design to kick-off that process.  Closing
