### ISSUE TITLE
New PIM Azure Tenancy Ownership and Operations Access Enablement

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2971]
**Describe the Issue**
New PIM Azure Tenancy Ownership and Operations access enablement, needed to create resiliency in platform service operations as part of an improved enterprise-ready service management stance
**Additional Context**
As owners of the Government secure landing zone platform and its Azure space for BC Gov, the Public Cloud team needs consistent role based access to the core tenancy. As well there is the need various management groups to have the ability to delegate access to other team members for business continuity.  This work will then evolve into a standardized/documented approach to leverage the most recent security and operational best practices, while managing platform services and delivered the client landing zone environment
**Acceptance Criteria**

- [x] Investigate Privilege Identity Management's (PIMs) most recent service information
- [x] Review latest best practices around PIM usage, evolved standards and service resiliency
- [x] Ideate possible design options for use of PIM in cloud platform service management
- [x] Learn about and incorporate OCIO PIM usage standards in current development
- [x] Work with internal SecOps, the ADMS team and OCIO Security Operations to refine the design
- [x] Coordinate with these teams for final review and ADMS for creation of AD/PIM group creations and configuration
- [x] Review and iterate on design where necessary with ADMS  
- [x] Provide ownership access ability to management team to support service resiliency
- [x] Final review with internal SecOps and creation of a documentation framework (Mgmt, Platform Admins, and SecOps teams)
- [x] Move to documentation\demo tickets for both internal SecOps and Operations teams

**Comment by jon-mc-git** [comment]
An review of the current tenancy PIM usage was held and a new design was worked out with ADMS and PIM nesting tested completed.  The new Security Group\PIM design was reviewed with Nick and OCIO SecOps and the request was submitted to ADMS to have these approximately 20 groups created and the associated PIM configurations applied.  ADMS will get back when these creations are completed, which will be tested (including a Multi-Cloud test) at that point before final implementation

**Comment by jon-mc-git** [comment]
Security group/PIM creations were received from ADMS and further testing took place.  Was found that there is an issue for nesting the ownership side of PIM.  Was discussed with ADMS and a modified solution was found so this part will change (use of PIM ownership groups) and the rest of the solution remains the same

**Comment by jon-mc-git** [comment]
PIM ownership issue was resolved by way of separate admin accounts within the design.  Reviewed with OCIO\SecOps and requested the accounts from ADMS.  Accounts were produced, applied to PIM groups by ADMS and some additional PIM groups were requested as per discussed needs.  Final review of PIM groups with SecOps was conducted and adjustments made to group memberships where necessary.  Possible future improvements discussed and a coordinated audit type process was worked out with SecOps to maintain and iteratively improve this going forward.  Some additional group were identified to resolve gaps and sent to ADMS for creation. Follow up questions will be reviewed with ADMS when the additional PIM groups are created coming up.

**Comment by jon-mc-git** [comment]
PIM review took place with SecOps reviewing access and eligible parties.  Remaining gaps were identified and set up PIM groups requested from ADMS.  Currently waiting for their activation of these last groups to complete the process.  Once done and gone over a review will be held with the PO finish it off and move to the PIM process elevation procedure docs

**Comment by jon-mc-git** [comment]
New additional PIM groupings were created by ADMS and reviewed with internal SecOps for last gaps.  One additional missing group was identified and sent to ADMS.  Operations and SecOps approved final operational groupings and a documentation framework to support it for both Operations and SecOps teams was discussed a summary table created.  Moving to next tickets for this demo\documentation phase.  Closing ticket
