### ISSUE TITLE
Enable access to AWS region US East-1

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2972]
**Describe the Issue**
Enable access to the AWS US East-1 region from the landing zone, to enable services that aren't available in Canada.

**Acceptance Criteria**

- [ ] Enable Access to US East-1 for the AWS Landing Zone
- [ ] Document changes to the SCPs - Team files - Ops Documentation

**Comment by prabhukiran9999** [comment]
- Enabled global region us-east-1 in Forge and Live
