### ISSUE TITLE
Saving Plans research

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2973]
**Describe the Issue**
Research information about how to best use Saving plans
**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**
- [x] Research information about how to best use Saving plans
- [x] Look at "_MAP Migration Acceleration_" for consideration
- [x] Present findings

**Comment by abibat-adesina** [comment]
The AWS Migration Acceleration Program (MAP) is a comprehensive and proven cloud migration program based upon AWS’s experience migrating thousands of enterprise customers to the cloud. 
MAP specialized workloads is a scaling mechanism designed to accelerate migration and modernization of on-premises workloads to AWS. MAP specialized workloads are available for Mainframe, Windows, Storage, VMware Cloud on AWS, SAP, Databases, and Connect.
