### ISSUE TITLE
Shared account password updates

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2980]
**Describe the Issue**
We need to update our shared email's passwords
**Additional Context**
Compliance with Service Bulletin 1577
**Acceptance Criteria**

Update passwords of the following accounts:
- [x] OCIO AWS Master Acccount CITZ:EX
- [x] CITZ Cloud Pathfinder CITZ:EX
- [x] Public Cloud Invoices CITZ:EX

**Comment by abibat-adesina** [comment]
OCIO service desk confirmed only the owner(s) could update the passwords

**Comment by abibat-adesina** [comment]
Passwords were updated
