### ISSUE TITLE
Ways to access all billing data in the SEA 

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#2981]
**Describe the Issue**
- Create a way to access all billing data across all project sets within the AWS SEA
**Additional Context**
- 
**Acceptance Criteria**
3 possible options
- Fix the billing role for the management account
- fix rls lambda to check master account billing role access and give access to all billing data
- create a Keycloak group that only has QuickSight reader role and make rls lambda to give access to all data

**Comment by ThibaultBC** [comment]
No longer relevant - SEA outdated - will need to reconsider for LZA
