### ISSUE TITLE
Update SEA to newest version

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2986]
**Describe the Issue**
Check ASEA new versions and update to current one.

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**

- [ ] Check ASEA new versions and update to current one.

**Comment by MaxWardle** [comment]
Note: think about change management during this ticket, document in the future

**Comment by abibat-adesina** [comment]
Update across the two environments done. The latest version is v1.5.10
