### ISSUE TITLE
Understand the GCP customer support needs, current GCP Support, options & how Platform Ops can help

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#2988]
**Describe the Issue**

**Additional Context**
Add any other context, attachments or screenshots

**Acceptance Criteria**

- [x] Research how to start support tickets with GCP
- [x] Document steps in a 1-page max document, stored in CPF Teams Ops Documents.
- [x] Test what role is needed to open a support case
- [x] send email to gcp clients letting them know that enterprise support is enabled in gcp and include instructions on how to use it.

**Comment by ThibaultBC** [comment]
Old CRM might have some data on users.

**Comment by abibat-adesina** [comment]
https://bcgov-my.sharepoint.com/:w:/r/personal/abibat_adesina_gov_bc_ca/Documents/GCP%20Enhanced%20Support%20Support%20Case.docx?d=w9c967bdaadec46a58ae2c41971587170&csf=1&web=1&e=PuviEI
