### ISSUE TITLE
Double check expiring cloud.gov.bc.ca is a NOOP

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#299]
**Describe the issue**
A 30 day cert expiration notice for cloud.gov.bc.ca was sent to the team on Aug 19.  We wish to confirm this requires attention or not.

**Which Sprint Priority is this issue related to?**
Operations

**Additional context**
Most likely this is not “our” cert, since we had our set issued in April/May timeframe and they should not be expiring until 12 months from then.  We did have a cert issued for the same domain “cloud.gov.bc.ca” but probably the one referenced below pre-dates and was initiated by another group.  It likely does *not* need to be renewed.

**Definition of done**
- Be able to rule out definitively that this can be ignored, or if not
- Create a ticket to renew the cert

**Comment by lukegonis** [comment]
No longer relevant
