### ISSUE TITLE
GCP - Finish non-IDIR cleanup

### ISSUE THREAD

**Issue by NickCorcoran** [bcgov/cloud-pathfinder#2996]
**Describe the Issue**
- Still users in GCP that are not managed - reach out to POs to get fixed (have list)
- Figure out issues with users that initial try at IDIR integration didn’t work (contractors generally)
- Draft comms re: turning off non-IDIR for product teams

**Additional Context**
https://app.zenhub.com/workspaces/cloud-pathfinder---aws-5e4dbb426c3c6af8dcbf06a7/issues/gh/bcgov/cloud-pathfinder/2865

**Acceptance Criteria**
- [ ] Contact POs for products to remediate non-IDIR users
- [ ] Look into specific users that were having issues w/ enforced login (CGI contractors)
- [ ] Draft comms for GCP users to enforce IDIR only login (Just Google Cloud, not Google Workspace)

**Comment by bruce-wh-li** [comment]
Test with Shelly H successfully.  Convert Shelly to Workspace (managed) and added to gcp sso group.  Discussed with Nick on how to inform unmanaged GCP account and plan to enable SSO.  Change the unmanaged accounts in three batches.  Jul 29th, Jul 31st, Aug 2nd.    This ticket is to change unmanaged account to managed by transitioning the local google account authentication to Idir SSO through Microsoft Entra Id for user has both Idir and Entra ready.  No change to permission.

**Comment by bruce-wh-li** [comment]
New ticket #3040 work related to unmanaged External Identity (Non Idir)  is created.

**Comment by bruce-wh-li** [comment]
All the unmanaged Entra Ids converted to managed by organization.
