### ISSUE TITLE
Incident Management Diagram publishing

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#3008]
**Describe the Issue**
Publish incident management diagram

**Acceptance Criteria**

- [ ] Diagram published on PO Website (Get Support Page): https://digital.gov.bc.ca/cloud/services/public/get-support/
- [ ] Diagram published on Tech Doc website

**Comment by mitovskaol** [comment]
I suggest doing usability testing for the diagram before it is published. I find that it some paths on it are still confusing, for example after the entry point where it says "Issue detected by OCIO monitoring scripts" that is supposed to only detect landing zone outages,  the path leads to the " Has there been an App issue?" , why?

**Comment by jon-mc-git** [comment]
Some meeting were held with Michelle and Pilar from the web design group and another version of the diagram created to attempt to simplify the IM diagram for publication.  This version was discussed and refined further in August before their vacations and sent summary notes and additional changes requested to them.  People are back from vacations so work was completed there and a follow up meeting to review those and any final recommended changes is scheduled for tomorrow.  After this the draft goes to the PO for comments\additions and it will finalized & approved by the Director for publication

**Comment by jon-mc-git** [comment]
Final review of the new IM simplified diagram for web publication held with Olena and some further clarifications are being added to it.  Designers are preparing it for publication and once updates complete it will be activated within our web pages

**Comment by jon-mc-git** [comment]
Update - Figma issues on the simplified version process flow document were resolved and changes were added at that time.  Design team have this content plus a description of it (requested for Accessibility).  They are taking care of finals and we have been told it will be published soon.  Closing ticket
