### ISSUE TITLE
FAQ - Calgary AWS

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#3028]
As a Ministry Team, I want a FAQ on the AWS Calgary region, so that I understand more about the availability, potential benefits and constraints, current and future states that this region offers.

Acceptance Criteria:
1. Create a list of main questions that we frequently hear or might anticipate. Suggestions: (What is available? Can I open a workload in YYC? Networking - Limitations - available services: now - later - when?)
2. Write answers for those questions (5-6 maximum)
3. Prepare a slide for the community update (July 30th)
4. Select a space to publish on PO Website
5. Get it published (Can be broken down in follow up ticket - close this ticket when follow up ticket to publish is created).

**Comment by MaxWardle** [comment]
Hey @ThibaultBC Pilar, Khurrum and I were talking about this one and we don't think this needs to be on the PO website as most people who ask would be developers. Also we think it's good to jsut have it in one place and be able to link it to people when they ask. If you agree we can close this ticket I think as the info is on the developer docs already.
