### ISSUE TITLE
Plan firewall change execution

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#3031]
- [ ] Plan the meeting/placeholder for selected date: Aug 1st
- [ ] List of steps for change (including communications) specific for Firewall
- [ ] Send communications by Thursday July 18th - so that it's a 2-week heads up.
- [ ] define prep steps

**Comment by jon-mc-git** [comment]
Change process for this firewall change was defined out for a better understanding of what was involved.  A two-week 'Change communication' was sent out to stakeholders to announce the upcoming change (Thurs, July 18th). 
 Worked with OCIO SecOps to create an RFP for this change using their current RFP register process and the team went through it with Chris to better understand their change format and the questions involved.  Ran through with the team then the smaller steps involved so everyone was on the same page as well.  The steps were somewhat undefined so we discussed and refined them, and some tech research was done to clarify these.  This change process brought these and other questions to the surface and plans were put in place to manage those elements (timing, lic tech questions, order of operations, online/in-place nature of the change, etc.).
