### ISSUE TITLE
Firewall change execution

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#3032]

**Comment by jon-mc-git** [comment]
Firewall Change execution process was initiated with the Change Team and is in progress - should be completed today, Aug 1st.

**Comment by jon-mc-git** [comment]
The change process was completed and the execution of the FW upgrade process was completed successfully on Aug 1st.

**Comment by jon-mc-git** [comment]
Post-change discussion held with Thibault to review.  Closing
