### ISSUE TITLE
GCP - Quarterly billing report

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#3048]
- [ ] start looking into generating a quarterly billing report for GCP clients
- [ ] Requirement: breakdown of cost generate per, per period (quarterly), so that we can sent a bill for cost recovery.

**Comment by MaxWardle** [comment]
Some thought into the architecture of the GCP projects is required for this ticket

**Comment by ThibaultBC** [comment]
Determined manual reporting is better for now - given there is no managed landing zone - too much effort to build and maintain, and we have a small amount of teams.
