### ISSUE TITLE
LZA Identity Design Doc & Diagram

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/cloud-pathfinder#3057]
- [ ] Creat e a list for design of the LZA
- [x] Diagram

**Comment by MaxWardle** [comment]
Written part of the process, and documented it here: https://bcgov.sharepoint.com/:w:/r/teams/01368-CPFScrumTeam/Shared%20Documents/CPF%20Scrum%20Team/007%20-%20Documentation%20%26%20Research/AWS%20LZA/LZA%20Identity%20Management%20Design.docx?d=wae3e18e0040d469e98a24af90efa612b&csf=1&web=1&e=u86LiD
