### ISSUE TITLE
Refactor `aws-login` app to use BC Gov tech stack/frameworks

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#318]
**Describe the issue**
Currently, the `aws-login` is implemented using a low-level coding library and for maintainability and consistency with other BC Gov apps, should be ported to use the higher-level, modern coding libraries that are in use for similar applications within BC Gov.  The application should also make better use of some native AWS services than it is currently doing to improve code maintainability, and to provide references for  other teams' apps'.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
An version of the application's code ported to React, using CloudFront for frontend hosting, Lambda for backend logic, checked into GitHub, redeployed, and tested in the LZ.

**Comment by sid-gov** [comment]
PO says we will do this before March 2021.

**Comment by mitovskaol** [comment]
Will be implemented in a different way, Not relevant anymore
