### ISSUE TITLE
SPIKE: Investigate how to build a cloud agnostic version of an AWS self provisioning menu

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#319]
**Describe the issue**
Andy found this http://ec2-18-223-40-154.us-east-2.compute.amazonaws.com menu and it could be a valuable addition to the self-serve CLI based team focused provisioner model we have.  The current approach is that we provide teams the ability to self-serve infrastructure to meet their own project needs, via a command line that ties into Cloud Pathfinder curated infrastructure modules.  What Andy has found here would be a nice front end sitting on top of the CLI version once the CLI work is feature complete and stable.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Understand what technologies are needed to replicate the self-serve GUI web menu in a way that will work in a multi-cloud environment, or that will be portable enough to be run in a similar manner in each cloud
- Create fulsome tickets describing the work

**Comment by lukegonis** [comment]
No longer relevant
