### ISSUE TITLE
Consolidate old docs

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#335]
**Describe the issue**
We have a legacy document system on documize which no longer need.  We are using Teams to store our team artifacts.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
https://docs.pathfinder.gov.bc.ca

**Definition of done**
- make sure everything is archived and stored in teams that was formerly on documize
- an old documize items tagged 'for your eyes only' get moved to the equivalent teams space
- delete cloud pathfinder documize presence

**Comment by mitovskaol** [comment]
no longer relevant
