### ISSUE TITLE
Find a easy to use replacement for public asset sharing

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#336]
**Describe the issue**
The team has asked team members for suggestions and has evaluated Miro, Teams, Documize, Github, Draw.io, Conceptboard, gsuite, Terrastruct, Lucidchart

For storing and working collaboratively on private docs, Teams is the clear winner.

We have not solved how to easily manage public artifacts like diagrams we wish to share.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- github allows public artifacts like .pngs that can just be viewed in the browser or included in a 3rd party webpage
- github is too hard to use
- documize allows public artifacts like .pngs but they only are resolved as a downloadable link
- refer to ticket 303

**Definition of done**
- find out what the community in BC Gov devexchange is using to easily manage artifacts for multi-disciplined teams without PR expertise
- implement it

**Comment by lukegonis** [comment]
No longer relevant
