### ISSUE TITLE
Make sure our Network for MVP is optimal per BC Gov

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#342]
**Describe the issue**
We want to pull in and go over the proposed LZ2 style of network architecture with our partners from within BC Gov. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- Scheduling to be arrange in prior Spike #341

**Definition of done**
- Have BC Gov eyes on the Network architecture of LZ2
- Discuss optimal endpoint settings
- Create slides for SecOps meeting

**Comment by sid-gov** [comment]
We have a meeting booked for April 21st with SecOps.
