### ISSUE TITLE
Customize Security Hub so that it is meaningful & actionable

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#345]
**Describe the issue**
This will be valuable to demonstrate how aggregated security will work grabbing events/alerts from team accounts and showing it in one centrally managed dashboard. 

Security hub is a collector of events and notifications from other services in AWS.  Hub and spoke model where separate accounts can send information to the central hub. 

We wish to simplify and triage the views of BC Gov determined high priority notifications.

The user for this is technology proficient users (Cloud Pathfinder and ISB).  

Insights' queries and filters have potential to meet the needs of this ticket.  Group by set of team project accounts, extra metadata.

For example.  Team X has 4 accounts (which we at BC Gov call an "account-set"), rigeorwh-dev, rigeorwh-test (PROBLEM HERE), rigeorwh-prod, rigeorwh-tools.  We wish to see a grouping that Team X or maybe rigeorwh- team has PROBLEM HERE

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
There's no LZ code yet so this will be manual for the console
- imagine a scenario with a dozen Early Adopters or so, all generating lots of events and logs.  We wish to not miss anything important.

**Definition of done**
- Final deployment to LZ2 if disruptive, do in LZ1 if the same features are available 
- WIP documentation of how this is applied to LZ1 in teams
- Working solution in LZ1 which can be deployed to LZ2 (stretch goal: through automation)
- Manual example with notes of how to reproduce that could feed into automation later
- Settings exports if possible
- a draw.io diagram stored in Teams (source included)
- Enough text to go into a nice slide
- Guardduty, Security Hub turned on and enabled
- Private demo to Security team, feedback incorporated
- Bonus: A small video demonstration to go into the demo deck

**Comment by ActionAnalytics** [comment]
Time Series Data

Ryan J: Splunk? Elastic Search service in AWS?
Bahram: Power BI

Snowplow/Looker

Integration tools exist, injest or send out. SIEM security incident event management.
We want to receive findings from security hub, not send data to security hub.
![Screen Shot 2020-09-22 at 2.35.53 PM.png](https://images.zenhubusercontent.com/5e98c26e92d4be32d8e29cb0/9a051e42-b4e8-4dde-b3ea-dc8fa46431e4)

**Comment by ActionAnalytics** [comment]
We've scoped this ticket down to not use extra tools and instead focus on visibility and discoverability using AWS security hub

**Comment by cloudsmart** [comment]
**Security Hub Configuration in LZ2:**
- Hub and Spoke architecture where there is a Security Hub instance on each account in LZ2 (Spoke), and a central Security Hub hosted on Security account (Hub). Spokes collect compliance status from AWS Config as well as findings (tread detection, anomaly, etc.) from Amazon GuardDuty, Macie, and IAM Access Analyzer for resources inside their local account. Spokes then send their local findings to the central Hub to aggregates the findings and presents them in a dashboard.
- Security Hub can also collect finding for Amazon Inspector, AWS System Manager Patch Manager, and AWS Firewall Manage but they've not been configured in LZ2.

**Security Hub Insights**:
- Security Hub comes with 31 built-in Insights that cover 
- Insights are queries that run against the findings to select the ones that match a criteria (filter). We can apply multiple filters from a list of available filters.
- We can group the results returned by an Insight based on only one attribute from a list of available groupby items.

LIMITATIONS: 
- Although we can add custom insights to Security Hub, we can't choose Filters or Group-by items outside the ones provided by Security Hub. As an example, we have the option of choosing Account-ID to group the results by it, but not the Account Name or Tags, etc. This limits our capability fo group the results based on Account Set which is one of the objectives of this ticket.

Options:
- Use the Security Hub dashboard with some level of customization within the limits.
- Deploy a solution based on ElasticSearch to build a new Dashboard

**Comment by cloudsmart** [comment]
Discussed limitations and potential options with Julian and Shea and decision was to:
- Not build external dashboards and use SH built-in dashboard
- Set up two Insights to list separate lists of findings based on Core LZ account vs. non-code (Teams) accounts. 
- Set up push notifications to send the output of Teams Insight to a Rocket.Chat channel for demo. To do this we need to modify existing code that was developed and maintained by AWS technical team (Ryan J.). After looking at the code Ryan J. provided we found that integrating the new Insights with the code wasn't a straight forward change and required deeper code changes in the Lamda function written in Python. This will be a candidate for another ticket to be developed in coming sprints.

End result: we demo the SH Insight for Team accounts using AWS dashboard and will work with BC Gov's SecOps team in the following sprints to build the solution for compiling, filtering, and transferring the findings based on their needs.

**Comment by cloudsmart** [comment]
Closing notes
Following artifacts were uploaded to Teams:
- draw.io source file (XML)
- draw.io diagram (png)
- Security Hub architecture (PowerPoint)
- Security Hub dashboard demo (mp4)

Automation work will be carried on under a new ticket #265

**Comment by ActionAnalytics** [comment]
This was an early demo piece where filtered out the landing zone noise, and created a filtered view that allows us to see team account generated events.  We demoed some events like root-account MFA missing alarms on team accounts that turned to be non-sensical, which highlights the need for us to do further work fine-tuning the alarms themselves to that things like root account checks don't happen on team accounts where there is no root user.
