### ISSUE TITLE
AWSConfigRole deprecation, possible LZ script update (tech debt)

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#363]
**Describe the issue**
A message was received about an expiring component possibly used by our Landing Zones.  We need to check that the codebase will run.

**Which Sprint Priority is this issue related to?**

**Additional context**
_"As part of our continued effort to provide AWS customers with fine grained and secure permissions management solutions, AWS Config has published a new managed policy called AWS_ConfigRole that is scheduled to replace and subsequently deprecate AWSConfigRole on December 1, 2020. This new policy removes the "S3:GetObject" permission as AWS Config does not need permissions to read S3 objects.

The AWSConfigRole  managed policy will continue working for all currently attached users, groups, and roles. However, effective December 1, 2020, AWSConfigRole managed policy cannot be attached to any new users, groups, or roles. No action is needed if your account does not utilize the AWSConfigRole managed policy."_

**Definition of done**
- Review LZ codebase for AWSConfigRole, and should it be present,
- Coordinate with our developers and AWS to update LZ Code (assuming we have it in source control by that point)
- Clean off LZ1 and try the code against it to ensure it still runs

**Comment by lukegonis** [comment]
No longer relevant
