### ISSUE TITLE
Curated list of consumable services for early adopters

### ISSUE THREAD

**Issue by ateppin** [bcgov/cloud-pathfinder#397]
**Describe the issue**
As the early adopter program is starting to take shape we need to pull together the necessary details for the participants about what services they can use.

**Which Sprint Priority is this issue related to?**
1

**Additional context**
#362

**Definition of done**
A list, catalogue or diagram of services available to early adopters & supported by CP team

**Comment by ActionAnalytics** [comment]
Done and included in Onboarding Workshop Slide Decks
