### ISSUE TITLE
Mural STRA/PIA

### ISSUE THREAD

**Issue by ateppin** [bcgov/cloud-pathfinder#403]
Describe the issue
We were using a trial version of Mural (after moving from Miro & Draw.io) & that trial is expiring on Oct 25.
Active members need to be removed & re-invited as "visitors". These do not need licenses.

Security initially gave us a "yes" to using Mural but we now need to follow-up & confirm

Which Sprint Priority is this issue related to?
Unprioritized

Additional context
- This is for team usage not corporate at this time

Definition of done
- Touch base with Paul and Sid and Stu, and Holly
- Work with CITZ MISO to review STRA/PIA work

**Comment by bluemel-gov** [comment]
- Task with IMB/IPS
- Ticket open for tracking/monitoring

**Comment by bluemel-gov** [comment]
- emailed about SOAR update 11/19

**Comment by bluemel-gov** [comment]
- initial risk assessment done and response back from IMB

**Comment by bluemel-gov** [comment]
- IMB reviewed document and confirmed that as long as no personal information is being used, that would be acceptable for privacy.
- Closed as complete
