### ISSUE TITLE
Report out on how we manage high level AWS notification

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#404]
**Describe the issue**
The Cloud Pathfinder team requires a clear mechanism for managing notifications from AWS regarding breaches in the AWS Network. This is part of our obligations regarding the security of Personal Information.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- clearly describe how we receive these notification i.e. who is named on the Province’s AWS Enterprise Account), and
- how we ensure continuity should persons responsible leave the CP team.

**Comment by lukegonis** [comment]
This is already covered by security teams CSPM Management
