### ISSUE TITLE
Review account metadata implementation in `aws-login`

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#414]
**Describe the issue**
Current implementation uses a slightly complicated set of services and configuration in order to extract and display account metadata. A different, simpler approach could possibly be used.  We should review the implementation and determine if we want to retain it or refactor it.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Intention to connect to project registry or other metadata source 

**Definition of done**
A decision on whether to retain of refactor the account metadata approach.
If applicable, tickets capturing the refactoring work.

**Comment by mitovskaol** [comment]
Not relevant anymore
