### ISSUE TITLE
Identify / extract training elements and approach for working with Digital Academy

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#416]
**Describe the issue**
We have identified many potential training elements related to cloud adoption. We will not have the capacity to delivery all of these.  We need to ensure that suitable, contextualized training is available through the appropriate channels for BC Gov cloud users.  We believe that the digital Academy has a role to play in facilitating this.  We need to work with the m to develop an approach for engaging, as well as specific training elements to be delivered.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Incorporate Shea's inputs into the training and onboarding

**Comment by sid-gov** [comment]
Met with Digital Academy but they didn't have capacity. Agreed to keep them informed.
