### ISSUE TITLE
Develop approach for LZ account lifecycle management

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#420]
**Describe the issue**
AWS does not currently support deletion of accounts, which means that we need to consider accounts more or less "permanent" once created.  Given this, it leads to question of to handle accounts that are no longer needed.  We need to develop a model / lifecycle and supporting tools (automations) for handling the purging / deactivation / idling of accounts as well as potentially "reactivation" of accounts from a pool of idling accounts.  There are existing tools and patterns for handling this problem, but we need to explore prior to implementation.

**Which Sprint Priority is this issue related to?**
Priority 2

**Additional context**

This will require consultation with AWS technical experts, and research into related challenges,  best practices available tools, etc. to support this activity.

**Definition of done**
- A description of the account lifecycle that we want to support, as well as rational/explanation for it
- Tickets capturing future work related to implementing the lifecycle, such as:
  - support tooling (scripts/TF modules)  
  - any LZ changes (e.g. policy and/or ou for "inactive"/idle accounts)

**Comment by sid-gov** [comment]
Close as duplicate with current sprint
