### ISSUE TITLE
Develop plan/approach to decommission / repurpose LZ1

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#421]
**Describe the issue**
LZ1 is nearing the end of its usefulness as we have moved away from the SLZ codebase it is based on and adopted the SEA codebase.  Therefore, we need to decommission or repurpose LZ1 account(s) - potentially into a "lab".  We need a lab because we need to give some of our teammates a place to experiment with things like geofencing or wide ranging changes.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
We will need to consult with AWS technical experts on this activity.

**Definition of done**
- decision regarding future use of LZ1
- a set of future tickets capturing the steps involved in repurposing as decided by team

**Comment by sid-gov** [comment]
We will make this a priority for CP Sprint 19

**Comment by ActionAnalytics** [comment]
Decision to bring under brokerage done
Currently bringing under GoC
