### ISSUE TITLE
Expand the retention period for logs/events/incidents in LZ2 prior to go-live

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#425]
**Describe the issue**
Currently we were operating in a beta low-cost mode but since we're about to go live we need to retain logs.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Discussion with AWS Ryan and Shea <- UPDATE probably not needed see below
- Get the actual retention period from Ryan.B <- UPDATE see comments below, it's 90 days
- Discussion with Cloud Pathfinder security as to their preference for retention
- Implement the change in conjunction with Ryan - likely this will involve changes to the LZ2 config and checking that in to the repo

**Comment by sid-gov** [comment]
Still a high priority according to PO.

**Comment by ActionAnalytics** [comment]
This has already been set to 90 days out of the box, which is ok per Ryan B and the Security Schedule

**Comment by ActionAnalytics** [comment]
So this is likely done and has nothing to do here, but confirm with Ryan B

**Comment by bluemel-gov** [comment]
https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-management-technology/information-security/information-security-awareness/cloud_security_schedule.pdf
'Log Generation and Retention
The Contractor must:
(a) generate and retain logs that are sufficiently detailed to determine who did what
and when for a period of 90 days online;
(b) provide real time access to logs;
(c) provide the technical capability to forward the logs to the Province; and
(d) correlate, monitor, and alert on logs.'

**Comment by cloudsmart** [comment]
There are two parameters in the LZ2 config file pertaining to log retention:
"central-log-retention": 730
"default-log-retention": 90

I expect the central-log-retention applies to Central Log Account and the "default-log-retention" applies to each individual account. 
Awaiting AWS Technical Resource (Ryan J.) to confirm!

**Comment by bluemel-gov** [comment]
- there is a bit of additional information and clarification I am trying to get for this from records management team when to use 90 days vs other durations @ActionAnalytics @cloudsmart FYI
