### ISSUE TITLE
SPIKE: Have a contingency plan for when Control Tower lands in Canadian Region

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#429]
**Describe the issue**
The AWS product Control Tower could replace some of what the Landing Zone does.  It is currently unavailable in Canada but will conceivably replace the Secure Cloud Accelerator (SCA).

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- A meeting with AWS occurs
- Executive is informed of timeline and risks
- Risk register updated
- Any immediate work items created as tickets for next refinement/planning

**Comment by lukegonis** [comment]
No longer relevant
