### ISSUE TITLE
DevHub Glossary providing agreed definitions of key cloud-related terms

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#437]
**Describe the issue**
Rumon has repeatedly asked for a clear definition of SaaS, as an example. Clear definitions of such key terms will enable increasing shared understanding, across government, in every discussion that references these terms. The current lack of shared understanding leads to different interpretations of direction-setting statements such as strategy, policy, standards.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Review with Stu, See Stu for draft to get started.  
- solicit input from Cloud Pathfinder team and others (HADF team, Platform Services, ES) on which cloud-related terms we need to define
- Draft the glossary in Teams
- Engage Tech team members and publish to DevHub 
- Present as living document during demo and solicit feedback

**Comment by mitovskaol** [comment]
Not relevant anymore
