### ISSUE TITLE
SPIKE: Investigate consumption caps with AWS

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#438]
**Describe the issue**
A ministry team on onboarding may have concerns about accidentally over consuming a spend level that is sustainable.

Cloud Pathfinder has with AWS created some rudimentary spend alerts at the Landing Zone level.

Possibly in conjunction with account tagging, can we offer teams the option to have a resource cap warning or even throttling automation?

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- Likely will require coordination with tagging development efforts

**Definition of done**
- Coordinate with AWS to understand what are the best approaches
- Select a best approach
- Create a set of well-defined and estimated tickets to implement a small demo based on the demo app
- Create a set of tickets for an Landing Zone work.

**Comment by lukegonis** [comment]
This is impossible/no longer relevant
