### ISSUE TITLE
Configure cloudfront logging for `aws-login`

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#442]
**Describe the issue**
Currently logging for cloudfront logging within the `aws-login` app is not enabled.  We should be capturing the log events  (access/login) in the for security/audit as well as debugging/troubleshooting purposes.  We may want to store these in the account where the application is deployed (for debugging/troubleshooting) as well as the shared logging account for visibility to security/auditing processes.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Initial discussion was had with AWS technical expert, exploring options but a specific implementation approach was not identified.  Further experimentation and likely consultation will be required in the course of completing this work item.

**Definition of done**

- code/deployment artifacts for `aws-login` are updated with logging configuration
- above deployed to LZ2
- behaviour validated (logs visible in expected locations as users interact with application)

**Comment by mitovskaol** [comment]
Not relevant anymore
