### ISSUE TITLE
Deploy aws-login with geofencing to LZ2

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#443]
**Describe the issue**
The latest version oft the `aws-login` app that incorporates geofencing has not been deployed to LZ2.  We want to have this in place as an additional security measure prior to bringing workloads on board.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**

**Definition of done**

- Latest version of app, with geofencing validated deployed to LZ2

**Comment by sheaphillips** [comment]
@cloudsmart please confirm and report whether remaining work to enable geofencing in LZ2 involves any changes *other than* updating KeyCloak link(s).  Inspecting set up in LZ1 should provide this info.

Check "saml:aud" value for IDP-related roles.  Does it include the cloudfront URL, or just the default AWS login plus the API gateway URL?

If update required we may wait to complete this work until #473 and #459 and/or #315 are complete.

**Comment by cloudsmart** [comment]
When aws-login is deployed through Terraform it creates a CloudFormation distribution that points to API Gateway. It returns the public DNS name for the distribution that should be copied to KeyCloak as the URL for SAML authentication.

**Comment by sheaphillips** [comment]
Thanks for the research @cloudsmart . The API gateway URL is currently hardcoded in several places and it will be tricky to track down and update without manual work. I'm going to close this ticket for now and leave geofencing in its current state.  We will work on this again once we have implemented a way of propagating the correct URL to all the places it is needed via Terraform.    I will create future tickets for the work.
