### ISSUE TITLE
Review AWS proposed changes to aws-login app

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#444]
**Describe the issue**
AWS has identified a number of suggestions/improvement to the aws-login app. We need to review these and apply them if we want to accept them.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
PR might be sitting in Ryan J's fork

**Definition of done**
- Updated code for aws-login, incorporating aws suggestions.
- updated documentation, and scripts as appropriate
- aws-login deplyoment in LZ with latest code.

**Comment by mitovskaol** [comment]
Not relevant anymore
