### ISSUE TITLE
SNS bot for Demo App

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#447]
**Describe the issue**
We have Rocket Chat connection from AWS alerts, budget, and security events.  Teams should be able to provision themselves with similar  abilities, but without having to run updates on the Landing Zone code.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- See if a pattern is possible
- Implement in Demo app
- in a separate repo

**Comment by lukegonis** [comment]
No longer relevant
