### ISSUE TITLE
SPIKE: How would a team app do CI/CD? 

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#448]
**Describe the issue**
We don't have a pattern for a team app to do CI/CD. And if we don't provide guidance, there will be multiple ways to do it. 

**Which Sprint Priority is this issue related to?**
Sprint 15

**Additional context**
- AWS is recommending a centralized CI/CD. 
- Discuss approach with Shea and Julian before starting this spike.

**Definition of done**
- Document initial proposal to present to Shea and Julian and get agreement on approach 
- Output of this would be part of a slide with recommendations.

**Comment by wrnu** [comment]
# Recommended CI/CD Architecture for Container Workloads

It is recommended to split the CI and CD into two separate workflows. The CI workflow stored in the application repository in GitHub and is implemented using a GitHub Action. The CD workflow is stored in the infrastructure repository for the team/application and  is implemented using a GitHub Action.

## Continuous Integration

- **Repository:** Application
- **Tool:** GitHub Action
- **Triggers:** Code is pushed to a branch or PR.
- **Artifacts:** Tagged container image in GitHub Container Registry.
- **Workflows**
  - **PR workflow**
    - Run tests only
  - **Branch workflow**
    - Run tests
    - Build container image
    - Tag container image
      - Tag pattern: `BRANCH_NAME-BUILD_NUMBER`
    - Push container image to GitHub Container Registry

## Continuous Deployment

- **Repository:** Application Infrastructure (could be many instances of this for separate deployments)
- **Tool:** GitHub Action
- **Triggers:** 
  - Container image is published or updated in GitHub Container Registry
  - Infrastructure code is pushed to a branch or PR.
- **Artifacts:** None
- **Required Credentials:**
  - Terraform Cloud token for the team
    - This has permissions for each TF workspace in the team (e.g. Dev, Test. Prod).
- **Workflow**
  - Determine TF workspace (Dev, Test, Prod) by filtering image tag
  - Using Terraform Cloud CLI workflow deploy image to the correct TF workspace.
  - **Non-production deployments**
    - Run tests that require a running application (e.g browser stack, load testing).

**Comment by wrnu** [comment]
This workflow could be generalized to any application that can be published as a GitHub Package (docker, npm, gem, mvn, gradle, donet).

**Comment by wrnu** [comment]
![cloud_pathfinder_ci_cd.png](https://images.zenhubusercontent.com/5fa99006c48838e6a262bb89/952587ab-3e1f-45bc-a107-e5823225db5e)
