### ISSUE TITLE
Review and update firewall VM parameters in SEA / LZ2

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#451]
**Describe the issue**
The current/default values for the perimeter firewall appliances are more than what is needed for the LZ.  Cost savings are possible by adjusting these.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
This recommendation was made by AWS technical expert.
Specifics suggestion is  to remove manager appliance, and to change EC2 sizing for remaining appliances to  c5n.xlarge from current setting.
Note: instance size changes for these appliances require deletion from config file and re-adding (in-place editing not supported) after state machine has executed.

**Definition of done**
Changes made to LZ config file and applied
Smaller instances running in place of current
Unused manager appliance no longer running

**Comment by sheaphillips** [comment]
@sheaphillips to confirm that this item is complete.

**Comment by sheaphillips** [comment]
@cloudsmart please refer to DoD and confirm that this is satisfied.

**Comment by cloudsmart** [comment]
Visually checked both Firewall instances and confirm they are c5n.xlarge instance type.
I did not see any manager appliance.

**Comment by cloudsmart** [comment]
Closing the ticket per Shea's confirmation!
