### ISSUE TITLE
AWS Guardrails additions based on GC Controls and shared responsibilties

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder#452]
**Describe the issue**
Based on feedback from the CP team. Update controls to reference GoC also. This will help for a lift and shift to other CSPs.

**Which Sprint Priority is this issue related to?**
3

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Complete review with PO 
- Add a column for the controls from the GoC https://github.com/canada-ca/cloud-guardrails for the one or more that apply. Column title 'Operations/teams'
- Add a column for the responsibility of the control (CSP/BC Gov Operations(ISB support)/BC Gov Ministry teams)
- Review internally with ISB staff
- Review with privacy
- Review and sign off by CP team( Gen/Paul/Stu)

**Comment by bluemel-gov** [comment]
set up meeting to review with PO on 12/4

**Comment by ActionAnalytics** [comment]
We decided to automate first, then craft the automation.

**Comment by bluemel-gov** [comment]
- set up meeting with privacy on 12/11 to review

**Comment by bluemel-gov** [comment]
- reviewed with privacy on 12/11

**Comment by bluemel-gov** [comment]
- reviewed with PO in Dec
- on Track to review with ISB internal on 1/08

**Comment by sid-gov** [comment]
Closing as complete. Meeting with PO to be set up.
