### ISSUE TITLE
Develop approach for ensuring "East-West" traffic isolation within subnets

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#469]
**Describe the issue**
Out understanding is that the SEA's security groups, subnet layout, NACLs, etc. do not provide network isolation between traffic in different teams' accounts within the same OU.  (e.g. `team-1-dev-account` can theoretically "see" traffic in `team-2-dev-account`) We need to explore and provide options for  how to ensure network traffic is *not* visible across different team accounts ((e.g. ensure `team-1-dev-account` *can't* "see" traffic in `team-2-dev-account`) .  There are likely different ways to fulfill this requirement, so we need to do some research/exploration and capture/document the options and a selection of an approach in order to develop an initial implementation.

**Which Sprint Priority is this issue related to?**
Priority 2 - LZ manageability

**Additional context**
- Only through security groups per Ryan J, these groups aren't pre-defined.
- this would have to be done on every resource created
- the sentinel policy would have to be pretty smart
- Inter-account East West not dev, test, prod East West
- Can do via tagging as well per Warren
- For future work, should/can we create one or more security groups as part of account creation instead of having teams do it?

**Definition of done**
- Textual or visual notes describing one or more solutions
- Description of how demo app would implement traffic isolation
- Updated sample app infrastructure TF Module with example implementation
- Sample app deployed with updated infrastructure (in Team member's account within LZ)
- Update early adopter decks/notes to communicate that by default/for the moment teams can see each others' stuff, and that it's their responsibility to hide their stuff (not sure PO likes this)

- Review with Ryan B and Julian prior to demo, include diagram (possibly pulled from/based on SEA docs)

**Comment by wrnu** [comment]
This may contain some useful info: https://aws.amazon.com/blogs/security/use-aws-firewall-manager-to-deploy-protection-at-scale-in-aws-organizations/

**Comment by sheaphillips** [comment]
Other ideas are to create a default security group per-account (during account provisioning) and restrict traffic based on that.  Workloads in an would be expected to be launched within that security group.  Checks could be implemented to flag workloads not running in that security group.

**Comment by cloudsmart** [comment]
**Problem Statement**
Secure Environment Accelerator (SEA) utilizes Shared VPC for central networking and edge connectivity management across multiple accounts in the Landing Zone. It provides isolation at environment level by allocating separate VPC’s for Dev, Test, Prod, Central, Unclass, and Sandbox. Each VPC contains several Subnets (e.g., Web, App, Data) that are shared among the participating accounts. 
While this level of segregation is necessary to isolate Prod workloads from Dev or Test workloads, it is not clear how it can isolate the workloads inside each environment. For example, is it possible for an application server hosted in App Subnet of Prod environment in Account A to access a database that is hosted in Data Subnet of Prod environment in Account B?  

**Solution Options**
1.	Share a different subnet for each participant account. One subnet per participant enables Network ACL to provide network isolation in addition to Security Groups.
https://docs.aws.amazon.com/whitepapers/latest/building-scalable-secure-multi-vpc-network-infrastructure/amazon-vpc-sharing.html

2.	Use Security Groups to isolate workloads within accounts. Currently SEA creates copies of Security Groups predefined in Shared Network account in each new Account as part of Account provisioning process. The local Security Groups control access to resources inside their Account and isolate them from resources hosed in other Accounts. 

 
**Compariosn**
Solution Option	
Option 1) Separate Subnets per accounts in the Shared Network account (fine grained)	
Pros:
•	Isolation at Subnet level through NACL
•	Controlled by central networking team	
Cons:
•	Potential for running out of IP addresses
•	Hard to manage as number of accounts increases

Option 2) Separate Security Groups per accounts within the Shared Subnets (coarse grained)
Pros:	
•	More practical from the implementation and maintenance point of view
•	Provided by SEA out-of-the-box therefore no customization is required	
Cons:
•	Participating accounts can alter the Security Groups or completely bypass them by setting up new Security Groups.

**Conclusion**
•	SEA provides workload isolation through Security Groups at Account level as part of the shared VPC architecture. 
•	This is the optimal solution considering various factors such as cost, maintainability, and extensibility.
•	Need to setup Config Rules to detect any alteration to the Security Groups created by the account provisioning process (Detective Guardrail) for visibility and corrective actions if required.
