### ISSUE TITLE
Port account provisioning code to Terraform Cloud

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#473]
**Describe the issue**
Our workload account provisioning automation code - the code that creates workload accounts and applies BC Gov-specific "layers" to them in the SEA landing zone - has been developed and tested on a developer's workstation, but not executed within a managed runtime / state management environment.  We need to do this so the code can be executed on demand by any CPF team with applicable permissions, and executions logged, monitored, etc.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- This task *does not* include implementation of CI/CD for the account provisioning code
- This should be done in a way that we can replicated for repurposed LZ1 and any subsequent AWS landing zones based on SEA codebase

**Definition of done**
- appropriate resources and access configured in TF Cloud.
- existing "state" migrated to TF cloud.
- provisioning code is triggerable remotely

**Comment by wrnu** [comment]
PR: https://github.com/bcgov-c/aws-lz2-workspaces-live/pull/2
