### ISSUE TITLE
Update SEA config.json to create HTTP listener on public albs

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#480]
**Describe the issue**
Currently there is a HTTPS listener but no HTTP listener on the public ALBs in the perimeter account. This means that attempted connections to sites in workload accounts will timeout when accessed via HTTP instead of redirecting to HTTPS. To solve this issue an HTTP listeners should be created and all HTTPS traffic should be redirected to HTTPS.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
SEA config is deployed to LZ2 and all HTTP traffic is redirected to HTTPS on both the Prod and DevTest ALBs in the perimeter account.

**Comment by mitovskaol** [comment]
Not relevant anymore
