### ISSUE TITLE
Create list of Azure workloads and see if Platform Services is ready to store them

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#481]
**Describe the issue**
Executive wishes to know who is on Azure now.  We don't have a list so we should create one, preferably not duplicating work Platform Services has done with the project registry.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- Book meeting with ES to gain info

**Definition of done**
- Provide a list of Azure workloads such that it can be ready for exec when requested
- Entries in the Project Registry if possible, but if this isn't ready we still need a list so Excel in Teams or even a drawing would suffice for the short term.  Emphasis on clarity and simplicity.

**Comment by lukegonis** [comment]
No longer relevant
