### ISSUE TITLE
SPIKE: How to connect/integrate AWS GoC Code guardrails watcher

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder#483]
**Describe the issue**
- there is a repo https://github.com/canada-ca/cloud-guardrails-aws
- How to use/apply that to the current LZ2

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by bluemel-gov** [comment]
- Cloud custodian, Cloudformation guard, prowler, aws config provide similar functionality as 'watcher' tools

**Comment by lukegonis** [comment]
No longer relevant
