### ISSUE TITLE
Deliver draft Early Adopter onboarding workshop for Traveler Screening (Health) team

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#484]
**Describe the issue**
PO is the owner of this ticket. We need to co-ordinate several speakers and slide decks such that we are all on message and we deliver an efficient onboarding presentation. 

We've designed two half-day workshops to introduce our team to the Early Adopter teams, and provide background on what we've set up in the way of Landing Zone, KeyCloak, Infrastructure-as-Code, Corporate PIA and STRA .. etc. Also review the Early Adopter Submission, Service Blueprint, Shared Responsibilities Model, and discuss how we propose to work together - all aimed at getting our Early Adopter Program off to a good start. 

**Which Sprint Priority is this issue related to?**
Sprint 16, Goal 1

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Speakers organized
- Materials prepared
- workshops conducted and feedback gathered on what the Early Adopters liked, and any suggestions they might have for improvements
- capture notes on how it all went

**Comment by sid-gov** [comment]
This has been postponed from Dec to Jan 2021.

**Comment by bluemel-gov** [comment]
- Reviewed on dec 12 with ISB
- Draft deck ready for PO review
- Next steps incorporate feedback and meet w/isb again

**Comment by ActionAnalytics** [comment]
Done, team did a fantastic job presenting a 3 hour series of Onboarding Workshop Slide Decks
