### ISSUE TITLE
Document lessons learned so far on policy 

### ISSUE THREAD

**Issue by emilyjones430** [bcgov/cloud-pathfinder#485]
**Describe the issue**

The team wishes to capture lessons learned on policy so far, so that it's repeatable and reusable (internal audience).
Ensure future ministry understanding of happy-path to effective policy work (external audience).

-DNs
-Comms
-FAQs
-Specific policy concerns (RMB)
-Website updates

**Which Sprint Priority is this issue related to?**

**Additional context**
audience: CP team member
Other audience: Gen messaing out to gov stakeholders that this is hard - don't go it alone, come take advantage of the work we've done

**Definition of done**

- lessons learned
- what work/what could be better
- time estimate and actual time spend ( paste in vertical timeline)
- meetings
- stakeholders involved ( and roles)
- approval chain used
- in Teams scrum/agile, lessons learned
- This is intended to be a draft collection of material for future aggregated document

**Comment by sid-gov** [comment]
To be re-defined in the next couple of days in the next sprint. (Meeting with Julian, Stu and Emily)
