### ISSUE TITLE
Follow up with remaining Early Adopter candidates, towards setting target dates for onboarding

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#489]
**Describe the issue**
We announced two Early Adopter teams at our sprint demo on November 17th. Several other candidates are still working towards preparing to join the EA Program - we promised to keep the conversation going with them.

**Which Sprint Priority is this issue related to?**

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Connect with each remaining Early Adopter candidate and inquire as to their work towards completing our submission template
- Update our spreadsheet with status of each and date for next meeting

**Comment by sid-gov** [comment]
Closed as complete.
