### ISSUE TITLE
Dry-Run: Compliance Review on EA Workshop content

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#490]
**Describe the issue**
Po is the owner of this ticket. There is a bunch of material being created for EA workshops and CP compliance should be aware of it's contents so they can align their presentations. 

**Which Sprint Priority is this issue related to?**
Sprint 16, Goal 1

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Dry-run conducted for Gen
- Compliance shared understanding of material that will be presented to the Early adopters
- Improved compliance early adopter material using that general understanding

**Comment by ActionAnalytics** [comment]
Done and presented Onboarding Workshops today successfully!
