### ISSUE TITLE
Review CSS with PO

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#491]
**Describe the issue**
We want to review the Cloud Security Schedule to ensure maximum fit for all parties involved based on the unique perspective for the CP team as a central hub for vendor and contractor experiences so far. 

**Which Sprint Priority is this issue related to?**
3

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Document with any proposed changes to CSS

**Comment by bluemel-gov** [comment]
- Booked meeting for 11th for 1hour

**Comment by bluemel-gov** [comment]
- Booked an hour for 02/12

**Comment by bluemel-gov** [comment]
- Booked follow up session for 17th

**Comment by bluemel-gov** [comment]
- met with PO on 02/17.
