### ISSUE TITLE
Review of EA Implementation

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#494]
Describe the issue
This is a sanity check on the technical aspects of each team is proposing to do in AWS and how they will do it involving the three SMEs for them to bring their lens of expertise to the process so that we don't miss any subtle problems. This will come in useful for when teams ask questions to our 3 SMEs because they will have a basic understanding of what they are doing already. This is to enable CP Compliance to get context of what EA teams are doing. 

Which Sprint Priority is this issue related to?
Sprint 16, Goal 1 (?) - learning is for Emily, Ryan and Holly

Additional context
- 1st version of Early Adopter Onboarding and Training
- Support Early Adopters and learn from them
- These meetings involve Julian, Emily, Holly and Ryan. 

Definition of done
- This is a 30 min. verbal review/virtual meeting
- Written document for problems that arise (if any)
- Book the meeting in the new year after the EA session and aim for the meeting in the end of Jan 2021.

**Comment by hromanow** [comment]
Meeting scheduled for Jan 27.

**Comment by sid-gov** [comment]
Closing as done and making another one for Mines.
