### ISSUE TITLE
Tagging model for Cloud Resources

### ISSUE THREAD

**Issue by lukegonis** [bcgov/cloud-pathfinder#5]
Here is the meta data we add to an openshift namespace:
In the background we use the GAL codes for the org structure, notably missing is the standard GL coding from iStore orders because we wanted to force the conversation of rolling up quota to the IMB level as a single "digital investment" instead of a chargeback.
Labels:		
		bus_org_code=CITZ
		bus_org_unit_code=BCDEV
		category=venture
		environment=prod
		mcio=CITZ-IM
		miso=CITZ-IMBSPC
		mpo=CITZ-IMBSPC
		name=devhub
		product=devhub
		project_type=user
		team=DevOps
Annotations:	
		openshift.io/description=The home and supporting services for the BC Government Developer program (developer.gov.bc.ca) (prod)
		openshift.io/display-name=BC Developer Hub (prod)
		product-lead=Patrick.Simonian@gov.bc.ca
		product-owner=todd.wilson@gov.bc.ca

**Comment by mumit** [comment]
One hour workshop as first iteration to gather the metadata, with three possible sources:
- OpenShift cluster metadata that is currently being injected via BCDK
- Azure tenancy tags defined
- AWS guidance (+ informed by a few implementations)

Question for the team: cost accounting is just one aspect, so can we take that out of the title? We'll likely capture most of what we need, including for cost accounting, in the workshop.

**Comment by mumit** [comment]
BC Gov Azure base tags (cf. Sec 2.5.1 in **BC Gov's Azure Foundation** v0.9):

- **Solution-Name**: Application or solution name
- **Environment**: tech environment ("PRD", "DEV", etc)
- **Classification**: Data/system classification
- **Cost-Centre**: 
- **GL-Code**: 
- **Expiry-Date**: empty value implies 100 years

Note that tag naming convention needs to be take into account multiple providers (GCP mandates lower-case only for example).

**Comment by mumit** [comment]
Three things to consider:
- Dimensions: bucket tags for technical (app name, id, role, env, ver, what-not), business (billing, project, owner, etc), security/compliance (pii/hipaa, data classification, etc), automation/optimization
- Tagging standard -- what are the conventions for names/values for at least the 3 big vendors
- Operationalize -- how do we set things up to auto-inherit the base set, and how much does that leave for each of the 3 big vendors (+ other cloud providers)

**Comment by mumit** [comment]
Whiteboard from meeting on Tue Mar 3. Next step is to break down the pieces -- metadata store, provisioning, etc.
![metadata model whiteboard resized.jpg](https://images.zenhubusercontent.com/5e50286a61915b28ac9e58e3/65bce870-e01e-4c0b-8814-6ed2c2cee023)

**Comment by kelpisland** [comment]
[https://github.com/BCDevOps/openshift-tools/tree/master/provisioning/environment/playbook](url)
