### ISSUE TITLE
Test drive PIA

### ISSUE THREAD

**Issue by paulroberts68** [bcgov/cloud-pathfinder#513]
We want to see how many of the AWS services will be covered by the corporate PIA. The results will tell us which services will show up in the Managed Cloud Services (MCS) catalogue.

DOD:
1. List of GoC AWS services in each PIA category.

**Comment by sid-gov** [comment]
We intend to check that Compliance lines up to the services offered in BC Gov LZ2 and rather than take a manual approach via PIA/SoAR, we will use Security controls to automate it.
