### ISSUE TITLE
Onboard and submit service order requesting AWS agreement to additional terms

### ISSUE THREAD

**Issue by paulroberts68** [bcgov/cloud-pathfinder#514]
**Describe the Issue**
Successfully onboard to the GoC Cloud Brokerage Service, and negotiate agreement with AWS and Shared Services Canada on additional terms for BC compliance.

**Sprint Priority**
1

**Additional Context**
- There's a significant amount of uncertainty and back and forth that is complicating the estimate. 

**Definition of Done**
1. Get access to the order fulfilment system
2. Obtain wording from LSB for terms to be added to AWS Framework Agreement
3. Create and send Service Order to requesting AWS agreement to additional terms

**Comment by scayzer** [comment]
Completed 2020-12-16
