### ISSUE TITLE
Review Chapter 12 and determine implications for OCIO vs Ministry responsibilities in our Managed Cloud Service 

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#517]
**Describe the issue**
There is uncertainty about who is responsible for what in accessing cloud services (procurement, privacy and security compliance, policies, standards, guidelines ..).  If we are actively promoting a shared responsibility model, we wish to make sure there are no contradictions elsewhere.

**Which Sprint Priority is this issue related to?**
Priority 1

**Additional context**
- New Chapter 12 is yet to be approved by Treasury Board (TB).
- estimated as fairly high level (Gen)
- Feeds into Service Blueprint

**Definition of done**
- Complete an analysis, develop summary document outlining responsibilities.
- look for tech code of practice, digital principles
- Peer review (both Ch12 team and Cloud Pathfinder Team).
- Stu and PO to review, Gen to approve.

**Comment by emilyjones430** [comment]
Draft being put forward for branch review by EOD Wednesday (Feb 10).

**Comment by emilyjones430** [comment]
First draft sent to Jenny R. for review EOD Feb 10.

**Comment by emilyjones430** [comment]
Final draft sent to @cstua Feb 22nd.
