### ISSUE TITLE
Connect AWS Guardrails Security work with Shared Responsibilities Model

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#518]
**Describe the issue**
We wish to be able to go from a high level shared responsibility model diagram all the way down to the code.
We already have a related ticket to connect the bc gov security schedules with the AWS recommended controls.
- addresses lack of security detail in the Shared Responsibilities Diagram
- have a visual representation of the security at the different levels (CSP--OCIO--Ministry)
- a diagram that has security automation pieces captured on it
- responsibility of the ministry and the OCIO on it
- considers Multi Factor Authentication (MFA)

**Which Sprint Priority is this issue related to?**
Goal 1

**Value to the MVP**
- This will help for early adopters

**Additional context**
- wish to avoid impedance/mismatch with master diagram.

**Definition of done**
- an Excel file mapping relationships
- tied very closely to the Shared Responsibility Diagram
- a draft document that has been reviewed from security, privacy and Cloud Pathfinder at the different layers
- Is AWS focused because of MVP
- Includes up to protected B data

**Comment by lukegonis** [comment]
No longer relevant
