### ISSUE TITLE
Finalize Early Adopter Workshop agenda for early January 

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#521]
**Describe the issue**
We have two Early Adopter teams currently scheduled to begin work in our compliant Landing Zone, starting in earnest in January. The Health Team (Freshworks - COVID Traveler Screening app) has requested a workshop on December 15. We've set expectations that the Landing Zone and Cloud Pathfinder support team won't be fully available in January, and their requirements for the workshop are minimal as they've already been building and running this app in AWS for several months. Therefore, we need an agenda tuned to this context for December 15

**Which Sprint Priority is this issue related to?**
1

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- collaborate with Julian on building the agenda and supporting slide deck
- review with Gen and incorporate her input
- review with Pam Smith and incorporate her input

**Comment by ActionAnalytics** [comment]
Update Health to Jan 6 or 7

**Comment by ActionAnalytics** [comment]
Still need to schedule Mines

**Comment by ActionAnalytics** [comment]
Done, presented to Health today and have date lined up for Mines right after their release
