### ISSUE TITLE
SPIKE: Explore Sentinel policies

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#522]
**Describe the issue**
Cost estimate is inspiring, any other low-hanging fruit high value items we can demo?

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- New well-formed tickets in ZenHub 
- A slide in the demo presentation discussing some of the features

**Comment by mitovskaol** [comment]
Not relevant anymore
