### ISSUE TITLE
SPIKE: Evolve CI/CD pattern and associated capabilities to support use of shared team/LZ resources 

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#524]
**Describe the issue**
Currently the accounts are isolated from each other, how would we accomplish an ECR in a tools account and promote that to the different environments.  Currently we use public github gov registry but we may wish to look at other approaches if dealing with gov-c

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- there is no connectivity per Ryan J
- project spec Resource Access Management sharing (using the project spec to set up shared resource)
- avoid circuitous expensive routing 

**Definition of done**
- Research and spend time with Ryan J
- Determine the pattern, does Cloud Ops run an ECR, then ACL so people can't clobber images

**Comment by wrnu** [comment]
- Create shared ECR repository in the Tools (sandbox) account. This ECR repo will be shared by all environments (dev, test, prod, etc)
- Assign a policy to the ECR repo that allows allows principals read/write access
  - Principals allowed are each environment account `arn:aws:iam::account-id:root` and a service account with limited access (e.g. only push on ecr).
- The service account has long lived credentials that can be used to push images from CI (github actions)
- The policy allows AWS services such as ECS (in any account specified on the policy) to pull from the ECR repo.

References:
- https://aws.amazon.com/premiumsupport/knowledge-center/secondary-account-access-ecr/
