### ISSUE TITLE
Implement AWS-recommended mods to LZ

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#527]
**Describe the issue**
We have had a LZ2 review from Andy Fase and there are some items we wish to change on LZ2.  Initially we intended for Andy to do the work but due to procurement delays we will likely have to do the work ourselves.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- This is not the IP Range work, this is the LZ2 review

**Definition of done**
- The majority of the changes are config changes that need to be done in the repo
- There is an additional piece that needs to be scripted, and added as the last step of an SEA LZ upgrade process because the upgrade will clobber it.  We also need to ask the SEA maintainers to include this as a part of SEA so we can avoid custom steps.
[PO to provide more detail]

**Comment by mitovskaol** [comment]
Not relevant anymore
