### ISSUE TITLE
SPIKE: Draft CI/CD patterns to reuse code

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#531]
**Describe the issue**
Instead of seeing an ecosystem or CI/CD sprawl, we want to group patterns so that teams can work off a common set of CI/CD code to avoid sharp edges for each team.  Also to consider PR based workflows -> Master branch.  

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- For PR based workflows we would need to either bake off entire ECS clusters or better inject differently named pods inside existing.
- URL firewall step is a manual process at the moment (which is perimeter network, which we don't want to allow team automation to change)

**Definition of done**
- Roll up CI/CD into an NPM module or Action Step including patterns
- Create plan to move CI/CD forward
- Determine the need for / balance around tightly wrapped CI/CD functionality (make the molecule, provide all the atoms)
- Balance early optimization vs pathfinding
- Timebox to a solid day's effort

**Comment by sid-gov** [comment]
Follow-up with CP Tech team needed.
