### ISSUE TITLE
Document lessons learned on procurement so far on the Cloud Pathfinder journey

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#532]
**Describe the issue**
The team wishes to capture lessons learned on our procurement work so far, including negotiation of contract terms, so that it's repeatable and reusable (internal audience).
Ensure future ministry understanding of happy-path to effective communication and engagement (external audience).

**Which Sprint Priority is this issue related to?**
Sprint 15

**Additional context**
audience: CP team members

**Definition of done**
lessons learned
what work/what could be better
time estimate and actual time spend ( paste in vertical timeline)
meetings
stakeholders involved ( and roles)
approval chain used
in Teams scrum/agile, lessons learned
This is intended to be a draft collection of material for future aggregated document

**Comment by sid-gov** [comment]
Closed as done. Further tickets may be created for next steps.
