### ISSUE TITLE
Investigate and capture patterns for Service key rotation (Vault)

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#540]
**Describe the issue**
We want clarity and instructions for Ministry teams on how they should be handling security key practices and security. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Meeting with the CP Technical team
- Scoped table with multiple services and policies for each
- Meeting with Platform Services to investigate Vault capabilities
- A jurisdictional scan of other potential groups in Govt. who are standing up key management services 
- Incorporate the input from the capabilities of AWS

**Comment by wrnu** [comment]
No longer relevant
