### ISSUE TITLE
Standup GoC Prowler

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#541]
**Describe the issue**
We have a list of 70 odd compliance checks that need to be done on a recurring basis. 

**Which Sprint Priority is this issue related to?**
3

**Additional context**
- GoC has a repo full of similar automated checks that we can reuse. (https://github.com/canada-ca/cloud-guardrails-aws)

**Definition of done**
- A scheduled task that is running the set of tests from GoC. 
- Results of the 1st set of tests

**Comment by wrnu** [comment]
# GoC Prowler

## Summary

Prowler provides an easy way to leverage the work done by the GoC to verify Guardrails for AWS.

### Pros

- Leverages work done by GoC and the wider community.
- Flexible. Checks are bash scripts that can run any code or tool to perform the validation.

### Cons

- Difficult to maintain.
- GoC roadmap is to move away from Prowler.
- No remediation action available. 

## Notes

- Prowler is written in bash.
- Checks are imperative and written in bash.
  - aws cli generally used to inspect aws resources, although it is possible to write custom code and call it from the bash checks.
- Supports AWS Security Hub Integration.
- GoC Roadmap includes plan to move away from Prowler.
- Running against multi-accounts is not build in to Prowler. An account list must be created externally and looped over.
 - Demo Github action for running prowler (https://github.com/wrnu/cloud-guardrails-aws)
