### ISSUE TITLE
Standup Cloud formation guard

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#543]
**Describe the issue**
We are looking for automation solutions to security compliance. This is one of the 3 proposed solutions. 

**Which Sprint Priority is this issue related to?**
3

**Additional context**
- Overlap and scope between this and AWS config unknown

**Definition of done**
- Small example implemented on LZ2
- Sample output available to compare to other solutions
- time-boxed to 2 days

**Comment by wrnu** [comment]
# CloudFormation Guard

CloudFormation Guard is a tool that checks AWS CloudFormation templates for policy compliance using a simple, policy-as-code, declarative syntax.

This tool is a more limited scope than real time security compliance verification of AWS resources and is not analogous to Cloud Custodian or Prowler.

Additionally, this tool only applies to CloudFormation templates and cannot verify policy compliance of other IaC tools such as Terraform. The equivalent tool in the Terraform ecosystem would be HashiCorp's Sentinel product.

## Links

https://github.com/aws-cloudformation/cloudformation-guard
