### ISSUE TITLE
Figure out what apps are in Azure

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#544]
**Describe the issue**
We wish to know what legacy workloads are currently present in BC Gov Azure. 

**Which Sprint Priority is this issue related to?**

**Additional context**
- David Ell has said he may have the list of subscriptions

**Definition of done**
- Reach out to Microsoft to figure out subscriptions owners
- Ask David if there are others besides him who would know that information
- Reach out (with above if any) 
- Deliver the list to Julian, Gen
- Create any tickets needed for Compliance review after Gen/Julian's input

**Comment by scayzer** [comment]
Update 2021-01-13: obtained list from David and have shared with Julian and Gen on Teams

**Comment by scayzer** [comment]
Update 2021-01-13: obtained list from David and have shared with Julian and Gen on Teams
