### ISSUE TITLE
SPIKE: Start developing a plan of what Cloud pathfinding work to do in Azure

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#545]
**Describe the issue**
We wish to get moving with Cloud pathfinding in Azure taking advantage of the momentum that Enterprise Services has. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- Reach out to Greg, David Julian and Justin

**Definition of done**
- Document in CP Teams that is a living planning document with a mini roadmap and brainstorming ideas
- Reviewed by Julian, Paul and Gen
- time-boxed to 1 day

**Comment by scayzer** [comment]
Researched 2 options for Azure procurement with David Ell, Michel Pariseau (manager of the Cloud Brokering Service) reviewed and tuned-up with Julian, Paul and Gen. 

Added an outline of how pathfinding might proceed and shared with collaboration group (Julian, David, Mac, Greg, Justin, Dennis), inviting their input - 2021-01-28. Will open a new ticket if more work required on this.
