### ISSUE TITLE
Update certificates for LZ Firewall admin console

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#546]
**Describe the issue**
Currently firewalls are using self-signer certificates for TLS termination.  We should generate CA-signed certs for this use so we don't get browser certificate warnings.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- It Is possible to use Load balancer for this
- May involve creating DNS

**Definition of done**
- No more security warnings when visiting the firewall GUI
- Has to be done before 16th April

**Comment by wrnu** [comment]
This may not be relevant once we move to the checkpoint firewalls

**Comment by mitovskaol** [comment]
Not relevant anymore
