### ISSUE TITLE
Follow-up for Onboard session to capture feedback

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#549]
**Describe the issue**
We'd like to know how the team felt about the 3 hour onboarding session such that it can benefit the teams that come after.

Specifically: How was that?  What can we do to improve that?  Did that land well?  Could this have been done differently such that it better allows you to process the material? Has anything come up that you wish had been included? Was there info you didn't need?

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Coordinate Derek & Emily (assuming Emily is leading this)
- Capture missing pieces
- Look for material to cover better
- Some of recipients could become presenters

**Comment by emilyjones430** [comment]
Survey was developed and sent out, responses have been compiled in a spreadsheet and a meeting to review the responses has been booked with Bahaa and @scayzer on Feb 8.

**Comment by emilyjones430** [comment]
Feedback was discussed and suggestions have been included in an onboarding schedule brainstorming doc.
