### ISSUE TITLE
Post-mortem after Onboarding Session for HADF, Playbooks, Academy

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#550]
**Describe the issue**
A group session after the Mines demo to share feedback and discuss integration with HADF, Playbooks, Training Academy material.

**Which Sprint Priority is this issue related to?**
Goal 1
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- Derek interested in how info gets to high-level stakeholder.

**Definition of done**
- Mines demo to happen with HADF, Playbooks, Training Academy teams watching
- One hour meeting afterwards to gather feedback

**Comment by bharmouche** [comment]
too much time has gone by since the session, we suggest we build a general survey that the team attending the session can run it with clients.

**Comment by mitovskaol** [comment]
Not relevant anymore
