### ISSUE TITLE
Hands-on Technical Workshops, onboard

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#555]
**Describe the issue**
We would like to enable LZ2 tenants to deploy and get started tech-wise.

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
- unless #525 are done, the tenant will need to reach out to the ops team to help connect the app such that it can be viewed from outside browsers
- Priority 1

**Definition of done**
- Ask the team to nominate an initial devops designee
- Only for people with accounts and credentials who can do it, not watch.
- 2 hour session
- Invite Health team, Clecio (and Derek R), Gary W, and any other team we have onboarded at this point (potentially NRM Observability Metrics, Mines - but we could do those next sprint if needed)
- Health team is able to stand up and update (tear down they cannot do yet) the demo app on their own
- Guided workshop help them to deploy the demo app
- Document in the cloud ops repo and improve onboarding material 
- Handle follow-on questions

**Comment by ActionAnalytics** [comment]
Clecio
It may be fine with starting with shared namepspace s(which is what we did for openshift 101), but for 201 we endeup with multiple/individual namespaces because even during 101 they wore colliding all the time

we used the collision as a teaching opportunity to emphasize the diligent needed on naming and labeling


suggest making it clear that this pattern is for the lab, one time, but in prod you do multi

**Comment by wrnu** [comment]
# Workshop Outline

## AWS SEA Overview

- Brief Intro
- Architecture Diagram(s)
- Networking

## LZ2

- LZ2 specific architecture
  - Shared workload networks
- Project setup
  - Project spec 
- Accessing AWS / Credentials
  - Users (Keycloak)
  - Service accounts (Terraform Cloud)
- Supported resources

## Startup Sample Project (Demo App)

This section will be a mix of presentation and hands-on. The end result will be the demo app running in their account.

- Overview
- Local development
- Infrastructure
  - Architecture
  - Terraform / Terragrunt
    - Intro (terraform, terraform cloud, terragrunt)
    - Architecture
    - Running locally with team token
- CI/CD
- Configure public access
- Accessing Logs

**TBD**
- what to do about demo app code
  - fork into user repo?
  - make repo a template?

**Comment by ActionAnalytics** [comment]
Clecio, Derek R, Gary W all have working AWS access and are ready for the lab sessions (thanks Shea and Warren)
