### ISSUE TITLE
Create a security viewer role and build into account vending machine

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#556]
**Describe the issue**
We need to deploy into every existing account, and we need to have this built in to the automation.

**Which Sprint Priority is this issue related to?**
Priority 3

**Additional context**
- auto-remediation will happen later and will require higher permissions (danger - can delete!)
- core accounts will be different
- lives in LZ2 live
- this ticket does *not* include implementing an IAM mechanism for cross-account security auditing, which will be ticketed separately once better understood.

**Definition of done**
- each account has a reduced permissions view-only security role
- this is only for the workload accounts
- provisiong "stack" (terrform/terragrunt)  includes creation of a "security reader/audit" role along with Admin, ViewOnly, and Developer
- existing accounts "retrofitted" with new role by executing automation against them.

**Comment by sheaphillips** [comment]
collaborate with @wrnu as needed.

**Comment by sheaphillips** [comment]
We have created a "Security Auditor" role with the AWS-defined/managed SecurityAuditor" policy.  We may refine the policy for the role but we will use this a stating point for now.
