### ISSUE TITLE
Update AWS security to Rocket.Chat integrations with new Rocket.Chat URL 

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#559]
**Describe the issue**
The Platform Services team has/will be migrated Rocket.Chat to a new cluster and it will soon have a new URL as part of the migration (chat.developer.gov.bc.ca).  We have a set of notifications generated by the AWS security stack and these currently are tied to the original Rocket.Chat URL (chat.pathfinder.gov.bc.ca).  We need to update our integrations to use the new URL.

**Which Sprint Priority is this issue related to?**
Priority 3

**Additional context**
Timeframe for migration to the new URL is...?

**Definition of done**
Integrations are visible in channel through the *new* Rocket.Chat URL.

**Comment by sheaphillips** [comment]
@cloudsmart would you mind taking a look at this?

**Comment by cloudsmart** [comment]
- There is a solution called ROCKETCHAT-NOTIFICATIONS (RCN) that deploys all the bits and pieces required for sending security and budget notifications to Rocket Chat. 
- The RCN solution is not under BCGov repositories on GitHub and needs to be added
- RCN was deployed by Ryan J. to LZ1 but hasn't been deployed to LZ2 yet
- RCN uses AWS EventBridge to filter out the events for notifications and there is a Lambda function that sends the notification to destination channels on Rocket Chat based on the event type an severity: Budget, Low, Medium, High, Critical
- We need to setup Web hooks in Rocket Chat and add their URL's to variables.tf file to allow the Lambda function route the notifications properly. Note: Same URL can be used for more than one category of events 
- Once the above steps are complete we can deploy the RCN solution to LZ2

**Comment by cloudsmart** [comment]
New ticket (#629) is created for adding RCN code to a GitHub repository under the BCGov organization, and deploy it to LZ2.
