### ISSUE TITLE
Work with Bahaa to develop approach for collaborating with early adopters to refine our Customer Journey

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#560]
**Describe the issue**
We've drafted our Customer Journey (within our Service Blueprint) using best intelligence from Service Design work, our UX workshops and survey. Now that we have ministry teams working with us in AWS, we have the opportunity to learn the real practicalities of providing a service that enables ministry teams to succeed with public cloud - how best to capture lessons learned as we go, and enhance our Service Blueprint accordingly?

**Which Sprint Priority is this issue related to?**
Priority 1

**Additional context**
Bjorn's Journey (high-level), Service Blueprint (details)

**Definition of done**
- Draft an approach for working with ministry teams through current quarter, that will focus on most efficient capture of lessons learned, leading to enhancements to our Service Blueprint
- Focus on customer journey that people can understand with priority on the business owner perspective (priority 1), secondary perspective (Technical owner)
- Review with product owner and amend if and as required 
- Review with ministry teams' product owners, capture any suggestions/request for changes for discussion with our product owner
- Final tune-ups to the plan, and create tickets for tasks to implement

**Comment by mitovskaol** [comment]
Not relevant anymore
