### ISSUE TITLE
Identify top 5 controls and start implementing in Cloud Custodian

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#568]
**Describe the issue**
There are too many controls for us to respond to manually and we wish to automate a small achievable amount of the most important controls by end of sprint. Creating reusable code/pattern and controls for CP and teams. 

**Which Sprint Priority is this issue related to?**
Priority 3

**Additional context**
Think of this as 'Test Driven Development' exercise that will start out with tests designed to fail and in later iterations, tests will go green. 

**Definition of done**
- Check that Prowler doesn't have these controls already
- Identify 5 top-most important controls to start out with
- Apply the Cloud Custodian control on the appropriate accounts grouping (Teams or Core)
- Review in a meeting with PO, ISB
- Start Implementation with co-operation with Technical Team
- Results from Cloud Custodian first run will be available to team next sprint
- Ability of Ryan to work from his workstation (server-based scheduled runs out of scope for this ticket)

**Comment by bluemel-gov** [comment]
- Working on cloud custodian and controls.
- Recent python library update caused issue, expected to be fixed EOD 02/02

**Comment by bluemel-gov** [comment]
- 5 Controls around identity, access, and monitoring set and tested.

**Comment by bluemel-gov** [comment]
- Updated CIS controls published (v1.30 instead of 1.20)
- Re-opened ticket to review updated configs and tune controls as needed.

**Comment by bluemel-gov** [comment]
- Closed as complete as have working controls and will make a video for the demo
