### ISSUE TITLE
Review in-scope services for usage 

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#569]
**Describe the issue**
In the onboarding presentation, Gary Wong presented some services that haven't been reviewed by Security and Privacy and we need to do a mini-review on them. 

**Which Sprint Priority is this issue related to?**
Priority 1

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Review: PITR, Glacier 
- Determine what storge backup is for s3, glacier and rds
- Modify existing STRA and PIA if needed. 
- Slide in the demo that talks about the approach

**Comment by hromanow** [comment]
It looks like PITR and Glacier would be covered under the Databases and Storage categories respectively in the PIA. I'll stay connected with Ryan for security on these services.

**Comment by hromanow** [comment]
Confirmed data residency with Ryan Jaeger for Glacier and PITR.

**Comment by bluemel-gov** [comment]
- Security Review completed
-- There are configurations and settings that should be enabled for deploying these services.
---- eg. define the policy for access and keys

**Comment by bluemel-gov** [comment]
- wrote checks as cloud custodian controls. 
- Closed ticket as complete.
