### ISSUE TITLE
Narrative on our Business Model Canvas for Public Cloud

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#571]
**Describe the issue**
3 pager to describe to external exec in understandable language of a summary of our service model for a Managed Cloud Service, along the lines of a narrative version of a business model canvas

**Which Sprint Priority is this issue related to?**
Priority 1 

**Additional context**
Business Model Canvas - current understanding, Bjorn's journey, Concept Case, Resourcing Model

**Definition of done**
- 3-page document that describes our proposed service model for a Managed Cloud Service
- Review with PO

**Comment by ActionAnalytics** [comment]
Additional late-in-the-game feedback from exec that I neglected to post earlier.  Exec prefers: https://online.visual-paradigm.com/diagrams/templates/analysis-canvas/business-model/open-business-model-canvas/

Recognizing this is very late can either roll ticket to next sprint or create a new one.

**Comment by bharmouche** [comment]
Awaiting the workshop lead with Martha and I to come up with a map for this document.

**Comment by bharmouche** [comment]
I guess this one will be delayed or paused, as it was supposed to be part of the after math of the Business Module canvas.

**Comment by bharmouche** [comment]
We did the workshop end of Sprint. will study and create a one pager narrative this coming sprint and share with everyone.
