### ISSUE TITLE
SPIKE: Evolve image handling pattern in demo app CI/CD

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#573]
**Describe the issue**
The manner in which the CI/CD associate with the demo app currently handles docker images is inefficient and could result in slow deployment and autoscaling times.  We would like ti explore options to improve this. 

**Which Sprint Priority is this issue related to?**
Priority 2

**Additional context**
- candidate solution is to push from image built in GitHub action to ECR in Sandbox account, with application workload environment runtime pulling from ECR (instead of GHCR or DockerHub as is done now).  This should reduce network overhead and speed up deployment and autoscaling times
- we should benchmark / profile to ensure we  would be getting meaningful speed improvement by implementing this proposal
- cross account ECR replication may also be part of the solution if problems encountered with cross-account pull

**Definition of done**
- Working code/config that pushes to ECR in a sandbox acount for GitHub action
- working code/config that validates that an ECS task within a  workload account in an account set (e.g. dev) can pull an image from ECR in a  sandbox account and launch the task
- working code/config that validates  that on autoscaling event, image can be pulled and launched
- timings/metrics for launch time with and without ECR in the mix (e.g. baseline is ECS pulling from DockerHub or GHCR)

**Comment by sheaphillips** [comment]
We will add a ticket to Sprint 18 to create a service account and role for the purpose of enabling write access to shared ECR // cc: @wrnu

**Comment by wrnu** [comment]
On hold until custom IAM service accounts are implemented. This will allow us to create ecr specific service account credentials that can push to ecr.

**Comment by wrnu** [comment]
Code pushed https://github.com/bcgov/startup-sample-project/
 with support from https://github.com/BCDevOps/terraform-octk-aws-workload-ecr
