### ISSUE TITLE
FAQ review with CP Team

### ISSUE THREAD

**Issue by emilyjones430** [bcgov/cloud-pathfinder#576]
**Describe the issue**
We want to have a session with the team to give everyone an idea of the types of questions we receive from ministries, and the answers that are being provided to them. 

**Which Sprint Priority is this issue related to?**
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Link to FAQs on team wiki 
- Presentation given to team by Emily and Sid

**Comment by sid-gov** [comment]
Sid working on: 
- How many questions came in and from which ministries? 
- Cross-reference the FAQ doc to the questions from the inbox to see if anything's missing
- Look at the deck and add content

**Comment by emilyjones430** [comment]
Sent invite for FAQ review with team on March 17.

**Comment by sid-gov** [comment]
Presentation given. Feedback from team captured.
