### ISSUE TITLE
Change RocketChat-Notification source code to support new usecases

### ISSUE THREAD

**Issue by cloudsmart** [bcgov/cloud-pathfinder#577]
Describe the issue
There is a project called RocketChat-Notification that allows Security Hub findings be sent to various Rocket.Chat channels. 
1) There is a Lambda function written in Python that receives SH events and pushes them to proper rocket.chat channel that we've configured for Critical, High, Medium, Low severity items.
2) There is a Terraform variable that holds Webhooks for the rocket.chat channels per each category (Critical, High, Medium, Low)

We want to send Landing Zone Core accounts findings to different rocket.chat channels than the findings of non-core accounts.

 
Which Sprint Priority is this issue related to?
The 'Milestone' should clearly list Sprint Priorities - which one is this issue related to?

Additional context
- Separation of findings based on Account type (Core vs non-Core) can be done in the Lambda function or Terraform.
- Doing it in Lambda gives us more flexibility but takes longer as requires development and testing.
- Doing it at Terraform level is quicker as we modify the event pattern by adding the account-ids to it. This way Cloudwatch filters our the events belonging to core accounts and won't invoke Lambda. Although this method is faster to implement, it's not flexible as the Lambda function keeps separating the findings based on their severity (as before), although this time for the non-core accounts only.
- Both options require Core Account-ID's which should be parameterized and possibly stored in a secret store.
- The current solution sends only the SH findings originated from GuardDuty, no compliance nor Macie, or others. We should add those to the scope.

Definition of done

Final deployment to LZ2 
WIP documentation of how this is applied to LZ2 in teams
Working solution in LZ2 (stretch goal: through automation)
a draw.io diagram stored in Teams (source included)
Enough text to go into a nice slide
Guardduty, Security Hub turned on and enabled
Private demo to Security team, feedback incorporated
Bonus: A small video demonstration to go into the demo deck

**Comment by lukegonis** [comment]
Closing this issue as it is out of date and a duplicate of other work around Rocket.Chat notifications.
