### ISSUE TITLE
CITZ ADM Procument Options Decision Note 

### ISSUE THREAD

**Issue by emilyjones430** [bcgov/cloud-pathfinder#578]
**Describe the issue**
Develop a note for the ADMs around the procurement options for the MCS pilot. 

**Which Sprint Priority is this issue related to?**
2

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Completed decision note reviewed by Gen and Paul

**Comment by ActionAnalytics** [comment]
Emily: Still unsure of the priority on this one.
@scayzer please confirm if otherwise

We will close this for now and reopen if it's needed later.
