### ISSUE TITLE
Security compliance for additional database offerings

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#581]
**Describe the issue**
It's looking very likely a team onboarding into LZ2 will want to explore ElasticSearch, DocumentDB and Nepture, as database offerings next to DynamoDB and RDS.

**Which Sprint Priority is this issue related to?**
Priority 1

**Additional context**
- In this context, ElasticSearch database is offered and managed by AWS.  Elastic the company is 100% not involved, nor are any other outside parties.  
- Logstash and Kibana in this potential usage would exist in/connected to ECS managed by the team
- NRM Observability Metrics team request is likely (currently they are deciding by price)

**Definition of done**
- Review security compliance around Elastic (ElasticSearch, Logstash, Kibana), DocumentDB and Neptune
- Clecio V available for details
- Update the SOAR/STRA
- Update with PO if substantially different that RDS/Dynamo

**Comment by ActionAnalytics** [comment]
Just snuck in DocumentDB from another team request.  Will discuss in a few minutes - hopefully it shouldn't change scope too much but if needed can break out to another ticket

**Comment by bluemel-gov** [comment]
- updated estimate from 3-5 due to scope changes.

**Comment by bluemel-gov** [comment]
- Some configurations and settings would be needed for service offerings
-- eg elasticsearch ((cluster,  index, document, field level))
- Documented recommendations for PO review

**Comment by bluemel-gov** [comment]
- controls in #648
- Closed ticket as complete
