### ISSUE TITLE
Additional privacy compliance for additional database elastic search

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#583]
**Describe the issue**
It's looking very likely a team onboarding into LZ2 will want to explore ElasticSearch, DocumentDB and Nepture, as additional offerings next to DynamoDB and RDS.

**Which Sprint Priority is this issue related to?**
Priority 1

**Additional context**
- In this context, ElasticSearch database is offered and managed by AWS.  Elastic the company is 100% not involved, nor are any other outside parties.  
- Logstash and Kibana in this potential usage would exist in/connected to ECS managed by the application team
- NRM Observability Metrics team requests that they are most likely looking at these databases

![What the heck is Elastic Search.png](https://images.zenhubusercontent.com/5e98c26e92d4be32d8e29cb0/1ff337bd-1bc7-450c-9974-f610ad8ca98a)

**Definition of done**
- Review privacy compliance around Elastic (ElasticSearch, Logstash, Kibana), DocumentDB and Neptune databases
- Update the PIA
- Update with PO if substantially different that RDS/Dynamo

**Comment by ActionAnalytics** [comment]
Might not need to crack open the PIA due to future flexible service category approach

**Comment by hromanow** [comment]
Documented these services in an Excel sheet. The corporate PIA service categories cover them and the Canadian region was confirmed for all of the services in this ticket.
