### ISSUE TITLE
Evolve Demo App to demonstrate additional patterns

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#593]
**Describe the issue**
With ticket bcgov/cloud-pathfinder#523 completed we now have the ability to create extra workspaces, for each environment, in addition to the default workpaces. By moving the sample app to an application specific workspace we can demonstrate using the default workspace for common infrastructure that is independent of the sample application

**Which Sprint Priority is this issue related to?**
Goal 2
> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
the purpose of this to demonstrate the additional terraform workspaces. 

**Definition of done**
- Sample app deployed using the `tnfhhm-ENV-startup-sample-project` workspaces
- Infracture repo deployed and CI/CD that deploys everything except ec service

**Comment by mitovskaol** [comment]
Not relevant anymore
