### ISSUE TITLE
Decide on a Survey Tool

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#595]
**Describe the issue**
The Cloud Pathfinder team needs to conduct online surveys in a modern, secure and compliant manner.  It may prove useful for onboarding request forms too.  This ticket is scoped only to picking a favourite and seeing if any one else has run compliance on it.

We are looking at several options and at the end of this ticket we would like to have a selection to drive at.

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
- Jenny's team has already done an application level PIA for Airtable
- The Exchange Lab did an overarching Program-Level PIA for the whole team including a listing of the tools or the types of the tools used
- Airtable (tailormade, reuse from other teams), SurveyMonkey (legal concerns?), Lime Survey, Miro, Mural, Simple Survey, SharePoint Survey, SurveyGizmo, CheckboxSurvey, Wordpress/Drupal/CMS Survey, Federal Algorithmic Assessment in GitHub.
- PO has an existing Lime Survey instance that has already gone through compliance, which is an option
- Consider SaaS sprawl - so don't do a new PIA/STRA/SOAR
- Selection Criteria (what the tool needs to do):
- - good easy visualizations of results
- - multiple ways of addressing Qs that can be open-ended or not (easy UI for both admins and participants)
- - simple data exports
- - compliant with Cloud Security Schedule if SaaS
- - easy to turn on or hide survey
- - stable predictable UI
- most teams don't have a privacy and security person actually on the team, and thus this team has less need to talk to an external MPO

**Definition of done**
- confirm a narrow as possible scope for the nature of the surveys Cloud Pathfinder intends to perform (current assumption is surveys to prospective tenants, and surveys to existing tenants)
- Exec preference is for Program Level PIA, pulling in (or reusing) existing PIAs/STRAs/SOARs and not creating new ones.
- If SaaS, terms agreed to (and owner of agreement identified)
- Data Classification done
- Product selected, any other related tickets defined and ready to go.

**Comment by ActionAnalytics** [comment]
Exec has indicated that in order to control SaaS sprawl, we are to use existing tools instead.  Please connect to me for details if needed. @emilyjones430 @bharmouche @hromanow @bluemel-gov  Sorry for the confusion and thanks in advance!

**Comment by ActionAnalytics** [comment]
It may be that there already is a PIA/STRA for Airtable, and if so then we can consume it.  But the goal we want is to focus effort on the program level PIA in ticket 669 (see related).  I'll book us a meeting to sort this out.

**Comment by ActionAnalytics** [comment]
Let's focus the scope down to Surveys only at the moment.

**Comment by bluemel-gov** [comment]
- From conversation last week, Security is reviewing completed risk assessments and what dev-exchange  has done (platform wide) to see what can be re-leveraged.

**Comment by bluemel-gov** [comment]
@bharmouche You mentioned last week to have me review what had been completed from security/completed work. That will take a bit of time, and will break my capacity this sprint but happy to review and check compliance for one or more tools that you find. Thanks

**Comment by ActionAnalytics** [comment]
Simple Survey has existing compliance in the form of PIA/STRA
There was also a demo of Team Surveys for which a PIA/STRA is in the works, about a month off to turn on features per Stu

Most of the other options did not pass compliance and we will revisit this ticket to make sure the team all has a chance to input

**Comment by ActionAnalytics** [comment]
Taking too long, PO decision on Airtable

**Comment by ActionAnalytics** [comment]
We're not focusing on Airtable (that's replaceable) we're focusing a Program PIA on the activity of conducting surveys.
