### ISSUE TITLE
Integrate Vault into account provisioning automation

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#600]
**Describe the issue**
Vault could be used to improve the security and improve usability (multi-team member access) of provisioning processes.

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
Assumes that this fits nicely with the usecase of platform services team

**Definition of done**
- Account provisioning-related secrets stored in Vault and pulled from there at runtime.
- Onboarding tech team members into vault

**Comment by sheaphillips** [comment]
Platform Services Vault deployment is not accepting users yet, but we may have an opportunity to be early users based on discussions with Platform Services team.

**Comment by mitovskaol** [comment]
Not relevant anymore
