### ISSUE TITLE
Create automated map report of accounts vs owners for supporting manual bill creation

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#609]
**Describe the issue**
Currently we have a manual spreadsheet (talk to PO for sample) and rather than maintaining a manual artifact, we wish to have a canned report or query we can run monthly and provide to Stuart showing the Team Tenant accounts.

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
- get manual spreadsheet (talk to PO for sample)

**Definition of done**
- the query or canned report should be fairly easy to access by PO so that it can be run and provided to Billing for the (currently) manual reconciliation that will feed the into the JV billing to each team
- the fields should be as close as possible to the sample spreadsheet
- invent the concept of billing group in the metadata

**Comment by sheaphillips** [comment]
@cloudsmart please spend a small amount of time investigating whether there is an automatable mechanism to extract a consolidated bill in csv or other machine-readable format so that we could insert the "owner" metadata automatically.

**Comment by cloudsmart** [comment]
**Analysis**

- AWS API "ListAccounts" retrieves list of all accounts in an Organization. 
- The output is a JSON document similar to this:
{
   "Accounts": [ 
      { 
         "Arn": "string",
         "Email": "string",
         "Id": "string",
         "JoinedMethod": "string",
         "JoinedTimestamp": number,
         "Name": "string",
         "Status": "string"
      }
   ],
   "NextToken": "string"
}

- Only the account "Id" and "Name" attributes match the content in Julian's spreadsheet (columns E and F).   
- Following columns in the spreadsheet do not have any corresponding attribute in AWS Organization/Account:
  > Owner
  > Ministry
  > Team Name
  > Project-set License Plate (can be retrieved from account name)
  > Account Meta Project
  > Notes

- AWS Organization provides another API called "ListTagsForResource" that returns the tags for a given Account

**Solution**

1. Add the missing attributes to each account as tags. This can be done manually for the existing accounts and also baked into the account creation automation (Account Vending Machine) for new accounts
2. Write a Python program that:
  - Retrieves the list of all accounts using ListAccount API and stores it in an array
  - Iterate through the list of accounts and retrieves the Tags for each account using ListTagsForResource
  - Outputs the list of accounts combined with their tags as a csv file

**Comment by sheaphillips** [comment]
This can be done in terraform. Let’s discuss tomorrow.

**Comment by sheaphillips** [comment]
The terraform module at https://github.com/BCDevOps/terraform-aws-sea-organization-info partially does what is needed for this ticket.

Basic steps:

- clone the module from GitHub
- grab suitable temporary AWS credentials and paste into shell
- from the module checkout directory, run the following  
```terraform output -json workload_accounts  | jq -r '(map(keys) | add | unique) as $cols | map(. as $row | $cols | map($row[.])) as $rows | $cols, $rows[] | @csv' > accounts_info.csv```

The command above will create an CSV output with a column for each account attribute, and a row for each account.  Tags will not be shown in the CSV as the Terraform resource does not expose them.  We will need follow on work (as a subsequent ticket)  to pull in account metadata.

@cloudsmart Please verify steps above and document in wiki or other suitable location accessible to team.

**Comment by sheaphillips** [comment]
For reference the `jq` code was adapted from here: https://stackoverflow.com/questions/32960857/how-to-convert-arbitrary-simple-json-to-csv-using-jq

**Comment by cloudsmart** [comment]
@sheaphillips I followed the instructions above but the csv file is empty! When I run the "terraform output -json workload_accounts" command it returns all workload_accounts so it appears to be the `jq` code not able to parse the list of accounts properly.

**Comment by cloudsmart** [comment]
The command works correctly but requires `jq` to be installed first. Documentation is created and uploaded to CPF Teams repository. 
Following is summary for record:

**Prerequisites**
- Terraform v. 0.14 or higher (brew install terraform)
- Jq 1.6 (brew install jq)

**Execution Steps**
- Clone the module from GitHub (https://github.com/BCDevOps/terraform-aws-sea-organization-info)
- Obtain suitable temporary AWS credentials for AWS master account through LZ2 login page and paste into shell
- From the module checkout directory, run the following:
- `terraform init`
- `terraform plan`
- `terraform apply`
- `terraform output -json workload_accounts | jq -r '(map(keys) | add | unique) as $cols | map(. as $row | $cols | map($row[.])) as $rows | $cols, $rows[] | @csv' > accounts_info.csv`
