### ISSUE TITLE
Cross Account Workload integration through private API endpoints 

### ISSUE THREAD

**Issue by cloudsmart** [bcgov/cloud-pathfinder#612]
**Describe the issue**
In AWS LZ2 we create separate AWS Accounts to host different workloads. This is to provide isolation from various point of views such as security, cost management, etc.
The workloads are expected to use API's for integrating with other workloads, however some workloads may not expose their API's publicly or even so it may not be necessary to use public endpoint to integrate with a workload hosted on different account on AWS.
We need a mechanism to allow workloads integrate through API with other workloads across different AWS Accounts in LZ2.     

**Which Sprint Priority is this issue related to?**
Goal 2
> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
- AWS LZ2 provides a Central  Account which can be used for this along with API Gateway
- optimization that will reduce costs
- In the future would enable accessing API in BC gov on-prem
- Requires additional applications to implement
- Good to do this in advance of and in collaboration with the NRM team

**Definition of done**
- Workloads hosted on different AWS Accounts in LZ2 can integrate through API using privately addressable endpoints.
- Publish private APIs for use of inter-application communication in/across ministries
- Collaborate with Jonathan Brummel around possible automation to DataBC list of APIs

**Comment by sheaphillips** [comment]
This will be useful but don't have any teams with a specific need for this functionality.  We will push to a future sprint and re-prioritize based on demand, etc.

**Comment by mitovskaol** [comment]
Not relevant anymore
