### ISSUE TITLE
Research how to duplicate zenhub tickets quickly during refinement

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#613]
**Describe the issue**
Being able duplicate tickets (especially support ops bucket tickets would save time for our refinements.

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- find and share way to do this with team by next sprint if possible

**Comment by sid-gov** [comment]
No data available on duplicating tickets. Looked at creating new issue templates instead: 
[Link](https://help.zenhub.com/support/solutions/articles/43000074624-create-multiple-new-issue-templates-in-a-workspace#:~:text=Creating%20templates%20in%20a%20repo&text=GitHub%20Issue%20Templates%20live%20in,Request%2C%20and%20a%20custom%20template.)
