### ISSUE TITLE
GitOps for bcgov-c/aws-lz2-workspaces-live

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#614]
**Describe the issue**
`bcgov-c/aws-lz2-workspaces-live` is deployed from a developer's workstation using terragrunt. We want a GitOps workflow to prevent issues like terraform/terragrunt versioning, deploying incorrect git commit/branch, etc. 

**Which Sprint Priority is this issue related to?**
Goal 2
> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Discussion with Shea to further refine the ticket
- `bcgov-c/as-lz2-workspaces-live` is deployed using a GitHub Action
- Action runs in AWS not on GitHub's infrastructure

**Comment by mitovskaol** [comment]
This ticket has been completed!!!
