### ISSUE TITLE
Plan Security CoP topics

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#617]
**Describe the issue**
Nick from Platform Services frequently presents at the Security Community of Practice.  Now that we are operational, we have material to share and wish to build connective tissue across gov.

**Which Sprint Priority is this issue related to?**

**Additional context**
- It could be possible that Ryan is already doing this, we wish to confirm and expand if so

**Definition of done**
- Connect with Nick from Platform Services to find what has worked best and what the community likes/dislikes in a presentation
- Prepare a small deck of material to share with the Security CoP from the available material we already have
- Find next date for Security CoP, make time for Ryan to attend
- Present at next Security CoP
- Report back to the CP team how it went

**Comment by bluemel-gov** [comment]
- booked meeting on 02/10

**Comment by bluemel-gov** [comment]
- rebooked to 17th, as was out of office on 10th.

**Comment by bluemel-gov** [comment]
- Met with Nick on 18th
- Planned to meet with Security Community today.

**Comment by bluemel-gov** [comment]
- Presented to community
- collected and questions and slides in internal repo
- Posted to team with link (on how it went)
- Closed ticket as complete.
