### ISSUE TITLE
SPIKE: Gain clear understanding of Cloud Pathfinder service

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#619]
**Describe the issue**
An understanding of Cloud Pathfinder portfolio of products/services would help our team focus and our stakeholder relationships to clarify what are our products.  This is descriptive at a higher level (compute & storage in AWS), rather than the fine grained tiles in the login page.

**Which Sprint Priority is this issue related to?**

**Additional context**
- Align this work with OKRs
- Idea inputs include an example excel spreadsheet done by platform services team (Stu has)
- This will be helpful to inform the business case
- This work may produce something like this for posting on DevHub: https://developer.gov.bc.ca/BC-Government-OpenShift-Container-Platform-Service-Definition (if not, suggest we create another ticket to develop a CPF version of this DevHub page)

**Definition of done**
- The deliverable is a document that is based on some public and private cloud services in OKR 6
- Publish to DevHub with Shea's help, Prabhu to do it (he will be taking on learning debt do it). 
- PO, Stu, Bahaa to review prior work by ES and Platform services in order to identify the most reusable pieces

**Comment by ActionAnalytics** [comment]
Alluvial work and platform services items are feeding into this

**Comment by scayzer** [comment]
Completed as per additional context: This work may produce something like this for posting on DevHub: https://developer.gov.bc.ca/BC-Government-OpenShift-Container-Platform-Service-Definition (if not, suggest we create another ticket to develop a CPF version of this DevHub page)

... but not as per definition of done:
Excel spreadsheet format similar to Justin & Olena's (eg. AWS SEA, GCP SEA)

**Comment by scayzer** [comment]
New ticket #942 opened for publishing this on DevHub, and #
