### ISSUE TITLE
Establish a presence in DevHub linking to our source of truth Secure Cloud website

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#620]
Describe the issue
We wish to establish a presence in DevHub because many members of the developer community go there as a starting place for information.
Initially, we want a "Cloud Pathfinder" page and navigational "tile" within an existing "Topic" that has our logo, about us, and links to all our public information (the spot formerly known as "Secure Cloud").

Sprint Priority
- Goal 1

Additional context
- Patrick S. owns DevHub but talk to Shea or Julian for help with the GitHub part of this work
- Emily has provided the [Secure Cloud website](https://www2.gov.bc.ca/gov/content/governments/services-for-government/cloud-computing-in-the-bc-government?keyword=cloud)
- There is also the following page, with "Cloud Services" in the title, that cites ServiceNow (SaaS version) as the only cloud service:
[Data Centre, Managed Hosting and Cloud Services](https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/data-centre-managed-hosting-and-cloud-services)

- A detailed description of how to contribute content to the DevHub is [here](https://github.com/bcgov/devhub-app-web/blob/master/docs/registry.md) but the relevant elements for this ticket can be distilled down as follows:

[] Create a markdown file called "README.md" in Cloud Pathfinder GitHub repo [here](https://github.com/bcgov/cloud-pathfinder/devhub-content) 
[] Populate the file with content specified in Definition of Done, adding headers, etc.
[] Apply metdata ("frontmatter") to top of file similar to:

```
---
description: BC Gov Compliant Public Cloud.
title: Cloud Pathfinder
image: "https://raw.githubusercontent.com/bcgov/cloud-pathfinder/master/logos/cloud%20pathfinder%20team%20logo%20-%20logo%20only.png"
author: scayzer stuart.cayzer@gov.bc.ca
---
```

[] Create a pull request against the DevHub GitHub repo [here](https://github.com/bcgov/devhub-app-web) containing an additional "source" element in the JSON file [here](https://github.com/bcgov/devhub-app-web/blob/master/web/topicRegistry/developer-tools.json) which is the topic definition for the "Developer Tools" topic.  The source should look similar to:

```
...
  {
        "sourceType": "github",
        "sourceProperties": {
          "url": "https://github.com/bcgov/cloud-pathfinder",
          "owner": "bcgov",
          "repo": "cloud-pathfinder",
          "files": [
            "devhub-content/README.md"
          ]
        }
      }
...

Definition of done
- A new Tile titled "Cloud Pathfinder" (see description above for details) is added to the existing "Developer Tools" topic.
- The Tile includes the cloud Pathfinder team logo
- The Tile description is "BC Gov Compliant Public Cloud"
- The page in DevHub that the tile links to contains the following text: "BC Gov Cloud Pathfinder is offering compliant Compute and Storage in various Cloud Service Provider clouds for Ministry Application Developer Teams.  Here are the links to details:" With a list of official public websites containing detailed Cloud Pathfinder info see Secure Cloud website above.  This text content and list of websites will be in a markdown file in one our github.com/bcgov/cloud-pathfinder repo in a subfolder called "[devhub-content](https://github.com/bcgov/cloud-pathfinder/tree/master/devhub-content)"

**Comment by sheaphillips** [comment]
@scayzer @ActionAnalytics DoD isn't clear and it may be hard to action this ticket.  I am happy to help capture things more "step-by-step".

**Comment by scayzer** [comment]
Update: met with Bahram to discuss, followed up with a request to Jason and Patrick on RocketChat. Patrick suggested we "author a markdown file in your repository with all your relevant content. Then you can annotate the markdown with some metadata including the logo, summary, tags etc" - Bahram now following up with Patrick for more info and getting this done. I've also asked that Bahram connect with you @sheaphillips

**Comment by sheaphillips** [comment]
Okay.  I'd prefer that we try to minimize leaning on Patrick as they have
designed their process to be mostly self-serve and I am fairly familiar
with them.

**Comment by cloudsmart** [comment]
That's great, thanks @sheaphillips! Let's connect and see what needs to be done for this.

**Comment by cloudsmart** [comment]
I followed Shea's instructions and:
- Created a README.md file in  https://github.com/bcgov/cloud-pathfinder/devhub-content
- Forked The Devhub repository and added the json code block to Developer Tools topic in my forked repo.
- Submitted a PR to DevHub team to merge it into their repo.

**Comment by cloudsmart** [comment]
Cloud Pathfinder Team tile is added to DevHub according to the DoD.
https://developer.gov.bc.ca/Developer-Tools/Cloud-Pathfinder
