### ISSUE TITLE
Review Terraform Cloud team member access.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#630]
**Describe the issue**
We have evolved the way we use Terraform Cloud since we started and likely have redundant users and/or workspaces.  We should review the workspaces and memberships to adjust as necessary.  This may involve confirming their usage/lack of usage with external individuals.

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
TFC Memberships and workspaces reflect current users of tool.

**Comment by mitovskaol** [comment]
Completed. Team access has been reviewed.
