### ISSUE TITLE
SPIKE: Check if Startup Sample Project is aligned with LZ2 built-in Security Groups

### ISSUE THREAD

**Issue by cloudsmart** [bcgov/cloud-pathfinder#632]
**Describe the issue**
The Startup Sample Project was created prior to adopting GoC SEA Landing Zone (LZ2) and thus has Security Groups in it which may be redundant and not fully align with the LZ2 built-in security groups:
- sample-load-balancer-security-group
- sample-ecs-tasks-security-group
- sample-endpoints-security-group

**Which Sprint Priority is this issue related to?**
Goal no. 2

**Additional context**
- LZ2 leverages Shared VPC across the team accounts with predefined subnets, NACL's, and Security Groups
- RCN code has already been refactored to align with LZ2 networking (VPC and Subnet) 
- recent app changes may have solved some of this

**Definition of done**
Startup Sample App uses LZ2 built-in Security Groups:
- Web_sg
- App_sg
- Data_sg

**Comment by wrnu** [comment]
- The LZ sgs are directly attached to their associated subnets
- The sample app uses the default alb that is created for the env as part of the account setup, this is in the web subnet/sg
- ecs is created in the app subnet and has a custom sg that allows traffic from the web sg on the specific port used. This is stronger than the default sgs attached to the web and app subnets
