### ISSUE TITLE
(3 hr Deck) Distill Bjorn’s journey to core message for App Team Leadership

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#633]
**Describe the issue**
Due to feedback about the length and material in the 3hr onboarding session deck, downplaying mention of the details of Bjorn’s journey to the core essentials for product owners would reduce the length (it’s just another piece of Service Design work that has informed our design of our MVP service)

**Which Sprint Priority is this issue related to?**
Goal 1
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Book review with PO as most of this is done and only review feedback cycle remains
- Reduce the journey slides from 13 to a smaller amount
- Have Service Design go over the Bjorn slides looking at them from the App Team Leadership Market Segment's point of view
- Service Design review Bjorn slides for opportunities to replace text with graphics if/wherever possible

**Comment by scayzer** [comment]
2021-02-09: reduced to 7 slides - will ask Bahaa to see if he can make further improvements. May work to convert slides 17-60 into a journey timeline like the ones on developer.gov.bc.ca ?

**Comment by scayzer** [comment]
2021-02-11 Bahaa developed a 1-slide version of slides 17-20. Looks good - Julian to review.

**Comment by sid-gov** [comment]
Book 30 min meeting with Julian to close this.

**Comment by scayzer** [comment]
Done - Stu, Bahaa and Julian met 2021-04-06 and agreed on a couple more enhancements to the slides. Bahaa completing the work.
