### ISSUE TITLE
(3hr deck) Clarify elements of training schedule via Journey Model

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#636]
**Describe the issue**
The training roadmap is not clear to onboarding teams. We wish to provide an easy to understand visual model for teams to understand.

**Which Sprint Priority is this issue related to?**
Goal 1 

> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
- See DevHub's Journeys https://developer.gov.bc.ca/journeys
- If we reuse what's used in DevHub then we get the diagram for free but it's additional work

**Definition of done**
- all onboarding and training captured in a list that is then used to create
- a visual Journey Map (see addnl contxt)
- connect with Digital Academy, show AWS connected pieces, ask if they wish to own now or later
- 1 day max work
- Demo Review with Bahaa, Stu and fix any changes

**Comment by bharmouche** [comment]
awaiting Julian's availability to do it
