### ISSUE TITLE
Meeting with GoC about Azure Guardrails

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#644]
**Describe the issue**
We wish to understand the coverage of the GoC guardrails to custom work done on existing Azure space

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- schedule meeting with GoC and get detailed understanding
- include PO possibly Exec
- feature comparison table between the 2 solutions

**Comment by scayzer** [comment]
Meeting scheduled for 2021-03-23 - should also be able to address the question of additional tools and services in this meeting (ticket #
