### ISSUE TITLE
Make sure that the security role can see the team groups used by RBAC

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#645]
**Describe the issue**
We wish to have security automation coverage over the RBAC connected policies that are assigned when RBAC users are provisioned to SEA items.

**Which Sprint Priority is this issue related to?**
Goal 2 

> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
- KeyCloak is the current RBAC mechanism
- An IDIR or GitHub user attempts a login at KeyCloak and fails (but loads the user meta into KeyCloaks records)
- A Cloud Pathfinder Team member (future automation) connect that user meta link with the team accounts that have been created with automation

**Definition of done**
- Meet with Ryan B and confirm his CloudCustodian security role access cannot list the team groups (confirm the issue)
- Make sure security role can see the groups (eg. yrt234ty-developer -> yrt234ty-dev) (fix the issue)

**Comment by ActionAnalytics** [comment]
Place this ticket top priority for the tech team so that Ryan is not blocked at start of sprint

**Comment by sheaphillips** [comment]
unclear on exactly what is needed for this ticket, but will get clarity from Ryan B

**Comment by bluemel-gov** [comment]
@sheaphillips Appreciate the clarification today. Is there any current mechanism outside of keycloak to see the groups being assigned?

**Comment by sheaphillips** [comment]
@bluemel-gov for tenant team users and workload accounts, the only way users are assigned to groups is within KeyCloak.  This is currently done manually by our team on behalf of tenants  but eventually we hope to delegate to teams to self-serve.  It may also be relevant to note that in this context "group" is a KeyCloak group which has no relation to an AWS IAM Group, which your controls are likely referencing.
