### ISSUE TITLE
Get security work into github and develop daily pattern

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#646]
**Describe the issue**
We need to get a pattern going from the start of getting daily changes in GitHub

**Which Sprint Priority is this issue related to?**
Goal 2 

> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Daily changes the CloudCustodian work are in GitHub at the end of every day on which the tests are worked on
- There are items to demo (not necessarily finished but in progress is fine) at demo dry-run time every sprint

**Comment by bluemel-gov** [comment]
- no work done on 02/09 due to conflicting priorities, so no commits made.

**Comment by bluemel-gov** [comment]
- set ongoing reminders and have a daily pattern made.
- closed ticket as complete
