### ISSUE TITLE
Gather Identity Community, create meeting, explain what we're doing ask for input

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#647]
**Describe the issue**
This will be the exact same approach as the SecOps SIEM group

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
- Consider having JP do this

**Definition of done**
- Facilitate a meeting with the Identity Community, use a matrix to capture each member's characteristics focusing on unique traits
- Drive down to what they can provide for Cloud Pathfinder, and what kind of role they see themselves
- Focus on working together and community

**Comment by sid-gov** [comment]
Rumon, Gen and JP taking a lead on this.
