### ISSUE TITLE
Compliance on chosen Survey/CRM/dashboarding

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#649]
**Describe the issue**
Cloud Pathfinder is looking to conduct surveys, a program-level PIA is preferred.  A **program-level PIA** would be more general and would involve PCT reviewing the types on questions and would allow Cloud Pathfinder to just use tools that already have PIAs/STRAs/SOARs done.  The challenge is that the existing PIAs may have been scoped just for a particular project. 

The team has a ticket to decide on a survey common tool.  We wish to make sure we are clear and safe to use it.

**Which Sprint Priority is this issue related to?**
Goal 2 

> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
- Decision was made to use Airtable (not exclusive though Stu)

**Definition of done**
- Aiming for Program Level PIA that focuses on the activity of the Cloud Pathfinder team conducting surveys etc, not on the particular tool
- Privacy to lead, pull Security if needed

**Comment by sid-gov** [comment]
@bluemel-gov - Added to this ticket if work on this is required.

**Comment by bluemel-gov** [comment]
- Reviewing PIA today/tomorrow from security perspective

**Comment by bluemel-gov** [comment]
- Reviewed PIA from security and provided updates.

**Comment by hromanow** [comment]
Incorporated Ryan's feedback. 
Sent to Stu and Bahaa to confirm content matches with their needs.

**Comment by hromanow** [comment]
PIA submitted to PCT Intake for review. Number assigned: CITZ21028.

**Comment by hromanow** [comment]
PIA sent to Gen for signature.
