### ISSUE TITLE
Provide finer-grained (per-developer/per-deployment//dynamic) terraform cloud workspaces/access.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#653]
**Describe the issue**
Currently, we provide terraform workspaces on a per-environment and per-"service" basis/matrix.  Based on feedback from our initial tenants, we need to be considering how to provide finer grained/dynamic workspaces that would better support rapid-iteration, agile development practices. 

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
This could eventually be integrated into the command line tool suite being developed by NRM

**Definition of done**
A working mechanism for technical tenant team members (developers) to provision/access on-demand Terraform Cloud workspace(s)

**Comment by wrnu** [comment]
No longer relevant
