### ISSUE TITLE
Create permanent wildcards for training accounts for Immersion Days

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#654]
**Describe the issue**
Ryan J will be running an immersion day training in the SEA.  We wish to provision 20 accounts with permanent entries in the firewall.

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonomously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
Add any other context, attachments or screenshots
Exploration of implications of the corporate encryption standard (https://www2.gov.bc.ca/assets/gov/government/services-for-government-and-broader-public-sector/information-technology-services/standards-files/cryptographic_standards_v17.pdf) and related potential need for exemption  is out of scope for this ticket.  
Anything related to risk register is out of scope for this ticket as well.
Separate tickets will be created to capture above items as/when appropriate.

**Definition of done**
- coordinate with Ryan J so that he has everything he needs to conduct an immersion day this sprint
- something along the lines of training.cloudpathfinder.gov.bc.ca
- wildcard cert route 53 in perimeter acct 
- dns entry for each demo account demo acct 1, demo acct 2, ...

**Comment by sid-gov** [comment]
Consider the following for any exemptions that need to be made: 
https://www2.gov.bc.ca/assets/gov/government/services-for-government-and-broader-public-sector/information-technology-services/standards-files/cryptographic_standards_v17.pdf

**Comment by sheaphillips** [comment]
Closing as this was not needed for Immersion Day, and implementing this would increase cost of lab accounts due to associated creation of "default" ALB.
