### ISSUE TITLE
Create solution to teams' feedback about Demos

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#659]
**Describe the issue**
Some discussion between the PO and SM has happened around what to do to improve the utility of demos for the team.

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
- Consider proposal to add ceremony demo time for the team only
- Less roadmapping activities in the demo

**Definition of done**
- make a draft on how to address team feedback
- review draft with PO
- communicate back to team, experiment

**Comment by sid-gov** [comment]
To be discussed more after the Product discovery sessions focusing on identifying our users and the product.
