### ISSUE TITLE
SPIKE: Mechanism for adding SCPs in addition to those that are included with SEA

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#660]
**Describe the issue**

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by lukegonis** [comment]
Closing this issue as the mechanism portion is already determined. Deciding which SCPs will be the next relevant issue
