### ISSUE TITLE
Adjust role mapping so "maximum" access level corresponds to "PowerUser" vs "AdminAccess" policy

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#661]
**Describe the issue**
We want to prevent users from breaking their own teams' IAM setup and we therefore want to reduce the access provided by "Admin" role to correspond to "PowerUser" poilcy.

**Which Sprint Priority is this issue related to?**
Goal 2

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Identify what will need to happen/be delivered for this to be completely done

**Comment by wrnu** [comment]
We have determined that this is not a good approach.
