### ISSUE TITLE
Grant read access to our AWS environments for Shared Services Canada so they can monitor consumption

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#664]
**Describe the issue**
We've moved our AWS account, along with LZ2, LZ1 under the Cloud Brokering Service. Need to grant read access to Shared Services Canada so that they can monitor consumption to calculate the 10% Brokering Service fee.

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
- SSC has sent us a document with instructions on what is required;  
- we will omit the steps in the doc referenced abot related to AWS Private Marketplace

- LZ1 remains to be done.

**Definition of done**
- Technical steps from SSC-provided document to grant access to GoC for both :

[LZ1] (done as captured in comments; GoC seems to have confirmed via email to @scayzer that they have access)
[x]LZ2 

- Stu to notify SSC/Cloud Brokerage via email that access is enabled

**Comment by sheaphillips** [comment]
Steps completed per provided document, with exceptions below:

-  Step 15 "Enable remote billing access", which requires an access I don't have. The setting described may already be complete, but perhaps GoC staff can attempt their data extract and determine whether they can do what they need, or we can have @ActionAnalytics verify/apply the settings
- Policy list exclude those policies related to privat marketplace as we are not currently using that feature.

@scayzer over to you now!

**Comment by sid-gov** [comment]
Julian: Pls shoot them a note due to other priorities this will be done in few weeks and check their response.
