### ISSUE TITLE
Following login via AWS Login default region is not set to Canada (ca-central-1)

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#666]
**Describe the issue**
Currently, when users log in to the AWS web console via our landing zone via the aws-login custom login page, they may find themselves in an AWS region other than "ca-central".  We want them to be in that region by default so they avoid confusing UI error messages they might see when navigating around due to disallowed access non-Canada region.

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- aws-login app updated to ensure users have default region set to Canada following login
- updated app deployed
- functionality tested - set region manually to non-Canada region, log out, log back in and confirm region set to ca-central-1

**Comment by wrnu** [comment]
Deployed and tested in LZ1

**Comment by wrnu** [comment]
LZ2 deployment is blocked until I speak with @sheaphillips
