### ISSUE TITLE
Assemble personas for all users of our public cloud services

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#670]
**Describe the issue**
We have several personas that were created during the 2019 Cloud Service Design work, led by Jenny Romero.

Need to establish any additional personas that we need in support of our design of an Accelerated Public Cloud App Service for compute and storage, as well as our work on SaaS.

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
Our library of personas will build on those created in the 2019 Cloud Service Design work.

**Definition of done**
- import 2019 personas, and refer to UX research and onboarding work so far to determine which additional personas we need
- Import Bahaa's previous templates
- Import Mines core persona work
- create additional personas (with additional interviews if needed)
- review with product owner

**Comment by bharmouche** [comment]
the developer person is done on a pager powerpoint deck on our team channel. it is the first draft to be refined.
