### ISSUE TITLE
Fix the account limitation in the AWS dev access page

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#671]
**Describe the issue**
When accessing the SEA BC Gov AWS page as a developer, especially one on the Cloud Pathfinder team where we have access to lots of accounts, the page only shows a limited number of accounts.  This is problematic because some of the core accounts we need to access, or particular accounts for a demo, are hidden out of the list.

**Which Sprint Priority is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' overview/description (created in ZenHub) should clearly list Sprint Priorities/Goals. This section should indicate which of the priorities/goals this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- unlimit the # of accounts displayed on the SSO page
- if and only if the implementation is going to get fancy and use a paged list widget, then pls consider one with client side sorting that can sort off the meta field rather than the AWS account id, as the meta is meaningful, whereas the account id is meaningless. This is a nice to have, not a key requirement.

**Comment by ActionAnalytics** [comment]
Prioritize low due to existing workaround and only internal team-members are affected

**Comment by mitovskaol** [comment]
Re-architecture of the AWS Login app is required in order to accomplish this.  This work will tracked in other tickets.
