### ISSUE TITLE
Add Cloud Pathfinder email to LZ1 for AWS Invoices

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#672]
**Describe the issue**
AWS monthly invoices need to be sent to the CP shared mailbox for Sid to do create and maintain JV data for Ministry teams.  Applies to LZ1 since it is now in the brokerage.

**Which Sprint Priority is this issue related to?**

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Email is added to LZ1

**Comment by ActionAnalytics** [comment]
LZ2 confirmed, will need to do LZ1 and LZ0 when each enters the brokerage

**Comment by sid-gov** [comment]
This is complete.
