### ISSUE TITLE
Address loose ends on LZ0 and LZ1 

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#676]
**Describe the issue**
AWS accounts set up prior to Cloud Pathfinder work were not procured in a compliant manner and are being paid for by purchase cards.

Need to bring them under the Cloud Brokering Service (CBS), with supporting contract and purchase order, enabling standard invoice accounting and payment.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
LZ1 is ready to be brought under CBS.
LZ0 still has workloads that are near end-of-life - will need to get these shut down before bringing to CBS

**Definition of done**
Create a Service Order in CBS to bring in LZ0

**Comment by scayzer** [comment]
2021-03-03 Service order entered into CBS system: 0000316 ... now awaiting generated email that will provide an SO form for details and signatures

**Comment by ActionAnalytics** [comment]
We're still blocked on LZ0 but LZ1 is going well
