### ISSUE TITLE
Generate billing reports for AWS SEA workload accounts (for CPF Team to generate bills for tenants)

### ISSUE THREAD

**Issue by cloudsmart** [bcgov/cloud-pathfinder#677]
**Describe the issue**
AWS SEA leverages consolidated billing mechanism to consolidate the billing information of all participating accounts into a single bill. While this is helpful, often we need to know the monthly cont of individual accounts for accounting purposes. 

We wish to provide billing by account with metadata and with a service breakdown in the bill.

This will make it easier for reconciliation.

**Which Sprint Goal is this issue related to?**

**Additional context**
- AWS tracks the cost of each account separately
- We have a TF script that retrieves the list of workload accounts and their metadata (owner name, email, billing group, etc.)
- There is a github repo full of python code related to this
 
**Definition of done**
- See sample attached Excel File for the exact fields and order in which the columns should be:
[https://app.zenhub.com/files/241742911/6c1a50f6-b764-4b7e-9467-9fcc4fd496c2/download](https://app.zenhub.com/files/241742911/6c1a50f6-b764-4b7e-9467-9fcc4fd496c2/download)

- High priority because needs to be done in first week of sprint (2 weeks to years)
- Automated billing report that retrieves a list of workload accounts in AWS SEA environment
- CSV or Excel filetypes
- By service, by account, with metadata
- Easy to use CLI command to generate the report
- Each row Includes the following information:
> Account ID
> Account Name
> Account Owner Name
> Account Owner email
> CITZ Internal Project Code ####### eg 1234567 (maybe "rename"/replace Billing Group" tag to/with CITZ Internal Project Code)
> Account Status
> Consumption Service Charges 
- Demo involving Mirella S, Diandra L, Claudia L, Meara O

**Comment by ActionAnalytics** [comment]
Group by Account ID, Service.
