### ISSUE TITLE
LZ1 Teardown

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#678]
**Describe the issue**
LZ 1 is increasingly out of date.  We wish to tear it down to make space for a test SEA.  The value of this is to have a space to develop in that does not affect production workloads.

**Which Sprint Goal is this issue related to?**
Goal 3 - Platform Updation

**Additional context**
- Stu has a signed Service Order into the GoC Brokering Service, that work is progressing without blockers
- The state machines also take a long time to run in LZ2, so additional reason is to have a hot backup ready

**Definition of done**
- Acquire knowhow and code from Ryan J for burning down a enterprise root account (AWS Nuke)
- Clean out LZ1 as much as possible
- Aim for an LZ1 state that is suitable for deploying the old Oct 27 2020 version 1.2.2 of the SEA

**Comment by wrnu** [comment]
Mostly done. Need to nuke resources in accounts in the `Ignored` ou.
