### ISSUE TITLE
GitOps for SEA deployment

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#680]
**Describe the issue**
We wish to automate some of the SEA deployment automation

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- getting config.json in the right form is a manual exercise

**Definition of done**
- Aim to be idempotent
- Have it run the destroy step first (prompt for destroy/confirm please!)

**Comment by mitovskaol** [comment]
Not relevant anymore
