### ISSUE TITLE
Provision Rama to LZ2, TF & GitHub

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#684]
**Describe the issue**
Rama will be assisting with the Cloud Custodian work with Ryan.  The focus will be on
1. Automation running from GitHub on PR merge
2. Setup of a permanent runner and the CI/CD to update the runner
3. Scheduled runs
4. Dashboards time permitting

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Rama is fairly technical and the scope of his involvement is limited
- no controls work, just automation

**Definition of done**
- Needs to happen early next sprint (or even on the Friday before)
- PO & Security to agree on scope
- Onboard and provision Rama with the tools and concepts needed for the scope of his work (hard limit on the scope)

**Comment by bluemel-gov** [comment]
- Access provisioned.
