### ISSUE TITLE
Meet with GoC and ask for access to additional tools and services

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#688]
**Describe the issue**
We're aware that there are some new tools and services available that aid in maintaining and running SEAs of Azure and AWS flavours.  We wish to explore accessing these via the brokerage.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- might require some back and forth

**Definition of done**
- needs to start early in the sprint
- Meeting with GoC with Exec and PO

**Comment by scayzer** [comment]
Meeting booked for 2021-03-23 to ask about Azure guardrails (ticket #644) - can also address this ticket in that meeting

**Comment by sid-gov** [comment]
To be discussed in sprint planning. @sheaphillips
