### ISSUE TITLE
Review expiring cloud certificates and determine next steps

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#694]
**Describe the issue**
We acquired a set of certificates last year prior to having our current landing zones/tenancies, etc.  We received notices that these will be expiring in early April.  We have not used these certificates thus far, but we may still have a need these going forward.  We should review our anticipated work related to SSL Termination and make a decision whether to renew some/all of these.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**

**Definition of done**
Decision whether we need to renew certs.  If yes, ticket(s) related to renewals. If not, no-op.

**Comment by ActionAnalytics** [comment]
Decision not to use (due to capacity).  Make ticket to create new ones later if needed.
