### ISSUE TITLE
UX Researchers gain pre-requisite knowledge before going into the field

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#700]
**Describe the issue**
UX Researchers need a high-level knowledge of the product before sitting with the users to observe their interaction of the product. We have to know the Pathfinder vision to understand the product. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Tour of the application developer Command line interface (CLI), Web-console, Terraform cloud, Github
- A understanding of how this all fits together
- Developer role access in LZ along with a lab workspace, Terraform cloud workspace
- A close-enough diagram of the trainee's understanding of how everything fits together, validated in front of the trainer

**Comment by bharmouche** [comment]
We accomplished a high level knowledge on registry and getting to familiarize ourselves with the product.

**Comment by ActionAnalytics** [comment]
Real goal was to help prepare UX for the time with the app teams, and this happened
