### ISSUE TITLE
Select and contact team for user testing

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#702]
**Describe the issue**
Knowledge transfer between PO and UX researchers for who has attended training and onboarding, stage each app is at, identify contact person for the team

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Bahaa to book time with PO to organize meeting early at start of sprint
- Hopefully agreement and immediate embedding alongside the team to conduct user research

**Comment by ActionAnalytics** [comment]
PO has contacted both teams and has gained approval.  Teams are ready for UX researchers
