### ISSUE TITLE
AWS RACI meeting with CP and ISB

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder#703]
**Describe the issue**
Understand the current and future responsiblities in AWS between ISB and CP.

**Additional context**
- Questions around responsibilites and future responsiblities have come up. 
- By building on a shared understanding, it will help to know how systems are supported and how they will move over time.

**Definition of done**
- setup upto two meetings with CP and ISB for the evolution of a RACI (current and future state)
- Focus of RACI is between ISB and CP team
- understand that the space can change/evolve
- RACI is a snapshot in time.

**Comment by mitovskaol** [comment]
The Cloud Pathfinder Team is working on the RACI matrix for Security and Privacy for AWS SEA and will send it to CITZ ISB for review when it is finished. This work is tracked in a different ticket.
