### ISSUE TITLE
Review and Refine Business Model Canvas

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#704]
**Describe the issue**
Business model canvas done by the UX researchers needs to be reviewed by both POs. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Feedback captured 
- PO & Exec to be reminded about finalizing funding part
- Additional material work to be captured in other tickets

**Comment by bharmouche** [comment]
this is dependent on the group workshop and the defining the next steps.
