### ISSUE TITLE
Design CI/CD components of Cloud Custodian Automation

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#708]
**Describe the issue**
Part of the Cloud Custodian work will exist as hooks for events of when Ryan or others update the repo of Cloud Custodian tests with new tests.  The value of this is that a test run will happen automatically for Ryan so that after merging his PR, he just needs to go to a dashboard and see the results.  Everything in between is taken care of.

**Which Sprint Goal is this issue related to?**
Goal 3

**Additional context**
- Rama to do the implementation
- [mugc](https://github.com/cloud-custodian/cloud-custodian/tree/master/tools/ops#mugc)
- Run on a single account.
- Running on all accounts will be implemented in a future ticket

**Definition of done**
- Meet and knowledge transfer from Warren
- Create GitHub Action workflows:
  - PR triggers a Cloud Custodian dry-run scan of all policies automatically
  - Push to master
     - iterate through policies and folders
     - deploy the policies (run without --dry-run)
    - When policies are removed clean up any resources created by the removed policies (see mugc above)

**Comment by bluemel-gov** [comment]
- met w/CGI to clarify on 3/18
-- Expected updates later today.

**Comment by bluemel-gov** [comment]
- Reviewing possible issue with credentials provided, 
- next steps 'When policies are removed clean up any resources created by the removed policies (see mugc above)' and where to store the outputs from the runs.

**Comment by bluemel-gov** [comment]
- working on documentation and cleanup 
- further review needed on policy for users to access roles (separate ticket)
