### ISSUE TITLE
Build automatic scheduling of the Cloud Custodian test runs

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#709]
**Describe the issue**
Part of the Cloud Custodian work will exist a regular schedule of runs of the current existing snapshot of the entire Cloud Custodian test suite.  The value of this is that a test run will happen automatically in a cadence such that BC Gov can ensure that we don't go for extended periods without test coverage.

**Which Sprint Goal is this issue related to?**
Goal 3

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- meet with Warren to discuss
- Tests run on a regular interval
- There are 2 modes, a testing schedule and a production schedule.  The testing schedule will prioritize quick sequences of test runs such that Ryan can verify that the schedule mechanism works.  The Production schedule will prioritize cost savings and run in a manner that is less than $30/month (guesstimate - contact PO if this is higher and we will negotiate).
- Cost estimate of running the schedule provided to PO
- Demo of automation running on the testing schedule
- The setup for this work must be able to be deployed, torn down, and redeployed without issue (it must be quickly redeployable easily after a disaster recovery situation - full repave - of the landing zone).  This is intended to be deployed in multiple SEA landing zones once we have dev test prod.

**Comment by bluemel-gov** [comment]
spoke w/Warren. further review needed to set the recurrence in policy as lambda instead of as cron, closed ticket as complete.

**Comment by ActionAnalytics** [comment]
@bluemel-gov we also need to be good GitHub citizens and not run this all the time.  Once a week, maybe once a day, is probably fair.
