### ISSUE TITLE
Design Dashboard for Cloud Custodian results

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#710]
**Describe the issue**
Security needs a easily accessible dashboard to view and manage Cloud Custodian results.  We wish to make this in AWS for the moment.  Later on once connections to SIEM are in place we will use that but that part doesn't exist yet so out of scope for this item.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- https://aws.amazon.com/blogs/aws/cloudwatch-logs-subscription-consumer-elasticsearch-kibana-dashboards/
- ties to ticket #697 as that has notifications
- Security Hub exists and should be used if possible via custom events, but all the Cloud Custodian results should be all in one place

**Definition of done**
- Meeting with Warren & Prabhu to go over design
- Events are stored in AWS logging or event streams 
- Dashboard should default to arranging items in order of criticality, date
- Dashboard supports filtering, sorting, ordering
- Dashboard supports export to Excel
- we are looking for a widget design in the internal SIEM that would show results from Cloud Custodian

**Comment by bluemel-gov** [comment]
- booked meeting w/warren on 7/22

**Comment by bluemel-gov** [comment]
- spoke w/warren & sid, can integrate to security hub but this 'Dashboard supports export to Excel' isn't easily supported for the work. scoping out for future tickets as needed.

**Comment by bluemel-gov** [comment]
- blocked atm due to conflicting branch task

**Comment by bluemel-gov** [comment]
- spoke with prabhu on Aug 6th about current setup of kibana dashboard

**Comment by bluemel-gov** [comment]
- waiting for access to kibana dashboard

**Comment by bluemel-gov** [comment]
- Spoke with Sid, will review with PO to update DoD for the work

**Comment by bluemel-gov** [comment]
- met with Julian, discussed the current separation from Cloud Custodian LZ1 to dashboard lz2
- Decided to demo cloud custodian events going to security hub

**Comment by bluemel-gov** [comment]
- currently blocked due to implementation/technical issues
--- Back up plan to have a visual demo/diagram of how it works
