### ISSUE TITLE
Migrate KC users to automation-based groups

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#713]
**Describe the issue**
We have implemented a new set of KC groups for managing users, in paralllel to the manually-created structure.  No users have been populated into the automation-based groups, but we wish to remove the manually-create structure to make management more efficient and less error-prone in the future,as well as enabling delegated (self-service) user management.  Prior to removing the old structure, we need to populate the existing users into the autiomation-based structure.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
We do not anticipate problems, but we do need to be mindful about communicating and executing the change in order to avoid users' access being temporarily affected.  We should consider doing switch for critical users in "real-time".
This change will not affect how out team members access is managed.

**Definition of done**
Users populated into apprpriate locations in "new" structure
Old structure deleted.
Notices posted in RC channel(s) 
Direct communication with cirtical users
Sampling of users comfirm access.

**Comment by mitovskaol** [comment]
Done
