### ISSUE TITLE
Support delegation of of project/account-level DNS to team

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#714]
**Describe the issue**
Currently we are managing "top-level" and "project-level" DNS for tenants in the SEA.  This will become cumbersome and create a bottleneck if teams need to rely on us to make changes.  We can alleviate this by delegating a "hosted zone" to their control within the accounts.  This also will make it easier for teams to create and manage public-facing URLs.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**

New Automation "Layer" implemented to create hosted zones in each tenant account corresponding to the license plate / env.
Update to project.json
Process/tooling integrated into SEA management "stack".
Changes applied across workload accounts
Tenant and operations facing documentation created
Code and docs reviewed and committed into Github.

**Comment by mitovskaol** [comment]
It is still a good idea and we want to do this.

**Comment by wrnu** [comment]
No longer relevant
