### ISSUE TITLE
Create Serverless revision of Sample app using Lambda

### ISSUE THREAD

**Issue by cloudsmart** [bcgov/cloud-pathfinder#717]
**Describe the issue**
Current architecture of the sample app is based on AWS ECS (Elastic Container Services), API Gateway, and DynamoDB. It will be beneficial to teams to have a Serverless reversion of the app that utilizes AWS Lambda instead of ECS. The rest of the architecture can remain intact.
 
**Which Sprint Goal is this issue related to?**
Goal No. 2

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Application source code should work as-is without any change
- Only the packaging of sample app will be affected by this ticket: instead of creating a Docker image we would need to zip the build output
- Instead of deploying the Docker image to ECS the zip file is deployed to Lambda
- repo names will be something like:
- - startup-sample-project-aws-containers
- - startup-sample-project-aws-serverless
- - startup-sample-project-aws-vms
- - startup-sample-project-azure-serverless
- - startup-sample-project-gcp-serverless

**Definition of done**
- New Github repository is created that holds the source code of the app and TF
- CI/CD pipeline similar to the current sample app is created
- Serverless revision of the sample app is deployable to any AWS SEA account using the CI/CD pipeline

**Comment by sid-gov** [comment]
@wrnu to reach out to Prabhu to update the source code.
