### ISSUE TITLE
Go over procurement fit with Mines

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#720]
**Describe the issue**
During our demo this week, we showed the Procurement Journey.  Mines exec Jill C requested to go over the thresholds described in the Journey and compare it to the Mines configuration.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Meeting with Stuart and Jill, outcome to provide assurance to Mines.

**Comment by scayzer** [comment]
Meeting conducted - MDS cost estimate = $45K per year, and have options for CSP selection rationale
