### ISSUE TITLE
Review Procurement Journey with Mac

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#721]
**Describe the issue**
Mac requested review of Procurement Journey.  This could be accomplished in the Even More Collaboration series or one on one.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Mac has had an opportunity to walk through the journey and his feedback/suggestions/comments are captured
- Tickets created if needed

**Comment by scayzer** [comment]
Meeting scheduled for 2021-03-22
