### ISSUE TITLE
Book ASAP scrum training for Bahaa

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#722]
**Describe the issue**
Bahaa is new to the team and has indicated a desire to have the same training for Scrum Agile as everyone else.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Alluvial training booked (either SM or Agile 101.  Preference for 101)

**Comment by sid-gov** [comment]
Needs to be approved by ADM first.

**Comment by sid-gov** [comment]
Training is booked for Bahaa on April 7-8.
