### ISSUE TITLE
Bug: Unexpected results when assigning a developer role when provisioning roles to CP Lab accounts

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#723]
**Describe the bug**
Users recently provisioned see no meta data and see only the SAML provider account rather than the accounts they are supposed to see.

**Additional context**
While onboarding UX team-members to CP Lab 8 and CP Lab 9, they are able to see 2 accounts on log in, but they see the same umafubc9 account and none of the meta data loads for them.  Suspect that they are seeing the SAML provider account intended to grant view access to the login page rather than the actual accounts for CP Lab 8 and CP Lab 9 respectively.

**Definition of done**
- In SSO admin, when a user is linked to a developer role under a chosen account like one of the CP Lab accounts or a real project account, they should see the account they have been provisioned.
- Any common accounts like the common SAML provider and org read role should be invisible in the Login Page
- Emily and Bahaa's roles are working.

**Comment by sheaphillips** [comment]
Issue resolved by adding "Org Read Role" to top-level KC group for tenant teams.
