### ISSUE TITLE
UX review with Tech team

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#731]
**Describe the issue**
The UX has made some observations to be shared with the team which will drop into new tickets. 
**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**

**Definition of done**
- 30 min meeting with tech team 
- UX to bring notes to meeting, ask questions about the design goals and provide usability observations
- create well formed and narrow scoped tickets for any design changes required (tech team to help UX with this activity together)
- Create well-defined tickets 
- Book a meeting with PO on the Thursday before refinement

**Comment by bharmouche** [comment]
Met with the team and shared user insights  on a [mural deck](https://app.mural.co/t/cloudpathfinder2329/m/cloudpathfinder2329/1618253360064/9ae598587cac18b67b9c12b623ca1a6109b60d66) 

PO opened tickets that will be in the pipeline and will proceed as seen fit.
