### ISSUE TITLE
Amend Procurement Journey to provide alternate approach(es) to competing workloads within the Cloud Brokering Service

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#734]
**Describe the issue**
Discussions with Government of Canada are indicating that they won't support competing workloads of total value <$4.5M
Now working with Zach to determine what alternate approach(es) may be viable for BC government.

Will need to update our Procurement Journey map accordingly.

**Additional context**
- We will wait 1 sprint for our Procurement Director to join us and then co-work on this together
- This will likely also involve working with Douglas (LSB)

**Definition of done**
- Stu to provide overview of work so far on this topic
- Collaborate with Zach to explore options for workloads >$75K/year
- Update Procurement Journey and review with Zach and Gen

**Comment by ActionAnalytics** [comment]
@sid-gov @scayzer  to try break this into smaller bites so Stu can get traction this sprint

**Comment by ActionAnalytics** [comment]
To be pulled out once replaced with smaller ticket

**Comment by ActionAnalytics** [comment]
Zack's availability is a challenge at the moment.  Hold off until backlog clears

**Comment by mitovskaol** [comment]
Not relevant anymore
