### ISSUE TITLE
Renew CPF certificates

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#738]
**Describe the issue**
We have a set of certificates that we had created a year ago.  We need to review whether we want to retain these and act

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- There are currently expired but we have a period to renew them. 

**Definition of done**
- Connect Sid with Luke for administrative process
- Certificates are done the same way as last year 
- Check with Gen about the cost and explain the reason PO chose this approach

**Comment by sheaphillips** [comment]
@sid-gov assigning this one to you while you run with it and until you need my help again (to create+submit Certificate signing Requests)

**Comment by sid-gov** [comment]
Certificate requests sent to IMB. Blocked until they reply back.

**Comment by sheaphillips** [comment]
- CSRs submitted to IMS group on Jul 9.  
- expect certs themselves to come back within a day or two and will close ticket at that point.

**Comment by sheaphillips** [comment]
- artifacts stored in ACM and available to use in ACM-aware services
- keys stored/backed up in secrets manager
