### ISSUE TITLE
Review (and refine) our Business Model Canvas with Product Owners and with Developers

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#739]
**Describe the issue**
Having drafted our Business Model Canvas with our own team, we wish to get further input on it from the perspective of our customers/partners.

We'll be discussing things like value proposition, communication channels and revenue/pricing.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
We need to complete the current work on embedding with the user teams, and learning what we can from that experience. We also need to allow those teams to continue through a few billing cycles (months) to experience the service.

**Definition of done**
- 2 hr meeting with CP team at the end of sprint (Thu or Fri) 
- Gather insights and discuss with our team - create tickets for follow-up activities
- Demo to Gen with Stu, Bahaa, Sid and Julian at very end of sprint

**Comment by bharmouche** [comment]
We did the workshop end of Sprint. will study and create a one pager narrative this coming sprint and share with everyone.
