### ISSUE TITLE
Login Page Re-Architecture: Token Timeout change

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#740]
**Describe the issue**
Developer Users requested a longer timeout of 6 hours. An attempt was made to change this but there were settings in other places that still need to be changed. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- timeout change is done
- Follow up on Rocketchat thread on this topic

**Comment by wrnu** [comment]
I'm not sure if increasing the session time beyond an hour is possible with out current architecture. From the [docs](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithSAML.html):
 

> Role chaining limits your AWS CLI or AWS API role session to a maximum of one hour. When you use the AssumeRole API operation to assume a role, you can specify the duration of your role session with the DurationSeconds parameter. You can specify a parameter value of up to 43200 seconds (12 hours), depending on the maximum session duration setting for your role. However, if you assume a role using role chaining and provide a DurationSeconds parameter value greater than one hour, the operation fails.

**Comment by sid-gov** [comment]
This would be a good reason for re-architecting the Lambda behind the login page.
