### ISSUE TITLE
SPIKE: Develop a pattern for preventing teams from doing irreversible expensive actions

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#741]
**Describe the issue**
Teams are asking for things like reservations because reservations allow much cheaper usage rates. The problem with reservations is that they can be expensive and are essentially permanent. We wish to create a barrier that prevents teams from performing these kind of actions while allowing Cloud Pathfinder to perform these actions for them. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Stu and Gen are working on the financial implications of reserved instances wrt financial thresholds

**Definition of done**
- Create a set of well-defined tickets with a technical solution

**Comment by mitovskaol** [comment]
We are not pursuing Reserved instances at this moment. A new ticket will be created if this changes.
