### ISSUE TITLE
Placeholder for implementation of barrier to irreversible expensive actions

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#742]
**Describe the issue**
Placeholder for implementation of #741

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Exact steps tbd

**Comment by mitovskaol** [comment]
Not going to pursue at this moment.
