### ISSUE TITLE
Deliver Azure services list to Exec

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#746]
**Describe the issue**
Exec needs a list equivalent list of Azure services that AWS SEA uses.
We need to proceed in parallel because getting access to GOc SEA is taking a while. We need to login to Azure and see what's the setup there. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Deliver services list to Exec asap
- To be done in close cooperation with PO
- Read and understand the 200 pg design document
- Login to Azure
- Create any diagrams that highlight where our multi-cloud design might collide

**Comment by sheaphillips** [comment]
@ActionAnalytics  this might be useful - it includes tables mapping Azure to corresponding AWS services. https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services
