### ISSUE TITLE
SPIKE: Discuss a plan to deliver a Guided FAQ for the CSS

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#750]
**Describe the issue**
This is a consult piece to support Don because we've done FAQ work before and have some web experience.  He wants something similar to support the CSS.

Get the Cloud Security Schedules understood by various parties.  In it's current state, the CSS is a large document that applies to multiple stakeholders in specific manner.  It can be a lot of work to consume for a stakeholder, and Don is thinking about ways to improve the user experience such that stakeholder users of the CSS have an easier path to adoption because they only see what applies to them.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Different stakeholder perspectives: Cloud Service Provider CSP, SaaS Provider, User, Ministry Business area questions (what do security requirements mean to this segment?)
- What are their responsibilities and when do they need to flag? 

Guided FAQ that has the following: 
- Self-select what your role is? 
- Guided path to a branching questionnaire to determine scenario
- Arrival path is recommendation for behaviors in that situation
- Value for each perspectives/stakeholders: Uncluttered actionable list that is specific to the use case 

https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/information-security/cloud-security-schedule

**Definition of done**
- start by having a quick look at the spreadsheet Don gave us
- Meeting to discuss approach (policy, UX, included) happens
- Set of well-defined tickets for next steps
- Review meeting with Don

**Comment by ActionAnalytics** [comment]
Talk to me if you need any context or help.

**Comment by emilyjones430** [comment]
Multiple meetings with @bharmouche and @bluemel-gov to discuss approach. Created tickets #818, 804, and 805 for next steps for CSS.
