### ISSUE TITLE
UX Observation of Immersion Day training - Emily

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#752]
**Describe the issue**
Teams have a need for basic AWS knowledge and a preview of how the LZ is different from regular AWS so that they can plan and estimate their 
work for POs and EAs that are deciding whether or not they want to onboard to AWS. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Training is specific to BC Gov SEA provided by AWS in a regular format AWS calls Immersion day. 

**Definition of done**
- Review training track with PO prior to attending
- Attend immersion day training provided by AWS and gain understanding of experience for teams
- Creation of feedback form to capture any missing pieces/improvements needed from future attendees (Focus of the form: Did you get enough info to make a Go/No-Go decision to BC Gov SEA and what's missing)

**Comment by emilyjones430** [comment]
Reviewed training track, attended immersion day and created and sent out feedback form.
