### ISSUE TITLE
Security Automation test for detecting root usage in containers (ECS)

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#760]
**Describe the issue**
One of the best practices is to not have administrative accounts ever running in deployed pods in a container environment. We wish to scan the entire ECS ecosystem in the entire LZ and detect any usages of root accounts either by running pods or by image registry such that we can follow up with teams and stop usability. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**

**Definition of done**
- To accurately detect any usage of root either via image registry scan or running pods (preferences on running pods)
- Bonus points if it's easy automatically shut down any pods that are running out as root (if its easier shut off/isolate the entire ECS access)

**Comment by bluemel-gov** [comment]
- reached out to vendor for more information against resources found on 7/26

**Comment by bluemel-gov** [comment]
- resource found by CSP: https://github.com/hadolint/hadolint,  rule DL3002

**Comment by bluemel-gov** [comment]
- checking with ES teams now for how this is done on-prem

**Comment by bluemel-gov** [comment]
note
- what about inactive ECS instances?

**Comment by bluemel-gov** [comment]
https://cloudcustodian.io/docs/aws/resources/ecs-task.html?highlight=root

**Comment by wrnu** [comment]
@NickCorcoran can you review and close if not needed. I think this may be the teams responsibility

**Comment by NickCorcoran** [comment]
To revisit as part of capability included in CloudGuard CSPM.
