### ISSUE TITLE
Self-serve GUI for the SEA billing report generation process

### ISSUE THREAD

**Issue by cloudsmart** [bcgov/cloud-pathfinder#762]
**Describe the issue**
This is to create a GUI to have PO's self-serve from a Dashboard in the AWS Console GUI 

The current solution is comprised of two distinct steps:
1) Run a Terraform command manually to generate a list of all SEA workload accounts that includes the account ID's, account owner name and email (aka metadata) as a json document. This was delivered through ticket#662.
2) Pass the json document to an AWS step function to retrieve the billing data for the accounts and generate HTML outputs for tenants, This was delivered through ticket#677

**Which Sprint Goal is this issue related to?**
Goal 2

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- short solution is to write a bash script
- longer solution is to do the first step as a lambda function

**Definition of done**
- Billing report is self-sufficient and does not need a precursor to generate the json document for it

**Comment by mitovskaol** [comment]
Not going to pursue this at this moment
