### ISSUE TITLE
Provision Bahaa with Airtable

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#764]
**Describe the issue**
In order to do surveys, we will have a variety of tools available (MS Forms, Airtable).  

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Sid to connect with Meara to use p-card for Airtable (check with Gen first)
- Enable the use of Airtable for Bahaa and other team members as needed (Julian, Shea, Emily)

**Comment by sid-gov** [comment]
Closing this as access is provided.
