### ISSUE TITLE
Program level PIA Placeholder

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#765]
**Describe the issue**
Detail to be provided after discussion with Exec

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Details to be provided (time bucket for now)
- Delete this ticket if not needed

**Comment by hromanow** [comment]
Spoke with Gen and determined that the AWS corporate PIA can work as the program level PIA.
