### ISSUE TITLE
Build a Web application for SEA billing report

### ISSUE THREAD

**Issue by cloudsmart** [bcgov/cloud-pathfinder#766]
**Describe the issue**
A billing front-end for Sid or Julian to self-serve.

Currently the billing reports are generated through Command Line Interface (CLI) which makes it difficult for non technical users to run. Moreover, the output files are in HTML format that can be viewed by a browser.
This ticket is to create a Web application for billing reports that allows the user to generate reports for their respecting accounts for a reporting period (Year/Month) and view the reports through the same UI. Main users of this application are Cloud Pathfinder Product Owner and/or Scrum Master, as well as Product Owners of other teams who have a tenant in SEA Landing Zone (LZ2). 

**Which Sprint Goal is this issue related to?**
Goal 2

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
Secure Web application that satisfies following requirements:
- Utilizes billing report back-end that was delivered as part of ticket#677
- Accessible through a public URL under BCGov domain 
- RBAC with 2FA enabled
> Tenant PO's can view their own tenant accounts only
> Cloud Pathfinder users can select individual tenants or all tenants to generate billing report for
- Provides historical and current month billing reports

**Comment by mitovskaol** [comment]
Not relevant anymore
