### ISSUE TITLE
Enhancements to packaging and deployment of Rocketchat notifications for security findings

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#767]
**Describe the issue**
We wish to have additional means of notification for security hub findings in addition to the later SIEM integration work. The scope of this ticket is about deployment activities that needed to be finished for previous sprint. 

The intention is that we automate the LZ0, LZ1, LZ2 security notifications so that it manual to set up each time.  We do this via the terraform layers we run after ASEA upgrade/deploy actions.

**Additional context**
https://github.com/BCDevOps/terraform-octk-aws-sea-rocketchat-notifications/pull/1

**Definition of done**
- PR details are complete
- Terraform modules usable in LZ layers

**Comment by sid-gov** [comment]
Shea to review.

**Comment by unoah** [comment]
- Performed some tests using a local RocketChat instance and the Terraform [RestApi](https://registry.terraform.io/providers/fmontezuma/restapi/latest/docs) provider
- Successfully provisioned single channel but ran into issues with creating additional channels/arbitrary number of channels.
- Also some challenges with deleting channels. Collaboration with other engineers/initial test suggests discrepancies with how the RestApi provider makes calls against RocketChat API is at play here.

**Comment by ActionAnalytics** [comment]
Admitting defeat, you win Rocket Chat Terraform.  We will do manually.  Maybe write a provider for Rocket Chat.
