### ISSUE TITLE
Solve permissions warning in aws-security-medium

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#769]
**Describe the bug**
There's an AWS SecurityHub warning recurring in our aws-security-medium event stream.

**Additional context**
- Last event was 202104071610, viewable in RC aws-security-medium
- Bahram was doing some activity then

**Definition of done**
- determine if that is a legitimate warning we wish to see
- Test if resolving an issue in Security Hub appears in Rocket Chat
- Determine and document a pattern for CPF operations to responsively handle events showing up in Rocketchat such that when we show SecOps, the audit trail is sufficient to satisfy

**Comment by mitovskaol** [comment]
Not relevant anymore
