### ISSUE TITLE
Connect to the SecOps group users

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#772]
**Describe the issue**
We intend to give special kind of access to Security Operations users in the Cloud pathfinder environment. This access will be scoped to security investigations and logging. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Attend the series of CP and SecOps meetings (April 21st scheduled)
- Begin a user persona for this user group. (Requires a user profile file in Microsoft Teams)

**Comment by ActionAnalytics** [comment]
This is done already
