### ISSUE TITLE
1 minute Login Timeout time on Login Page

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#776]
**Describe the bug**
Users are saying that the 1 minute timeout on the login page is too short and logs out too fast. 

**Additional context**
- the timeout is unexpected and there is no feedback
- login page consists of several pages: scope is around the page that is displayed when user successfully logged in and MFA'd and is being shown the accounts they have permissions to. 
 

**Definition of done**
- 5 minutes would be a good target instead of 1 minute
- a visual indicator of the time remaining (clock countdown, progress bar?  surprise us)
- option to grab tokens and go through to web console GUI at the same time
- If timeout runs out, display original SSO link to restart process

**Comment by ActionAnalytics** [comment]
https://app.mural.co/t/cloudpathfinder2329/m/cloudpathfinder2329/1618253360064/9ae598587cac18b67b9c12b623ca1a6109b60d66

**Comment by wrnu** [comment]
Features Implemented:
- 5 minute timeout
- Display session time remaining
- Link to SSO when session time expires
- Open AWS console in new tab/window

Features Not Implemented
- option to grab tokens and go through to web console GUI at the same time
  - This is not needed now that the AWS console is opened in a new tab. The original aws-login page is available to retrieve the AWS cli credentials.
