### ISSUE TITLE
Maintained list of supported services on/or reachable from login page

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#777]
**Describe the issue**
Users want a quick lookup of the current list of compliant services

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- We have a list but it's unreachable to users because it's buried in our Teams
- Our business case for "Accelerated Public Cloud Services" promises: "A managed catalogue of compliant cloud services (including a registry of SaaS products that have already passed compliance reviews), with ongoing, demand-driven additions to the catalogue, enabling self-service access to the services."

**Definition of done**
- Might be cool to link right off the login page to a static web page one stop shop for quick info about the SEA for users
- Information is displayed in a Tab or sidebar
- Reword the above statement in our business case to better represent the service catalogue experience that we're aiming for
- List of supported services is stored in Airtable and the front-end will pull from there

**Comment by ActionAnalytics** [comment]
https://app.mural.co/t/cloudpathfinder2329/m/cloudpathfinder2329/1618253360064/9ae598587cac18b67b9c12b623ca1a6109b60d66

**Comment by scayzer** [comment]
Business case statement amended as follows, the Desired Future State section:
"BC government will have centrally supported Accelerated Public Cloud Services.

This will include 
1) Pre-qualified  Cloud Service Providers that can provide policy compliant compute and storage services.
2) A managed listing of available cloud services (including SaaS products) that have already passed compliance reviews), with ongoing, demand-driven additions, and appropriate means to consume the services.
3) A continuously improving, end-to-end service experience for ministry teams accessing cloud services, including:
a.	Pre-programmed technical guardrails that enable self-service and automated compliance with security and privacy policies to the greatest extent possible. 
b.    Access to tools for cost-estimation, and for monitoring of resource usage and costs incurred in real-time.
c.	Full transparency of invoices for cloud services provided to ministries (direct billing from cloud service providers if possible). 
d.	One or more governed and empowered Communities of Practice enabling collaboration and knowledge sharing on patterns for successful adoption of cloud services."
