### ISSUE TITLE
SPIKE: Evaluate Clecio's login scripts and tools for potential adoption by CPF

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#778]
**Describe the issue**
Clecio showed some login automation to our service designers.  They observed that others could benefit from that tools and this could be integrated into our training. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Rocket Chat links to cool shared tools
- Link to useful tools on the login page (Airtable)

**Definition of done**
- New tickets created if needed to incorporate tools 
- Timeboxed to 2 points

**Comment by ActionAnalytics** [comment]
https://app.mural.co/t/cloudpathfinder2329/m/cloudpathfinder2329/1618253360064/9ae598587cac18b67b9c12b623ca1a6109b60d66

**Comment by mitovskaol** [comment]
Not relevant anymore
