### ISSUE TITLE
Request for additional TF tokens limited in scope to dev and test, but not prod

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#779]
**Describe the issue**
Teams may want finer grained access that the wide 1 token we have now

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- This might be RBAC related or TF
- A related element is how to provide delegated self service management of role to user assignment to tenant teams so that they can maintain a matrixed based access control 
- Request seems to be to allow functionality for teams to request finer grained access control to key accounts

**Definition of done**
- Loop back through UX to find out who made the request and understand what they need
- Create tickets if necessary

**Comment by ActionAnalytics** [comment]
https://app.mural.co/t/cloudpathfinder2329/m/cloudpathfinder2329/1618253360064/9ae598587cac18b67b9c12b623ca1a6109b60d66

**Comment by mitovskaol** [comment]
Not relevant anymore
