### ISSUE TITLE
SPIKE: Metadata "Are you sure" delete prompt in ECR

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#780]
**Describe the issue**
Teams are wary of accidentally deleting in the ECR.  They want a pattern of are you sure.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- IaC and auto-backups will need to be in place
- CPF assumes that there is nothing that can be done to enforce but we will investigate by talking to the team
- Possible ECR lifecycle prevent destroy
- Trace back from Bahaa, Emily who the team was that had this issue

**Definition of done**
- Meeting with team to determine the actual need and priority

**Comment by ActionAnalytics** [comment]
https://app.mural.co/t/cloudpathfinder2329/m/cloudpathfinder2329/1618253360064/9ae598587cac18b67b9c12b623ca1a6109b60d66

**Comment by mitovskaol** [comment]
Not going to pursue this at the moment.
