### ISSUE TITLE
SPIKE: Develop approach for credential rotation/lifecycle management

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#786]
**Describe the issue**
We have a set of credentials that we generate and use with our automation tooling, and a set of credentials that we provide to our tenant teams.  We currently do not have an mechanism to manage the lifecycle of these credentials (rotation, revocation, etc.).  Manually managing this lifecycle will become unmanageable for our team as the number of teams  and credentials grow.  It is also inconvenient for tenant teams to manage certain credentials within their team. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Re-visit on-prem vault offering
- Review managed terraform cloud 

**Definition of done**
- document list of the different credentials types we create and manage
- proposed automation/tool-centric approach for efficiently and securely managing credentials
- Documented in BCGov-C

**Comment by mitovskaol** [comment]
We will be building the integration with Vault to generate ephemeral keys , instead of rotating keys for teams.
