### ISSUE TITLE
Determine Approach for tracking configuration of different LZ

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#789]
**Describe the issue**
Configuration of Landing zones (ex: SCPs) is currently stored only in within the LZ themselves. This provides no mechanism to compare differences between LZ and it is cumbersome to access like this. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

**Additional context**

**Definition of done**
- 1 or more private repositories containing the configuration artifacts related to each of our Landing zones. 
- Read me file indicating how and where these are to be used
- time-boxed

**Comment by wrnu** [comment]
All LZ config will be stored in the terragrunt overlay live repo

https://github.com/bcgov-c/aws-sea-bcgov-overlay-live/
