### ISSUE TITLE
Implement set of SCPs to protect overlay elements from modification

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#790]
**Describe the issue**
No technical controls (Service Control Policies) exist to protect overlay elements (parts of the landing zone that CPF adds on top of the landing zone). We want to implement a set of technical controls as identified by #784

**Additional context**
- This is about protecting team members' access by not accidentally deleting components they need

**Definition of done**
- Controls implemented and tested with layer automation tools (LZ1)
- Tags for Client VPN overlay layers have been created

**Comment by wrnu** [comment]
Moving to blocked, the tag based approach complete but untested. I have added a dependency on #787 so that we can test in LZ1 before deploying on LZ2.

**Comment by ActionAnalytics** [comment]
Part of the 1.5 upgrade, blocked until then

**Comment by ActionAnalytics** [comment]
Waiting for 1.5

**Comment by ActionAnalytics** [comment]
getting stale, questionable relevance...
