### ISSUE TITLE
Investigate options for enabling teams to purchase reserved instances

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#798]
**Describe the issue**
The scope for this is on a Ministry Team App, not the entire tenancy.

AWS offers reserved instances and savings plans that enable substantial savings over their standard on-demand pricing. Our current processes for funding our AWS account, providing access to teams, managing cost recoveries .. don't readily accommodate the use of these features.

Need to explore options and make recommendations on how best to enable access to these cost saving mechanisms. 

A scenario would be that a ministry team would be pricing out and planning for their year.  They know that they are using RDS (a database service from AWS) and they are looking for ways to save on those database costs because those are a key driver to their monthly bill amounts (RDS is a large comparative monthly expense).  By pricing out and using reserved instances of RDS, they could save a lot of monthly expense.

The issue is that once purchased, you cannot refund (you can only sell it "used" on some sort of internal marketplace - potentially possible to distribute to another BC Gov SEA tenant).

We don't want to allow self-serve in this case from a tech point.  Normally a team would run an automation script that would deploy AWS database (for example among many other things).  We have no problem with that because of two "controls"; the first is that if the team notices they ordered 10x too much by mistake, they simply run a different automation to fix it, secondly if they don't notice, the expense authority will soon notice during the pay period and come to the team to ask why the bill jumped so high.

CPF tech team wants to manage the deployment of reserved instances because it is a permanent action.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- We discussed Accounting implications with Finance: Answer is OpEx 
- Dependent on new hires: Procurement Director and Financial Analyst
- Likelihood of a Product Owner and contractor team turnover during 3 yrs is pretty high
- There are 3 possible routes, all with different discounts, to paying for reserved instances as described by our CSP:
- - no upfront, commit to term (12 or 36 months) which is a commitment, different from our consumption model
- - full upfront (12 or 36 months), not used very often, sometimes clients consider it cap ex (in our case it's op ex)
- - partial (12 or 36 months)

- We are estimating on happy path and if so, then this is a 1, if not then we will create further tickets

**Definition of done**
- Covered by Trade, 3CMB & Policy, (no longer needed Legal review with Douglas)
- Discuss procurement implications with Procurement Director and Financial Analyst - does reserved instance, $51K for 3 years paid in advance, equate to $17K/year against our $75K/year procurement threshold?
- Conversation with Gen

**Comment by scayzer** [comment]
Update: Gordon Dicks says it can still be OpEx - just need to provide CFS with info to enable allocation of costs to years throughout the life of a reserved instance

**Comment by fastaudra** [comment]
Scheduled meeting with Gen for 09-15-21.
