### ISSUE TITLE
Redesign our User Journey Map

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#800]
**Describe the issue**
Following our effort to knowing our user and fine tuning our service, mapping the User experience will help us into visualizing the steps our users going through. This exercise will help us as well to look at our service in a different clearer angle. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- This is a great [article](https://blog.practicalservicedesign.com/the-difference-between-a-journey-map-and-a-service-blueprint-31a6e24c4a6c) about the difference between 2 and this is a video that explains it all together. As for template we can adapt this one.
- Reference in [Devhub](https://developer.gov.bc.ca/Agile-Delivery-Journey/Alignment) 

**Definition of done**
- talk to users/business owners 
- map their journey (if we have users who went through the whole process)
- deliver a draft journey diagram 
- if possible, choose an analogy/format that is more editable 
- out of scope: publishing the journey map

**Comment by mitovskaol** [comment]
This is already documented in the Service Blueprint document.
