### ISSUE TITLE
CSS: Compile categorized questions into web content 

### ISSUE THREAD

**Issue by emilyjones430** [bcgov/cloud-pathfinder#805]
**Describe the issue**
Once we have categorized questions about the Cloud Security Schedule into stakeholder groups, we want a clear way to organize the information such that it is simple for the stakeholders to get to the information they need. 

We want to consider how to make this clear and accessible - potentially through web content or through a questionnaire (Common Hosted Forms).

This is important to make sure that stakeholders can access information specific to them to help them correctly complete the Cloud Security Schedule, without having to review large amounts of information.  

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- We will need well formed answers as input to this

**Definition of done**
- An Airtable completed questionnaire or web content that guides stakeholders through to specific information

**Comment by ActionAnalytics** [comment]
Bonnie over in Security is taking this over, Security really likes the demo that Emily arranged
