### ISSUE TITLE
CSS: Develop training for MISOs

### ISSUE THREAD

**Issue by emilyjones430** [bcgov/cloud-pathfinder#807]
**Describe the issue**
We know that MISOs receive questions about the Cloud Security Schedule that they don't know how to answer, and as such need to communicate with the OCIO for more information. Some of these questions have been developed into an FAQ, but we want to support the MISOs with the knowledge they need to answer questions about the CSS. 

We want to develop training based on the common questions received to ensure that the MISOs have the knowledge they need to help their ministries. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- We should be able to recycle a lot of the training we have to make this easier to accomplish

**Definition of done**
- Coordinate with Michael Foltinek who is also working in this space
- Creation of training material for MISOs (training session content, informational video)

**Comment by mitovskaol** [comment]
@NickCorcoran Can you please see if this is still something that you'd like to do.

**Comment by mitovskaol** [comment]
Not part of the CPF team's responsibilities anymore.
