### ISSUE TITLE
Get up to speed on Airtable

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#808]
**Describe the issue**
In order to help our users understand and accept the CSS, we want to host in a web format.  We also want our surveys in Airtable.  

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Airtable - suggested by CPF team

**Definition of done**
- needs to happen at the beginning of the sprint (Apr 26-30)
- Coordinate with the tech team and scrum master to all the CPF access
- organize a 2 hour hackathon exploration with Airtable
- - everyone can make a survey
- - everyone can make a page and embed in another

**Comment by sid-gov** [comment]
billing p-card issues deterred getting the whole team access to Airtable Pro accounts. Access provided to Bahaa, Emily and Shea

**Comment by sid-gov** [comment]
Exploration meeting with the above team members happened. Closing the ticket for this sprint.
