### ISSUE TITLE
Attend meetings with SecOps and PO to gain user understanding of SecOps

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#810]
**Describe the issue**
SecOps are identified as important stakeholders because they would need to do Security investigations and they would need to have information appear in their systems. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
This is the meeting Tuesday 27th called "Tour of Cloud Pathfinder"

**Definition of done**
- Attend meeting series with SecOps and CPF
- List of user likes/painpoints
- Rough user profile draft

**Comment by bharmouche** [comment]
after transcription a 1 pager deck created and saved on our team channel under service design.
