### ISSUE TITLE
Consult with HashiCorp about single runner problems

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#816]
**Describe the issue**
With our current TFC subscription, we are limited to a single "runner". In some cases, this can lead to the "noisy neighbour" problem where one team in a shared environment slows down or blocks another's progress.  We have some process workaround for this that seem to work at our current scale, but this could present problem going forward.  HashiCorp offers a number of different subscription/configuration options, but it is unclear whether adjustments in this area would improve our situation.  We should confer with their account/SA resources to explore together.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- a set of options for us to consider in addressing the "single runner" problem
- any SPIKE or other tickets resulting from the exploration

**Comment by wrnu** [comment]
No longer relevant
