### ISSUE TITLE
Periodic automated delivery of billing reports to CPF PO an tenant team POs

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#821]
**Describe the issue**
Product owners need to get easy visibility (at an appropriate level of detail) into AWS costs  their projects are incurring in advance of receiving their quarterly billing reports so they can create projections and/or track against budgeted amounts.  We would like to "push" reports (or otherwise make them accessible) to them at a shorter interval that quarterly.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- AWS provides billing functions but they are verbose and difficult for tenant Product Owners to access and decipher.  They are also missing "metadata" that indicates "which account is which". (dev, test, prod, etc.)
- a meeting is scheduled May 10 with tenant product owners to help inform this ticket.

**Definition of done**
- Scheduled mechanism implemented that generates billing reports using "billing utility" and sends these to account team contacts.
- Ability to trigger delivery manually (in addition to schedule)

**Comment by sheaphillips** [comment]
There is ongoing/open work with this ticket.  It will be wrapped up and/or transitioned to another team member during this sprint.

**Comment by sid-gov** [comment]
Closed as complete.
