### ISSUE TITLE
Design overall approach for UX research to inform continuous improvement of our Service Blueprint

### ISSUE THREAD

**Issue by scayzer** [bcgov/cloud-pathfinder#830]
**Describe the issue**
We have work currently underway embedding Bahaa and Emily into ministry teams working in our AWS SEA environment - this represents UX research that will inform continuous improvement of the latter phases of our Service Blueprint, and specifically the customer journey of the app development teams. We also wish to continuously improve the other phases of the Service Blueprint, and the experiences of other customers (Product Owners, executive sponsors, ministry compliance teams, .. etc)

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Service Blueprint enables the team to understand how the services are delivered. This becomes a part of onboarding document. It comprises the front stage, back stage and customer touchpoints. The audience is new team members who will become part of the Cloud Pathfinder team. 
- Include the information in Triangle diagram of the product discovery session as input

**Definition of done**
- Meet with PO to understand the triangle diagram
- Identify all consumers of our services that we currently know of
- Devise ways and means of researching their personas and experiences to inform continuous improvement of our Service Blueprint
- Review with PO and create tickets for follow-up work

**Comment by wrnu** [comment]
No longer relevant
