### ISSUE TITLE
Legal review of Airtable T&Cs

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#836]
**Describe the issue**
We might not even need this if we end up deciding on another common tool. Policy has a PIA and STRA for Airtable but the Legal Review wasn't done at that time.  We wish to reuse this work and make sure Legal is good with the terms of the contract.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Consider the source of the requirement for legal review is a newly documented SaaS process that may not be a good fit for a use case of this size.  The process has been in place for a while but not everyone was following it.
- Legal review is $220/hr
- Product use license is $96US/month

**Definition of done**
- Consult with exec to see if this fits SaaS use case, and if so
- Legal review complete

**Comment by sid-gov** [comment]
We discussed and we are going to experiment with Google.
