### ISSUE TITLE
SPIKE: Contribute to Enterprise Key Management solution research

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#837]
Needs work to break down - Epic sized

**Describe the issue**
James A Team Lead from IT Security Operations wishes to address the growing need for an enterprise key management system.  Some ministries have approached SecOps with respect to multiple cloud use case scenarios.  Looking for a "Swiss Army knife" solution to provide service for all these use cases on multiple platforms, or maybe a "knife block".

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Logs, Cyber incidents, vuln scanning, 
- Incident commander for cyber incident response
- Vault is already in service in the Platforms
- Digital Certificate service - backup/restore to be able to provide keys
- Vendor has a cloud service that is available - but procurement will need to be done
- See Gartner advice JA sent (takeaway is more than one solution is likely)
- Dilemma - what if the vendor is compromised?  or if we self-host that's an instant critical system
- Vendor meeting at end of month - can be deferred.

**Definition of done**
- A 2 hour working meeting with the following topics:
- Form a working group with James & co, Nick C and other experts and CPF 
- Consider how various cloud KMS' could work together (the "yard sale" together)
- A clear draw.io diagram that shows the KMS landscape (products & places) and how they could relate.  Look for opportunities to collapse multiple things down to one or a few core services.
- Create new tickets for next set of work

**Later Scope**
- Form a governance and advisory group for clients 
- Have practical guidance for ministries and clients ("don't email your keys!")
- Central vs Ministry self-procured
- Prototype with solution X, solution Y

**Comment by mitovskaol** [comment]
The Platform Services Team is working on rolling out Hashicorp's Vault product for secret management for apps in the BC Gov's Private Cloud Openshift PaaS in Q1 of 2021/2022 fiscal. Access to the Vault service will be available to all namespaces in Openshift 4 Silver cluster.

**Comment by mitovskaol** [comment]
Nick C is already working with SecOps on this.
