### ISSUE TITLE
Provide Billing Access to Aaron, JP, Olena, Pam

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#841]
**Describe the issue**

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Billing Access provided

**Comment by sheaphillips** [comment]
- olena is set up
- others will need to login and  respond to an email that was sent with instructions, etc.
- dropping in "blocked"

**Comment by sheaphillips** [comment]
- closing as all PO's who responded to reach-out have been set up for access.  the one who did not (Pam) can be set up as/when requested.
