### ISSUE TITLE
Start set up of new GCP org

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#842]
**Describe the issue**
Session with GCP happened with Richard, Mike, Shaun to create a new top-level org to eventually become our lab/dev environment.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Checklist of things todo, DNS, RBAC, etc

**Definition of done**
- Start the create new top-level org, see how far we get
- Timebox to 2
- Define new tickets

**Comment by sid-gov** [comment]
We are not doing this anymore.
