### ISSUE TITLE
SPIKE: Holistic approach to handle common services

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#846]
**Describe the issue**

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add Nick C and others if needed. 

**Definition of done**
- Conversation with James A to start with
- Come up with a strategy to handle procuring multiple products that could handle certificates and key mgmt services

**Comment by sheaphillips** [comment]
Assigned to @ActionAnalytics to determine if this can be called done for this sprint.
