### ISSUE TITLE
Document and demo image scanning to SecOps

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#848]
**Describe the issue**
We have AWS image scanning service and added to our demo app pipeline.  This will connect to a discussion around what is the approach to securing the software delivery pipeline across the org.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- SecOps is talking about setting up an image scanning service but we already have one of those.
- Sending the results to a centralized log would require some serverless code (Include in logs, export to SIEM)
- Tech team opinion is this is something that we should turn on at the SEA level (and push back to parent SEA repos?)

**Definition of done**
- Have a slide that describes what is present in the demo app and possible in AWS for presenting to the next SecOps User meeting on May 25

**Comment by wrnu** [comment]
https://github.com/aws-samples/aws-securityhub-remediations/tree/main/aws-ecr-continuouscompliance

**Comment by wrnu** [comment]
Slide added to 2021-06-08 demo deck
