### ISSUE TITLE
Consolidate AWS hosted SIEMs

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#853]
**Describe the issue**
Bahram and Clecio both have ES instances.  We are hoping that we can consolidate the efforts, accepting it may not be possible.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- ES = Elastic Search

**Definition of done**
- Ideally consolidate the two ES instances

**Comment by sheaphillips** [comment]
Closing following discussion with NRM OneTeam tech lead. This ticket is not required based on decision not to move forward with #852.
