### ISSUE TITLE
Determine Privacy Implications of Serverless at Edge

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#854]
**Describe the issue**
Lambda by itself can be set to run in the CDN region.
Lambda at Edge is a serverless edge computing that happens in the closest AWS node to the visitor.  Lambda at Edge runs in US East and is useful for teams that want do traffic shaping / geofencing, improved perf, latency improvements (eg Netflix instant load, no buffer).

There are questions about where exactly the processing happens and we need to review from a compliance (Privacy) point of view.  

**Which Sprint Goal is this issue related to?**
Sprint May 14-June 04

**Additional context**

**Definition of done**
- Determine if Lambda considered temporary processing under FOIPPA
- Determine if there are any other privacy risks
- Examine ways to use Cloudfront Distributions in order to force processing to only happen in Canada
- Review the compliant serverless patterns document that advices on the good patterns to use (Ryan has this document)

**Comment by hromanow** [comment]
Met with Ryan to get an understanding of Edge. Documented the privacy assessment in the Excel sheet for AWS services. 

The PIA will not be re-opened. It looks like the temporary processing provision applies to Edge and there are mitigations in place to turn on the Canadian region control after it's turned off.
