### ISSUE TITLE
Custom shared responsibility scoped to serverless workflows

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#856]
**Describe the issue**
The AWS shared resp model and the CPF model both are too wide to clearly explain to POs, SecOps and Developers the nuances around serverless that need to be considered and handled.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Warren provided this 3 diagram model: https://www.cloudhealthtech.com/blog/how-aws-shared-responsibility-model-works

**Definition of done**
- Adding a new version customized to our setup that uses labels like "teams" instead of "customer" and any other changes Ryan wishes to do.
- Review with Holly, PO, tech...

**Comment by bluemel-gov** [comment]
Booked meeting w/privacy on June 1 to review

**Comment by bluemel-gov** [comment]
- Followed up with Privacy on June 3rd, no concerns or edits.

**Comment by bluemel-gov** [comment]
- booked meeting with PO on 15th.

**Comment by bluemel-gov** [comment]
- met and reviewed with PO on 15th.
- Updated source documents (export png and .drawio file) to 'Diagrams, Technology, Training/Diagrams with Source Files' in shared folder.
- No further changes needed, closed ticket as complete.
