### ISSUE TITLE
Accessibility QA on written documentation training

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#857]
**Describe the issue**
We are just about to launch our training pre-reading.  It uses the CPF internal PPT deck format, which has colours that are not official per BC Gov and is very likely to be difficult for people with colour blindness to consume.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- We intend to release the documentation as is as a draft, but want to improve in anticipation of a wider audience
- The material is currently in pptx 

**Definition of done**
- Service design review of accessibility of the document
- a 1-page Quick mockup edit of document to apply better format

**Comment by mitovskaol** [comment]
Accessibility will be addressed as part of the new Public Cloud website  and a new Tech Doc website developement
