### ISSUE TITLE
Funnel improvements to the tracker document

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#859]
**Describe the issue**
The current excel file is in Teams and has a lot of fields and entries that may be dormant. It is difficult to find the latest status of who the most active prospective tenants are. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Audra to be assigned once onboarded to ZenHub
- https://www.futurefounders.com/news-article/what-is-customer-discovery-4-step-guide-to-building-the-right-product-for-the-right-customers/

**Definition of done**
- Audra to book a Meeting to walkthrough the excel document (PO, Audra, Stu, Bahaa, Shea)
- Have some sort of an automated reminder (tool tbd)
- Filterability and most important information available at a glance

**Comment by sheaphillips** [comment]
For reference/inspiration: 

- https://airtable.com/templates/professional/expvjTzYAZareV1pt/sales-crm
- https://zapier.com/learn/google-sheets/spreadsheet-crm/

**Comment by fastaudra** [comment]
@sid-gov testing the ticket

**Comment by fastaudra** [comment]
Thanks @sheaphillips for the inspo!

**Comment by fastaudra** [comment]
- Audra to book a Meeting to walkthrough the excel document (PO, Audra, Stu, Bahaa, Shea) - done

- Have some sort of an automated reminder (tool tbd) - removed from DoD - potential to pick this up again for a future sprint if business case for it is sufficient enough to warrant switching tools for CRM.

- Filterability and most important information available at a glance - done
