### ISSUE TITLE
Build a sales pitch deck for prospective clients interested in AWS SEA (now with Serverless! #leadgen FTW)

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#861]
**Describe the issue**
We want to engage prospective clients interested in Serverless and do a presentation to populate the funnel. This is about creating "marketing material" to interest new tenants and about prioritizing the most effective channels in which to do outreach.

**Additional context**
- Reuse the pre-reading material Julian developed 
- This could feed into future web presences as a next ticket
- V2 could be to get this into the hands of some vendors with deep gov tech team penetration (CGI West Coast CoP presentation via Bahram Wed May 19)

**Definition of done**
- Develop CPF intro presentation for TIF, DevOps Commons, Security Community of Practice, Privacy Smart (PriSm) Community of Practice

**Comment by mitovskaol** [comment]
This content will be developed in the new Public Cloud website.
