### ISSUE TITLE
Meeting the team for User/Personas segmentation discussion 

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#866]
**Describe the issue**
After having several Persona creation and interviewing our users, It will be be ideal to meet with the team and have a talk about what we think and the sub categories of each users. For example (gov developers VS contracted developers). 

**Additional context**
Following the user experience personas of the UK Gov, there was a segmentation of their personas depending on the skill set. It will be a good idea to revisit our personas through that lens. 

**Definition of done**
- Booking a meeting with our team
- Showcase the personas in hand
- have a discussion on the sub categories and make a plan for the next steps.

**Comment by wrnu** [comment]
No longer relevant

**Comment by wrnu** [comment]
No longer relevant
