### ISSUE TITLE
Give PO access to Cloud Pathfinder mailbox

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#867]
**Describe the issue**
PO would like visibility to the cloud mailbox in order to see invoices and inquiries now that some of them have disappeared from the web console after switching billing modes.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- PO gets access to cloud mailbox from outlook/summer

**Comment by sid-gov** [comment]
Closing as complete
