### ISSUE TITLE
SPIKE: Pool image scanning service knowledge

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#868]
**Describe the issue**
Several groups in gov are thinking about image scanning during the application build process.  We want to coordinate and discuss.

**Additional context**
- SecOps is looking at centralized tools
- Platform Services just turned on Aqua https://www.aquasec.com in Private Cloud

**Definition of done**
- A list of similar tools and a brief description of the needs and characteristics or the various solutions
- A Community of Practice channel in Teams or RocketChat

**Comment by NickCorcoran** [comment]
I have setup an initial meeting between SecOps, Cloud Pathfinder and Platform Services to keep in touch on planned initiatives (20 May).  I plan for this to be ongoing.

Initial talk will likely serve as a kickoff for image scanning services.

**Comment by ActionAnalytics** [comment]
I think things settled down a bit and Ryan is capacity limited this coming so pulling out and leaving at the top of the backlog in case this lights up again

**Comment by sid-gov** [comment]
PO update: Nick is reviewing some commercial solutions for image scanning in coordination with SecOps and will keep CPF informed.
