### ISSUE TITLE
Create SecOps roles

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#869]
**Describe the issue**
We need a role for SecOps to come in to the environment to access GUI log viewers, and for investigations

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Can be the same role as the tenant team security roles but in the security core account
- Austin to provide 2 or 3 users to get access first, then we see if ticket 870 is a more effective way to manage access or not
- It can be a Read only or Security Auditor access

**Definition of done**
- Access to AWS GUI web console shared security account for view access to the S3 bucket
- No write access
- Automation for KeyCloak for SecOps group

**Comment by sheaphillips** [comment]
Thread ongoing with SecOps team.  Access to be provided when users identified, etc.
