### ISSUE TITLE
SPIKE: Investigate AD group ability in SSE

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#870]
**Describe the issue**
James A is asking if possible to integrate the SecOps Admins users group

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- A SecOps Admins global AD group exists (possible via SSO?)
- See if it's easy
- Define tickets if it's easy, otherwise loop back to James A's replacement, SecOps meeting series update

**Comment by mitovskaol** [comment]
@NickCorcoran Can you please see if it is still relevant and if not, close it.

**Comment by wrnu** [comment]
No longer relevant
