### ISSUE TITLE
Product Owner interview AWS outside of our service.

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#872]
**Describe the issue**
As per our sprint conversation concerning interviewing product owners who are using AWS out of our service. the candidate nominated was Dan P. The intent is to check and compare AWS it to our service and check it with our values

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Book a meeting with Dan P
- Document and analyze insights
- Present a to PO in power point document.

**Comment by mitovskaol** [comment]
This will be addressed in the research into team's journey into the public cloud. Closing as duplicate.

**Comment by mitovskaol** [comment]
@gautammalhotra21  Lets see if we can interview some of the teams that use AWS outside of the SEA service to understand why.
