### ISSUE TITLE
Minimal post-provisioning training handout

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#879]
**Describe the issue**
We need some take-away documentation to hand to teams summarizing the technical provisioning.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Shea: a single slide these are your 4 next steps
- Shea: video recording of onboading, required viewing
- Warren: what to do if you have a new team member?

**Definition of done**
- a powerpoint deck that we flatten to PDF and share with teams

**Comment by wrnu** [comment]
This will be addressed in other tickets
