### ISSUE TITLE
Cloud briefing materials for POs value in using Cloud

### ISSUE THREAD

**Issue by bharmouche** [bcgov/cloud-pathfinder#882]
**Describe the issue**
Through our 1 on 1 interviews with the POs using our service, POs highlighted a pain point that cloud pathfinder can  help with. the request is to provide POs Cloud briefing materials for ADMs to bolster POs business value in using cloud. 
We need to provide POs reusable content that makes them look fully aware of the business benefits of using cloud and clearly describes a way in which they are benefitting from CPF services with the intended audience being their leadership. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
POs are having a problem explaining to their executive and selling the importance of requesting and benefiting from using cloud.
- Connect with CPF PO for location of source material

**Definition of done**
- A short CPF branded 3-10 page Powerpoint deck reusing content from demos and training material scoped to Executive leadership audience. 
- QA with team member 
- Review with PO

**Comment by ActionAnalytics** [comment]
This would be a good fit for Emily and/or Audra to collab with Bahaa on.  We just don't have time this sprint

**Comment by bharmouche** [comment]
shared with our PO and we would like to pass it to our clients PO and get feedback
