### ISSUE TITLE
Lambda & Cloudfront usage for teams

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder#889]
**Describe the issue**
We want to provide support for teams to use different cloud services in a safe and secure fashion, and accelerate their overall velocity including in the area of compliance.  We can help by capturing a set of service-based settings/configurations/patterns applicable to particular use cases, data classifications, compliance requirements, etc. . Eventually this could be incorporated into a CPF-maintained knowledgebase / documentation repository demonstrating usages of different AWS services alongside corresponding Terraform snippets.

**Which Sprint Goal is this issue related to?**

**Additional context**
- Ensure onboarding teams are aware and community is aware
-

- Scope of this ticket is the follwing services only: 
-- Lambda (Note: Lamdba@Edge is out of scope because of region restriction)
-- CloudFront (include cloudfront functions)
- References for other services will be added in the future
-- keep in mind/Future proof against non-AWS specific
- Reference should indicate if/when/how controls are dependent on data classification
-- EG. risk to public endpoints and with data of protected data VS public endpoint and non-protected data
- While working on this ticket, consider whether need for any SOAR changes is surfaced. If so/maybe, discuss with PO/team and create corresponding ticket(s) fro future sprint.

**Definition of done**
Artifact (spreadsheet?) with ~3 columns similar to "service name", "risk/concern/rationale",  "settings/configurations/pattern"
- Review and approve content with tech team and PO
- timed to a 3 effort, if starts to involve more then involve PO
- Ensure onboarding teams are aware and community is aware ( slide deck updates for security deck and devops deck)

**Comment by bluemel-gov** [comment]
@wrnu @sheaphillips Please review and comment if well-formed and you agree with the DoD.

**Comment by sheaphillips** [comment]
did some work/cleanup.  I think it more clear/simpler now.

**Comment by wrnu** [comment]
@bluemel-gov This is looking good to me.

**Comment by bluemel-gov** [comment]
Updated 'Artifact (spreadsheet?) with ~3 columns similar to "service name", "risk/concern/rationale", "settings/configurations/pattern"

Review and approve content with tech team"
to 
"Artifact (spreadsheet?) with ~3 columns similar to "service name", "risk/concern/rationale", "settings/configurations/pattern"

Review and approve content with tech team and then PO"

**Comment by bluemel-gov** [comment]
@ActionAnalytics @sid-gov ticket created with tech team for lambda usage, when you have a moment could you please review and prioritize.thx

**Comment by bluemel-gov** [comment]
- ongoing documentation building to include 
https://wiki.gccollab.ca/GC_Cloud_Infocentre & https://wiki.gccollab.ca/images/7/7a/API_First_Architecture_Patterns_EN_Endorsed.docx

**Comment by bluemel-gov** [comment]
@sheaphillips  @wrnu @ActionAnalytics - Link posted in teams for your review when you have a moment. Let me know if you have questions/want to chat. Thx
