### ISSUE TITLE
Onboard SecOps team so they can run forwarder/proxy components to on-prem SIEM in their own AWS accounts.

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#893]
**Describe the issue**
We have created aggregation/forwarding configuration for SEA logs to be sent to on-prem SIEM, but we would like to have a simple, stable, agreed-upon interface to send to, and like the SecOps team to be able to control more specifics of how data is ingested into their systems.  As a way of enabling that, we want to establish/onboard the SecOps team as a tenant, with their own account set so they can manage deployment and configuration of the elements to complete the integration, as well as evolving it over time if/when it changes.  

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
The current SIEM integration has progressed, but the "last mile" has not been completed.  This ticket is an approach towards getting through that last mile, and setting things up for a sustainable model with clear responsibilities as well as technical interfaces. 
- Connect with Austin

**Definition of done**
- Involve Bahram and Prabhu in these meetings
- Coordinate with Stu and get his help to add the teams to funnel
- concept socialized with SecOps team
- account set created
- team onboarded

**Comment by sid-gov** [comment]
We may not do this if the outcome of #894 goes sideways.
