### ISSUE TITLE
Document behaviour/configuration of AWS/KeyCloak sessions/tokens

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#896]
**Describe the issue**
There is confusion/lack of clarity about how Keycloak and AWS sessions related and interact, and the associated UX. We want to document this in a clear way for tenant users, and potentially for security audiences.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- documentation/slide describing login process/configuration.
- Create in CloudOps repo

**Comment by wrnu** [comment]
No longer relevant
