### ISSUE TITLE
Create new DevHub "Topic" with contents reflecting CPF AWS services

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#898]
**Describe the issue**
We want an easily consumable and manageable reference of CPF AWS services for tenant teams.  The DevHub is a natural and commonly used mechanism by teams for technical references.  The DevHub can also be "embedded" within our AWS Login.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- we can/should generate the DevHub content based on the AirTable base described in ticket ???

**Definition of done**
- new topic created and "populated" with "tiles" for each CPF AWS services
- <stretch goal> replace AirTable listing in AWS Login "tab" with iframed DevHub topic

**Comment by sheaphillips** [comment]
- as discussed, there is an exiting utility to source content from an external spruce (in our case AirTable) and convert to DevHub-freindly markdown + manifest files.  It is located at https://github.com/bcgov/cloud-pathfinder/tree/master/tools/registry/generator .  It will need adaptation as the current version works with Google Sheets and uses a specific template but the framework and pattern are reusable.

**Comment by wrnu** [comment]
PR Created: https://github.com/bcgov/devhub-app-web/pull/1639

New content for "AWS Services" documentation pushed: https://github.com/bcgov/cloud-pathfinder/commit/e6429bf7bf9b2ff76359440ba9181d955cf56df8

**Comment by wrnu** [comment]
Updated PR: https://github.com/bcgov/devhub-app-web/pull/1640

**Comment by wrnu** [comment]
Dev Preview:

https://devhub-app-web-1640-bdec76-dev.apps.silver.devops.gov.bc.ca/Cloud-Pathfinder/AWS-Services
