### ISSUE TITLE
Create a distribution list in Platform Subscription Service for public cloud updates

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#901]
**Describe the issue**
Olena uses a subscription based email blast tool to notify stakeholders of changes to OCP. we wish to use the same system if it's low effort to sign up.  

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- If this is a one-off system that Olena built, investigate using Airtable
- The frontend of the referenced service is here https://subscribe.developer.gov.bc.ca/subscription
- BC Gov GitHub repo is here: https://github.com/bcgov/Mautic-Subscription-App
- appears to based on the Mautic OSS project here:  https://www.mautic.org

**Definition of done**
- Reach out to Olena 
- Get access to the system
- Seed the recipient list with the invitees to our Demos and all POs and Developers

**Comment by OmoAttah** [comment]
Duplicate ticket
