### ISSUE TITLE
SPIKE: Explore establishing the use of certificates from AWS

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#903]
**Describe the issue**
This is coming from NRM Observability Metrics. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Currently we understand that there is a policy that certificates must be Entrust certificates procured via iStore. 
- There is a technical capability to deploy certificates from AWS 
- Public load balancer is not in their account 
- There are some services where Public endpoints are currently in use (Ex: API Gateway, Lambda, Elastic Search) which we may discontinue, or disallow in the new version of LZ code
- possible chat w/Bahaa if there is time/capacity from service design POV
- Note that AWS is a top-tier certificate provider

**Definition of done**
- We're trying to enable the use of certificates for teams because we need to provide this
- Self-signed vs not (we're looking at trusted CA [certificate authority], not the self-signed ones)
- Survey existing Policy patterns & gather associated risks focused on the AWS service itself
- Connect with the Compliance officer for that team and Michelle Douville

**Comment by bluemel-gov** [comment]
- spoke with ISB governance on June 15th

**Comment by bluemel-gov** [comment]
- Working with teams responsible for this.

**Comment by bluemel-gov** [comment]
- meeting set on 13th.

**Comment by bluemel-gov** [comment]
- NRM team to provide hostname, possibly in own AWS instance
- More AWS cert info to provide to CITZ team for their review
supporting link: https://www2.gov.bc.ca/assets/gov/government/services-for-government-and-broader-public-sector/information-technology-services/standards-files/cryptographic_standards.pdf

**Comment by bluemel-gov** [comment]
- emailed NRM team to meet and review information found.

**Comment by bluemel-gov** [comment]
- meeting with NRM scheduled on thursday.

**Comment by bluemel-gov** [comment]
- waiting for confirmation from NRM, ticket is blocked until we hear back/confirmed.

**Comment by bluemel-gov** [comment]
- NRM replied back and confirmed notes

**Comment by bluemel-gov** [comment]
- DoD met and notes saved.
'Survey existing Policy patterns & gather associated risks focused on the AWS service itself
Connect with the Compliance officer for that team and Michelle Douville'
- closed ticket as complete.
