### ISSUE TITLE
First Nations territorial acknowledgement

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#904]
**Describe the issue**
We wish to add the first nations territorial acknowledgement to our Community Update slide deck

**Additional context**
See Page 7 of https://d3n8a8pro7vhmx.cloudfront.net/bcgeu/pages/8498/attachments/original/1539118086/FNguide-GEU-oct2018.pdf?1539118086

**Definition of done**
-  a slide with the territorial acknowledgement  is added to the Community Update deck template

**Comment by sheaphillips** [comment]
[https://app.zenhub.com/files/241742911/d93dbd57-8b5f-4319-91b9-2279909dfd09/download](https://app.zenhub.com/files/241742911/d93dbd57-8b5f-4319-91b9-2279909dfd09/download)

^ from @Work https://intranet.gov.bc.ca/justice/tools-resources/indigenous-hub-beginning/guide-to-territorial-acknowledgements?

**Comment by ActionAnalytics** [comment]
Bahaa and Emily interested
