### ISSUE TITLE
Compliance for team request for SES

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#906]
**Describe the issue**
The ENV Falcon team is wanting to use the Amazon Simple Email Service and wishes us to prioritize a compliance review of this service for tenant team usage and inclusion in the developer's toolkit / allowed list of services.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Contact Max Wardle on team Falcon (he's a gov employee so Teams is fine)
- There currently are several teams using the compliant BC Gov Common Hosted Email Service (https://developer.gov.bc.ca/About-the-Messaging-Common-Service), but we are unsure of the operational capacity of this product (industrialized, supported 24/7, on a platform with 7 9's uptime etc)
- There is a review in flight over the GoC Notify Service (Greg F)

**Definition of done**
- Compliance review of SES service done
- Decision of inclusion into developer toolkit (or not)
- Connect back to Falcon with update on timeline before June 15

**Comment by bluemel-gov** [comment]
- proposed meeting with NRM on 14th.

**Comment by bluemel-gov** [comment]
- meeting planned with nrm on 14th.

**Comment by bluemel-gov** [comment]
- deprioritized due to other tools being used by NRM

**Comment by sid-gov** [comment]
Team Falcon ended up using GC Notify service but another team has come to us with a request for SES.

**Comment by mitovskaol** [comment]
Not relevant anymore
