### ISSUE TITLE
Compliance Policy Review and Comparison with Federal Process

### ISSUE THREAD

**Issue by emilyjones430** [bcgov/cloud-pathfinder#909]
**Describe the issue**
Conduct a policy review of the federal government to understand the division of compliance work between the center and the agencies. This will help with the understanding of the process for the federal equivalent of corporate vs. ministry level compliance documents, and understand how that maps to BC's process. This will also help us understand how we are matching up with the experience we are describing as part of the Pathfinder experience - for example, that some of the compliance 'heavy lifting' will already have been done (as per the Shared Responsibility Model).

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- This task will provide important context and alignment with proposed components of the HADF strategy.
- Julian & Shea have a lot of context over the GoC teams and how they are working

**Definition of done**
- Stuart to share product lifecycle with Emily
- Start with meeting with Julian & Shea for knowledge transfer
- Summary document outlining federal process for providing services to their agencies, including any compliance work done up front and any work that remains for the agencies to take on. 
- Summary document will also include overview of provincial process including the policy background of compliance documents.
- Cap to 3 this sprint (we could go waaaayyyy deeper)
- factor in capabilities and capacities of the whole government, org capability vs team capacity

**Comment by ActionAnalytics** [comment]
I think this work is no longer happening as Emily has moved on to other priorities.  Closing, can reopen if that's incorrect
