### ISSUE TITLE
Compliance against Cloud Custodian tool

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder#911]
**Describe the issue**
A lack of compliance and monitoring of the tools used for Cloud Providers and repeatable to other providers.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Looking to timebox the effort on this to  1-2 for an estimate

**Definition of done**
- SOAR reviewed with stakeholders
- Completed SOAR and submitted for sign off
- Completed PIA if needed or review with PCT team
- Create repeatable patterns for future external tools to use.
- Update to risk registers as needed

**Comment by lukegonis** [comment]
No longer relevant
