### ISSUE TITLE
Compliance for team for SES

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#913]
**Describe the issue**
The ENV Falcon team is wanting to use the Amazon Simple Email Service and wishes us to prioritize a compliance review of this service for tenant team usage and inclusion in the developer's toolkit / allowed list of services.

**Which Sprint Goal is this issue related to?**
Sprint: Jun 14 - Jul 9

**Additional context**
- If additional info need, pls contact Max Wardle on team Falcon (he's a gov employee so Teams is fine)
- There currently are several teams using the compliant BC Gov Common Hosted Email Service (https://developer.gov.bc.ca/About-the-Messaging-Common-Service), but we are unsure of the operational capacity of this product (industrialized, supported 24/7, on a platform with 7 9's uptime etc) 
- There is a review in flight over the GoC Notify Service (Greg F)
- The on-prem email services SMTP server is inaccessible outside gov

**Definition of done**
- Scoped to Privacy implications of SES itself mostly with eyes open to other efforts
- Strategic implications of offering a notification service for government.  One locally installed product to rule-them-all vs mature services already in place in each cloud, vs external SaaS (which happens to be GoC)
- Compliance review of SES service done
- Decision of inclusion into developer toolkit (or not)
- Connect back to Falcon with update on timeline before June 15

**Comment by hromanow** [comment]
Closing for now as this work is no longer the priority. Gov of Canada's Notify service is being contemplated instead.
