### ISSUE TITLE
Service order for second cloud

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#918]
**Describe the issue**
There is procurement work under way with the service order for a second cloud, possibly through the GoC brokerage.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- many subsidiary agreements, precedence, conflicting terms adds difficulty in assessing

**Definition of done**
- Draft of the terms for the first version of the service order for a 2nd CSP over in the hands of the CSP
- Take care of all the legal meetings and follow-ups, email comprehension

**Comment by fastaudra** [comment]
Sent over to Scott Anderson of MSFT on Thursday, July 8.
