### ISSUE TITLE
Review of cloud companion guardrails with CPF

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder#926]
**Describe the issue**
As more teams ask about cloud, CPF and ISB to provide direction and guidance from security perspective

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Helps to build on team partnership and expansion

**Definition of done**
- Review of excel file with PO
--- if scope changes
- Incorporate any feedback
- publish with review from ISB

**Comment by bluemel-gov** [comment]
- meeting booked for 27th with PO

**Comment by ActionAnalytics** [comment]
Ryan and I reviewed the Companion Guardrails Document and while I very much want to be an accelerator, in this case I cannot sign off this document as it is based on the Cloud Security Schedule which is still in it's original format without any of the disambiguation that I asked for several months ago in the review of the CSS.  For example, several key parties are not describe in a clear way which cascades ambiguity up to this Guardrails document.  Who is a Contractor?  The answer should not be "it depends on the situation".  

I think once we have a well-formed CSS then the rest of these related documents will naturally work well.
