### ISSUE TITLE
Record the Group Start Cloud Onboarding Session

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#929]
**Describe the issue**
We're comfortable with the 3h onboarding session now, we'd like to have a recording to provide any stragglers or for people that missed part of the message and wish to review.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Record the June 22 session with Falcon

**Comment by sid-gov** [comment]
Two things to consider: 
- Where do we post the recorded session? (Teams Channel, Youtube)
- Accessibility Portion: Include captions, ASL (American Sign Language) aspect which will require additional cost

For Consent form: 
- Let the participants know beforehand and request to keep video off if they do not wish to be recorded
- Consider recording just the team in a separate session to avoid the above
