### ISSUE TITLE
Review concerns around CPF Demo recording

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#932]
**Describe the issue**
We put the option of recording our demos on the table for our audience at our last demo.  PO asked for +1's in support of or -1's if concerned about recording demos.  Majority was +1 but there were some -1's.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Scrum Master to follow up with -1's from demo chat, listen to, and gather concerns
- Present to PO for decision whether to record or not

**Comment by sid-gov** [comment]
Spoke to Ryan B, Mark L. Their concerns with recording demos were the following: 

- Risk of recording being shared outside the intended audience (Mitigation: have a slide in the beginning saying 'this is intended for audience of BC Gov and users')

- Concerns around location where the demos are stored and maintained

- Watching a recorded session may not be the best use of time for someone who missed the session. Would prefer a self-serve stats and health service-level  dashboard style that talks about current issues, list of high-level outcomes  and things achieved in that particular sprint

- Other ideas on the above: showing upcoming milestones on GitHub on a wiki or pages site. RC is sometimes too noisy and unreliable for good communications (prefer RC only for mission-critical stuff)

**Comment by sid-gov** [comment]
Health and service Dashboard examples: 
https://www.google.com/appsstatus#hl=en&v=status
https://www.apple.com/ca/support/systemstatus/
https://api.twitterstat.us/

**Comment by sid-gov** [comment]
https://docs.microfocus.com/itom/Network_Automation:2020.11/ReleaseLog

**Comment by sid-gov** [comment]
Follow-up with Gen and check if we need to record our demos. Run concerns and risks, PO agrees with the dashboard style idea as a  Release log tab in the login page.
