### ISSUE TITLE
Review GCP microservices demo repo and compare to startup-sample-app

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#933]
**Describe the issue**
Shaun M from GCP has pointed out a demo repo for GCP that has code that might be similar to the startup-sample-project.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- https://github.com/GoogleCloudPlatform/microservices-demo

**Definition of done**
- Review the repo, compare to startup-sample-project
- Create tickets for next steps to create a GCP focused startup-sample-project
- Timeboxed to 3.14

**Comment by mitovskaol** [comment]
Too old, we will make new sample apps for GCP as part of the SEA build out
