### ISSUE TITLE
Improve Routing Automation in AWS SEA

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#935]
**Describe the issue**

Support automation of ingress-related resources for "FQDN" within ASEA OCTK.  Fully Qualified Defined Network.

Internal routing requires an ALB.  This is to make internal DNS names count for routing.

We currently have functionality within the ASEA OCTK to automate the configuration of ingress (frontend ALB, firewall) components to support routing to ALBs within tenant team accounts.  We have identified that there this is not sufficient to support the range of use cases that tenants are likely to need.  We would like to implement an generalized automation approach based on "FQDNs" (fully qualified domain names) where ingress components can be configured to route to a tenant-specific FQDN, independent of the "type" of target the FQDN is associated with (e.g. ALB, API Gateway, ElasticSearch, etc.).

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Fully Qualified Domain is wanted

**Definition of done**
- Wait for Major Network focused version of SEA to check if this is already covered.
- TODO: define DoD

**Comment by wrnu** [comment]
Done in another ticket, no longer relevant
