### ISSUE TITLE
QA SIEM work

### ISSUE THREAD

**Issue by prabhukiran9999** [bcgov/cloud-pathfinder#939]
**Describe the issue**.
Prabhu has just joined and needs to get up to speed. PO has asked for the review of SIEM as a learning excersice and QA

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Bahram(cloudsmart) has the information on the tickets 
- There are two SIEM systems in scope; First is built by Bahram based on open source code deployed in AWS, The second is over at BC Gov datacenter and is managed by different team called the Security Operations Team 

**Definition of done**
- Identify all the tickets relating to this work
- At least two hour sessions with Bahram, Get him to explain the security operations persona(Also available from team members Bahaa and Sid)
- Assist and ensure that data is flowing from BC Gov to both SIEM
- Get access to all the Repos where this work is

**Comment by ActionAnalytics** [comment]
Comments as you work go here, keep in mind that this is public so keep sensitive security and procurement related materials out please.
