### ISSUE TITLE
Update DevHub with the Service Definition/Overview

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#942]
**Describe the issue**
There are two documents, Service Overview from the Business Model Canvass and the Service Definition from the funding request effort.  We want to take the best info from both and place as a tile on DevHub.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Take content from #943 and convert to markdown in our repo
- Tile is visible in DevHub, following the same format as the Cloud Pathfinder one (or update that one if that's better - you decide).
- Service Definition tab in login page has a filtered view on all CPF related tiles on DevHub.

**Comment by mitovskaol** [comment]
This content will be developed as part of the new Public Cloud website.
