### ISSUE TITLE
Create top-level DevHub topic for Cloud Pathfinder

### ISSUE THREAD

**Issue by sheaphillips** [bcgov/cloud-pathfinder#944]
**Describe the issue**
We would like to establish/expand our presence on the DevHub.  

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- currently we have content within an existing topic ("Developer Tools" or similar); we want to create a *new* topic that will contain only materials related to our service
- this will require creating a pull request against the DevHub main repo with the new topic
- our current DevHub content is being sourced from https://github.com/bcgov/cloud-pathfinder/tree/master/devhub-content ; we probably should continue to use this as the default location for additional DevHub content

**Definition of done**
- pull request created and "preview" validated
- pull request accepted/merged
- new topic visible within "live" DevHub instance

**Comment by wrnu** [comment]
PR Created: https://github.com/bcgov/devhub-app-web/pull/1639

**Comment by wrnu** [comment]
Updated PR: https://github.com/bcgov/devhub-app-web/pull/1640

**Comment by wrnu** [comment]
Dev Preview:

https://devhub-app-web-1640-bdec76-dev.apps.silver.devops.gov.bc.ca/
