### ISSUE TITLE
Review any new potential user personas stemming from Azure integration with Jon

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#945]
**Describe the issue**
We are joining forces with Enterprise Services about Azure and we want to be open to any potential new user categories that they may know about that we haven't accounted for yet. 

**Additional context**
- Jon M is a good source for this information.
- Jon is saying not everyone is an app developer and some prople just want a little service or automation. 

**Definition of done**
- Meet with Jon, talk about the personas, and get the doc started
- List of up to 3 representative users to talk to
- Discover potential questions different from AWS
- QA with team member
- Review with PO

**Comment by bharmouche** [comment]
Met with Jon and we decided to explore it thoroughly by meeting the delivery of the infrastructure to the profile of the team between team that are ready to deploy, teams that are in discovery mode or team that want to experiment.
