### ISSUE TITLE
Updated list of Azure tenants and prospects

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#946]
**Describe the issue**
We need a report on the subscriptions in use in Azure currently and anything that has been promised to prospective tenants. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Jon M likely has this information
- We are scoping this to application related subscriptions only (Visual Studio, components are out of scope)
- Reach out to Audra for access to the funnel on Airtable

**Definition of done**
- Get familiar with Airtable at the same time
- Airtable entries from the intake funnel, or Excel in Teams partnering with Audra

**Comment by ActionAnalytics** [comment]
This is top priority to provide to Audra, takes priority over all other Azure activities please

**Comment by jon-mc-git** [comment]
Completed and sent last week.  Closing.
