### ISSUE TITLE
SPIKE: Azure account automation feasibility

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#949]
**Describe the issue**
Currently project sets are provisioned by ADMS and/or Jon. We wish to create a quick and reliable vending machine style experience for users to always receive project sets in a reliable manner. 
We believe that this is valuable because it will lend to governance very well same as in AWS. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- This work is assumed to be independent of whether or not Azure is using a SEA.  
- phase 2 uses multiple resource groups as a "project-set" as we know it

**Definition of done**
- Timeboxed to 3 points
- Well-defined tickets created to describe implementation of an azure account vending machine

**Comment by wrnu** [comment]
This work will be tracked in other tickets

**Comment by wrnu** [comment]
This work will be tracked in other tickets
