### ISSUE TITLE
Diagram of the current Azure onboarding process

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#950]
**Describe the issue**
we want a Diagram of the current Azure onboarding process. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Connect with PO on how to use Draw.io
- Draw.io diagram saved in our Teams 
- Clear description visually of the Azure onboarding process showing who does what along with what the recipient gets.

**Comment by jon-mc-git** [comment]
Just a note that documents finished, but not attaching here due to apparent issue.  Will drop the draw.io and png\pdf files into the Sharepoint drive once I have the proper location when back next week

**Comment by jon-mc-git** [comment]
![Gov.Azure-Current.Intake.Process.png](https://images.zenhubusercontent.com/60dcec0926df4b0c6ab687ad/fde907b5-a0f9-42f1-81a5-7f753038a9ee)

**Comment by jon-mc-git** [comment]
Draw.io not supported here, will be in Sharepoint

**Comment by jon-mc-git** [comment]
Got word on our proper location for diagram files in the Sharepoint.  Files have been uploaded
