### ISSUE TITLE
Dev Community of Practice

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#951]
**Describe the issue**
The first meeting in the regular CoP series for Developers needs to happen. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Create small powerpoint deck reusing material from the demo decks and other content. 
- Present to Developers how to set costs of thresholds. 
- Q&A session with Developers

**Comment by sheaphillips** [comment]
Scheduled for Wed Jul 28.
