### ISSUE TITLE
Backfill Cost Thresholds for existing teams in Developer CoP

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#954]
**Describe the issue**
Several teams are operating already and they may not have cost threshold automation.  

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Organize Dev CoP meeting
- Get each financial threshold info from MoU docs
- apply the cost thresholds per formula in 952 on each team

**Comment by sheaphillips** [comment]
Closing this ticket as detailed discussion was had at developer CoP and teams are exploring budget-related capabilities with our support.
