### ISSUE TITLE
Embed CSS FAQ into Cloud Sign In Page

### ISSUE THREAD

**Issue by emilyjones430** [bcgov/cloud-pathfinder#956]
**Describe the issue**
Once the Cloud Security Schedule FAQ has been finalized in CHEFs, we want to embed a link to this resource into the cloud sign in page. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Alter the login page to contain to either a link or an embedded content section for a CSS FAQ.

**Comment by wrnu** [comment]
No longer relevant

**Comment by wrnu** [comment]
No longer relevant
