### ISSUE TITLE
AWS Access for ISB Advisory Services

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder#957]
**Describe the issue**
- By allowing access it will allow for reporting and tracking of awareness, and eventually compliance automation and vulnerability notification

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- This is an ask from ISB management
- This is dependent on the dashboard being finished. 
- A project-set is the grouping of spaces that we provision to one team's project (one per app). 

**Definition of done**
- Grant reader access to the future AWS Project-Set only dashboard for one or more team members in Advisory Services.

**Comment by lukegonis** [comment]
We will not be doing this until the ISB team hires an FTE architect to support
