### ISSUE TITLE
Follow-up on Business Case 

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#959]
**Describe the issue**
There's a review next week with IMB and CFO. We want to develop slide deck for SME review and for the Digital Investment board. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Review next week with IMB and CFO.
- Develop slide deck for SME review and for the Digital Investment board. 
- Incorporate changes from the above reviews

**Comment by scayzer** [comment]
Completed, along with preparation and presentation of a summary deck for DPDD All Staff meeting
