### ISSUE TITLE
Review of ISB document(s) with Cloud PO/leads

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder#964]
**Describe the issue**
- ISB has a few artifacts that involve cloud space and are security focused.
- Want to build capacity and knowledge sharing with our teams for shared documentation and collaboration.

**Which Sprint Goal is this issue related to?**

**Additional context**
- Time booking to a hour of meetings, so .5

**Definition of done**
- Review of up to 2 security documents about cloud with PO/team leads
- ISB to publish these and communicate out.
- future reviews would be made as tickets.

**Comment by bluemel-gov** [comment]
- Review w/Scrum master& PO

**Comment by mitovskaol** [comment]
Not relevant anymore
