### ISSUE TITLE
Get airtable licenses for whole team

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#965]
**Describe the issue**
We need AirTable licenses for the whole team, as we're using it more for onboarding

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Get approval and more licenses for the entire team

**Comment by sid-gov** [comment]
Teams invited to the Airtable space
