### ISSUE TITLE
SPIKE: Figure out demand for Azure

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#971]
**Describe the issue**
Investigative work to figure out what our clients want, by scanning existing emailed & other inquiries, getting the info from Jon.  This is to assist Jon with ticket 946.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- PRE-WORKSHOP if possible

- How does NRM Files fit in this?
- Audra has a ticket about who are the existing tenants

**Definition of done**
- Jon to share email info, Sid to ask for them.  Related to the work Jon is doing with Audra about existing clients
- Information on who wants what in Azure
- Define a set of tickets based on the feedback we get, well-defined, estimated

**Comment by sid-gov** [comment]
What is the project? 
Bonus is: what Services are they using?
