### ISSUE TITLE
SPIKE: Find link sharing pattern for Airtable

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#972]
**Describe the issue**
Airtable seems to allow a 1-time sharing of links to people. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Investigate if a solution exists
- Share with team

**Comment by mitovskaol** [comment]
Not relevant anymore
