### ISSUE TITLE
kabana dashboard access for security staff

### ISSUE THREAD

**Issue by bluemel-gov** [bcgov/cloud-pathfinder#977]
**Describe the issue**
There is a SIEM dashboard that uses kabana and we want to grant read-only access to the security users to the dashboard. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Connect with Warren/Shea to look at the client vpn sso automation

**Definition of done**
- Pull in Max W to onboard (if available)
- define the roles
- grant read-only access as needed.

**Comment by mitovskaol** [comment]
Not relevant anymore
