### ISSUE TITLE
Deploy SIEM to LZ1 

### ISSUE THREAD

**Issue by wrnu** [bcgov/cloud-pathfinder#981]
**Describe the issue**
We want to have an isolated space for testing things. New SIEM solution was deployed to LZ2, we want to have it in LZ1 as well so that dev work can happen there.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
-  Reach out to Shea or Julian for getting access to create new repo. 

**Definition of done**
- SIEM deployed to LZ1
- Automate any additional steps 
- Code developed for this should be forked into a new BC gov bcdevops repo

**Comment by ActionAnalytics** [comment]
No longer need because Ryan J has a PR upstream for integrating into the SEA
