### ISSUE TITLE
Mantis Bug Tracker for tracking system and project management tool

### ISSUE THREAD

**Issue by azuberi60** [bcgov/cloud-pathfinder#982]
**Describe the issue**
We propose using Mantis Bug Tracker as a tracking tool for clients and internally. 
It is an open source web-based application tool. It is used for Bug Tracking throughout Defect Lifecycle. Along with bug tracking, Mantis supports Release Features to manage various releases of a project or a software. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Some features of Mantis Bt are:

• Email notifications: It sends out emails of updates, comments, resolutions to the concerned stakeholders.
• Access Control: You can control user access at a project level
• Customize: You can easily customize Mantis as per your requirements.
• Mobile Support: Mantis supports iPhone, Android, and Windows Phone Platforms.
• Plugins: An ever-expanding library of plugins to add custom functionality to Mantis Issue Tracker.
• Reporting and graphing built 

**Definition of done**
- Look at our current processes and document painpoints if any with the current tool.

**Comment by ActionAnalytics** [comment]
Not doing
