### ISSUE TITLE
Security Automation Checks

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#984]
**Describe the issue**
We want to create some automation to see if we can detect some situations we care about:
- Checking that team hasn't configured their **custom runtimes** of lambdas and that those are up to date
- All CloudFront function check outside of a VPC
- Detect non-compliant usage of services

**Additional context**
- Confirm the secret vax app is no longer in use
- Lambda's region checks (already covered by an SCP)
- Process does not default to Cloud Custodian, it arrives there as a last resort, better to have SEA config changes and this will involve the tech

**Definition of done**
- The above controls need to be implemented
- Step 1. AWS config check at SEA?
- Step 2. SEA Guardrail via SCPs? Detective/Preventative
- Step 3. Cloud Custodian if none of the above work

**Comment by wrnu** [comment]
Not relevant
