### ISSUE TITLE
Find out what happened to our feedback for changes to CSS

### ISSUE THREAD

**Issue by sid-gov** [bcgov/cloud-pathfinder#990]
**Describe the issue**
CP Team feels that there are improvements that need to be made to the CSS before it is used as a artifact to drive other deliverables. Feedback was provided early this year and it appears like it got lost. We are hoping to have our feedback included. 

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
- Avoid big email chains
- https://www2.gov.bc.ca/assets/gov/british-columbians-our-governments/services-policies-for-government/information-management-technology/information-security/information-security-awareness/cloud_security_schedule.pdf

**Definition of done**
- re-initiate the process with a kick-off meeting with the right stakeholders (PO, ISB Mgmt)
- Determine current author of the document  
- Engage directly with face-to-face meetings
- Gain an understanding of the commitment capacity and timeline for the proposed changes 
- feedback received and acted upon

**Comment by bluemel-gov** [comment]
- meeting booked on July 30th (30min)
- follow up meeting on  13th to discuss with lead (30min)

**Comment by bluemel-gov** [comment]
- Determine current author of the document - > ISB

**Comment by bluemel-gov** [comment]
- planned meeting about 'Gain an understanding of the commitment capacity and timeline for the proposed changes' on 17th.

**Comment by bluemel-gov** [comment]
'- have 15min meeting wit ISB regarding awareness and capacity. Further review of the notes captured from #491 from ISB governance to happen before any further meetings to happen. '

**Comment by bluemel-gov** [comment]
- followed up with goverance lead on 8/23. they are planning on reviewing this week,

**Comment by bluemel-gov** [comment]
- internal meeting scheduled on 26th.  unblocked ticket

**Comment by bluemel-gov** [comment]
- ticket  blocked due to staff being away. Finding alternative routes and paths forward.

**Comment by ActionAnalytics** [comment]
PO is away for 3 weeks

**Comment by sid-gov** [comment]
Julian and Audra had face-to-face with Don and will engage Bonnie.
