### ISSUE TITLE
Plan deployment of GCP SEA work with GCP

### ISSUE THREAD

**Issue by ActionAnalytics** [bcgov/cloud-pathfinder#997]
**Describe the issue**
We need to get moving with GCP.  We need a meeting to kick off the next stage of work which is deploying an SEA to the test area we have.

**Which Sprint Goal is this issue related to?**
> Note: 'Milestone' is a ZenHub term that we use synonymously with 'Sprint'. 

The 'Milestone' description (created in ZenHub) should clearly list Sprint Goals. This section should indicate which 'goal' this issue is related to.

**Additional context**
Add any other context, attachments or screenshots

**Definition of done**
- Post a "hello, let's meet" in the gcp channel
- Meeting with GCP happens
- We refined tickets for GCP SEA deployment in ticketing system

**Comment by wrnu** [comment]
Reached out in #gcp-operations waiting to hear back and schedule the meeting
